### ISSUE TITLE
Add Unix Socket Support for Redis and Predis

### ISSUE THREAD

**Issue by Mosely** [PHPSocialNetwork/phpfastcache#107]
Some users might be only able to connect to Redis via a Unix socket, so having this ability to use Unix sockets would be good.

**Comment by khoaofgod** [comment]
Sure, Unit Socket is on working schedule.

**Comment by Geolim4** [comment]
Gotta implements this for V5 :)

**Comment by khoaofgod** [comment]
Add them soon

**Comment by khoaofgod** [comment]
added to working scheudle for next release.
