### ISSUE TITLE
Support PSR-6

### ISSUE THREAD

**Issue by gcleaves** [PHPSocialNetwork/phpfastcache#118]
Do you have any plans for phpfastcache to support PSR-6? https://github.com/php-fig/fig-standards/blob/master/proposed/cache.md

**Comment by khoaofgod** [comment]
Can you help on that? I am so busy now, if someone can help me that, I will thanks ful, and I will accept the commit as a new version.

**Comment by khoaofgod** [comment]
IF we work on that, it will be version 4.0.0

**Comment by gcleaves** [comment]
OK, let me see if I can make some time for this.

**Comment by bfintal** [comment]
I'm assuming version 4.0.0 is the current final branch, correct?

**Comment by lean-stack** [comment]
One big change would be necessary: the PSR treats null as a legitimate value.

See comment at the get()-Method in the CacheItemInterface
> Note that null is a legitimate cached value, so the isHit() method SHOULD be used to differentiate between "null value was found" and "no value was found."

**Comment by khoaofgod** [comment]
Ok, I put this on working right now, I will do some scratch work on version 4.

**Comment by Geolim4** [comment]
Reported to V6 as the V4 and V5 will keeps the same method names and had already interfaces.

**Comment by Geolim4** [comment]
As the v4 will be supported for a while, the psr6 will be implemented in v5 (branch created but no yet commited).

**Comment by barayuda** [comment]
Thank you, hope can join to prepare on it :)

**Comment by Geolim4** [comment]
I will need some testers so can i get in touch with you when the first preview will be available ?

**Comment by Geolim4** [comment]
Hi, the V5 just got his first commit with psr6 implementation:

https://github.com/PHPSocialNetwork/phpfastcache/tree/v5
Anyway i suggest you to carefully read the roadmap: https://github.com/PHPSocialNetwork/phpfastcache/blob/v5/V5-ROADMAP.md

The V5 is not yet finalized neither released, it's just for information :)
We're working hard on it, expect again 2 months of dev for the first BETA :)

Regards,
Georges

**Comment by Geolim4** [comment]
@lean-stack Will be added to the roadmap

**Comment by Geolim4** [comment]
@bfintal The v4 will be maintained for at least 2 years until v4.5.x maybe 4.6.x
We want user to have the time to upgrade their code to be php 5.5/composer compatible.

**Comment by Geolim4** [comment]
The psr6 is now fully implemented in v5.
Thanks you for your contribution :)
