### ISSUE TITLE
Describe syntax of functions

### ISSUE THREAD

**Issue by SebastianZ** [PHPSocialNetwork/phpfastcache#122]
[3.-Available-Methods](https://github.com/khoaofgod/phpfastcache/wiki/3.-Available-Methods) lists the available methods of phpFastCache. Though there is no information about what they do and about how to use them.

I'd expect to see something like this:

### Syntax
```php
set($keyword, $value = '', $time = 300, $options = array());
```

### Description
Stores a variable in the cache.

#### $keyword
Keyword used to reference the value saved within the cache.

#### $value
Value to store within the cache. Optional, defaulting to an empty string.

#### $time
Timespan in seconds the value will be stored within the cache. After the timespan is exceeded, the value will be flushed from the cache, so it needs to be saved again. Optional, defaulting to 300.

#### $options
Array of additional options used to store the value within the cache. Optional, defaulting to an empty array, meaning, no extra options are defined. The supported options are:

* `skipExisting`: If the keyword already exists within the cache, it will not be overwritten.

Sebastian

**Comment by khoaofgod** [comment]
>_< let's schedule for October >_< Until that I am crazy like hell with many projects >_<

**Comment by SebastianZ** [comment]
There is no update on the mentioned page, so why did this get closed?

Sebastian

**Comment by khoaofgod** [comment]
this one closed because we have plan to make a new wiki next week already. New Wiki on phpfastcache.com not github anymore, since we gonna have 3 version : 3,4,5

**Comment by SebastianZ** [comment]
I see. So I'll have a look again when the new wiki is up. Thanks for the fast reply!

Sebastian

**Comment by SebastianZ** [comment]
khoaofgod commented on 11 Feb 2016 
> this one closed because we have plan to make a new wiki next week already.

That's quite a long "week"! 😁 Is it still planned to move away from GitHub? So far I just see https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV5%CB%96%5D-API:-Available-Methods.

Sebastian

**Comment by Geolim4** [comment]
Hello @SebastianZ,

We have decided to delay the Wiki as an non-prioritized task.
Currently the Wiki is very descriptive and comprehensive enough .
The readme provides also a lot of useful information.

Also we have been working on drastically improving code annotations.
Therefore any today-IDE is now able to understand PhpFastCache code.

Cheers,
Georges
