### ISSUE TITLE
Premature end of script headers

### ISSUE THREAD

**Issue by bfintal** [PHPSocialNetwork/phpfastcache#128]
A bit of background: we're building a commercial caching WordPress plugin. As of the moment it is working great except for this certain error which I cannot get a hold of. We've been testing for the better part of a week now. We are getting this error from the PHP logs which triggers a 500 error:

> Premature end of script headers

Have you encountered this before?

We are testing in a number of shared hosting sites and it happens in most if not all of them in random intervals and areas. We have drilled down the problem to the page caching we implemented which is using the filesystem for caching. Basically we're just getting the URL, hasing it then checking based on the hash if there is something saved. (This is part of the code, parts have been removed since they do not seem important to the issue, this is just the gist of what we are doing).

	$config = array(
		'default_chmod' => 0755,
		"storage" => 'auto',
		"fallback" => "files",

		"securityKey" => "auto",
		"htaccess" => false,
		"path" => ABSPATH . "wp-content/gambit-cache/page-cache",
	);
	
	global $gambitPageCache;
	$continue = true;
	try {
		phpFastCache::setup( $config );
		$gambitPageCache = phpFastCache( "files" );
	} catch ( Exception $e ) {
		$continue = false;
	}
	
	// Further down the line
	if ( $continue ) {
		try {
			$html = $gambitPageCache->get( $pageHash );
		} catch ( Exception $e ) {
		}
	}

We also call the `delete` function so there might be something there too.

I've done my research and so far it's not a memory problem, permission problem, server configuration, server load, etc. We've tried a ton of solutions to fix the problem by Googling the error, but so far it's still there.

We've also removed parts of the code to find out what's going wrong and it seems that this random internal server error only occurs when using the filesystem for storage in phpfastcache.

Any help would be really appreciated.

**Comment by khoaofgod** [comment]
so, you got Internal Server Error ?
Server run: CGI / Fast or Module PHP ?

**Comment by bfintal** [comment]
CGI / FastCGI

Yup I'm somehow getting internal server errors. This is boggling my mind.

As of the moment, I've dropped support for caching stuff that tend to get modified often.. because maybe there's too much IO file activity. So far, there's almost no internal errors. there are sometimes though and those show up as premature end of script headers.

**Comment by bfintal** [comment]
Reason for the close? I'd appreciate help on this

**Comment by khoaofgod** [comment]
Hahah, I thought u said u have no more problem with the script anymore.
Internal Error is something problem with Apache Server, not PHP it'self. Or PHP run something that Apache doesn't have that function.
So, to check the Internal Error, you have to open the Apache Log, and see the time that you get problem. I am sure it log the bug there,

Let me know.

**Comment by bfintal** [comment]
Nope it's still there, only happens less because I lessened the caching calls. But it's still there sometimes during caching activity.

The message regarding premature headers is from the error log. From the browser all you can see is the internal server error notice. No other clues other than that cryptic premature end of script headers

**Comment by khoaofgod** [comment]
Ok, I think I got the problem.
I will do optimize by this weekend, and see new version on Monday will fix it or not.

**Comment by bfintal** [comment]
That would be great, we are almost finished testing the plugin and we are aiming for a release this week.

What did you figure the problem is?

**Comment by khoaofgod** [comment]
if it's Files Cache, the problem is I/O hit, when the Files is OPEN, other process can not overwrite it. It's barely happen, but I think it is.

**Comment by bfintal** [comment]
So we need add a) file locking if that's the case, or to b) just gracefully fail the other write when the file is inaccessible.
