### ISSUE TITLE
SASL Authentication

### ISSUE THREAD

**Issue by sarahansen223h** [PHPSocialNetwork/phpfastcache#133]
SASL authentication for memcache/memcached would be nice to have

**Comment by khoaofgod** [comment]
Add them soon

**Comment by khoaofgod** [comment]
added to working schedule next release.

**Comment by ddauto** [comment]
Hi, 
Does the newest version include the SASL auth ready?
Thanks.

**Comment by Geolim4** [comment]
Hi, not yet, i will add this to my todo-list.
Sorry for closed the bug too soon :)

**Comment by Geolim4** [comment]
[Merged](https://github.com/PHPSocialNetwork/phpfastcache/pull/333) :+1:
