### ISSUE TITLE
Allow foreign language characters as keywords?

### ISSUE THREAD

**Issue by thekksed** [PHPSocialNetwork/phpfastcache#134]
Hi, I use my post title as keywords, some of them contain some japanese and korean characters. It seems phpfastcache won't be able to use those words as keywords.

Can you add support for those foreign language characters?

Thank You.

**Comment by Geolim4** [comment]
Related to #164

**Comment by khoaofgod** [comment]
add mb_ function soon

**Comment by khoaofgod** [comment]
Done.
