### ISSUE TITLE
What is the purpose of the "storage" setting in config file?

### ISSUE THREAD

**Issue by fbonzon** [PHPSocialNetwork/phpfastcache#138]
In the first example on the homepage, I see;
```php
phpFastCache::setup("storage","files");
```
What is the purpose of this setting?

It seems to me that it is useless. When creating a new `phpFastCache()` object with no storage specified, I would expect that this default storage specified in the config file would be used.

But this is not the case. Instead, `self::getAutoClass` gets called and overwrites whatever is specified as default storage in the config file.

**Comment by ZiZuu-store** [comment]
:+1:

**Comment by fbonzon** [comment]
Would you rather fix the code to honor this config setting, or remove this config option? It makes no sense to keep it if it doesn't work. Only adds confusion.

**Comment by shiroamada** [comment]
and for the storage function, seem like once the path is writeable it will not select other.
```
if(is_writeable($path)) {
     $driver = "files";
}
```
The predis also not included in the storage.

**Comment by fbonzon** [comment]
@khoaofgod What do you think here?

**Comment by fbonzon** [comment]
So, was this config useful? Or is it obsolete in version 4?

**Comment by khoaofgod** [comment]
on version 4 its fixed already.
Look at Examples: global.setup.php 
^_^
