### ISSUE TITLE
Memcache method make 2 get requests at once

### ISSUE THREAD

**Issue by Axisar** [PHPSocialNetwork/phpfastcache#149]
Memcache method make two get requests at once
first one with each request with key "changed"
second one with real key.

**Comment by khoaofgod** [comment]
what you mean on this?

**Comment by Axisar** [comment]
i start empty memcache.
making cache this way
...
$html = $cache->get($keyword_webpage);
if($html == null) {
	ob_start();
...  script work here ...
	$html = ob_get_contents();
	$cache->set($keyword_webpage,$html, $cachetime);
...

then request stats of memcached
(echo -e 'stats\nquit'; sleep 1) | telnet localhost 11211
and see 
STAT get_hits 0
STAT get_misses 2
but just one request made by script.
after it i just add echo $keyword_webpage;
and see 2 keys, one with name "changes" second with my cached one.

**Comment by kirillDanshin** [comment]
Please, show your hashing function. It seems, you add time() result to your HF.
