### ISSUE TITLE
cache can't read after moving server

### ISSUE THREAD

**Issue by fajarfariyanton** [PHPSocialNetwork/phpfastcache#158]
hello.

i'm use sqlite cache without expired time. i have a lot of sqlite cache generate by phpfastcache.

next time, i'm moving from old vps to new dedicated server.

but why phpfastcache not read old cache.

can you help me?

**Comment by khoaofgod** [comment]
take a look at the PATH and if you move all the sqlite files on CACHE PATH to your new server, it should read, if the domain name is the same.

**Comment by fajarfariyanton** [comment]
yes i'm use same domain. and same PATH, my PATH is correct. but phpfastcache not read from old sqlite.

**Comment by mipapo** [comment]
Missing php5-sqlite?

**Comment by dansenjaya** [comment]
no, i'm succes create new cache with sqlite , but can't read old cache.

**Comment by dansenjaya** [comment]
sorry i'm use new github account because my old account is lost password email

**Comment by Geolim4** [comment]
Did you checked the chmod (777) ?
Also you may need to chown the directory as you changed the server, the uid may changed too.

**Comment by dansenjaya** [comment]
@Geolim4 can you give me example

**Comment by Geolim4** [comment]
Bash commands:
- `chown -R user your_cache_directory`
- `chmod -R 777  your_directory`
