### ISSUE TITLE
Unicode Problem

### ISSUE THREAD

**Issue by ibnbd** [PHPSocialNetwork/phpfastcache#164]
Cache working perfect and faster, but having problem with locale unicode support. In live version Unicode working perfect "নাগরিক টিভিতে আপনার প্রতিষ্টানের ইমেইজ। ভিডিও। ডিজিটাল বিজ্ঞাপন দিন।।" this is our Bangla Unicode text.

In cached version it becomes 
"à¦¨à¦¾à¦—à¦°à¦¿à¦• à¦Ÿà¦¿à¦­à¦¿à¦¤à§‡ à¦†à¦ªà¦¨à¦¾à¦° à¦ªà§à¦°à¦¤à¦¿à¦·à§à¦Ÿà¦¾à¦¨à§‡à¦° à¦‡à¦®à§‡à¦‡à¦œà¥¤ à¦­à¦¿à¦¡à¦¿à¦“à¥¤ à¦¡à¦¿à¦œà¦¿à¦Ÿà¦¾à¦² à¦¬à¦¿à¦œà§à¦žà¦¾à¦ªà¦¨ à¦¦à¦¿à¦¨à¥¤à¥¤" 

don't know what it is. any solution?

**Comment by Geolim4** [comment]
What is the driver you used ?

**Comment by Geolim4** [comment]
@ibnbd ? :)
