### ISSUE TITLE
You cannot serialize or unserialize PDOStatement instances

### ISSUE THREAD

**Issue by efyoung** [PHPSocialNetwork/phpfastcache#169]
I get this error when trying to do the basic cache:

Uncaught exception 'PDOException' with message 'You cannot serialize or unserialize PDOStatement instances'

Here is my code:

        $cache = phpFastCache();

        // Try to get $geo from Caching First
        // geo_results is "identity keyword";
        $geo = $cache->get("geo_results");

        if ($geo == null) {
            $geo = $this->connection->prepare("call sproc_qryGeo($latitude, $longitude, $radius, $numResults, $startPosition, $pageSize)");
            // Write geo results to Cache in 10 minutes with same keyword
            $cache->set("geo_results", $geo, 600);
        }

        // return geo results
        return $geo;

**Comment by khoaofgod** [comment]
you can cache RESULT ( array, object, string, number, null, ..etc ) , not a PDO statement

**Comment by efyoung** [comment]
So, how best would the above be written? I want to cache the results of my stored procedure.

**Comment by khoaofgod** [comment]
$geo = $this->connection->prepare("call sproc_qryGeo($latitude, $longitude, $radius, $numResults, $startPosition, $pageSize)");

After prepare, you have to Excute and Fetch() the object.
For example:
$stm = $this->connection->prepare("YOUR QUERY");
$stm->execute();
$geo_result = $stm->fetch();

HERE , you can cache ur $geo_result;
Try to look for PDO Prepare / execute / fetch

**Comment by efyoung** [comment]
That helped, but now my testing shows no cache. This is what I have now:

$cache = phpFastCache();

        // Try to get $geo from Caching First
        // geo_results is "identity keyword";
        $geo = $cache->get("geo_results");

        if ($geo == null) {
            // execute and fetch
            $sth = $dba->getGeo($latitude, $longitude, $radius, $numResults, $startPosition, $pageSize);
            $sth->execute();
            $geo = $sth->fetchAll();
            // Write geo results to Cache in 10 minutes with same keyword
            $cache->set("geo_results", $geo, 600);
            echo "NO CACHE";
        }

   // More code goes here

**Comment by efyoung** [comment]
Is it because I'm refreshing the page?

**Comment by Geolim4** [comment]
Try fetching as an array using `PDO::FETCH_ASSOC` :)

**Comment by nikmauro** [comment]
@Geolim4  https://www.wetransfer.com/downloads/c3b90b7bee0954e955ee9a91eae57d1520160205191615/10fe6a496881290b175bcdd154d1d08020160205191615/6295f1
