### ISSUE TITLE
Cache mysql_fetch_assoc

### ISSUE THREAD

**Issue by wetvibes** [PHPSocialNetwork/phpfastcache#170]
I spent over 3 hours to try makeing this php code cache with phpfastcache:

function getvalue($field, $table, $id)
{
    $sql = "select " . $field . " from " . $table . " where id = '" . $id . "'";
    $res = mysql_query($sql);
    if( $res ) 
    {
        $row = mysql_fetch_assoc($res);
        return $row[$field];
    }

}

Any help would much appreaciated. Thank you!

**Comment by khoaofgod** [comment]
$cache = phpFastCache();
$keyword = $field.$table.$id;
$data = $cache->get($keyword);
if($data === null ) {
       $data = getvalue($field, $table , $id );
       $cache->set($keyword, $data, 600 );
}
echo $data;

You can also cache level inside your function getValue , same logic , instead of echo data, you return data.

**Comment by wetvibes** [comment]
Thanks alot @khoaofgod for the fast reply. If you have 1 more minute to spare can you please tell me exactly how should i use phpfastcache with this function i mean the exact code. I really cant put it all together:

function getvalue($field, $table, $id)
{
    $sql = "select " . $field . " from " . $table . " where id = '" . $id . "'";
    $res = mysql_query($sql);
    if( $res ) 
    {
        $row = mysql_fetch_assoc($res);
        return $row[$field];
    }

}

Thank you!
