### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by wloske** [PHPSocialNetwork/phpfastcache#174]
Hi @khoaofgod,

I am having trouble with setting up phpFastCache. It seems that my settings array is being ignored. When I set up the storage engine statically `phpFastCache::setup('storage':'sqlite')` it is not being setup correctly. The engine used is `files` The path, also being set up statically, is being set correctly. 

```
phpFastCache::setup('storage','sqlite');
phpFastCache::setup('path','D:/cache/');
phpFastCache::setup('htaccess',false);

$cache = phpFastCache();

$cache->set('key','value',60);


echo $cache->get('key'); //value
var_export($cache);
```

The `var_export()` in the end gives this:
```
phpfastcache_files::__set_state(array(
   'tmp' => 
  array (
  ),
   'config' => 
  array (
    'storage' => 'sqlite',
    'default_chmod' => 511,
    'fallback' => 'files',
    'securityKey' => 'auto',
    'htaccess' => false,
    'path' => 'D:/cache/',
    'memcache' => 
    array (
      0 => 
      array (
        0 => '127.0.0.1',
        1 => 11211,
        2 => 1,
      ),
    ),
    'redis' => 
    array (
      'host' => '127.0.0.1',
      'port' => '',
      'password' => '',
      'database' => '',
      'timeout' => '',
    ),
    'ssdb' => 
    array (
      'host' => '127.0.0.1',
      'port' => 8888,
      'password' => '',
      'timeout' => '',
    ),
    'extensions' => 
    array (
    ),
  ),
   'fallback' => false,
   'instant' => NULL,
))
```

The desired `sqlite` engine is being used when I call `phpFastCache('sqlite')` but the htaccess setting is being ignored, too. When I create a setup array and call `phpFastCache('auto', $config)` it does not work, either. Also changing your file in `phpfastcache.php` from the project root, which is being included by the examples you provide, does _not_ work.

I am on Windows with Apache and php 7.

Thanks for looking into this.

**Comment by wloske** [comment]
Can you please explain why you closed this?

**Comment by Geolim4** [comment]
It was probably fixed :)

**Comment by wloske** [comment]
Might be. Might be not. ;-) ... I thought a little message would be nice or a link to a commit ...
