### ISSUE TITLE
Plesk server hosting error backup

### ISSUE THREAD

**Issue by nikmauro** [PHPSocialNetwork/phpfastcache#180]
Hello i have on application who use the phpfastcache file system.
The plesk 12.5 linux when run the daily back up return in this client this notice.

Not all the data was backed up into /var/lib/psa/dumps/clients/****/domains/**** successfully. For security reasons, backing up is performed on behalf of subscription's system user. This system user has no read access to: /var/www/vhosts/****/httpdocs/tmp/cache/cache.storage.****/09 /var/www/vhosts/****/httpdocs/tmp/cache/cache.storage.****/1d /var/www/vhosts/****/httpdocs/tmp/cache/cache.storage.****/4b So it was not backed up. All other data was backed up successfully. To fix this issue you may grant access read/write to the file or directory for system user "****" or "apache".

This client run PHP as FastCGI application server y Apache

Any suggestion?

**Comment by khoaofgod** [comment]
can you do chmod -R 0777 /var/www/vhosts/[client]/httpdocs/tmp/cache/cache.storage./
or do change own for  /var/www/vhosts/[client]/httpdocs/tmp/cache/cache.storage./ to same user with host client.
OR simple: 
setPath the cache to outsite httpdocs for it doesn't backup the cache.
Look like apache backup or system backup don't have permission to read that client's folder.
If you still can't handle it, I will try setup Plesk on my VM and see how the backup work.
