### ISSUE TITLE
Where I can download older version?

### ISSUE THREAD

**Issue by radiaku** [PHPSocialNetwork/phpfastcache#200]
Where I can download the older version? I still using php 5.3 and Currently using phpfastcache v2.1 but **_phpFastCache::$files_cleanup_after  = 1;_** doesnt work...

SS
![screenshot_3](https://cloud.githubusercontent.com/assets/5983350/12870889/cd6a7f5c-cd8c-11e5-8489-28cbc235d323.png)
and here my code
![screenshot_4](https://cloud.githubusercontent.com/assets/5983350/12870893/ecb8fec4-cd8c-11e5-9a0d-59ac081a35ef.png

Thanks :)

**Comment by Geolim4** [comment]
Hi,

The 2.1 is now pretty old ! You should consider to upgrade quickly  :)

Regards,
Georges

**Comment by khoaofgod** [comment]
here, on release page:
https://github.com/PHPSocialNetwork/phpfastcache/releases

**Comment by khoaofgod** [comment]
https://github.com/PHPSocialNetwork/phpfastcache/releases?after=3.0.8

**Comment by radiaku** [comment]
Yeah, i know 2.1 is old. But if its worked without vendorload stuff.

@khoaofgod thanks for replying.. i didnt see release link on your github.

**Comment by khoaofgod** [comment]
We will make sure new version support legacy code again.

**Comment by radiaku** [comment]
@khoaofgod
Thank you, its Wonderful...., so i can just simply include it?

Btw how setting limit cache? I still getting error using 3.10. The error lookalike ss in above?
