### ISSUE TITLE
4.0 release notes?

### ISSUE THREAD

**Issue by w3l** [PHPSocialNetwork/phpfastcache#219]
4.0 is a major bump, mostly interested in if 4.x breaks backward compatibility?

**Comment by khoaofgod** [comment]
yes, minimum php 5.3, everything else is same.
support autoload and legacy coding as 3.x

**Comment by Geolim4** [comment]
Indeed, we are working hard with the V4 to get the code much close as we can with psr standards.
For now we keep the legacy working, but you have to have to think at your code to be composer-compliant as soon as you can ;)

**Comment by w3l** [comment]
Thx, that helped! :smile:
