### ISSUE TITLE
Fatal error: Class 'phpFastCache' not found

### ISSUE THREAD

**Issue by olivermcruz** [PHPSocialNetwork/phpfastcache#223]
after pulling latest changes. I noticed there were major changes. My code used to work and i tried pointing phpFastCache.php to the new directory but im getting same problem. I tried using new methods and followed examples but nothing seems to work for me

Here is my sample code:
  require_once("libs/phpfastcache/src/phpFastCache/phpFastCache.php");
  phpFastCache::setup("redis",$REDIS_CONFIG);
  $PFC = phpFastCache('redis');

This used to work before the update

Thanks and great work!

**Comment by olivermcruz** [comment]
side note: i used predis instead of redis. Seems like class redis was not defined class prior to the new update.  Also my last checkout before the update was end of january if that helps. Thanks again!

**Comment by khoaofgod** [comment]
@olivermcruz 
phpFastCache::setup is not working.
Look at folder: examples/global.setup.php that file will tell you how to use version 4.
However, if you can go to release, and pull version 3 it stable too.

**Comment by olivermcruz** [comment]
@khoaofgod - Thanks for a quick response. 
I followed the examples/global.setup.php.
So my new setup looks like this:
    require_once("libs/phpfastcache/src/phpFastCache/phpFastCache.php");
    use phpFastCache\CacheManager;
    $config = array(
        "storage"   =>  "predis", //redis not working
        "redis" => $REDIS_CONFIG 
    );
    CacheManager::setup($config);
    $PFC = CacheManager::getInstance();

This setup is working for me the only issue was the storage "redis". I need to change it to "predis".
When im using "redis" storage, I'm getting this error message.
( ! ) Fatal error: Call to a member function connect() on a non-object in C:\wamp\www\theweddingexpert.com\libs\phpfastcache\src\phpFastCache\Drivers\redis.php on line 93

I dont know if this is a bug but i had the same issue on stable version. I figured using predis instead and "predis" work on both versions.

Thanks a lot this issue is solved.

**Comment by khoaofgod** [comment]
@olivermcruz 
oh, redis mean you have to setup "pecl install redis" on your server to make Redis extensions for PHP.
Incase your dont have access to server, phpFastCache built in "predis" to help people use redis without install PHP extensions.

**Comment by olivermcruz** [comment]
Predis is exactly what i needed. i dont like to adding extensions as much as possible. Thanks again!
