### ISSUE TITLE
@method Search for all drivers

### ISSUE THREAD

**Issue by olivermcruz** [PHPSocialNetwork/phpfastcache#224]
I noticed there is a new api search (unless it was already on version 3) i tried using this method
like this: $PFC->search('hello'); 
But im getting error 
( ! ) Fatal error: Uncaught exception 'phpFastCache\Exceptions\phpFastCacheDriverException' with message 'Search method is not supported by this driver.' in C:\wamp\www\theweddingexpert.com\libs\phpfastcache\src\phpFastCache\Core\DriverAbstract.php on line 172
( ! ) phpFastCache\Exceptions\phpFastCacheDriverException: Search method is not supported by this driver. in C:\wamp\www\theweddingexpert.com\libs\phpfastcache\src\phpFastCache\Core\DriverAbstract.php on line 172

Does this mean redis does not support search?

Thanks again

**Comment by khoaofgod** [comment]
right now Redis is not support search yes, the search is only work for files right now.
You can use Tags it work almost like search.
I will put search to global caching soon on next weeks.

**Comment by khoaofgod** [comment]
@olivermcruz  method @search added. Look at Examples: Search.YourCaching.Php

https://github.com/PHPSocialNetwork/phpfastcache/releases/tag/4.2.1
