### ISSUE TITLE
CachingMethod and Setup right syntax

### ISSUE THREAD

**Issue by nikmauro** [PHPSocialNetwork/phpfastcache#232]
* Please more explanation about right syntax setup and CachingMethod.
* The CachingMethod setting affect all storage types?
* The CachingMethod is proper to use as setup variable? ['','method'=>'fast','']
```PHP
    $config = array(
        "storage" => 'files',
        "path" => '::temp'
    );
    CacheManager::setup($config);
    CacheManager::CachingMethod("phpfastcache");
`

**Comment by khoaofgod** [comment]
yes, it's gonna effect all storage after call CachingMethod.
It come with 3 values: normal, fast, fastest ( default is fastest = phpfastcache )
or: normal, memory, phpfastcache.

On setup , you can put: cache_method = 1,2,3 ( default is 2 = fastest , 1 is normal , 3 is memory )

**Comment by nikmauro** [comment]
Thanks!
