### ISSUE TITLE
[Question] - How do I know when cache is getting full?

### ISSUE THREAD

**Issue by swatip-erosnow** [PHPSocialNetwork/phpfastcache#233]
I'm planning to use the lib extensively. Is there any way to know if cache is full? Depending on how much space I might want to delete some keys. Is the eviction policy handled in lib already?

Thanks

**Comment by khoaofgod** [comment]
for Files / Sqlite they store on disk, so, u can build a function get diskpace
Other caching use memory, and on Linux , sometime it show full memory, but actually not full yet, they are reserved memory for running apps faster. For memcached / Memcached, u can call their function to get available memory.

I will assigned this one and put them to a new function for next release on next 3 weeks.

**Comment by swatip-erosnow** [comment]
It would be better to have the method available in the lib. Without method will have atleast 2 handles to memcached. 
Also, I'm planning to use stats to find out more about hits and misses. Current stats() method does provide all the keys, corresponding size and write_time. Did I miss something?

**Comment by khoaofgod** [comment]
I will add this as function on next one,
Added to working list already.
Also, you will have 1 more function to see hit rate of phpfastCache
