### ISSUE TITLE
delete() does not work

### ISSUE THREAD

**Issue by akbaryahya** [PHPSocialNetwork/phpfastcache#234]
I just got an update, getting into trouble

delete(); not work in new update

```php
CacheManager::CachingMethod("phpfastcache");
$cachex = CacheManager::getInstance();
$cachex->delete($ver);
```

but when I use

```php
CacheManager::CachingMethod("normal");
$cachex = CacheManager::getInstance();
$cachex->delete($ver);
```

it works but is old?

when I tried to debug using
```php
$array = $cachex->stats();
print_r($array);
```
I think in latest version it does not delete because
```array
Array
(
    [info] => Array
        (
            [Total [bytes]] => 559
            [Expired and removed [bytes]] => 0 <- this
            [Current [bytes]] => 559
        )

    [size] => 559
    [data] => Array
        (
            [d08e5948ab68424bd483a52176aca86c] => Array
                (
                    [size] => 559
                    [write_time] => 1455978764
                )

        )

)
17
```
I'm using php 5.5/5.3, files, linux (CloudLinux?)
so what should I do now?
btw how do I enable debug?

**Comment by jahanna** [comment]
Same here, when phpfastcache is active delete method can't locate to instanced keyword.

On Core/DriverAbstract.php within delete method;

CacheManager::$memory[$this->config['instance']][$keyword]

This always returns null and can't find the index of $keyword.

Traditional trigger with;

 $this->driver_delete($keyword, $option);

Works.

**Comment by Geolim4** [comment]
We'll have a look , thanks for the report :)

**Comment by khoaofgod** [comment]
gotcha, i fix it now

**Comment by khoaofgod** [comment]
Fixed

**Comment by canc** [comment]
Hey @khoaofgod 
I'm having same problem. I've downloaded your latest release and i've memcached 1.4.21 running, but can't get delete() command work.

Any ideas? 
Thanks.

**Comment by khoaofgod** [comment]
are you on the latest version, @canc ?

**Comment by canc** [comment]
@khoaofgod yes. I downloaded again just a few hours ago.

**Comment by khoaofgod** [comment]
@canc I will reopen the ticket, give me couple hours tonight, I will test it, and fix it. Then you can download again.

**Comment by canc** [comment]
@khoaofgod thank you for your help, appreciated.

**Comment by Geolim4** [comment]
@canc 
Can you send me your phpinfo to contact@geolim4.com please ?
Thanks you !

**Comment by canc** [comment]
@Geolim4 sent, thanks!

**Comment by Geolim4** [comment]
Got it, thanks you :)

**Comment by Geolim4** [comment]
To be honest i will have a look this weekend cuz my week days are tiring :)

**Comment by canc** [comment]
hi @Geolim4, @khoaofgod 
any progress on this? or do you have any suggestions for a workaround?

thanks.

**Comment by khoaofgod** [comment]
@canc : can download get final commit and try again. Let me know. ( not the release )

**Comment by canc** [comment]
@khoaofgod tried it but no luck. still can't delete.

**Comment by canc** [comment]
hmm, this is interesting. your example code seems to work fine. i'll take a look again, looks like there's something wrong with my code.

![screen shot 2016-04-04 at 04 54 25](https://cloud.githubusercontent.com/assets/8061037/14236650/7225f844-fa21-11e5-82a7-3428a1dcc77d.png)

**Comment by canc** [comment]
i finally got it work! 
i changed my config completely with your memcached example (/examples/memcached.php) and boom! 

it's just weird that the config methods on your webpage ("Document") causing problems.

anyway, thanks for your support!
