### ISSUE TITLE
New methods suggestions

### ISSUE THREAD

**Issue by nikmauro** [PHPSocialNetwork/phpfastcache#235]
Hello here some suggestions  methods for new version!
```PHP
function clean_tags(){} //this method clean all cache tags
function clean_other(){} //this method clean cache set by name
function clean(){} //same function clean all cache tags and b name 
~~~

**Comment by Geolim4** [comment]
Hi @nikmauro, you can extends phpfastCache to implements 'em.
If you look closely to the driver interface they already exists:

https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/Core/DriverInterface.php
