### ISSUE TITLE
Config for memcache

### ISSUE THREAD

**Issue by swatip-erosnow** [PHPSocialNetwork/phpfastcache#238]
Hi,

I'm using memcache storage. I would like to make sure that if memcached isn't running, I would like to fallback on option files and path. However when I specify this, keys are always stored on files mentioned at a path under newly created folder with hostname. Here is the config for the same - 
CacheManager::setup(array(
		"storage"   =>  "memcache",
		"server"        =>  array(
				array("127.0.0.1",11211,1)),
		"overwrite"     =>  "files", // overwrote it in files until we have memcache server running
		"path"	=> "/tmp"
		)
);

What am I doing wrong?

Thanks,
Swati

**Comment by khoaofgod** [comment]
yes, when "overwrite" setup , it will use "files". So, remove that line.
I will take a look at the "fallback" , fallback is different setup. I will update this ticket when i get home
