### ISSUE TITLE
What about a mechanism concerning max cookie size to prevent 400 bad requests

### ISSUE THREAD

**Issue by DerDu** [PHPSocialNetwork/phpfastcache#241]
I'm not sure if this can be achieved but it would be nice to have. 

I. an automatically check of the current cookies size (before set) and

II.a) if it would exceed the 4kb border (=> III)
II.b) if it would not exceed the 4kb border (=> V.a)

III. it should remove the oldest cache item
IV. and re-check free space (till enough space for cache to set) (=> I)

V.a) set cache
V.b) or not set cache if too large to fit

**Comment by khoaofgod** [comment]
I see, ok, I added it to the list

**Comment by Geolim4** [comment]
Anyway cookie "cache" should be used for very small things, so we must simply trow an exception when the size is exceeded.

**Comment by koenpunt** [comment]
Cookie cache is actually not useful at all. Just set the correct expiry headers on the response and let the browser handle the caching.

**Comment by khoaofgod** [comment]
It's here:
https://github.com/PHPSocialNetwork/phpfastcache/releases/tag/4.3.13
Look at file: example/cookie.php have limited function there.
