### ISSUE TITLE
how we know php cache is working 

### ISSUE THREAD

**Issue by shoppingadda** [PHPSocialNetwork/phpfastcache#253]
how we know php cache is working after installing

**Comment by khoaofgod** [comment]
take a look at the cache folder, but it actually work or not, is up to how do you code your class.

**Comment by shoppingadda** [comment]
i just include this file on my header section of website  <?php   Include("phpfastcache/phpFastCache/phpFastCache.php");?>

**Comment by shoppingadda** [comment]
i opened my cache folder "phpfastcache" but tell me what i do on this folder because i want to know my phpFastCache is running or not??

**Comment by shoppingadda** [comment]
pls reply

**Comment by Geolim4** [comment]
Check with the api get() function.
If it return something then it's working :)

**Comment by shoppingadda** [comment]
bascially i just follow two step for installtion of phpfastcache ,

1. Click Download & Unzip
2. Include("phpFastCache/phpFastCache.php");

Its Enough ??

**Comment by khoaofgod** [comment]
You need to see Examples, and this is a Library for PHP projects. If you don't understand how to use a library, please hire a developer.

**Comment by shoppingadda** [comment]
actually i am also a developer but i m little bit confused, if you check this link then there is only two step given for phpcache installtion http://www.phpfastcache.com/   , i install and follow these steps but i am little bif confused
