### ISSUE TITLE
phpFastCache.php throwing fatal error

### ISSUE THREAD

**Issue by fredGDS** [PHPSocialNetwork/phpfastcache#254]
When calling phpFastCache() I keep getting a fatal error with this content ('PLEASE CREATE OR CHMOD ' . $full_path . ' - 0777 OR ANY WRITABLE PERMISSION!'). I have all files on the test server set to 777 so there should not be an issue with the permissions. It would be great if anyone knows how to solve that issue. :)

Btw: I just downloaded phpFastCache over composer so it should be the latest version

**Comment by khoaofgod** [comment]
Hi. Can u check that full path. To see if u can write there.

**Comment by fredGDS** [comment]
I just played around a little bit and if I change the code to:

        $tmp_dir = ini_get('upload_tmp_dir') ? ini_get('upload_tmp_dir') : sys_get_temp_dir();
        $path = $tmp_dir;
                
        $full_path = $path;
        $full_pathx = md5($full_path);

then it works. So I guess that the problem is somewhere with line 164:

else {
                $path = isset($_SERVER[ 'DOCUMENT_ROOT' ]) ? rtrim($_SERVER[ 'DOCUMENT_ROOT' ], '/') . '/../' : rtrim(__DIR__, '/') . '/';
            }

**Comment by khoaofgod** [comment]
@fredGDS thank you ^_^ I will update the code tonight

**Comment by khoaofgod** [comment]
Fixed it

**Comment by westy92** [comment]
I got this error, but it turned out to be a configuration error.  My `'path'` was set to `/cache` instead of `dirname(__FILE__) . '/cache'`.

**Comment by Geolim4** [comment]
@westy92 Please open a new issue if you have any issue.
Thanks :)
