### ISSUE TITLE
Memcache Problem on destruct

### ISSUE THREAD

**Issue by sv1gzf** [PHPSocialNetwork/phpfastcache#257]
Hi great work with the github project

I've been using it for a while. Recentry I downloaded the latest version 4.3.11

I have noticed that the $this->instant is NULL on
 if (!$this->instant->addserver($s[ 0 ], $s[ 1 ])) {
                        $this->fallback = true;
                    }

When the object is destroyed I get 
( ! ) Warning: Invalid argument supplied for foreach() in xxxxx/github/vendor/phpfastcache/phpfastcache/src/phpFastCache/CacheManager.php on line 165
Call Stack
#	Time	Memory	Function	Location
1	23.8497	53906704	phpFastCache\Core\DriverAbstract->__destruct( )	.../DriverAbstract.php:0
2	23.8497	53906704	phpFastCache\CacheManager::cleanCachingMethod( )	.../DriverAbstract.php:57
3	23.8498	53906704	phpFastCache\CacheManager::__CleanCachingMethod( )	.../CacheManager.php:154

**Comment by khoaofgod** [comment]
ok,
I update the code tonight together with other bugs.

**Comment by khoaofgod** [comment]
@sv1gzf I fixed it.
