### ISSUE TITLE
sqlite driver_get() not working

### ISSUE THREAD

**Issue by vatnoise** [PHPSocialNetwork/phpfastcache#258]
It was working before but today I've noticed it's not working (although only on localhost, on production it's still all good). Updated it to the latest version and same results.

I'm using the lazy method because there's no composer in our website system.
Tested CacheManager::setup("storage", "files") and that is working fine but "sqlite" is not for some reason.

I've also tried to debug it and basically when in gets to this line in driver_get:

     $stm = $this->db($keyword)
              ->prepare("SELECT * FROM `caching` WHERE `keyword`=:keyword LIMIT 1");

the browser just returns

    No data received

    ERR_EMPTY_RESPONSE

**Comment by khoaofgod** [comment]
Ok, I will take a look tonight too.

**Comment by khoaofgod** [comment]
@vatnoise I tested it on my localhost, and I don't see any problem.
Can you use examples/Sqlite.php and see how it works on your localhost and ur prods.

**Comment by khoaofgod** [comment]
Try pull new version that I just push today 4.3.12

**Comment by vatnoise** [comment]
> Can you use examples/Sqlite.php and see how it works on your localhost and ur prods.

prod:

    FIRST LOAD // WROTE OBJECT TO CACHE // RELOAD THE PAGE AND SEE // SQLite Cache --> Cache Enabled --> Well done !

    Back to index -- Reload

localhost:

    The connection was reset

    The connection to the server was reset while the page was loading.

        The site could be temporarily unavailable or too busy. Try again in a few moments.
        If you are unable to load any pages, check your computer's network connection.
        If your computer or network is protected by a firewall or proxy, make sure that Firefox Developer Edition is permitted to access the Web.

Tried 4.3.12 on localhost and got same results.
