### ISSUE TITLE
Search feature is not compatible with tags

### ISSUE THREAD

**Issue by tatet** [PHPSocialNetwork/phpfastcache#267]
I tried enabling search mode and then categorized my cache data into tags but did not work. I dived in the code and I could see that when the search mode is enabled overrides tags option with de "search" tag, maybe merging the array can fix the issue.

https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/Core/DriverAbstract.php#L109-L117

**Comment by khoaofgod** [comment]
thank you, I will commit the fix in 1-2 hours, and you can try again. I will let you know.

**Comment by khoaofgod** [comment]
@tatet : Fixed, you can try again ( not the release yet, just download the code from last commit )
https://github.com/PHPSocialNetwork/phpfastcache/archive/final.zip

and Let me know if it fix the problem / or just simple close the ticket.

**Comment by tatet** [comment]
Now works perfect!!! Thanks a lot!!

Best Regards.
