### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by Dimofinf-mark** [PHPSocialNetwork/phpfastcache#270]
PHP Fatal error:  Access to undeclared static property: phpFastCache\CacheManager::$memory in phpFastCache\CacheManager.php on line 163

**Comment by khoaofgod** [comment]
I will update it today and let u know.

**Comment by Dimofinf-mark** [comment]
thanks

**Comment by Dimofinf-mark** [comment]
Note: only in cache_method 3

**Comment by khoaofgod** [comment]
I don't see the problem. Can you try download the new final code and try again.
