### ISSUE TITLE
Delete Key with prefix ?

### ISSUE THREAD

**Issue by erhanharm** [PHPSocialNetwork/phpfastcache#271]
Hello
Thanks for this library. I searched but can not find this feature

My cache keys like   data_%dataid%
e.g.     data_123      data_356

So ı want to delete cache files like    data_*  
so how can i do that ?

Thanks in advanced
Erhan

**Comment by khoaofgod** [comment]
You can look at example folder, Tags and Search. They will do that
function.

**Comment by Geolim4** [comment]
You cal also store an array of your value and re-set/get it with unseted key :)

**Comment by khoaofgod** [comment]
You have to do like that with files cache. With other cache methods, they
have built in functions. You can call the driver and call their function
directly. Like Redis or Memcached.

**Comment by khoaofgod** [comment]
But the logic of work is the same.

**Comment by khoaofgod** [comment]
When you write a cache use Tag, and then you can use "deleteTags" to delete these cache. Or you can enable search, then look by keyname only and delete these keys.

**Comment by erhanharm** [comment]
Hi thanks everyone, 

But when i tried to search i got this error;

I use File cache. should i install sqlLite ? 


[PHP Fatal error:  Uncaught exception 'phpFastCache\\Exceptions\\phpFastCacheDriverException' with message 'SQLITE is not installed, cannot continue.' in /var/www/otokilik/src/phpFastCache/Drivers/sqlite.php:73\nStack trace:\n#0 /var/www/otokolik/src/phpFastCache/CacheManager.php(91): phpFastCache\\Drivers\\sqlite->__construct(Array)\n#1 /var/www/otokolik/src/phpFastCache/CacheManager.php(128): phpFastCache\\CacheManager::getInstance('Sqlite', Array)\n#2 /var/www/otokolik/src/phpFastCache/Core/DriverAbstract.php(672): phpFastCache\\CacheManager::__callStatic('Sqlite', Array)\n#3 /var/www/otokilik/src/phpFastCache/Core/DriverAbstract.php(672): phpFastCache\\CacheManager::Sqlite(Array)\n#4 /var/www/otokolik/src/phpFastCache/Core/DriverAbstract.php(720): phpFastCache\\Core\\DriverAbstract->_tagCaching()\n#5 /var/www/otokolik/src/phpFastCache/Core/DriverAbstract.php(265): phpFastCache\\Core\\DriverAbstract->getTags('search', false)\n#6 /var/www/otokolik/examples/Search.YourCaching.php(14): phpFastCache\\Core\\DriverAbstr in /var/www/otokolik/src/phpFastCache/Drivers/sqlite.php on line 73

**Comment by khoaofgod** [comment]
You can install SQLite, or you can go there and change it:
https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/Core/DriverAbstract.php#L665

change the work sqLite to Files
