### ISSUE TITLE
Search not working in between pages

### ISSUE THREAD

**Issue by on-d-mand** [PHPSocialNetwork/phpfastcache#273]
Currently we're implementing PHP fast Cache into one of our projects and have great results so far (thanks for that)!.

We are having issues with the search functionality on both APC and File storage where Search is only functional on the page where the cache was previously set. This can be easily reproduced by editing 'Search.YourCaching.php' running it once with both $cache->set functions and disable this on a second run.

We're writing cache with the table name as a partial identifier, wish to search for all caches regarding this table and then deleting all results (after a change in a relation table for instance).

Is this expected behaviour and should we fill search manually in a seperate cache or is this an issue (it seems odd you can't search between page calls...)

**Comment by khoaofgod** [comment]
can you create an examples file and send it to me khoaofgod@gmail.com to show me more details ( leave comment on source code, and output that you see on ur screen in comment ). I am not sure what's problem here. When you turn the search all, it store all Key Index to a database. so it should work with all pages before or after page calls.

**Comment by on-d-mand** [comment]
Hi Khoa, an e-mail has been sent to you with the example files.

For others reproduction can easily created by running the script and thus setting the cache and then just simply renaming set to get (and echo-ing) to see the values exist but are not searchable

**Comment by khoaofgod** [comment]
i got it, i will run the test.

**Comment by on-d-mand** [comment]
Hi Khao(ofgod?)

We've started looking into this issue since we're currently stuck with a inefficient custom clean up code for our tool and noticed that changing the "cache_method" in _tagCaching from 3 to 2 (Line 670) seems to fix searching in the examples and also in our own projects!. I'm unaware what the difference is between those 2 methods internally but this might give you an idea on where to look?

**Comment by on-d-mand** [comment]
Last issue we do find (can open a new ticket) is that the tags for the search are not cleaned after a delete.. Might be a minor thing I don't know.

**Comment by khoaofgod** [comment]
oh, that the fix memory bugs, I did release it on April 15th. Try it. I think it will fix your problem.

**Comment by on-d-mand** [comment]
Indeed! Would it be possible to mention the version nr somewhere in the code? Through composer I've received 4.3 which was stated as the latest version. But apparently online there is already a newer version in the GIT. In the code the version nr is never mentioned thus it is very hard to check if composer or the local repository is out of date

**Comment by khoaofgod** [comment]
hahaha. That's the problem, when we fixed bugs, we can't release the code to composer right that day, we have to wait until 15th or 1st of month for release new version. 
I will make a mailing list next month for any fix bugs will be send to mailing list, it will be better on keep track.
