### ISSUE TITLE
"Can't use this driver for your website" problem

### ISSUE THREAD

**Issue by hupengbuaa** [PHPSocialNetwork/phpfastcache#279]
`        $config = [
            'storage' => 'files',
            'path'  => '\path\to\cache'
        ]; `
   `     CacheManager::setup($config);`
   `     CacheManager::CachingMethod();`
  `      $cache = CacheManager::getInstance();`
The above is part of my code, just the same as the document, so why I get the problem. And unfortunately I couldn't google the problem out,  so little info of it. Sad~

**Comment by Geolim4** [comment]
What about ?

    $cache = CacheManager::getInstance('Files', ['path' => '\path\to\cache']);

**Comment by Geolim4** [comment]
Also is your directory writable and readable ? (Not outside php open_basedir)

**Comment by khoaofgod** [comment]
Closed the ticket since it was 7 days without new respones
