### ISSUE TITLE
All data is gone for seconds

### ISSUE THREAD

**Issue by val4o0o0** [PHPSocialNetwork/phpfastcache#283]
I using this beautiful cache class, but when my storage is files or sqlite numerous data is gone for 1 (one second) and shows again after that second.
I want to prevent that thing. How to do that ? Or I must use memcache type ?

**Comment by Geolim4** [comment]
Where did you put the $path config ?

**Comment by val4o0o0** [comment]
In my config file

```
$cache_config = [
  "path"      =>  "cache",
  "storage" => "sqlite",
];
```

**Comment by Geolim4** [comment]
your path must be an absolute path

**Comment by val4o0o0** [comment]
The cache/localhost is created and there is sqlite cache files (two) with information in them. Everything seem's to be ok.
Only information with numbers is hidden for one sec, the other one information with text and numbers is not hidden like the data with numbers only.

I try with:
` "path"      => __DIR__. "/cache",`
but not working for me.

I don't want to put self-written path like C:/program files/wamp bla-bla or something. If you know a way with function - tell me :)

**Comment by Geolim4** [comment]
__DIR__ returns an absolute path so it's fine. To be honest i have no idea of such behaviour o.O

**Comment by val4o0o0** [comment]
OK, i'll waiting someone with ideas how to fix this, because is annoying and people ask what's going on (where is the information)

**Comment by Geolim4** [comment]
did you have a "slow" I/O server performance ?
Sqlite can take a while especially when writing a lot of data.

**Comment by val4o0o0** [comment]
I'm on localhost. Sqlite and 'files' type working the same. The data with numbers only is hidden for one sec (when cache is expired and when is time to generate new - it shows again)

Here is some piece of code:
function get_total_sessions() {
global $link, $bb_prefix, $bb_db, $cacher;

$total_sessions= $cacher->get("total_sessions_from_forum");
if(is_null($total_sessions)) {
    $mysql=mysqli_query($link,"select session_user_id,COUNT(session_user_id) as count_sess from `$bb_db`.".$bb_prefix."_sessions s INNER JOIN `$bb_db`.".$bb_prefix."_users u ON u.user_id = s.session_user_id WHERE session_user_id <> 1 AND (session_time + 300) > UNIX_TIMESTAMP(NOW())") or die(mysqli_error($link));
    $fetchrow = mysqli_fetch_assoc($mysql);
    @mysqli_free_result($mysql);
    $cacher->set("total_sessions_from_forum",$fetchrow['count_sess'], 60);
}

return $total_sessions;
}

This one is return only numbers and have exact problem (with hiding).

**Comment by Geolim4** [comment]
You had the same issue with both Files and Sqlite drivers ?

**Comment by val4o0o0** [comment]
Yes, exactly. :)

**Comment by Geolim4** [comment]
I can't reproduce the problem right now :/

**Comment by khoaofgod** [comment]
both Files & SQlite based on I/O of HDD. When the HDD locked access because it reached full speed, the results will always return NULL. 
@val4o0o0  Try to use this on setup of phpFastCache:
cache_method => 2

This one will reduce I/O load for slow Hard Drive and multiple access on same caching on 1 script. Try this and let me know.

**Comment by val4o0o0** [comment]
Not working with cache_method => 2 too. The data is hiding again and again :)

**Comment by val4o0o0** [comment]
I try with memcache - all data is gone for forever now. This problem is only happen with numbers only.
Maybe the core can't catch numbers (something goes wrong and can't catch them)
Please, test memcache with simple as:

```
    $total_topics= $cache->get("total_topics_from_forum");
      if(is_null($total_topics)) {
        $cache->set("total_topics_from_forum",1423232, 60);
      }
   echo $total_topics;

```

**Comment by Geolim4** [comment]
What abotu casting to string ?

**Comment by val4o0o0** [comment]
I try with string too - not working.

**Comment by Geolim4** [comment]
Then i don't know what's wrong for now.
Maybe @khoaofgod will know something i missed :'(

**Comment by khoaofgod** [comment]
@val4o0o0 
Can you do me a favor?
Can you make an example file which will pre-produce this problem, and then send it to me at khoaofgod@gmail.com
For I can just run it, and debug the problem.

**Comment by val4o0o0** [comment]
I find the problem. Memcache php module is Enable, but memcached server is not installed. When the server is installed - everything is ok. But data is hiding again for one second and shows again after this second.
This happens when cache expire and data need to be overwritten in cache files (or memcache server)
I can make a video clip for you, to see what is happen. :)

**Comment by khoaofgod** [comment]
LOL. So, what are your solution for this one?

**Comment by val4o0o0** [comment]
I don't have a solution. I write here, to get a solution and fix this problem. I think that local files is the problem with this hiding process, but now when i using memcache now - everything is the same.
The data is hiding again.

I don't know, maybe this cannot be fixed...
I hope that php fastcache works in way with overwritting files / memory (not to delete and create new)
I have not seeing the core files of phpfastcache, just quickly integrate it into my CMS.
If anyone else has this problem, let writes ...
The problem is only noticeable if you constantly refresh the page.
You have to hit the exact moment in which phpfasttsache will overwrites information or creates a new (whatever that is)

**Comment by khoaofgod** [comment]
Okay,
I notice this ticket when I develop new features will try to handle this one.
