### ISSUE TITLE
Object of class IdiormResultSet could not be converted to string

### ISSUE THREAD

**Issue by mahmed-ntd** [PHPSocialNetwork/phpfastcache#284]
Cannot store object of class,

CacheManager::setup('path');
CacheManager::CachingMethod();
$cache_instance = CacheManager::Files();

**Comment by Geolim4** [comment]
You did it the wrong way, here is the good one:
$cache_instance = CacheManager::Files(array('path' => 'path to the cache'));

**Comment by mahmed-ntd** [comment]
Thanks @Geolim4 it worked now.

Really appreciate for your rapid reply.

**Comment by Geolim4** [comment]
You're welcome :)
