### ISSUE TITLE
Cannot create cache on Windows machine on non-standard ports

### ISSUE THREAD

**Issue by ylorant** [PHPSocialNetwork/phpfastcache#286]
Hey there,

This morning, I tried to set up remote debbuging tools for Chrome to debug my phone, and with that, I set up port forwarding to my phone on the 8080 port. And then, I got an error from PHPFastCache that couldn't create its cache folder named "localhost:8080" (using the files driver obviously). Indeed since I am on Windows, I can't create folders nor files with colons in them.

I think a quick and easy fix for this would be to substitute the ":" for an underscore "_" in the folder name (since it isn't used in domain names and it's allowed in file names everywhere).

**Comment by Geolim4** [comment]
Ok, i handle it.

**Comment by Geolim4** [comment]
Fixed, thanks you for your contribution.

:innocent:
