### ISSUE TITLE
Fatal error CacheManager.php on line 163

### ISSUE THREAD

**Issue by mpemburn** [PHPSocialNetwork/phpfastcache#289]
I'm running a script to retrieve a number of items from the cache.  It is doing this successfully, but, after everything is finished, I get this error:

PHP Fatal error:  Access to undeclared static property: phpFastCache\CacheManager::$memory in [path]vendor/phpfastcache/phpfastcache/src/phpFastCache/CacheManager.php on line 163

Doesn't appear to affect anything, but I'd prefer to have no mysteries in my code.  Thanks!

**Comment by khoaofgod** [comment]
Can you try the new latest commit and see if it fix the problem or not.
I remember this one was a bug from old version.

**Comment by mpemburn** [comment]
Thanks for your reply— and sorry for my delay in getting back to you.  I pulled from https://github.com/PHPSocialNetwork/phpfastcache and still see the same message.

Don't know if this makes any difference, but here's what I'm doing: using a file-based cache, I retrieve a  record containing ~1,200 keys.  I then iterate over those keys and retrieve data associated with them.  As I mentioned, no errors occur until everything has finished successfully.

**Comment by Geolim4** [comment]
Hi,
We can't find out the origin of this issue, as you can see that property is already well-defined:
https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/CacheManager.php#L40

Don't you, anytime in your code, unset this var ?
Regards,
Georges

**Comment by mpemburn** [comment]
Hi Georges,

Yes, I did look at this as soon as I encountered the error and no, I had no
reason to touch that part of the code.  What I can do, the next chance I
get, is to see what happens if I change the storage class and, if that
doesn't work, step the code to see I can find the point in the call stack
where it's changed.

Yours,

Mark

**Comment by Geolim4** [comment]
Can you temporary set this property to "protected" instead of public to identify out the code part that unset this var.

Thanks you,
Georges

**Comment by mpemburn** [comment]
Hi Georges,

I tried your suggestion this morning, and this was the result:

PHP Fatal error:  Cannot access protected property
phpFastCache\CacheManager::$memory in
.../vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/DriverAbstract.php
on line 149

Also, I only get the original error (CacheManager line 163) on our Linux
staging server (running PHP 5.6.11) and not on my Mac dev box (running
5.6.2) if this makes any difference.

Mark

**Comment by Geolim4** [comment]
Ok thanks you i will have a look tonight.
Georges

**Comment by Geolim4** [comment]
I really can't reproduce this bug. And there's no code that unset this var, it's always reset to "array()"
You may have a php memory leak (this occurs pretty often tho). Try to upgrade your php version to the last 5.6.x version (if possible).

Regards,
Georges
