### ISSUE TITLE
Cache clear permission denied  (v5 rc2)

### ISSUE THREAD

**Issue by reno1979** [PHPSocialNetwork/phpfastcache#294]
When not setting an explicit path the fastcache clear() function will try to delete all content in the dir retrieved from sys_get_temp_dir()

when I change my config to: 

`CacheManager::getInstance("files",array('securityKey'=>"long", 'path'=>sys_get_temp_dir()."/cache");
`
The phpfastcache clear mechanism will work.

ps. I all ready use a securitykey to create separate multiple instances

**Comment by Geolim4** [comment]
Can you try with the latest fix ?
(Not merged yet, so you have to hard-fix it)

**Comment by Geolim4** [comment]
448c49ce97ed55c3361e2365a0ebe90b8a9bd08c

**Comment by Geolim4** [comment]
Sorry i just realized that i pushed on the wrong branch....

**Comment by reno1979** [comment]
Your fix should do the trick, I'll hard-fix it for now. :) 

Thank you,

**Comment by reno1979** [comment]
fix works, but for now I'll explicitly set path in config to prevent te same errors on composer update etc

**Comment by Geolim4** [comment]
Ok, i will release it on master, thanks you.

**Comment by Geolim4** [comment]
Fixed on V5. If no bug appears, the release will be dispatched next week
