### ISSUE TITLE
getItem suggestion for improvement (v5 RC2) 

### ISSUE THREAD

**Issue by reno1979** [PHPSocialNetwork/phpfastcache#296]
In the getItem function (StandardPsr6StructureTrait.php) I noticed the use of array_key_exist()

In my experience using isset is significantly faster. (5 times) But be aware, isset() is testing if the key exists and if the value is not NULL

Perhaps worth testing. 

A nice blog: http://www.zomeoff.com/php-fast-way-to-determine-a-key-elements-existance-in-an-array/

**Comment by Geolim4** [comment]
Indeed, I always thought that array_key_exist was faster than isset (despite it's a structure control) due to the fact that isset checks if the key exist and is not null while array_key_exists just tests if the key exists.
Thanks for the benchmark, would you make a pull request for this ?

**Comment by reno1979** [comment]
Ok I will try

**Comment by Geolim4** [comment]
Ok, i give your some time to do it, anyway my stash is ready, just in case :smile:

**Comment by Geolim4** [comment]
Just donc forget to checkout on v5 ... :)

**Comment by reno1979** [comment]
Ok this can be closed, just read the explanation why the use of array_key_exist and it is a very good reason.

**Comment by Geolim4** [comment]
Ok thanks you :)
