### ISSUE TITLE
phpfastcache Support for MongoDB Driver

### ISSUE THREAD

**Issue by toutavous** [PHPSocialNetwork/phpfastcache#310]
phpfastcache doesn't appear to support MongoDB driver yet. Kindly add this to your to-do list.

**Comment by Geolim4** [comment]
Will be added for 5.1

**Comment by toutavous** [comment]
Thanks so much in advance. I never had the time to appreciate you both for such a wonderful cache solution. I look forward to it.

**Comment by Geolim4** [comment]
Thanks you to you for trusting on Pfc  :)

**Comment by Geolim4** [comment]
Planned in 5.1 as per [V5.1 Roadmap](https://github.com/PHPSocialNetwork/phpfastcache/blob/v5.1/V5.1-ROADMAP.md) :)

**Comment by Geolim4** [comment]
Would you like to provide me a ftp access with a test url where your 
server is installed ?

Mine just crashed and i do not have any other server on my hand :/
Thanks you,

Georges

**Comment by Geolim4** [comment]
@toutavous
