### ISSUE TITLE
tagging does not work with memcache

### ISSUE THREAD

**Issue by cotthemh** [PHPSocialNetwork/phpfastcache#327]
when you use tagging with the memcache driver this does not work you get a driver error:

Type: phpFastCache\Exceptions\phpFastCacheDriverException
Message: SQLITE is not installed, cannot continue.
File: /var/www/nelosproject/dist/api/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/sqlite.php
Line: 73
Trace

#0 /var/www/nelosproject/dist/api/vendor/phpfastcache/phpfastcache/src/phpFastCache/CacheManager.php(91): phpFastCache\Drivers\sqlite->__construct(Array)
#1 /var/www/nelosproject/dist/api/vendor/phpfastcache/phpfastcache/src/phpFastCache/CacheManager.php(128): phpFastCache\CacheManager::getInstance('Sqlite', Array)
#2 /var/www/nelosproject/dist/api/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/DriverAbstract.php(672): phpFastCache\CacheManager::__callStatic('Sqlite', Array)
#3 /var/www/nelosproject/dist/api/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/DriverAbstract.php(672): phpFastCache\CacheManager::Sqlite(Array)
#4 /var/www/nelosproject/dist/api/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/DriverAbstract.php(695): phpFastCache\Core\DriverAbstract->_tagCaching()
#5 /var/www/nelosproject/dist/api/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/DriverAbstract.php(116): phpFastCache\Core\DriverAbstract->_handleTags('testcache/1', 600, Array)
#6 /var/www/nelosproject/dist/api/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/DriverAbstract.php(689): phpFastCache\Core\DriverAbstract->set('testcache/1', '{"info":{"Total...', 600, Array)
#7 /var/www/nelosproject/dist/api/v1/articles.php(153): phpFastCache\Core\DriverAbstract->setTags('testcache/1', '{"info":{"Total...', 600, Array)

**Comment by Geolim4** [comment]
Hello,

This is most likely because your php installation does not include Pdo_Sqlite.
Check it out and try again later.

Cheers,
Georges

**Comment by cotthemh** [comment]
ye i looked into the code, actually tags only work when you install sql-lite, i think you should put that in the doc somewhere, because now its confusing, also im not sure i want to install sql lite on my server.

what would give the fastest results using phpfastcache?  now i use memcache but maybe something else is faster (its just standalone)

**Comment by Geolim4** [comment]
We will specify this in the V4 branch, anyway the V5 will fix this problem because the tags are stored in the same driver than items :)

**Comment by cotthemh** [comment]
Ok, great plan, so which driver you recommend on a server with plenty of memory? I want something ultra fast

Thx:)

H

**Comment by Geolim4** [comment]
Ssdb and Redis a both great and very efficient !
