### ISSUE TITLE
Argument 1 passed to phpFastCache\Core\DriverAbstract::driverUnwrapTime() must be of the type array, boolean given

### ISSUE THREAD

**Issue by phuyem** [PHPSocialNetwork/phpfastcache#330]
This just rarely happens but it is still a bug

	Argument 1 passed to phpFastCache\Core\DriverAbstract::driverUnwrapTime() must be of the type array, boolean given, called in /somepath/ow_libraries/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Files/Driver.php on line 122
	File: /somepath/ow_libraries/vendor/phpfastcache/phpfastcache/src/phpFastCache/Cache/DriverBaseTrait.php 

	Trace:

	#0 /somepath/ow_libraries/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Files/Driver.php(122): phpFastCache\Core\DriverAbstract->driverUnwrapTime(false)
	#1 /somepath/ow_libraries/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/StandardPsr6StructureTrait.php(55): phpFastCache\Drivers\Files\Driver->driverRead(Object(phpFastCache\Drivers\Files\Item))
	#2 /somepath/ow_libraries/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/ExtendedCacheItemPoolTrait.php(62): phpFastCache\Core\DriverAbstract->getItem('_TAG_friends.co...')
	#3 /somepath/ow_libraries/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/ExtendedCacheItemPoolTrait.php(122): phpFastCache\Core\DriverAbstract->getItemsByTag('friends.count')
	#4 /somepath/ow_libraries/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/ExtendedCacheItemPoolTrait.php(144): phpFastCache\Core\DriverAbstract->deleteItemsByTag('friends.count')
	#5 /somepath/ow_plugins/ext/classes/backend_phpfastcache.php(54): phpFastCache\Core\DriverAbstract->deleteItemsByTags(Array)
	.........................................................
 

My guess : 

in \phpfastcache\phpfastcache\src\phpFastCache\Drivers\Files\Driver.php

$object = $this->decode($content); 

not always return array.

Can I make a fix like this :  adding **!is_array($object) ||**

      if (!is_array($object) || $this->driverUnwrapTime($object)->getTimestamp() < time()) {
            @unlink($file_path);

            return null;
        }

**Comment by Geolim4** [comment]
I'll check it out. What's your Os/driver used?
Thanks you.

**Comment by phuyem** [comment]
It is Windows 10, Files driver . I proposed a fix actually, 

in \phpfastcache\phpfastcache\src\phpFastCache\Drivers\Files\Driver.php, line 122

adding !is_array($object) ||

   if (!is_array($object) || $this->driverUnwrapTime($object)->getTimestamp() < time()) {
        @unlink($file_path);

        return null;
    }

**Comment by Geolim4** [comment]
I will make some test, the weird part is that i'm testing on a strict environment, so this error should appeared before oO

**Comment by Geolim4** [comment]
Is that boolean true or false ?

**Comment by phuyem** [comment]
I just applied phpfastcache for around 1 week, no problem on Windows 10 so far.

The problem happened on our Production, which is ubuntu 16.04, the cache location is /tmp.  we are running nginx-fpm along with php command client for cron job. 

Merci pour la reponse rapide et le superbe lib :-)

**Comment by Geolim4** [comment]
Merci de lui faire confiance et de lui donner sa chance :)
Thanks for trusting it and giving it a try :)

I'm gonna made an additional check on the abstract class. May this will help.

**Comment by phuyem** [comment]
> Is that boolean true or false ?

False, I guess it may be some data corruption or something

#0 /somepath/ow_libraries/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Files/Driver.php(122): phpFastCache\Core\DriverAbstract->driverUnwrapTime(false)

the error looks minor but it does crash the whole flow... so I dunno if I should catch that error...

**Comment by Geolim4** [comment]
It must be true because this statement is true:

https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/Core/StandardPsr6StructureTrait.php#L57

**Comment by phuyem** [comment]
hmm, I see.. but wait you are showing line 57, but this error occurred at line 55

#1 /somepath/ow_libraries/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/StandardPsr6StructureTrait.php(55): phpFastCache\Drivers\Files\Driver->driverRead(Object(phpFastCache\Drivers\Files\Item))

and the log said it is a "false"

**Comment by Geolim4** [comment]
Weird, what do you have at line 122 ?
#0 /somepath/ow_libraries/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Files/Driver.php(122)

Can you dump the whole file on gist please ?

**Comment by Geolim4** [comment]
At line 57: https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/Core/StandardPsr6StructureTrait.php#L57

Can you replace 
```php
                if ($driverArray) {
```
with

```php
                if ($driverArray && is_array($driverArray)) {
```

**Comment by Geolim4** [comment]
@phuyem Is it working for you ?

**Comment by Geolim4** [comment]
@phuyem Bump !

**Comment by Geolim4** [comment]
@phuyem I need your confirmation before merging this patch, thanks !

**Comment by phuyem** [comment]
Sorry Geolim4 for the late reply. I was on vacation. 

Here is what I did in line 122 Driver.php

        if ($this->driverUnwrapTime($object)->getTimestamp() < time()) {
            @unlink($file_path);

            return null;
        }

=> 

        if (!is_array($object) || $this->driverUnwrapTime($object)->getTimestamp() < time()) {
            @unlink($file_path);

            return null;
        }

I guess your solution is better. But I just don't want to test since it is production and it is working with my fix. So I guess it is an OK from me.

Again thank you for your great library. 

Merci les gars!

**Comment by r0b-** [comment]
@phuyem: I have another code at line 122 in Files/Driver.php
@Geolim4: I think the is_array check will fix the issue for now, but I'm wondering why the decode returns a boolean instead of an array from time to time...

**Comment by Geolim4** [comment]
The main reason that the decode methods returns a boolean is that the serialized string is truncated or corrupted which leads unserialize to returns false. 
This leads me to the second question: Why the hell does the if() statement is true with false boolean passed through oO ?

**Comment by Geolim4** [comment]
@phuyem are you sure that you got the very latest version ?

**Comment by r0b-** [comment]
Hmm your're right and additional there should be an exception in the line before that (121) because driverUnwrapData() needs an array as well, but somehow it passes this call. 

Well I just updated my production environment to the latest version and if the error is thrown the next time I will take another look.

Anyways, I strongly encourage to add the is_array check!

**Comment by Geolim4** [comment]
Ok got it, i will fix it asap :)
