### ISSUE TITLE
Error Code 500 for fopen, fwrite and fclose

### ISSUE THREAD

**Issue by yad1995** [PHPSocialNetwork/phpfastcache#337]
I got this error 500 on phpfastcache module. I did not meddle with any of the files and I was merely clearing the cache then refreshed the site and got a error 500. Any help?

**Comment by Geolim4** [comment]
What's your php version ? It look like a server misconfiguration to me.

**Comment by Geolim4** [comment]
Hello @yad1995,

I’m closing this pull request _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the pull request / rebase your branch / clarify …).

Regards,
Georges.L
