### ISSUE TITLE
Warning: readdir() expects parameter 1 to be resource, string given in phpfastcache.php line 148

### ISSUE THREAD

**Issue by drakenm** [PHPSocialNetwork/phpfastcache#34]
Warning: readdir() expects parameter 1 to be resource, string given in phpfastcache.php line 148

I'm not quite sure what this means but here is my script:
$cache = phpFastCache();
$full_product_list = $cache->get("products");
if ($full_product_list == null)
        {
            $full_product_list = $dbh->fetch_rows($query_products);
            $cache->set("products",$full_product_list, 5); // 600
        }

**Comment by LisaYF** [comment]
still not

**Comment by Geolim4** [comment]
@LisaYF Please open a new topic if you got an issue, thanks you.
