### ISSUE TITLE
"Files is not installed or is misconfigured, cannot continue. (0)"

### ISSUE THREAD

**Issue by calebdre** [PHPSocialNetwork/phpfastcache#344]
I'm not sure what's happening, i'm going through the sample code on the wiki, but i get this error everytime. I install it via composer and Files directory and Driver file are there. 
  
How can I fix this issue?

**Comment by PhilHilton** [comment]
I've gotten this error when running under systemd and apache while trying to clear the cache. I suspect it's related to the pseudo private httpd systemd /tmp directories, but I'm not sure.

I had no luck trying to specify an alternate path.

I've been restarting apache (which deletes and creates a new /tmp/[random name]-httpd-blah/ directory) to simulate  a cache clearing as needed, which is rarely so it's not an issue for the moment.

Still, if anyone has any insight I'd be interested in hearing it.

**Comment by Geolim4** [comment]
Hi,

Are you sure that the $path is writable by Apache ?

Cheers,
Georges

**Comment by calebdre** [comment]
I'm actually using nginx for the server. Just to make sure, i'm specifying my own path inside of my project to dump the cache files like so:  
```php
CacheManager::setDefaultConfig(array(
    "path" => './cache',
));
$this->cache = CacheManager::getInstance("files");
``` 

I think the error is coming from this line:
https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/CacheManager.php#L111  
  
It can'ts find the instance here: https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/CacheManager.php#L103  
  
Is the `self::$instances` array supposed to be empty? I get an empty array when i `var_dump` it.

**Comment by calebdre** [comment]
Okay i just figured it out - it was the line the @Geolim4 mentioned. 

it wasn't automatically creating  the `/tmp/phpfastcache/project/files` directories. And then when i created it, I had to make the directory writable. I also had to make the `./cache/project/files` directory writable.

Thanks for your help @Geolim4 and @PhilHilton!

**Comment by Geolim4** [comment]
Thanks you to you for trusting on Pfc :)
Happy coding !!
