### ISSUE TITLE
ETA ON V.5?

### ISSUE THREAD

**Issue by ATouhou** [PHPSocialNetwork/phpfastcache#348]
Wondering about ETA on v.5? 
As to know if it's safe using this in a framework, without having to update everything pretty soon...
:-)

**Comment by khoaofgod** [comment]
we published V5 already. It's production right now.

**Comment by Geolim4** [comment]
Hi,

The V5 is fresh, you can be absolutely be quiet about using it in a framework.
However for the [V4 it's a bit different](https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%5D-Support-timeline) :)

The V5.1 is coming for Christmas and will not introduce api-breaking features. The V5.1 will be a core update of the V5 with some few core improvements.

For the Summer 2017 a V6 is planned for taking the full benefits of phpNG :)
However the V5 will live for some years, so you can be absolutely quiet about this !

Cheers,
Georges

**Comment by Geolim4** [comment]
You can rely on this class to detect any PhpFastCache API updates:
https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/Api.php

Please read carefully [this notice](https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/Api.php#L25) if you plan to rely on the API version.

**Comment by ATouhou** [comment]
Thanks for the quick answers :D 
Nice community you got going

**Comment by Geolim4** [comment]
This community is build on the trust of guys like you ;)
Have a nice day !
