### ISSUE TITLE
Call to undefined method phpFastCache\Drivers\Files\Driver::delete() 

### ISSUE THREAD

**Issue by mattheworres** [PHPSocialNetwork/phpfastcache#352]
Hi,
When I attempt to call `delete()` on a cache instance that is setup to use `files` storage method, I get this error:

`Call to undefined method phpFastCache\Drivers\Files\Driver::delete()`.

Here's how I'm using it:

```
use phpFastCache\CacheManager;


$cacheInstance = CacheManager::getInstance('files');
$cacheInstance->delete('itemKey');
```

Version I'm using is 5.0.8.

**Comment by Geolim4** [comment]
Hello @mattheworres 

Please see the Wiki: https://github.com/PHPSocialNetwork/phpfastcache/wiki#item-api
The code structure has changed as of the V5 :)

Cheers,
Georges
