### ISSUE TITLE
Files is not installed or is misconfigured, cannot continue

### ISSUE THREAD

**Issue by SimBioT1954** [PHPSocialNetwork/phpfastcache#353]
Updated to V5. 
On localhost everything is fine, on server I got this exception:
`Fatal error: Uncaught exception 'phpFastCache\Exceptions\phpFastCacheDriverCheckException' with message 'Files is not installed or is misconfigured, cannot continue.' in (PATH....)/example.com/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Files/Driver.php:49 Stack trace: #0 `

How can I solve this issue?

**Comment by Geolim4** [comment]
Hello,

Check if your path exists and is writable :)

Cheers,
Georges

**Comment by SimBioT1954** [comment]
@Geolim4  I'll check this out

**Comment by SimBioT1954** [comment]
@Geolim4 that's it. There was `"path" =>  "/files/cache"` instead of  `"path" =>  "files/cache"`

**Comment by Geolim4** [comment]
Np, happy caching !

**Comment by johnbasinger84** [comment]
phpFastCache\Exceptions\phpFastCacheDriverCheckException Object ( [message:protected] => Redis is not installed or is misconfigured, cannot continue.

**Comment by Geolim4** [comment]
Hello, please open up a new issue.
Thanks !
