### ISSUE TITLE
deleteItemsByTag(s) not remove item from pool right away

### ISSUE THREAD

**Issue by phuyem** [PHPSocialNetwork/phpfastcache#354]
Hello. 
Here is my observation of the issue: 

Case 1:

1. Invoke deleteItemsByTags return true
2. Then immediate invoke : getItem($key)->get(). **Expect  null  but the cached item**

Case 2

1. Invoke deleteItemsByTags return true
2. Then **later** invoke : getItem($key)->get().  return null  as expected 

 => Looking at deleteItemsByTag(s) , I see only **$result = $this->driverDelete($item);**, no logic for clearing thing from memory pool. So my gut feeling is that you are clearing the item separately / asynchronously

**Comment by Geolim4** [comment]
Hello @phuyem

What version are you using exactly ?
I don't see any code looking like `$result = $this->driverDelete($item);` actually.

Cheers,
Georges

**Comment by Geolim4** [comment]
Got it, it seems that issue has been fixed in 5.0.6, see 72dbeaed13c5af96444b91e8056dfcdc698d534f :)

**Comment by phuyem** [comment]
oh, really, let me checkout the latest code. Thank for the info

**Comment by phuyem** [comment]
updating did indeed solve the issue. What an awkward issue. 

Again thank you for your super quick reply.

**Comment by Geolim4** [comment]
Np. Happy caching :)
