### ISSUE TITLE
Right approach for using phpfastcache?

### ISSUE THREAD

**Issue by SimBioT1954** [PHPSocialNetwork/phpfastcache#355]
Hello, it's me again. As you know I have updated my code to V5 and now I have little question about this.

On current version I got more lines of code than before.

My code before update:
```php
$row = $app->cache->get('my_row');

if ($row === null) {

$row = 'some_value';

$app->cache->set('my_row', $row, 300);

}

print_r($row);
```
And for now something like this:

```php
$row_cache = $app->cache->getItem('my_row');
$row = $row_cache -> get();

if ($row === null) {

$row = 'some_value';

$row_cache -> set($row)->expiresAfter(300);
$app->cache->save($row_cache);

}
print_r($row);

```
Am I doing right?

**Comment by Geolim4** [comment]
Hello @SimBioT1954 

Here is a little guide to help you to migrate your code:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%5D-Migrating-your-code-to-the-V5

Cheers,
georges
