### ISSUE TITLE
phpfastcache issue

### ISSUE THREAD

**Issue by sandeepsmn** [PHPSocialNetwork/phpfastcache#356]
I have checked and try to implement phpfastcache code but I am bit confuse as you have mentioned the code below

<?php
    // In your config file
    // include("phpFastCache/phpFastCache.php"); or use "Composer" / Autoload
    use phpFastCache\CacheManager;

    $config = array(
        "storage"   =>  "files", // memcached, redis, ssdb, ..etc
        "path"      =>  "/your_cache_path/dir/",
    );
    CacheManager::setup($config); // look at folder "Examples" for more setup & config

    // In your Class, Functions, PHP Pages
    // First try to get from Cache first with an Identity Keyword
    $cache_keyword = "product page, item sku, md5(url), API url...";
    $products = CacheManager::get($cache_keyword);

    if(is_null($products)) {
        $products = "YOUR DB QUERIES RESULT AS OBJECT || ARRAY || HTML || GET_PRODUCTS_FUNCTION";
        // Cache your $products 600 seconds, phpFastCache will take care your heavy traffic.
        CacheManager::set($cache_keyword, $products,600);  // 0 = never expired
    }

    // LOOP | Output Your $products

Here it is clearly shown that we need to include phpFastCache/phpFastCache.php file but I am unable to find this file in code directory which I have downloaded through http://www.phpfastcache.com/ 

Please let me know the procedure to integrate it as I am doing code in core php.

**Comment by Geolim4** [comment]
Hi,
As of the V5 the syntax has changed.
Please check out the wiki:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%5D-Migrating-your-code-to-the-V5

It will help you to migrate from v4 syntax :)
Cheers,
Georges

**Comment by Geolim4** [comment]
Let me know if have any problem to implements the V5 :)

**Comment by sandeepsmn** [comment]
Hi,

I am unable to understand the actual process...when I am
running examples/legacy.php then I got below error message

http://192.168.3.28/phpfastcache-final/examples/legacy.php

I don't understand what is the error...please can you provide detailed
documentation.



*SMN Infocom Pvt. Ltd.*
SSRawat
+91 9988061971

**Comment by sandeepsmn** [comment]
sorry error msg

*Parse error*: syntax error, unexpected '[' in
*H:\spirewebs\shops\httpdocs\phpfastcache-final\src\autoload.php* on line
*27*

*SMN Infocom Pvt. Ltd.*
SSRawat
+91 9988061971

**Comment by Geolim4** [comment]
Please note that the V5 requires at least php 5.5.
Also the wiki is pretty clear, can you post me your code, or PM it on gist please ?
