### ISSUE TITLE
Warning: Ambiguous class resolution

### ISSUE THREAD

**Issue by meirlo** [PHPSocialNetwork/phpfastcache#357]
Hi,
I'm Getting this warning message after updating to 5.0.9.

Warning: Ambiguous class resolution, 
"phpFastCache\Drivers\Devnull\Item" 
was found in both ".../vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Devfalse/Item.php" 
and ".../vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Devnull/Item.php",
 the first will be used.

Also, the entire "Psr\Cache" namespace seems to be exists in the phpFastCache legacy folder,
while composer.json which require downloading it.

Thanks :)

**Comment by Geolim4** [comment]
Hi merlo,

I am unable to reproduce this error, which php version did you use ?

Also the Psr\Cache namespace is a purpose for people which does not makes use of composer.

Cheers,
Georges

**Comment by Geolim4** [comment]
Hum i may found the origin of the error, let me try something

**Comment by Geolim4** [comment]
The release 5.0.10 is out and fixes the issue.
Thanks you for your report :)
