### ISSUE TITLE
How can I integrate this library with CodeIgniter?

### ISSUE THREAD

**Issue by cyb3rwin** [PHPSocialNetwork/phpfastcache#364]
In older version, i use this way:
- Create file **FastCache.php** in application/libraries
```
<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Fastcache
{
    public function __construct()
    {
        require_once APPPATH.'third_party/phpFastCache/phpFastCache.php';
    }
}
```

- And in controller that need this library:

`use phpFastCache\CacheManager;`

But in newest version, I can't  

May be you can help me best way to integrate phpfastcache with codeigniter

**Comment by Geolim4** [comment]
Hello,

For the newest version you need to load the autoload and it will handle the rest.

Cheers,
Georges

**Comment by Geolim4** [comment]
Have a look at this file:
https://github.com/PHPSocialNetwork/phpfastcache/blob/final/examples/TestingFunctions.php

**Comment by cyb3rwin** [comment]
@Geolim4 Thanks, it work :)
