### ISSUE TITLE
Is it possible to "pause" PFC?

### ISSUE THREAD

**Issue by qahar** [PHPSocialNetwork/phpfastcache#368]
Looking at the wiki an googling it but cannot found information on how to temporary pause PFC.
If it's not possible for now, please consider to add this features. I hope it would be as simple as:
```
$cache = CacheManager::getInstance('files', array(
    'pause' => true, // clear cache and stop
));
```

**Comment by Geolim4** [comment]
Hi,

You can use another driver instead, like **Devnull** , it used to be be used this way :)

Cheers,
Georges

**Comment by qahar** [comment]
sorry to bother you again.

I try to clear chace with devnull driver but it's not work. This is my code.

`$cache_driver = is_file('.development') ? 'devnull' : 'files';
$cache = CacheManager::getInstance($cache_driver, array(
    'defaultTtl' => 3600, // 1 hour
));
if (is_file('.development')) {
    $cache->clear();
}`

Step:
1. $cache driver is 'files'
2. Change to driver 'devnull'
3. All cache is expired, as expected. Thank you.
4. After 10 minute use back 'files'
5. I have cache viewer and all cache from step-1 is back with expired-in 48 minute.

The docs state that it's possible to clear cache with 'devnull' driver. Does my code above wrong?

**Comment by thomich** [comment]
i made my own cache class, like in example https://github.com/PHPSocialNetwork/phpfastcache/blob/final/examples/extendedPhpFastCache.php

in my cache class i have own get/put methods, where i can decide to load data from cache or load directly..

maybe you also can do it like this, with a own cache class and needed methods..

**Comment by Geolim4** [comment]
The clear() method is distinct to the driver. Clearing Devnul ldriver wont clean Files drivers.

**Comment by qahar** [comment]
@Geolim4 now I understand why @thomich suggest to extend.
Thank you for the answer

**Comment by qahar** [comment]
After trying few thing, I found that it could be hard if using extending because each driver actually have different code to clear the cache. 
So I'm using simple method to use native driver and hope someone will find this usefull.

```
if (is_file('.development') && !is_file('.development_over')) {
    file_put_contents('.development_over', '1');
}

$cache_driver = is_file('.development') ? 'devnull' : 'files';
$cache = CacheManager::getInstance($cache_driver, array(
    'defaultTtl' => 3600, // 1 hour
));

if (!is_file('.development') && is_file('.development_over')) {
    unlink('.development_over');
    $cache->clear();
}
```

**Comment by Geolim4** [comment]
As of the V6 there's an "ActOnAll" helper:

https://github.com/PHPSocialNetwork/phpfastcache/blob/V6/src/phpFastCache/Helper/ActOnAll.php

Warning: This helper will act on driver which has been initialized at least only once time (using getInstance).
