### ISSUE TITLE
Load PhpFastCache in Class

### ISSUE THREAD

**Issue by hatimdisawala** [PHPSocialNetwork/phpfastcache#369]
Hi,

I need to load phpfastcache library in a class and initialize library in __construct() function and want to run code in public function. How to do that?

**Comment by thomich** [comment]
Hey @hatimdisawala 

Have you checked the example: https://github.com/PHPSocialNetwork/phpfastcache/blob/final/examples/extendedPhpFastCache.php?

thomi

**Comment by Geolim4** [comment]
Hello,

@thomich said everything :)

Cheers,
Georges
