### ISSUE TITLE
PHP Notice:  Method "setup" is deprecated and will be removed in V6 Use method "setDefaultConfig" instead

### ISSUE THREAD

**Issue by rafaelspecta** [PHPSocialNetwork/phpfastcache#370]
I am getting the followin error in the final and 6 branches

PHP Notice:  Method "setup" is deprecated and will be removed in V6 Use method "setDefaultConfig" instead. in /Users/rafaelsantos/Workspace/flow-engine/vendor/phpfastcache-6/src/phpFastCache/CacheManager.php on line 228

**Comment by Geolim4** [comment]
Hi,

Then you must follow the provided message, that's pretty clear ;)
Replace the use of ``setup()` with `setDefaultConfig()`

Cheers,
Georges

**Comment by rafaelspecta** [comment]
Sorry... I thought that message was from PHP core not from inside your code... Got it

**Comment by Geolim4** [comment]
It's a E_USER_DEPRECATED error :)
It cannot be from Core, as the core returns E_DEPRECATED errors.

Happy cahing,
Georges
