### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings

### ISSUE THREAD

**Issue by rafaelspecta** [PHPSocialNetwork/phpfastcache#371]
I am getting the following error on final and 6 branches.

PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /.../vendor/phpfastcache-6/src/phpFastCache/Drivers/Files/Item.php:39
Stack trace:
#0 /.../vendor/phpfastcache-6/src/phpFastCache/Drivers/Files/Item.php(39): DateTime->__construct()
#1 [internal function]: phpFastCache\Drivers\Files\Item->__construct(Object(phpFastCache\Drivers\Files\Driver), 'teste')
#2 /.../vendor/phpfastcache-6/src/phpFastCache/Core/Pool/CacheItemPoolTrait.php(65): ReflectionClass->newInstanceArgs(Array)
#3 /.../vendor/phpfastcache-6/src/phpFastCache/Drivers/Files/Item.php on line 39

**Comment by Geolim4** [comment]
Hi,

This due to a misconfiguration in your php.ini
Add this to your php.ini:

`date.timezone = Europe/Paris`

Cheers,
Georges
