### ISSUE TITLE
Cache dissapear

### ISSUE THREAD

**Issue by ZeroTheon3** [PHPSocialNetwork/phpfastcache#374]
I have two scripts currently on my server. One is for creating cache and the other is for reading it.
When i run the writting script (30 times with unique 'hash' per 5 sec) i can read them in my second script. But after few refreshes of my reading script they just dissapear and get recreated (list gets empty and then it slowly gets filled again).

Is this a phpfastcache problem? or i am doing something wrong

Writing:
```
<?php
	require __DIR__ . '/vendor/autoload.php';
	use phpFastCache\CacheManager;
	use phpFastCache\Core\phpFastCache;	
	CacheManager::setDefaultConfig([
		  "path" => "/files/",
		]);
	$InstanceCache = CacheManager::getInstance('files');

	$hash = //one of 30 random hashes from POST

	$InstanceCache->save($InstanceCache ->getItem($hash)
		->set((new DateTime())->getTimestamp(), 0)
		->addTag('ActiveComputer'));
```

Reading:
```
<?php
	require __DIR__ . '/vendor/autoload.php';
	use phpFastCache\CacheManager;
	use phpFastCache\Core\phpFastCache;	
	CacheManager::setDefaultConfig([
		  "path" => "/files/",
		]);
	$InstanceCache = CacheManager::getInstance('files');
	$items = $InstanceCache->getItemsByTag('ActiveComputer');

	foreach ($items as &$item) {
		echo $item->get()."\r\n";
	}
```

**Comment by Geolim4** [comment]
Hi,

The "Files" cache is not intended to be used for 30 writing operation/sec, use Redis/SSdb for intensives usages.

Also you don't use set() method well. There's no 2nd argument on it.
Use: `set((new DateTime())->getTimestamp())->expireAfter($ttl)`

Cheers,
Georges

**Comment by Geolim4** [comment]
Also:

/files/ is an absolute path which is wrong here, you must put your absolute script path a relative path from your working dir :)
