### ISSUE TITLE
V6 predis error

### ISSUE THREAD

**Issue by nikmauro** [PHPSocialNetwork/phpfastcache#375]
Fatal error: phpFastCache\Drivers\Predis\Driver and phpFastCache\Core\Pool\DriverBaseTrait define the same property ($instance) in the composition of phpFastCache\Drivers\Predis\Driver. However, the definition differs and is considered incompatible. Class was composed in /vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Predis/Driver.php on line 29

**Comment by Geolim4** [comment]
Does this appears on V5 too?

**Comment by nikmauro** [comment]
I have the v5 up and running without problems!

**Comment by Geolim4** [comment]
Please test it :)

**Comment by Geolim4** [comment]
Feel free to let me know if it's still not working :)
