### ISSUE TITLE
$InstanceCache->save(); does not persist

### ISSUE THREAD

**Issue by pinksharpii** [PHPSocialNetwork/phpfastcache#377]
The documentation is very confusing. I'm trying to figure out which lines of code belong in which files. In my project I have an includes.php. Here I have:

    `use phpFastCache\CacheManager;

	// Setup File Path on your config files
	CacheManager::setup(array(
	    "path" => DOC_ROOT . '/cache', 
	));`

And in an included file, event.php, I have a function that pulls events from the database. I want to cache these results. In my function I use.

`$InstanceCache = CacheManager::getInstance('Memcache');
		$CachedQuery = $InstanceCache->getItem('event_list');
		
		if (!is_null($CachedQuery->get()))
		{
			return $CachedQuery->get();
		}`

But it never goes into the if conditional. It always goes through the rest of the function and completes the database query. At the very end of my query code I have:

`$CachedQuery->set($event_list)->expiresAfter(CACHE_EXPIRES); //CACHE_EXPIRES is 120
$InstanceCache->save($CachedQuery);`

When I print $CachedQuery after this, it looks good. But when I refresh the page, $CachedQuery is empty. It does not persist. What am I doing wrong?

**Comment by Geolim4** [comment]
Hello don't you forget to set the data?,

**Comment by Geolim4** [comment]
Also which version (v5/v6) and driver are you using (Files i guess) ?

**Comment by pinksharpii** [comment]
I am setting the data. I said:
$CachedQuery->set($event_list)->expiresAfter(CACHE_EXPIRES);

$event list is my array of events from the DB.

The driver is Memcache like stated above.
I would assume I'm using v5? I don't know how to tell. I just downloaded the latest from Composer.

**Comment by pinksharpii** [comment]
So I got it to work by changing Memcache to files. 
However, I still have a question on expiresAfter(). There is no clear documentation on what that value should be. I have it to be 120 (60 sec * 60 mins), so one hour. Is this correct? 
What should this value be?

**Comment by Geolim4** [comment]
It's documented here:

https://github.com/PHPSocialNetwork/phpfastcache/wiki#item-api

It's a ttl (time to live).
Also don't use `!is_null($CachedQuery->get()` but `$CachedQuery->isHit()` which is more appropriate.

Cheers,
Georges

**Comment by pinksharpii** [comment]
What does TTL mean though? Is it a number like I have? (60*60)? Is it a date()? a time()?

Also your example on the website uses !is_null(). If that's not the best way to do it, you should change the example.

**Comment by Geolim4** [comment]
is_null ensure you that the value _is not null_ ofc :)
isHit ensure you that the value is effectively extracted from the cache, whenever the value is null or something else

On the example I make use of _is_null_ because I expect that the "value" NULL can be cached from a no database result.

$ttl like defined in [phpDoc](https://github.com/PHPSocialNetwork/phpfastcache/blob/final/bin/legacy/Psr/Cache/src/CacheItemInterface.php#L92) is expected to be Int|DateInterval :)

Cheers,
Georges

**Comment by Geolim4** [comment]
If it's working I'm closing this right issue.
Feel free to re-open it if you have any additional question/comment, Kayla.

Cheers,
Georges
