### ISSUE TITLE
expired used timestamp

### ISSUE THREAD

**Issue by cm060210216** [PHPSocialNetwork/phpfastcache#380]
use as files cache, I try to set expire after 2038 , get cache once, destroy the file.

**Comment by Geolim4** [comment]
Hi, can you provide me more details please ? 
Thanks you.

**Comment by Geolim4** [comment]
Hello @authorname,

I’m closing this pull request _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the pull request / rebase your branch / clarify …).

Regards,
Georges.L
