### ISSUE TITLE
Relative path returned by `Directory::getAbsolutePath`

### ISSUE THREAD

**Issue by bukowskiadam** [PHPSocialNetwork/phpfastcache#381]
Testing #373 I've found issue introduced by commit 23eee898537799fc312974c06b4617da3e8da3ce
Method `\phpFastCache\Util\Directory::getAbsolutePath` returns relative path on linux system - e.g. `srv/http/test`, instead of `/srv/http/test`, which causes that my cache is stored in directory `/srv/http/test/srv/http/test/cache/cli/Files/...`
Both branches are affected V6 and final. Are you developing on Windows? Probably on windows absolute path does not begin with `DIRECTORY_SEPARATOR` and such issue should not occur. I don't have any windows instance to test it out.

**Comment by bukowskiadam** [comment]
I've made two pull requests for two branches (I can't find any option to make this at once).

There were couple of methods to solve this issue. We could detect OS from `PHP_OS`, but according to [this SO thread](http://stackoverflow.com/questions/738823/possible-values-for-php-os) and my knowledge only *nix systems use starting slash and it's always slash.

**Examples of root paths**:

- Unix\linux\Mac OS X: /
- OS/2: C:\
- Amiga: dh0:

So I think that it should be working ok.

Best regards,
Adam

**Comment by jfcherng** [comment]
why not

```php
    // prepend directory separator for non-Windows OS
    $absolutes = '/' === (__FILE__)[0] ? [ '/' ] : [];
```

**Comment by bukowskiadam** [comment]
You're right that I could use `(__FILE__)[0]`, but you can't set `$absolutes` to `/`, because from `[ / , srv , test ]` after implode you'll get `//srv/test`. Also for path traversal it won't work, because from path `/srv/../../cache`, you should get `/cache`, and with your suggestion array_pop will cause to pop root slash and you'll get `cache`

**Comment by Geolim4** [comment]
The V5 must remain php 5.5 compatible. 5.6 for the v6

**Comment by Geolim4** [comment]
Also please make use of DIRECTORY_SEPARATOR constant thanks 🤗

**Comment by Geolim4** [comment]
Ok looks good, I'll run some additional tests @ home tonight.
Thanks you.

**Comment by Geolim4** [comment]
Merged, thanks :)
