### ISSUE TITLE
Temporarily disable the cache system

### ISSUE THREAD

**Issue by LaVieh** [PHPSocialNetwork/phpfastcache#387]
Any possible way to set a variable and temporarily disable the cache system with it?

**Comment by Geolim4** [comment]
Hello

Use Devnull driver, i will make a Wiki for that :)

Cheers,
Georges

**Comment by Geolim4** [comment]
Here's the Wiki:

https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV5%CB%96%5D-Disabling-PhpFastCache

Cheers,
Georges
