### ISSUE TITLE
Path issues

### ISSUE THREAD

**Issue by ricardodavidsoares** [PHPSocialNetwork/phpfastcache#390]
Hii, first of all, congrats for your work. I been using phpFastCache for a while, but now I want to integrate it with an Yii project.
I been using it with another application, that gets stock exchange data and saves it on a file. Now I just want this new Yii project to read from that file. My problem is, when I define the path to the existing file, in Yii, phpFastCache adds four directories to that specified path. Like I have the file in /temp/blabla (an example) and when I set the path in Yii with "$config = ['storage' => 'files', 'path' => /temp/blabla'];
$InstanceCache = CacheManager::getInstance('files', $config);" it tries to read from "/temp/blabla/localhost/Files/files/39".
I just want a help to make it search in the final path I set, and not add any other subdirectory.

Thank you in advance. Best regards.

**Comment by Geolim4** [comment]
Hello,

It's not a bug, it's a feature :)
We made this in order to make the PhpFastCache directory more structured.
Therefore there's no risk to overwrite data of other drivers/cache instances.

Cheers,
Georges

**Comment by ricardodavidsoares** [comment]
Hi,

I know it wasn't a bug but a feature :)
What I was wondering is if I can't disable that subdirectory creation, because the older project that saves the data doesn't do it that way. So is hard to integrate them. Because, even tho' I define the same path in both, one saves in the folder I set on path while the other searches in a subdirectory it makes on that folder.
(They're different projects because one was made a while ago, without framework, and the new one is with Yii framework)

**Comment by Geolim4** [comment]
In that case you can set the securityKey that will override the automatic http_host set as the securityKey.
Or maybe i don't understand well your demand ?

Cheers,
Georges

**Comment by ricardodavidsoares** [comment]
Hii,
I finally found a solution. I figured out that the projects were using two really different versions and so the structure of the cache folder and file names were different. Basic error. I'm sorry for it and thank you for replying to my problem. Really appreciate it.


Best regard,
Ricardo :)
