### ISSUE TITLE
Memcached is not installed or is misconfigured, cannot continue.

### ISSUE THREAD

**Issue by Endzeitlive** [PHPSocialNetwork/phpfastcache#394]
Hello,

i dont know what i'm doing wrong.

i installed "apt-get install memcached php5-memcache" and i'm using the examples files.

**Comment by Geolim4** [comment]
Hello,

Did the memcache daemon is running (and installed ofc) ?


Cheers,
Georges

**Comment by 4b42** [comment]
Hello

try:
`service php5-fpm restart` or `/etc/init.d/php5-fpm restart`
it worked for me

**Comment by Geolim4** [comment]
Hello @authorname,

I’m closing this pull request _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the pull request / rebase your branch / clarify …).

Regards,
Georges.L
