### ISSUE TITLE
Path issues 

### ISSUE THREAD

**Issue by Tim456** [PHPSocialNetwork/phpfastcache#399]
Hello,

I am successfully running v4 locally (WAMP) and on my hosting. For some reason I am not able to run v5 nor v6 locally and on my hosting. I am testing to code provided in the examples; files.php. 

PHP Version:
WAMP: 5.5.12
Hosting: 7.1

While testing v5 and v6 on my hosting I don't see any errors, just a blank page. But locally I see the following errors:

## **[1]**
When using "require 'autoload.php';"
Fatal error: Cannot locate the Psr/Cache files in E:\wamp\www\v5\autoload.php on line 35

Call Stack
#	Time	Memory	Function	Location
1	0.0000	136432	{main}( )	..\index.php:0
2	0.0000	176640	phpFastCache\CacheManager::getInstance( )	..\index.php:20
3	0.0000	177920	spl_autoload_call ( )	..\index.php:107
4	0.0000	177968	{closure:E:\wamp\www\v5\autoload.php:21-46}( )	..\index.php:0
5	0.0468	213928	require_once( 'E:\wamp\www\v5\phpFastCache\Drivers\Files\Driver.php' )	..\autoload.php:44
6	0.0468	214136	spl_autoload_call ( )	..\autoload.php:31
7	0.0468	214184	{closure:E:\wamp\www\v5\autoload.php:21-46}( )	..\autoload.php:0
8	0.0624	220488	require_once( 'E:\wamp\www\v5\phpFastCache\Core\DriverAbstract.php' )	..\autoload.php:44
9	0.0624	220728	spl_autoload_call ( )	..\autoload.php:26
10	0.0624	220792	{closure:E:\wamp\www\v5\autoload.php:21-46}( )	..\autoload.php:0
11	0.0624	247080	require_once( 'E:\wamp\www\v5\phpFastCache\Cache\ExtendedCacheItemPoolInterface.php' )	..\autoload.php:44
12	0.0624	247288	spl_autoload_call ( )	..\autoload.php:27
13	0.0624	247336	{closure:E:\wamp\www\v5\autoload.php:21-46}( )	..\autoload.php:0
14	0.0624	247928	trigger_error ( )	..\autoload.php:35

## **[2]**
When using "require 'phpFastCache/CacheManager.php';"
Fatal error: Class 'phpFastCache\Drivers\Files\Driver' not found in E:\wamp\www\v5\phpFastCache\CacheManager.php on line 107

Call Stack
#	Time	Memory	Function	Location
1	0.0000	136448	{main}( )	..\index.php:0
2	0.0030	171200	phpFastCache\CacheManager::getInstance( )	..\index.php:20

I am a PHP noob so please be patient with me.

**Comment by Geolim4** [comment]
Did you included all the project files ?
For non-composer users, you must include the autoload.php in your project.
Also the bin/src dirs must be present :)

**Comment by Tim456** [comment]
Thank you for the quick reply. I didn't know that I had to include the 'bin' dir as well. Just tested everything locally and on the hosting without any problems. 

Thank you.

**Comment by Geolim4** [comment]
Yeah you must include the whole lib directories :)
