### ISSUE TITLE
Redis is not installed or is misconfigured, cannot continue.

### ISSUE THREAD

**Issue by gracedigital** [PHPSocialNetwork/phpfastcache#400]
If we set the driver to "predis" it works...
phpFastCache\CacheManager::getInstance('predis');

However, if we set the driver to "redis"...
phpFastCache\CacheManager::getInstance('redis');

I get the error:
Redis is not installed or is misconfigured, cannot continue.

Are there any other requirements to interface with redis directly?  Do we need the PHP-REDIS extension installed first?

**Comment by Geolim4** [comment]
Yep exactly :)

**Comment by Geolim4** [comment]
Let me know if it's working,

Cheers,
Georges

**Comment by gracedigital** [comment]
Yes. That did it.

**Comment by Geolim4** [comment]
Ok nice ;)
