### ISSUE TITLE
deleteItemsByTags should have 'and' not 'or'

### ISSUE THREAD

**Issue by piernik** [PHPSocialNetwork/phpfastcache#404]
I'm using version 5.0.
I think that method `deleteItemsByTags` should delete only those keys that have ALL given tags. I think now it deletes using OR statment.

If I want to use OR I would use `deleteItemsByTag` in loop.

**Comment by Geolim4** [comment]
Hi @piernik

This is the intended behavior, all items that contains one of these tags will be deleted.
I can consider adding an optional argument (AND/OR/XOR) but as of the V6 exclusively since the v5 wont receive such major changes anymore.

Cheers,
Georges

**Comment by Geolim4** [comment]
Hi @piernik

To be honest i tried today to implement a logical strategy using OR/AND/XOR operators and the result is a disaster:

1) I lost a lot of performances (about more than 30%) with many-tagged items
2) The code became unreadable and unmaintainable
3) The Interfaces looked ugly as hell 
4) The compromise features/performances was not very satisfiable IMO
5) The V6 approaching the Gold release soon, i wont take the risk to implement such a major change

Cheers,
Georges

**Comment by piernik** [comment]
Maybe adding extra method? `deleteItemsByTagsAll`?

**Comment by Geolim4** [comment]
@piernik 

This is a considerable option and a nice compromise that I can plan for the V6.
But for more logic I have to make the same change for:

- GetItemsByTags
- IncrementItemsByTags
- DecrementItemsByTag

I'll let you know when it'll be implemented.

**Comment by Geolim4** [comment]
As per: https://github.com/ideawu/ssdb

Persistent key-value, key-zset, key-map('hashmap') storage

So i would say "yes" ?

**Comment by Geolim4** [comment]
Ohhh and also:

- AppendtemsByTags
- PrependtemsByTags

 :sweat:

**Comment by Geolim4** [comment]
@piernik

Please test the V6 :)
_On Github, not packagist, I don't have released yet._

Cheers,
Georges

**Comment by piernik** [comment]
Thanks very much... I'll test it.

**Comment by Geolim4** [comment]
Great, take your time, make more tests, I'll let this issue open for one or two more days.

Cheers,
Georges.

**Comment by Geolim4** [comment]
The issue has been fixed, thanks you for your contribution :thumbsup:

_Geolim4_
