### ISSUE TITLE
PHP7 + mongodb driver

### ISSUE THREAD

**Issue by git-webmaster** [PHPSocialNetwork/phpfastcache#405]
###Configuration:

PhpFastCache version: 5.0.12
PHP version: 7.0.14
Operating system: Debian 8 x64 (+ Win10, same problem)

####Issue description:

Hi.
I was uanble to make cache run with mongodb driver under any environment i tried: php7 on debian /  php7 on windows (both mongodb lib from PECL installed). Tried different major MongoDB versions (v2.^,v3.^)(x32/x64) with no luck.

Is there any way to make it work on php7? 
(i hope it is known issue, a lot of old mongo db php tools didn't work on php7 due to some changes in lib)

P.S.

Im going to put in cache approx. 30 mil. objects, zipped up to 10kb each. 
Will there be any difference between sqlite driver (which i am able to use) on fast SSD \ and mongodb driver, if amount to store is approx. 500 GB, and i have only 16-18 GB of free RAM ?

Thank you!

**Comment by git-webmaster** [comment]
Thanks for the reply!
According to #326, there is no tested version of this driver, so im looking foreard to SSDB.

Please answer one question concerning implementation of ssdb driver: is this driver is using disk to store cached objects for long time, or it uses only available free ram memory, and resets every power-off? Thanks!

**Comment by Geolim4** [comment]
As per: https://github.com/ideawu/ssdb

> Persistent key-value, key-zset, key-map('hashmap') storage

So i would say "yes" ?

**Comment by git-webmaster** [comment]
Thank you.
I Will now close the issue.
