### ISSUE TITLE
Expired cache clear problem

### ISSUE THREAD

**Issue by mynakturk** [PHPSocialNetwork/phpfastcache#413]
###Configuration:

PhpFastCache version: 5.0.13
PHP version: 5.6
Operating system: centos

i want to clean only expired cache. when i use clear () function it delete all cache. how can resolve this problem.
i use file cache

**Comment by Geolim4** [comment]
Hello

The clear method purges the whole cache as described in interface.

This is the intended behaviour.

Cheers,
Georges.L

**Comment by mynakturk** [comment]
i want to clean up expired caches. is there any function for that?

**Comment by Geolim4** [comment]
@mynakturk 

Unfortunately, there's no such functions at this time. The problem resides in the fact that we cannot directly link a file to a cache item to check if it's expired or not.

An expired cache item is automatically deleted once it get called by getItem.
But there's a workaround for that.

Add a unique tag to each cache item using addTag().
When you need to "cleanup" the expired items, just call getItemsByTag($tagName).
Expired items will be automatically deleted.

Cheers,
Georges.L

**Comment by mynakturk** [comment]
thanks 👍

**Comment by tucoinfo** [comment]
@Geolim4 

Hi George,

Just wondering if this is still true in later versions like v8?

> An expired cache item is automatically deleted once it get called by getItem. But there's a workaround for that.
> 
> Add a unique tag to each cache item using addTag(). When you need to "cleanup" the expired items, just call getItemsByTag($tagName). Expired items will be automatically deleted.

**Comment by Geolim4** [comment]
> @Geolim4
> 
> Hi George,
> 
> Just wondering if this is still true in later versions like v8?
> 
> > An expired cache item is automatically deleted once it get called by getItem. But there's a workaround for that.
> > Add a unique tag to each cache item using addTag(). When you need to "cleanup" the expired items, just call getItemsByTag($tagName). Expired items will be automatically deleted.

Should be.
