### ISSUE TITLE
Predis no password is set 

### ISSUE THREAD

**Issue by nikmauro** [PHPSocialNetwork/phpfastcache#414]
###Configuration:

PhpFastCache version: ` dev-final `
PHP version: ` 7.0.14 `
Operating system: ` centos `

####Issue description:

Fatal error: Uncaught Predis\Connection\ConnectionException: `AUTH` failed: ERR Client sent AUTH, but no password is set [tcp://127.0.0.1:6379] in /var/www/vhosts/**/httpdocs/vendor/predis/predis/src/Connection/AbstractConnection.php:155 Stack trace: /var/www/vhosts/**/httpdocs/vendor/predis/predis/src/Connection/StreamConnection.php(263): Predis\Connection\AbstractConnection->onConnectionError('`AUTH` failed: ...', 0) /var/www/vhosts/**/httpdocs/vendor/predis/predis/src/Connection/AbstractConnection.php(180): Predis\Connection\StreamConnection->connect() /var/www/vhosts/**/httpdocs/vendor/predis/predis/src/Connection/StreamConnection.php(288): Predis\Connection\AbstractConnection->getResource() /var/www/vhosts/**/httpdocs/vendor/predis/predis/src/Connection/StreamConnection.php(394): Predis\Connection\StreamConnection->write('*2\r\n$3\r\nGET\r\n$3...') /var/www/vhosts/**/httpdocs/vendor/predis/predis/src/Connection/AbstractConnection.php(110): Predis\Connection\StreamConnection->wri in /var/www/vhosts/**/httpdocs/vendor/predis/predis/src/Connection/AbstractConnection.php on line 155

**Comment by Geolim4** [comment]
Hello @nikmauro 

I'll check this one tonight :)

**Comment by Geolim4** [comment]
Found it:
https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/Drivers/Predis/Driver.php#L127

I'm using redis index instead of predis one.

**Comment by Geolim4** [comment]
Try

**Comment by nikmauro** [comment]
@Geolim4  i have test this code and not working! 

Fatal error: Uncaught Predis\Connection\ConnectionException: `AUTH` failed: ERR Client sent AUTH, but no password is set [tcp://127.0.0.1:6379] in /var/www/vhosts/httpdocs/vendor/predis/predis/src/Connection/AbstractConnection.php:155 Stack trace: #0

**Comment by Geolim4** [comment]
Can you replace the empty string here:
https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/Drivers/Predis/Driver.php#L132

by `false` or `null` and tell me if it's working please ?

**Comment by Geolim4** [comment]
Should be working with null

**Comment by nikmauro** [comment]
with false
Fatal error: Uncaught Predis\Connection\ConnectionException: `AUTH` failed: ERR Client sent AUTH, but no password is set [tcp://127.0.0.1:6379] in 

with null
Fatal error: Uncaught Predis\Connection\ConnectionException: `SELECT` failed: ERR invalid DB index [tcp://127.0.0.1:6379] in

**Comment by Geolim4** [comment]
Ok null is working then.
Change `database` empty string to `0`

**Comment by nikmauro** [comment]
i try this and working 

```PHP
$this->instance = new PredisClient(array_merge([
          'host' => '127.0.0.1',
          'port' => '6379',
          'password' => null,
          'database' => null,
        ], $config));
```

**Comment by Geolim4** [comment]
Ok, nice to know, I will update it then.

**Comment by nikmauro** [comment]
Thanks!

**Comment by Geolim4** [comment]
Should be ok now.

**Comment by Geolim4** [comment]
Let me know if it's still working :)

**Comment by nikmauro** [comment]
Perfect!
