### ISSUE TITLE
getAbsolutePath returns relative path when in phar

### ISSUE THREAD

**Issue by jajm** [PHPSocialNetwork/phpfastcache#417]
### Configuration

PhpFastCache version: `5.0.14`
PHP version: `5.6.27`
Operating system: `Debian 8`

#### Issue description

When in a phar archive, `phpFastCache\Util\Directory::getAbsolutePath` returns a path without the leading `/` because `__FILE__` starts with `phar://` instead of `/`
So if I use a path like `/home/user/.cache/xxx` it creates `home/user/.cache/xxx` under the current directory.

**Comment by Geolim4** [comment]
Hi @jajm 

Thanks for the report, I'll check it out tonight.

Can you please dump me the $_SERVER var inside the Phar environment please ?

Cheers,
Georges

**Comment by jajm** [comment]
Output of `var_dump($_SERVER)` :

    array(24) {
      'HOME' =>
      string(11) "/home/omeka"
      'LANG' =>
      string(11) "fr_FR.UTF-8"
      'LOGNAME' =>
      string(5) "omeka"
      'MAIL' =>
      string(15) "/var/mail/omeka"
      'OLDPWD' =>
      string(17) "/home/omeka/omeka"
      'PATH' =>
      string(117) "/home/omeka/.local/bin:/home/omeka/bin:/home/omeka/.local/bin:/home/omeka/bin:/usr/local/bin:/usr/bin:/bin:/usr/games"
      'PWD' =>
      string(25) "/home/omeka/omeka/plugins"
      'SHELL' =>
      string(8) "/bin/zsh"
      'SHLVL' =>
      string(1) "2"
      'SSH_TTY' =>
      string(10) "/dev/pts/4"
      'TERM' =>
      string(15) "screen-256color"
      'TMUX' =>
      string(29) "/tmp/tmux-1001/default,2687,0"
      'TMUX_PANE' =>
      string(2) "%1"
      'USER' =>
      string(5) "omeka"
      '_' =>
      string(12) "/usr/bin/php"
      'PHP_SELF' =>
      string(40) "/home/omeka/src/omeka-cli/omeka-cli.phar"
      'SCRIPT_NAME' =>
      string(40) "/home/omeka/src/omeka-cli/omeka-cli.phar"
      'SCRIPT_FILENAME' =>
      string(40) "/home/omeka/src/omeka-cli/omeka-cli.phar"
      'PATH_TRANSLATED' =>
      string(40) "/home/omeka/src/omeka-cli/omeka-cli.phar"
      'DOCUMENT_ROOT' =>
      string(0) ""
      'REQUEST_TIME_FLOAT' =>
      double(1484060736.2255)
      'REQUEST_TIME' =>
      int(1484060736)
      'argv' =>
      array(3) {
        [0] =>
        string(40) "/home/omeka/src/omeka-cli/omeka-cli.phar"
        [1] =>
        string(2) "dl"
        [2] =>
        string(4) "test"
      }
      'argc' =>
      int(3)
    }

**Comment by Geolim4** [comment]
Ohh ok, it's a CLI script, I get it.

**Comment by Geolim4** [comment]
Can you please give me the full phar:// path please ?
Thanks !

**Comment by jajm** [comment]
If by "the full phar:// path" you mean the value of `__FILE__`, it's `phar:///home/omeka/src/omeka-cli/omeka-cli.phar/vendor/phpfastcache/phpfastcache/src/phpFastCache/Util/Directory.php`

**Comment by Geolim4** [comment]
Where did your cache attempt to write to ?
Outside or inside the phar ?

Can you please give me your driver configuration ?

**Comment by jajm** [comment]
Outside the phar, in `$HOME/.cache/omeka-cli` (full path is `$HOME/.cache/omeka-cli/cli/Files`)

I configured the cache manager like this:
```php
CacheManager::setDefaultConfig(array(
    'path' => $cacheDir, // $cacheDir = getenv('HOME') . '/.cache/omeka-cli'
));
```

**Comment by Geolim4** [comment]
Ok, can you please add:
`$path = preg_replace('~^(([a-z0-9\-]+)://)~', '', $path);`
before
`$parts = preg_split('~[/\\\\]+~', $path, 0, PREG_SPLIT_NO_EMPTY);`

In method `getAbsolutePath()` inside Directory.php and tell me if it's working.

Cheers,
Georges

**Comment by jajm** [comment]
No it doesn't work.

`$path` doesn't contain `phar://` in my case. It's the `__FILE__` constant that does.

But adding

```php
$__FILE__ = preg_replace('~^(([a-z0-9\-]+)://)~', '', $__FILE__);
```

after

```php
$__FILE__ = __FILE__; // allows to dereference char
```

works

**Comment by Geolim4** [comment]
Ahhh I see, I now get it completely. I wonder how to make a test for this one :'(
However I'm gonna patch it right now.

**Comment by jajm** [comment]
Thanks!

**Comment by Geolim4** [comment]
Np:)

If you're a composer user, a release will come next week.

Cheers,
Georges.
