### ISSUE TITLE
Guide to update from V3.0.0 to V5

### ISSUE THREAD

**Issue by moelfassi** [PHPSocialNetwork/phpfastcache#420]
###Configuration:

PhpFastCache version: `3.0.0 `

####Issue description:

> I have a big project with the phpfastcache V3 on it, is there any guide to update my code to the latest version?

> if not, at least please show me how to go from V3 to V4 

Thank you.

**Comment by Geolim4** [comment]
Hi,
the migration process from v3 to v5 is the same as migrating from v4 to v5:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%5D-Migrating-your-code-to-the-V5

Is that you're looking for ?

Cheers,
Georges

**Comment by moelfassi** [comment]
Thank you George,

This is what i need, just one more thing, how can i replace (import) library files ? do i keep the same structure or i have to change something.

my current phpfastcache V3 files:

<img width="235" alt="screen shot 2017-01-25 at 6 46 07 pm" src="https://cloud.githubusercontent.com/assets/10370643/22304326/db90641c-e32e-11e6-96ed-735295b42541.png">

Thank you.

**Comment by Geolim4** [comment]
You have two solutions:
- 1 You have composer: Then you don't need PhpFastCache library, just add it to the composer.json
- 2 You do not have composer: Include our own autoload and will load files automatically (Except Predis files that you need to include manually).

Whatsoever, replace the whole PhpFastCache directory/files with the new ones.

Cheers,
Georges

**Comment by moelfassi** [comment]
Thank you Georges!

**Comment by Geolim4** [comment]
:)
