### ISSUE TITLE
SSDB driver poor perfomance

### ISSUE THREAD

**Issue by git-webmaster** [PHPSocialNetwork/phpfastcache#423]
###Configuration:

PhpFastCache version: `5.0.14`
PHP version: `7.0.14`
Operating system: `Debian 8 x64`

####Issue description:

Hi, Georges.
Not an issue really, more a question.

Found out that SSDB driver shows really bad perfomance under load of 5 requests\sec and more (really small load, isn't it). I have fast SSD on my server, and SSDB daemon is constantly writing something on it really fast, and under moderate load (20 req\s) it takes approx. 1-2-3 sec to return a result, and for some part of queries it is 10-12 sec, which is, of course, inappropriate for cache. 

Most time consumption is here: `phpssdb\Core\SSDB::recv` and `phpssdb\Core\SSDB::recv_resp` (may take 10s or more to return a result). Here is a php trace from NewRelic (screen):

http://imgur.com/a/wvOyJ

As you can see, it took 2,8s + 4.5s + 0.5s to perform 3 calls of `phpssdb\Core\SSDB::recv_resp`.

Do you have any idea why is this happened? (i use mostly the same code as in phpfastcache/examples/ssdb.php)

**Comment by git-webmaster** [comment]
I have approx. 10 GB of data cached by this time (approx. 2.5% of planned use)
My ssdb.conf:

`# ssdb-server config
# MUST indent by TAB!

# relative to path of this file, directory must exists
work_dir = ./var
pidfile = ./var/ssdb.pid

server:
	ip: 127.0.0.1
	port: 8888
	# bind to public ip
	#ip: 0.0.0.0
	# format: allow|deny: all|ip_prefix
	# multiple allows or denys is supported
	#deny: all
	#allow: 127.0.0.1
	#allow: 192.168
	# auth password must be at least 32 characters
	#auth: very-strong-password

replication:
	binlog: yes
	# Limit sync speed to *MB/s, -1: no limit
	sync_speed: -1
	slaveof:
		# to identify a master even if it moved(ip, port changed)
		# if set to empty or not defined, ip:port will be used.
		#id: svc_2
		# sync|mirror, default is sync
		#type: sync
		#host: localhost
		#port: 8889

logger:
	level: warn
	output: log.txt
	rotate:
		size: 1000000000

leveldb:
	# in MB
	cache_size: 5000
	# in KB
	block_size: 32
	# in MB
	write_buffer_size: 64
	# in MB/s
	compaction_speed: 1000
	# yes|no
	compression: yes
`

**Comment by Geolim4** [comment]
Hi Anton,

I'll take a look tonight.

Cheers,
Georges

**Comment by git-webmaster** [comment]
FYI:

Installed CouchBase and made some initial testing - and CouchBase driver performs well, for now it writes 10x LESS data on disk every second (thus not making server LA high), use MUCH less CPU, and generally perfoms much better.

I will switch to CouchBase, will test it for couple of days, and will report here if there will be some issues.
And I do not recommend to use SSDB driver for write-heavy environment with current driver, looks like it is not in "High performances drivers" as said in Readme.

**Comment by Geolim4** [comment]
Can you tell me how is Redis doing it please ?
I'm afraid that the bug come from Ssdb itself oO

Cheers,
Georges.

**Comment by Geolim4** [comment]
Also can you try to enabled debug on Ssdb driver please ?
https://github.com/PHPSocialNetwork/phpssdb/blob/master/src/phpssdb/Core/SSDB.php#L16

Thanks

**Comment by git-webmaster** [comment]
>Can you tell me how is Redis doing it please ?

Unfortunatelly, im not able to test Redis on real data due to some reasons.
Also Redis is not persistent, and requires "data size = ram size" so i can't use it.

>Also can you try to enabled debug on Ssdb driver please ?

You want me to set it to true, and then test ssdb perfomance again, or some log to provide?

**Comment by git-webmaster** [comment]
Also, im continue to load test CouchBase driver.
By this time (several hours of 15-20 req/s) it started to consume much CPU, writes approx. same amount of data to disc as ssdb, but it utilize much more iops of my ssd (1000-1500) compare to SSDB (200-250), according to `iostat 1`.

But main thing: **throughput is stable**. Im not getting any spikes in responce time, it looks stable (see image).

And because my main concern is user responce time, I will use CouchBase :)

![p_stat](https://cloud.githubusercontent.com/assets/4274845/22437588/9ad524bc-e739-11e6-8611-31a8fd239f13.jpg)

**Comment by Geolim4** [comment]
> You want me to set it to true, and then test ssdb perfomance again, or some log to provide?

Yes, exactly. I need to understand why Ssdb is ressource-greedy for you as I tested it and did not see something similar.

However, glad to see that CouchBase is working fine for you, you are the first real tester :)

**Comment by git-webmaster** [comment]
>However, glad to see that CouchBase is working fine for you, you are the first real tester :)

More information on CouchBase:

Approx. on 1 mil. items in cache and 80% fill of avail. to bucket RAM (3.3 GB of 4 GB) it started to throw Errors on `$pfc_instance->save($html)`: 

`
Uncaught exception 'CouchbaseException' with message 'LCB_E2BIG: The object requested is too big to store in the server' in pcs://ext/couchbase/CouchbaseBucket.class.php:145
`

And there is nothing to do with the "object size", it throws this exception even when i try to store `"1"->"2"`.

But, despite this error it actually STORES data, and after next refresh im able to get object from bucket.
So right now im doing so:

```
try {
    $pfc_instance->save($html)
} catch (Exception $e) {
    // do nothing
}
```

Just catching this exception and doing nothing.
Beside this error, everything work smoothly, but im a bit confused about it - now im not shure whether it going to work as expected in the future, or not.

Im using `Couchbase Server Version: 4.5.0-2601 Community Edition (build-2601)`

**Comment by git-webmaster** [comment]
Is there a chance to see MongoDB driver for php7 anytime soon? 
Last chance for me to see a "stable" solution in all meanings.

According to #310 - it looks like that you have some code to test. 
Maybe you need something i can help you with?

**Comment by Geolim4** [comment]
CouchBase should be stable, it's just like you're storing too much data on the data field.
How huge is your $html variable (serialized) ?

**Comment by Geolim4** [comment]
About the MongoDb, I need time, much time to develop it as i Have to start from scratch.

**Comment by git-webmaster** [comment]
>How huge is your $html variable (serialized) ?

It is far below the CouchBase limit (that is 20 mb).
It is an usual html page, and i gzip it before storing - so, resulting object to store is ~300-400 kb.
And i use "//example.com/[page_path]" as key.

Error is not depend on $html size - because i was forcing variable to be short: `$html = 'test';` before storing and was getting the same error.

Also strange thing is that CouchBase was working smoothly couple of hours, and then suddenly 100% of request  started to throw this error on the url first load (when im firing `$instance->save($html);`). See image below (red background on a graph is an error load).

![errr](https://cloud.githubusercontent.com/assets/4274845/22465360/5eda55f2-e7cc-11e6-9398-1f3006e5ca56.png)

Also, one more concern - as you see, php execution time (blue) is steadily grows with the bucket size.
And now i have 1.5 mil. objects in cache, but going to have 100 mil.

Have you done any tests of Files driver performance on huge amount of files?
Im started to thinking that this is not as bad as i think of it before.
Modern linux will easily sustain 100 mil. of files on EXT4, and maybe random access time on SSD will be reasonable? Not sure about deletion by tag. Do you scan every file to determine its tag on ->deleteItemsByTag()? What do you think about it?

**Comment by Geolim4** [comment]
Can you try to replace the cache key by a md5 version of the key ?

**Comment by Geolim4** [comment]
Are you using a memcached bucket ?
See: http://stackoverflow.com/a/29822818/2123869

**Comment by git-webmaster** [comment]
>Are you using a memcached bucket ?

No, couchbase bucket with this settings:

```
Access Control: Authentication 
Replicas: disabled 
Compaction: Not active 
Cache Metadata: Full Ejection 
Disk I/O priority: High
```

>Can you try to replace the cache key by a md5 version of the key ?

Already tried. Also, i tried to md5 tags - and always get same exception.
Maybe, there is some problem with CouchBase PHP SDK.

>SSDB

Also made some more tests with ssdb.
As you know, SSDB uses LevelDB to store data on disk, so i made some optim. there (turn off compression, more write buffer, more block size due to my avg. object size):

```
leveldb:
	# in MB
	cache_size: 5000
	# in KB
	block_size: 256
	# in MB
	write_buffer_size: 128
	# in MB/s
	compaction_speed: 100
	# yes|no
	compression: no
```

And it started to performs a bit better.
But still, average SSDB "responce time" from php is pretty high under even small load (5-7 req\s, ssdb responce: >500 ms) so i decided to use CouchBase, that is, at least, has **stable** responce time (and i hope there will be no problems with inserting objects to cache further, despite the thrown exception).

p.s.

>I need to understand why Ssdb is ressource-greedy for you as I tested it and did not see something similar.

If you want, load it with ~15 GB of cache data, and check what happens on 5-10 request\second.


Feel free to close this issue.
Thank you!

**Comment by Geolim4** [comment]
IMO it's for Ssdb it's design issue from the driver itself, maybe you can report the bug to their tracker:
https://github.com/ideawu/ssdb

About CouchBase, I have no idea why this is error is thrown, I would appreciate to be sure that it's not caused by PhpFastCache code.

**Comment by Geolim4** [comment]
> No, couchbase bucket with this settings:

When you created the bucket do you have selected Couchbase cluster ?
By default ti's memory cluster

**Comment by git-webmaster** [comment]
>When you created the bucket do you have selected Couchbase cluster ?

Yes.

>About CouchBase, I have no idea why this is error is thrown, I would appreciate to be sure that it's not caused by PhpFastCache code.

CouchBase has limitation in 250 bytes for "primary key" (id) length:

```
Document IDs are assigned by application and to be valid they must:

- Conform to UTF-8 encoding
- Have no more than 250 bytes
```

http://docs.couchbase.com/developer/dev-guide-3.0/keys-values.html

So, maybe it would be useful to convert all ids to MD5 before storing, just as you did it in SSDB driver.
Now i am doing it by myself, if string length in bytes by strlen() > 250.

As for other things that i tried, (deletion by tag \ key, upsert) - everything work as expected.

**Comment by Geolim4** [comment]
Here we go, I'm gonna fix this, this is not a performances issue, but more like a... Bug :)

**Comment by Geolim4** [comment]
Luckily, as of the V6 we have method for that:
https://github.com/PHPSocialNetwork/phpfastcache/blob/V6/src/phpFastCache/Core/Item/ExtendedCacheItemInterface.php#L28

I'm gonna import it in the V5

**Comment by Geolim4** [comment]
Also as of the V6, we not support Cassandra, you may want to try it out.
The V6 should also include Mongo & DynamoDb support :)

**Comment by git-webmaster** [comment]
>I'm gonna import it in the V5

Great, that will fix some possible problems for future users.
But be aware that i will not be able to test it :)

At this moment i have loaded approx. ~10 mil. of items to cache with non-md5 keys (due to its length < 250 bytes), and will release application soon, so i will freeze phpfastcache version on 5.0.14, because everything work as expected now.

And i don't think that there will be some problems with that MD5 func addition.

>Also as of the V6, we now support Cassandra, you may want to try it out.

I will use it in my next projects, hope to see V6 release in a couple of months.
Thanks for the great lib :)

**Comment by Geolim4** [comment]
The fix for the V5 will occurs in the next release.
The V6 is planned for this summer, maybe spring...

> At this moment i have loaded approx. ~10 mil. of items to cache with non-md5 keys (due to their length < 250 bytes)

Damn you're such an amazing cache developer :open_mouth:

Cheers,
Georges

**Comment by Geolim4** [comment]
Mongodb driver has been updated for the V6, the V5 will keep the old Mongo class.

**Comment by Geolim4** [comment]
Hello Anton;

Just want to let you know that I added the Couchdb driver on V6:
https://github.com/PHPSocialNetwork/phpfastcache/commit/52abd1b796531f8afb5092a50fc2b2245e092622

:)
