### ISSUE TITLE
Retrieving cached item after it's expired?

### ISSUE THREAD

**Issue by Grayda** [PHPSocialNetwork/phpfastcache#428]
###Configuration:

PhpFastCache version: 5.0.11
PHP version: 5.6.11
Operating system: Windows 10 x64

####Issue description:

I'm writing an API that pulls in data from an external source and caches it (using the files driver)  for a bit. This works great, but I'm trying to code in a failsafe, as the external source is prone to intermittent troubles. If the cache has expired and the external source isn't working properly, I've got nothing to work with!

Is there a way I can force a cached item to be retrieved, after it's expired?

My API's workflow should go like this:

1. Call `getItem()` to retrieve the cached item
2. If there is a cached item, just return the contents to the user.
3. If the cached item doesn't exist, attempt to grab the data from the external source
4. If the external source times out, fall back to the last cached version we had

Step 4 is where I'm having troubles. A "force get" feature would be nice. It looks like the code [deletes the item](https://github.com/PHPSocialNetwork/phpfastcache/blob/f9c09668b313dd53a6417be42e4af02649914a89/src/phpFastCache/Core/StandardPsr6StructureTrait.php#L66-L82) the moment you call `getItem()` on an expired item. Perhaps this could be changed to check an internal variable (`$this->itemExpired` for example). If `itemExpired` is true, nothing is returned (as if it was deleted), while `itemExpired` being false, would return the cached item as normal. That way a person could still retrieve the cached item with a "force get" command until the next time it was overwritten and `itemExpired` was set back to false.

Thoughts?

**Comment by Geolim4** [comment]
Hello,

The item deletion is a security we added since some driver does not delete expired item automatically, but some driver does (Redis, Memcache, etc).

After reading your current workflow,  I think that you should make use of a persistent system like a simple database in fallback, using the cache as a primary data backend.
Here's a schema:

![sans titre](https://cloud.githubusercontent.com/assets/1332071/22618529/2ca4423a-eadf-11e6-8677-cb2d55313a8b.png)

Cheers,
Georges

**Comment by Grayda** [comment]
Ah yes, auto-deletion makes sense. Never really thought about it like that.

Also database never occurred to me. I'll do that instead. Thanks!

**Comment by Geolim4** [comment]
:+1:
