### ISSUE TITLE
Clear Cache Using a Wildcard

### ISSUE THREAD

**Issue by shefik** [PHPSocialNetwork/phpfastcache#429]
###Configuration:

PhpFastCache version: `5.0.14`
PHP version: `5.6`

####Issue description:

> Please add a way to clear caches in batch, using a wildcard in the key.

**Comment by Geolim4** [comment]
Hello,

That's not possible, sorry.
Instead, use tags.

Cheers,
Georges

**Comment by shefik** [comment]
What do you mean by using tags?

**Comment by Geolim4** [comment]
Read the docs and wiki 😃
- DeleteItemByTags
- Getitemsbytags
- AddTags

Etc.

**Comment by Geolim4** [comment]
Here you go:
https://github.com/PHPSocialNetwork/phpfastcache#item-api
