### ISSUE TITLE
V5. How difficult it is to maintain compatibility with php 5.4+?

### ISSUE THREAD

**Issue by landy2005** [PHPSocialNetwork/phpfastcache#430]
Subj?

###Configuration:

PhpFastCache version: 5.0
PHP version: 5.4.0
Operating system: linux

####Issue description:

I develop product, which used by users on old (still supported) systems (like RHEL6/CentOS6).

phpFastCache V5 have (as I see) many cool improvements over V4 and I want to use exactly V5 in our product.
But current minimum requirements php 5.5+ does not approach us..

**Comment by Geolim4** [comment]
Hello @landy2005 

The choice made to target php 5.5 was made mainly for the following reason:

- Arbitrary expressions on empty() to make code much cleaner without dirty temp vars
- Array/string literal dereferencing which globally simplify the code reading and avoid again dirty temp vars
- Better performances against Iterable manipulation (very noticeable difference on big set of data).
- End of support of php 5.4 announced by php, be aware that php 5.5 support has been abandoned too.

All these reasons prompted us to set the supported php version to php 5.5
Also for security reasons i strongly advise you to upgrade your php version to php 5.5, or even better php 5.6.

Cheers,
Georges

**Comment by landy2005** [comment]
I use php 7.0/7.1 and also recommended for our users upgrade to php 5.6/7.0 :)
And I complete agree with your reasons, but..

... our users have systems with such old php, and not always possible upgrade to newer php versions..

anyway thx for your work, I will try to just disable caching for old php versions.

**Comment by Geolim4** [comment]
However, you can still use the V4 on php 5.4 and below :)
Cheers,
Georges
