### ISSUE TITLE
Handling concurrent requests

### ISSUE THREAD

**Issue by girishkc** [PHPSocialNetwork/phpfastcache#433]
I have a web application built using PHP and MySQL. Now the database is hitting the red line due to the load. I am trying to use phpfastcache to store set of data into redis and reduce the load on the DB. The data set is from multiple tables and may take up to 15 seconds to fetch. But I am getting requests from client every 2-3 seconds. So there can be 5-6 requests while the cache is building. That is when the existing cache is expired and new one is getting build.

These requests are again trying to build the cache, that will add up to the cache building time.

Is there any way to workaround this problem?

Thanks :)

**Comment by Geolim4** [comment]
Hello,
I'm currently on vacations, I will come back to you in a week :)

Cheers,
Georges

**Comment by Geolim4** [comment]
Hello,

I think it's a design issue that we cannot fix at all:

We could set a "flag" with a temporary value to store the item as is, but if a concurrent request get the item it wont get the expected value such an array , but a boolean flag that you can't deal with :/

My idea is to work with a cron that will rebuild the cache Item regularly or you can build a batch system.

Cheers,
Georges

**Comment by Geolim4** [comment]
This remind me something like this i read recently on Doctrine project called "Cache Slams":
http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/reference/caching.html#cache-slams

**Comment by Geolim4** [comment]
I'm working on a prototype and I'm seeking for a tester, would you help me to test this out ?
Thanks :)

**Comment by girishkc** [comment]
Definitely.
Let me know how can I help.

**Comment by Geolim4** [comment]
Please test the V6 from the latest commits :)

**Comment by Geolim4** [comment]
The latest commits introduces a Batch system that force concurrent request to wait :)

**Comment by Geolim4** [comment]
Do you got the time to test it ? :)

**Comment by Geolim4** [comment]
Bump :)

**Comment by Geolim4** [comment]
In wrote a Wiki about this:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV6%CB%96%5D-Dealing-with-cache-slams

**Comment by Geolim4** [comment]
Hello @girishkc can you give me a feedback about this ?
It would be very appreciated :-)

Cheers,
Georges

**Comment by Geolim4** [comment]
The issue has been fixed, thanks you for your contribution :thumbsup:

_Geolim4_
