### ISSUE TITLE
Possible to cache chaine?

### ISSUE THREAD

**Issue by Tazer** [PHPSocialNetwork/phpfastcache#434]
#### Issue description:

I'm trying to find out if there is anything built in for cache chaining.
Something like: http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/reference/caching.html#cache-chaining

> A common pattern is to use a static cache to store data that is requested many times in a single PHP request. Even though this data may be stored in a fast memory cache, often that cache is over a network link leading to sizable network traffic.
> 
> The ChainCache class allows multiple caches to be registered at once. For example, a per-request ArrayCache can be used first, followed by a (relatively) slower MemcacheCache if the ArrayCache misses. ChainCache automatically handles pushing data up to faster caches in the chain and clearing data in the entire stack when it is deleted.

**Comment by Geolim4** [comment]
Hello,

The idea is interesting but is not intended for performances at all. In fact the chaining system is designed for availability to the detriment of the reactivity of the cache backend.

I will may consider introducing into the V6 by adding an helper that will do the job, but I personally does not like this kind of chaining which is more used on industrial purposes that require high availability.

Cheers,
Georges

**Comment by Tazer** [comment]
Hello @Geolim4 , 

Thanks for your answer.

Yes, your correct it's not only focused on performance. Maybe the feature is better as an "extension" or a separate library that just talks with phpfastcache. Cause  I'm after what stackoverflow wrote about in the architecture summary: https://nickcraver.com/blog/2016/02/17/stack-overflow-the-architecture-2016-edition/#cache--pubsub-redis . Really like the approach where you have redis (or some other cache that supports the behavior) pub/sub and keep your in-memory caches up 2 date across servers.

I'm from the .net world and there is one library that have implemented above. (http://cachemanager.net/). But haven't found any in php. So that's way I give it a shot here in this library and see if there is any interest or plans for something like that. 😄

**Comment by Geolim4** [comment]
I was wondering...
Does the ActOnAll Helper would not partially made the job ?
https://github.com/PHPSocialNetwork/phpfastcache/blob/V6/src/phpFastCache/Helper/ActOnAll.php

There's a Wiki about it:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV6%CB%96%5D-Act-on-all-instances

Cheers,
Georges

**Comment by Tazer** [comment]
I think the `events` (EventManager) can help me accomplish what I want 👍  , I will close this and if I get something working I will post about it.
