### ISSUE TITLE
Enhachment

### ISSUE THREAD

**Issue by hanabadler** [PHPSocialNetwork/phpfastcache#436]
Hello 
just want to add my 2 cents that might help others

i wrapped the package as wordpress plugin
to do so, all is needed is to add a "main.php" file on the root folder (near "readme" file), and add the following php code
```php
<?php
/*
Plugin Name: phpfast cache plugin
Plugin URI: https://github.com/PHPSocialNetwork
Description: phpfast cache plugin
Version: 1
Author: PHPSocialNetwork
Author URI: phpfast cache plugin
*/

define('__ROOT__', dirname(dirname(__FILE__))); 

require_once(__ROOT__.'/phpfastcache-final/src/autoload.php'); 

use phpFastCache\CacheManager;
use phpFastCache\Core\phpFastCache;
// Setup File Path on your config files
CacheManager::setDefaultConfig([
  "path" => sys_get_temp_dir(),
]);
// In your class, function, you can call the Cache
function samplefunction($cachekey ) {
        $InstanceCache = CacheManager::getInstance('files');   
        $CachedObj     = $InstanceCache->getItem($cachekey);
        if (is_null($CachedObj->get())) {
            $obj = "init this variable as you want. can be simple, array, sql result..";
            $CachedObj->set($obj)->expiresAfter(60);//in seconds, also accepts Datetime
	    $InstanceCache->save($CachedObj); // Save the cache item just like you do with doctrine and entities
        }
        return $CachedObj->get();
}
```

i hope you might consider add this to this project, providing wordpress developers additional applicative cache method.

thanks
Hana

**Comment by Geolim4** [comment]
Hello,

I will have a look at this.
What's the Wordpress compatibility about this ?

Cheers,
Georges

**Comment by hanabadler** [comment]
i used the latest wordpress version.

**Comment by Geolim4** [comment]
Ok thanks, I keep it aside :)

**Comment by osevan** [comment]
Anyone know if this cache working with wordpress ?

**Comment by Geolim4** [comment]
It's up to you to make the implementation. This is a cache library, not a a
cache module.

**Comment by osevan** [comment]
Anyone know if this cache working with wordpress ?

> Hello just want to add my 2 cents that might help others
> 
> i wrapped the package as wordpress plugin to do so, all is needed is to add a "main.php" file on the root folder (near "readme" file), and add the following php code
> 
> ```
> <?php
> /*
> Plugin Name: phpfast cache plugin
> Plugin URI: https://github.com/PHPSocialNetwork
> Description: phpfast cache plugin
> Version: 1
> Author: PHPSocialNetwork
> Author URI: phpfast cache plugin
> */
> 
> define('__ROOT__', dirname(dirname(__FILE__))); 
> 
> require_once(__ROOT__.'/phpfastcache-final/src/autoload.php'); 
> 
> use phpFastCache\CacheManager;
> use phpFastCache\Core\phpFastCache;
> // Setup File Path on your config files
> CacheManager::setDefaultConfig([
>   "path" => sys_get_temp_dir(),
> ]);
> // In your class, function, you can call the Cache
> function samplefunction($cachekey ) {
>         $InstanceCache = CacheManager::getInstance('files');   
>         $CachedObj     = $InstanceCache->getItem($cachekey);
>         if (is_null($CachedObj->get())) {
>             $obj = "init this variable as you want. can be simple, array, sql result..";
>             $CachedObj->set($obj)->expiresAfter(60);//in seconds, also accepts Datetime
> 	    $InstanceCache->save($CachedObj); // Save the cache item just like you do with doctrine and entities
>         }
>         return $CachedObj->get();
> }
> ```
> 
> i hope you might consider add this to this project, providing wordpress developers additional applicative cache method.
> 
> thanks Hana

This method still working as Plugin?
