### ISSUE TITLE
Please provide complete example of fallback from redis to files

### ISSUE THREAD

**Issue by samuelflor** [PHPSocialNetwork/phpfastcache#437]
Hi, I would appreciate it if you provided an example of using fallback from redis to files.  I did not see it in examples folder.  If redis Server is unreachable that it would fallback to files.  Thank you!

**Comment by samuelflor** [comment]
I'm using master final.

**Comment by Geolim4** [comment]
Hello, nice catch !!
I added an article to the wiki:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV5%CB%96%5D-Configuring-a-fallback-driver

Cheers,
Geogres

**Comment by samuelflor** [comment]
I tried to implement.  I used in $config array fallback, path, host, port, password.  I get error Uncaught RedisException: Redis Server went away in ...Driver.php on line 80.

**Comment by Geolim4** [comment]
This is Redis-related, the error does not come from Pfc :)

**Comment by Geolim4** [comment]
The Fallback work only when the connection fails, not when an error occurs runtime.
