### ISSUE TITLE
How can we use it with Vbulletin Forum ?

### ISSUE THREAD

**Issue by swapnil-iref** [PHPSocialNetwork/phpfastcache#439]
###Configuration:

PhpFastCache version: ` ...replace me... `
PHP version: ` ...replace me... `
Operating system: ` ...replace me... `

####Issue description:

> ...Your description goes here...

**Comment by Geolim4** [comment]
Hello,

You have to made the integration by yourself :)
At this moment we only provide support for Symfony/Drupal projects.

Cheers,
Georges
