### ISSUE TITLE
Tag index gets cleared

### ISSUE THREAD

**Issue by marcelrummens** [PHPSocialNetwork/phpfastcache#440]
###Configuration:

PhpFastCache version: 6.0.0-rc2
PHP version: 5.6
Operating system: Centos

####Issue description:

I'm having issues with the tag feature. The index seems to get randomly cleared. Items disappear from the tag, but the item still exist when I retrieve it by key. I'm using the Files driver.
It is a busy server, so a lot of items are written at the same time and a lot of files are generated ( > 1M).

I have set the TTL of some items to 5 years, the tag cache item gets the same expiration date, so it doesn't expire. It just gets emptied. Sometimes with just a couple of seconds interval.

Am I missing something?

**Comment by Geolim4** [comment]
Hello,

I will have a look at this issue, I may have an idea :)
In the meantime can you provide me a sample of code that describe me better the context ?
You may send it privately if needed :)


Cheers,
Georges

**Comment by Geolim4** [comment]
Also,

Can you try to setup these options ?
- preventCacheSlams
- secureFileManipulation 

Here's the wiki about that:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-The-driver-options

Cheers,
Georges

**Comment by Geolim4** [comment]
Theoretically this issue should not appears due to the following part of code:
https://github.com/PHPSocialNetwork/phpfastcache/blob/V6/src/phpFastCache/Core/Pool/DriverBaseTrait.php#L250

However you may facing to a cache slam issue, see my previous comment :)

Cheers,
Georges

**Comment by Geolim4** [comment]
Hello @marcelrummens,

I’m closing this pull issue _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the issue / add comment / clarify …).

Regards,
Georges.L
