### ISSUE TITLE
Mongodb driver Fatal error

### ISSUE THREAD

**Issue by jomisacu** [PHPSocialNetwork/phpfastcache#442]
###Configuration:

PhpFastCache version: `6.0.0-alpha `
PHP version: `5.6`
Operating system: `windows server 2012 r2`

####Issue description:

When selected driver is mongodb i got this error:

>"Fatal error: phpFastCache\Drivers\Mongodb\Driver and phpFastCache\Core\Pool\DriverBaseTrait define the same property ($instance) in the composition of phpFastCache\Drivers\Mongodb\Driver. However, the definition differs and is considered incompatible."

The reason of the error is because '$instance' field is protected on DriverBaseTrait and it is public on Mongodb\Driver.

On the other hand, the "driverCheck" method of the "phpFastCache\Mongodb\Driver" class should not evaluate if there is a class of an unsupported library, instead, it should evaluate if the necessary class ("MongoClient") exists. This would allow the use of packages like "alcaeus/mongo-php-adapter" that emulates the interface of the obsolete version of the mongodb library (pecl mongo).

I would also like to know the suggested way (the best way) to register my own drivers.

Thanks in advance!

**Comment by Geolim4** [comment]
Hello,

This error has been fixed in the latest RC's, please update PhpFastCache :)
About the class Pecl Mongo, this one has been deprecated and we do not support it anymore :)

Cheers,
Georges
