### ISSUE TITLE
Setting a host/port for Memcached

### ISSUE THREAD

**Issue by Fiorinol** [PHPSocialNetwork/phpfastcache#445]
###Configuration:

PhpFastCache version: ` 5.0.15 `
PHP version: ` 7.0.16 `
Operating system: ` Centos 6.8 `

####Issue description:

I can't figure out how to set a host/port for Memcached using phpFastCache and the example file doesn't state how to do so. I've tried using setDefaultConfig and the second getInstance parameter without success. With just memcached, this is simple enough;

$cache = new memcached();

$cache->addServer("127.0.0.1", 3333);

It works and sets/gets properly.

How do I achieve the same result with phpFastCache? I've tried the following;

$InstanceCache = CacheManager::getInstance("memcached", ['host' => "127.0.0.1",'port' => 3333]);
$key = "product_page";
$CachedString = $InstanceCache->getItem($key);
if (is_null($CachedString->get())) {
    //$CachedString = "APC Cache --> Cache Enabled --> Well done !";
    // Write products to Cache in 10 minutes with same keyword
    $CachedString->set("Memcached Cache --> Cache Enabled --> Well done !")->expiresAfter(120);
    $InstanceCache->save($CachedString);
    echo "FIRST LOAD // WROTE OBJECT TO CACHE // RELOAD THE PAGE AND SEE // ";
    echo $CachedString->get();
} else {
    echo "READ FROM CACHE // ";
    echo $CachedString->get();
}

But I never to get "Read from cache", indicating that phpFastCache isn't saving properly.

**Comment by Geolim4** [comment]
Hello,

Try this:
$InstanceCache = CacheManager::getInstance("memcached", ['memcache' =>[ ['host' => "127.0.0.1",'port' => 3333]]]);

The config name is a bit confusing, it may be changing in V6, however in V5 I'll rename "memcache" to "memcached" :)

Cheers,
Georges

**Comment by Geolim4** [comment]
I will may review this code partially in V5 and rewrite it completely in V6

**Comment by Geolim4** [comment]
Let me know if this fix is working (not yet merged).
Thanks :)

**Comment by Geolim4** [comment]
And because this code needs more logic, here you go..

**Comment by Geolim4** [comment]
@Fiorinol is it ok for you ?

**Comment by Fiorinol** [comment]
I've yet to test it, I will do so at the beginning of next week.

**Comment by Geolim4** [comment]
@Fiorinol Any news about this ? :)

**Comment by Geolim4** [comment]
@Fiorinol Bump :)

**Comment by Salvoxia** [comment]
Hi,

I'll chime in on this since I think that commit introduced a problem.
I'm developing with v6 RC4 and tried to connect to Memcache with the Memcache driver.
I'm getting

    Fatal error: Call to a member function addServer() on null in /var/www/edk405/common/phpfastcache/src/phpFastCache/Drivers/Memcache/Driver.php on line 146

Seems to me that the driver's $instance is never initialized, since that line has been removed without a proper replacement: 
https://github.com/PHPSocialNetwork/phpfastcache/commit/6bde602ddcdda997c127e08569f3494f75cf1460#diff-3e4e48ff5e83a812303e58ac64ce8403L53

Re-Adding that line (e.g. in ```driverConnect()```) solves it.

Best Regards,
Salvoxia
