### ISSUE TITLE
$expiration must be an object implementing the DateTimeInterface

### ISSUE THREAD

**Issue by jcperez2405** [PHPSocialNetwork/phpfastcache#447]
###Configuration:

PhpFastCache version: ` 5.0.15 `
PHP version: ` 5.4.19`
Operating system: ` i686-redhat-linux-gnu `

####Issue description:

```php
use phpFastCache\CacheManager;

CacheManager::setup(array(
	"path" => ABSPATH . '/wp-content/temp/'
));

$InstanceCache = CacheManager::getInstance('files');

$key = "reviews";
$cachedReviews = $InstanceCache->getItem($key);

if ( is_null( $cachedReviews->get() ) ) {

	$reviews = file_get_contents( __API_CALL_TO_GET_REVIEWS__ );

	$cachedReviews->set($reviews)->expiresAfter(5);
	$InstanceCache->save($cachedReviews);
	$reviewsData = json_decode( $cachedReviews->get() );

} else {
	$reviewsData = json_decode( $cachedReviews->get() );
}
```

Implementing this code, (btw the same come as in the example page) throws an **Fatal error**:
`Fatal error: Uncaught exception 'InvalidArgumentException' with message '$expiration must be an object implementing the DateTimeInterface' in __PATH_TO_FILE__/new/wp-content/themes/tfm/process/vendor/phpfastcache/phpfastcache/src/phpFastCache/Cache/ItemBaseTrait.php:134`

When the code runs for the first time (code executed and cached), runs normally, but the second time (get the code from the cache) is where throws the error.

**Comment by Geolim4** [comment]
Hello,

Try to upgrade your php version to php 5.5 or later.
Currently the v5 is not supported on php 5.4.

Cheers,
Georges

**Comment by jcperez2405** [comment]
I don't have permission to install new versions of PHP, and the **5.4.19** is the higher version my hosting can provide me. So, downgrading to branch 4 was my solution.

Thnxs

**Comment by Geolim4** [comment]
Just by curiosity who's your hosting provider ?
