### ISSUE TITLE
PHP 5.3.10

### ISSUE THREAD

**Issue by samuelflor** [PHPSocialNetwork/phpfastcache#448]
Hi,

What version of PHPFastCache supports php 5.3.x?

Thank you,

Sam

**Comment by Geolim4** [comment]
Hello,

The version 4 and older :)

Cheers,
Georges

**Comment by samuelflor** [comment]
PHP Parse error:  syntax error, unexpected '[' in file path - phpFastCache\src\autoload.php on line 23  PHPFastCache 4.3.18 PHP 5.3.10

**Comment by Geolim4** [comment]
Hello,

I think that you made a mistake:
https://github.com/PHPSocialNetwork/phpfastcache/blob/v4/src/autoload.php

The line 23 does not exists :/

Cheers,
Georges
