### ISSUE TITLE
 undefined method phpFastCache\Drivers\Files\Item::expireAfter()

### ISSUE THREAD

**Issue by sanishan** [PHPSocialNetwork/phpfastcache#449]
###Configuration:

PhpFastCache version: ` I don't know how to find, but i am using latest one (just download 1 hours ago)`
PHP version: `5.6.18`
Operating system: `Windows`

####Issue description:

I am using phpfastcache as legacy!

I want to use "File" engine instead of "memcache or others"

Problem is when i run cache i received this error:

> Fatal error: Call to undefined method phpFastCache\Drivers\Files\Item::expireAfter() in D:\UwAmp\www\mp3oranolang\test.php on line 13

Code:

```
<?php
use phpFastCache\CacheManager;

  require __DIR__ . '/class/phpcache/src/autoload.php';
    $InstanceCache   = CacheManager::getInstance("Files");
    date_default_timezone_set("Europe/Paris");

    // try to get from Cache first.
    
    $key = "website";
$CachedString = $InstanceCache->getItem($key);
if (is_null($CachedString->get())) {
    $CachedString->set(file_get_contents("http://website.com/"))->expireAfter(3600*24);
        $CachedString->save($CachedString);
    
}   else {
    echo "READ FROM CACHE // ";
    echo $CachedString->get();
}
?>
```

I am new to php, can you tell me what i am doing wrong?

**Comment by sanishan** [comment]
anybody? please check my issue!

**Comment by Geolim4** [comment]
Hello,

Do you use any IDE ?
Because you have a type, it's not "expireAfter" but "expiresAfter" :)

Cheers,
Georges
