### ISSUE TITLE
ItemPool->clear() Warning (APCu)

### ISSUE THREAD

**Issue by ShawnTeoh** [PHPSocialNetwork/phpfastcache#450]
### Configuration:

PhpFastCache version: `5.0.15`
PHP version: `7.0.15`
Operating system: `Ubuntu 16.04.2`

#### Issue description:

A warning is generated when I call `ItemPool->clear()`, seems that apcu_clear_cache does not take any arguments: http://php.net/manual/en/function.apcu-clear-cache.php

#### Warning message:

`PHP warning:  apcu_clear_cache() expects exactly 0 parameters, 1 given in ./vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Apcu/Driver.php on line 111`

**Comment by Geolim4** [comment]
Hello,

It's fixed, I will release soon.

Cheers,
Georges
