### ISSUE TITLE
Redis TTL -1 forever ?? 5years ?!

### ISSUE THREAD

**Issue by getchu** [PHPSocialNetwork/phpfastcache#453]
vendor/phpfastcache/phpfastcache/src/phpFastCache/Cache/ItemBaseTrait.php 

   /**
     * @param \DateInterval|int $time
     * @return $this
     * @throws \InvalidArgumentException
     */
    public function expiresAfter($time)
    {
        if (is_numeric($time)) {
            if ($time <= 0) {
                /**
                 * 5 years, however memcached or memory cached will gone when u restart it
                 * just recommended for sqlite. files
                 */
                $time = 30 * 24 * 3600 * 5;
            }
            $this->expirationDate = (new \DateTime())->add(new \DateInterval(sprintf('PT%dS', $time)));
        } else if ($time instanceof \DateInterval) {
            $this->expirationDate = (new \DateTime())->add($time);
        } else {
            throw new \InvalidArgumentException('Invalid date format');
        }

        return $this;
    }
--------------------------

5 years ?? 5 months ??

**Comment by Geolim4** [comment]
Hello,

If you pass an int like "3600" this will cache up the data for an hour.
But you can pass a DateInterval Object too.

Cheers,
Georges

**Comment by Geolim4** [comment]
Hello @getchu,

I’m closing this issue _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the issue / add comment / clarify …).

Regards,
Georges.L
