### ISSUE TITLE
$driverName to be a string got "boolean"

### ISSUE THREAD

**Issue by nikmauro** [PHPSocialNetwork/phpfastcache#456]
###Configuration:

PhpFastCache version: `dev-final`
PHP version: `7.1`
Operating system: `centos 6`

####Issue description:

```php
$this->cache = CacheManager::getInstance('predis');
```

Fatal error: Uncaught phpFastCache\Exceptions\phpFastCacheInvalidArgumentException: Expected $driverName to be a string got "boolean" instead in /vendor/phpfastcache/phpfastcache/src/phpFastCache/CacheManager.php:379 Stack trace: #0 /vendor/phpfastcache/phpfastcache/src/phpFastCache/CacheManager.php(200): phpFastCache\CacheManager::standardizeDriverName(false) #1 //vendor/phpfastcache/phpfastcache/src/phpFastCache/CacheManager.php(258): phpFastCache\CacheManager::getInstance('Apc', Array) #2 //vendor/phpfastcache/phpfastcache/src/phpFastCache/CacheManager.php(186): phpFastCache\CacheManager::getAutoClass(Array) #3 /library/cache.php(106): phpFastCache\CacheManager::getInstance() #4 /library/cache.php(12): cms39_cache->__construct() #5 /home/domainpn/public_html/pc- in /vendor/phpfastcache/phpfastcache/src/phpFastCache/CacheManager.php on line 379

**Comment by Geolim4** [comment]
Hello,

I will have a look, but it's because predis driver seem to be unavailable (missing config?) therefore no fallback driver has been found, throwing that error.

Cheers,
Georges

**Comment by Geolim4** [comment]
I got it:
https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/CacheManager.php#L200

There's a wrong exception thrown due to the new driverName check introduced in v6.
I'll fix it tonight, in the meantime please setup the Predis driver using a relevant config (see Example folder).

Cheers,
Georges

**Comment by nikmauro** [comment]
hello @Geolim4 , i have the same code with this example https://github.com/PHPSocialNetwork/phpfastcache/blob/final/docs/examples/predis.php

**Comment by nikmauro** [comment]
i have install in composer the predis driver "composer require predis/predis" and now working

**Comment by nikmauro** [comment]
Now i have this problem

```php
Notice: Undefined index: e in /var/www/vhosts/8.com/httpdocs/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/Pool/DriverBaseTrait.php on line 186

Fatal error: Uncaught phpFastCache\Exceptions\phpFastCacheInvalidArgumentException: $expiration must be an object implementing the DateTimeInterface in /var/www/vhosts/8.com/httpdocs/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/Item/ItemBaseTrait.php:158 Stack trace: #0 /var/www/vhosts/8.com/httpdocs/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/Pool/CacheItemPoolTrait.php(122): phpFastCache\Drivers\Redis\Item->expiresAt(NULL) #1 /var/www/vhosts/8.com/httpdocs/library/cache.php(130): phpFastCache\Drivers\Redis\Driver->getItem('497aae29104bc7f...') #2 /var/www/vhosts/8.com/httpdocs/library/cache.php(59): cms39_cache->get('497aae29104bc7f...') #3 /var/www/vhosts/8.com/httpdocs/library/plugins.php(1034): cms39_cache_fetch('siteurl') #4 /var/www/vhosts/8.com/httpdocs/library/cms39_validate.php(98): get_option('siteurl') #5 /var/www/vhosts/8.com/httpdocs/library/settings.php(21): cms39_has_subdomain() #6 /var/www/vhosts/8.com/httpdocs/library/shared.php in /var/www/vhosts/8.com/httpdocs/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/Item/ItemBaseTrait.php on line 158
```

**Comment by Geolim4** [comment]
Can you show me the context of this error please ??

**Comment by Geolim4** [comment]
Ahhhh I got it.
Please purge your cache, from V5 to V6 it's necessary x)

I forget to mention that.

**Comment by Geolim4** [comment]
It is working as expected now ?

**Comment by nikmauro** [comment]
Perfect, thanks @Geolim4
