### ISSUE TITLE
Unknown driver path reference (phpFastCache\Drivers\Setup\Driver)

### ISSUE THREAD

**Issue by giacomodeglinnocenti** [PHPSocialNetwork/phpfastcache#460]
###Configuration:

PhpFastCache version: `1.2.5` (got from Api.php)
PHP version: ` 5.6.30`
Operating system: `Mac OSX `

####Issue description:

Fresh install, cloned the whole dir on my virtualhost, and setupping it without composer as follow:
```
    use phpFastCache\CacheManager;

    require __DIR__ . '/libs/PhpFastCache/src/autoload.php';

    CacheManager::setup(array(
        "path" => $_SERVER['DOCUMENT_ROOT']."cache",
    ));
    $InstanceCache = CacheManager::getInstance('files');
```

and I get the following error:

`Fatal error: Class 'phpFastCache\Drivers\Setup\Driver' not found in /Users/Jack/Documents/VirtualHosts/xxx/inc/libs/PhpFastCache/src/phpFastCache/CacheManager.php on line 198`

How could I make it work without composer?

Thanks.

**Comment by Geolim4** [comment]
Hello,

The version is wrong (it's the API version), where did you got the lib ?
Also the method setup() is no longer valid use https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/CacheManager.php#L324() instead.

See:
https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/CacheManager.php#L324

Cheers,
Georges

**Comment by Geolim4** [comment]
However I'll add a deprecation message regarding this method.

**Comment by giacomodeglinnocenti** [comment]
I confirm that using `setDefaultConfig()` the problem is solved.

I still don't know where to get the version from.

**Comment by Geolim4** [comment]
The version can be revealed with composer (if you are using it).
Or from github on releases page :)
