### ISSUE TITLE
Driver defaults to `auto` but is compared with `Auto` (see case)

### ISSUE THREAD

**Issue by PerWiklander** [PHPSocialNetwork/phpfastcache#462]
### Configuration:

PhpFastCache version: `final`

#### Issue description:

The default value of the `driver` parameter is `auto`. When checking if the autoDriver should be used the string `Auto` is used.

See: https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/CacheManager.php#L186

Also, github markdown requires a space after `###` to get headers, might want to change the new issue template.

**Comment by Geolim4** [comment]
Hello,

Indeed there's an issue with markdown template, I'll fix it.
However I don't get the issue with 'Auto' driver ? 
The method `CacheManager::standardizeDriverName()` is here to standardize the driver name, so it does not matter about the driver case sensitive ?

Cheers,
Georfges

**Comment by Geolim4** [comment]
I fixed the issue template issue :)
I also updated the default driver name. Is it ok for you ?

Cheers,
Georges

**Comment by PerWiklander** [comment]
I'm sorry, I missed the line that does
`$driver = self::standardizeDriverName($driver);`.

I'm not sure how `securityKey` is related though?

**Comment by Geolim4** [comment]
The securityKey is only available for Files-based drivers (Files, sqlite, leveldb) etc.
It's by default the current value of HTTP_HOST, but you can change it for more safety.

**Comment by PerWiklander** [comment]
I guess you can close this now.
