### ISSUE TITLE
Get Random Cache Key From Saved Cache

### ISSUE THREAD

**Issue by zaingithub** [PHPSocialNetwork/phpfastcache#465]
Hello, can i get a random key from saved cache? So i can call any random data has been cached in the cache folder? I build a dynamic website, and always calling request to any datasource i need.

Thanks.

**Comment by Geolim4** [comment]
Hello,

It's not possible right now, but you can use tags features and php mt_rand functions (on indexes):

https://github.com/PHPSocialNetwork/phpfastcache/wiki#itempool-api
http://php.net/manual/en/function.mt-rand.php

Cheers,
Georges

**Comment by zaingithub** [comment]
Thank you for reply. Can you show me how i can implement a tag to my saved cache?

$saving->set($data_cache)->expiresAfter($expires)->addTag('testing-tag');
$this->cache->save($saving);		

when i try to make $this->cache->getItemsByTag('testing-tag')

it always return to NULL
