### ISSUE TITLE
phpfastcache php 7.0 pb with Memcache

### ISSUE THREAD

**Issue by delafred** [PHPSocialNetwork/phpfastcache#466]
### Configuration:

PhpFastCache version: ` v6 `
PHP version: `7.0. `
Operating system: `debian`

#### Issue description:
I tried this code but it seem not work.
(I'm not php expert so maybe I do a big mistake.

`
require_once('../fonctions/autoload_phpFastCache.php');
use phpFastCache\CacheManager;

echo "step a";
$InstanceCache = CacheManager::getInstance('memcache', ['servers' => [
  [
    'host' =>'127.0.0.1',
    'port' => 11212
  ],
]]);

echo "step b";`

I receive only "step a" so I think the script totaly stop 

I think trying echo "step a and b" in the main class CacheManager.php that 
`self::$instances[ $instance ] = new $class($config);` seem not well executed.

What I did wrong ?

Thanks a lot

**Comment by Geolim4** [comment]
Hello,

Do you have any exception thrown, any debug log ?

Cheers,
Georges

**Comment by delafred** [comment]
I added this on the top of my script
```
error_reporting(E_ERROR | E_WARNING | E_PARSE);
ini_set('display_errors', '1');
```

But nothing is shown


So I did that 

```
                echo 'step 1<br/>';
                var_dump($class);
                var_dump($config);
                self::$instances[ $instance ] = new $class($config);
                echo 'step 2';
```

step 1
string(36) "phpFastCache\Drivers\Memcache\Driver" array(16) { ["itemDetailedDate"]=> bool(false) ["autoTmpFallback"]=> bool(false) ["secureFileManipulation"]=> bool(false) ["ignoreSymfonyNotice"]=> bool(false) ["defaultTtl"]=> int(900) ["defaultKeyHashFunction"]=> string(0) "" ["securityKey"]=> string(4) "Auto" ["htaccess"]=> bool(true) ["default_chmod"]=> int(511) ["path"]=> string(0) "" ["fallback"]=> bool(false) ["limited_memory_each_object"]=> int(4096) ["compress_data"]=> bool(false) ["preventCacheSlams"]=> bool(false) ["cacheSlamsTimeout"]=> int(15) ["servers"]=> array(1) { [0]=> array(2) { ["host"]=> string(9) "127.0.0.1" ["port"]=> int(11212) } } }

I don't know how to catch error of 
`self::$instances[ $instance ] = new $class($config);`

**Comment by Geolim4** [comment]
If you're on php7 catch \Throwable interface and see what happens :)

**Comment by delafred** [comment]
I added 'E_ALL' and it show me

Fatal error: Cannot locate the Psr/Cache files in /home/park4night/public_html/fonctions/autoload_phpFastCache.php on line 35

I think I didn't copy enought files because I don't have /bin/ folder in my configuration

Really sorry and thanks a lot for your help

**Comment by Geolim4** [comment]
Do you use your own autoload to load PhpFastCache files ?

**Comment by delafred** [comment]
The problem was that I copy only the "phpFastCache\src\phpFastCache" folder.
instead of copy "phpFastCache\bin" and 'phpFastCache\src" to my /fonctions/ folder
Now it work well.

I thaught "/bin/" folder was for other languages ;)

**Comment by Geolim4** [comment]
Okay :)
Please note that PhpFastCache provides it's own autoloader.
Just include it in your code.

Cheers,
Georges
