### ISSUE TITLE
Allow to specify the file extension in the File Driver

### ISSUE THREAD

**Issue by rwngallego** [PHPSocialNetwork/phpfastcache#467]
### Configuration:

PhpFastCache version: 6
PHP version: 5.6
Operating system: Ubuntu 14.04

#### Issue description:

> Is it possible to add the file extension as a configurable option in the 'file' Driver? Currently it's using the .txt file extension. Current implementation: [Core/Pool/IO/IOHelperTrait.php](https://github.com/PHPSocialNetwork/phpfastcache/blob/23c54c1251c8983e3163cf0b11cbbc2c71422669/src/phpFastCache/Core/Pool/IO/IOHelperTrait.php#L163)

**Comment by Geolim4** [comment]
Hello,

Why would you change the file extension ??
This could lead to some dangerous behavior.

Cheers,
Georges

Le 11 juin 2017 11:18 PM, "Rowinson Gallego" <notifications@github.com> a
écrit :

**Comment by rwngallego** [comment]
What possible dangerous behavior? It's up to the developer who implements the cache system. I need to  change the .txt extension to something like .db or .cache but it's not even possible with the current implementation.

**Comment by Geolim4** [comment]
It could be dangerous as a misconfigured file extension could lead to a
possible code injection inside the cache directory. Also why do you need to
change the file extension? The phpFastCache directory should not get shared
at all.

Le 11 juin 2017 11:30 PM, "Rowinson Gallego" <notifications@github.com> a
écrit :

**Comment by Geolim4** [comment]
I will study this possibility to make it the most secure as possible.

**Comment by rwngallego** [comment]
Perfect, thank you :)

**Comment by Geolim4** [comment]
I found out how to make it secure: I'll set up a list of forbidden file extensions (basically executable files extensions) and throwing an Exception if a forbidden extension is passed to the config manager.

**Comment by Geolim4** [comment]
Hello, 

it's been implemented and will be released in 6.0.2.
Current allowed extensions: 'txt', 'cache', 'db', 'pfc'
See option "**cacheFileExtension**" on [Wiki](https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-The-driver-options)

Thanks you for your contribution,
Georges
