### ISSUE TITLE
fallback must be a boolean

### ISSUE THREAD

**Issue by diego-vieira** [PHPSocialNetwork/phpfastcache#471]
### Configuration:

PhpFastCache version: `6.0.1`
PHP version: ` 5.6.30 `
Operating system: ` MacOS `

#### Issue description:

I've tried to set files as fallback as described [here](https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV5%CB%96%5D-Configuring-a-fallback-driver) but got the following
```
phpFastCache\Exceptions\phpFastCacheInvalidConfigurationException
'fallback must be a boolean' in /src/phpFastCache/CacheManager.php on line 470
```

```php
CacheManager::setDefaultConfig([
  'fallback' => 'Files',
  'path' => './cache'
]);
```

**Comment by diego-vieira** [comment]
Also described [here](https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-The-driver-options#global-options).

**Comment by Geolim4** [comment]
Thanks for the report, I'll take a look !

**Comment by Geolim4** [comment]
This bug is now fixed, thanks for your report.
A dedicated test has been created to prevent any regression:
https://github.com/PHPSocialNetwork/phpfastcache/blob/final/tests/issues/Github-471.test.php

Cheers,
Georges
