### ISSUE TITLE
Parse error: syntax error

### ISSUE THREAD

**Issue by ofhk** [PHPSocialNetwork/phpfastcache#473]
### Configuration:
PhpFastCache version: 5.0.16
PHP version: 5.5.36 
Operating system: Mac OS 10.11.6

#### Issue description:

Using phpfastcache throws an parse Error:
Parse error: syntax error, unexpected '[' in htdocs/vendor/phpfastcache/phpfastcache/src/phpFastCache/CacheManager.php on line 59

it is included in my file like this:
`require "../vendor/autoload.php";
use phpFastCache\CacheManager;`

Here is the install log:
Using version ^5.0 for phpFastCache/phpFastCache
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing phpfastcache/phpssdb (1.0.1): Downloading (100%)         
  - Installing predis/predis (v1.1.1): Downloading (100%)         
  - Installing psr/cache (1.0.1): Downloading (100%)         
  - Installing phpfastcache/phpfastcache (5.0.16): Downloading (100%)   

Any idea what is going wrong?

**Comment by Geolim4** [comment]
Hello,

I seriously doubt it that you are on php 5.5, as this error can be thrown on 5.4 and below.
Print a phpinfo just to be sure.

Cheers,
Georges.L

**Comment by Geolim4** [comment]
@ofhk Bump :)

**Comment by ofhk** [comment]
Hi Georges,

you are right. I used php from command line to get the version but the app runs in xampp and indeed this was a very old version. After updating I get `Fatal error: Uncaught exception 'phpFastCache\Exceptions\phpFastCacheDriverCheckException' with message 'Apc is not installed or is misconfigured, cannot continue.' in ` . I thought using composer I get all dependencies automatically?

**Comment by Geolim4** [comment]
Apc is not a dependency that are resolved through composer. It's a php extension :)

**Comment by ofhk** [comment]
ok thanks. I am new to php :-)

**Comment by Geolim4** [comment]
No problem man, happy caching :)
