### ISSUE TITLE
Class 'phpFastCache\Drivers\Memcache\Driver' not found

### ISSUE THREAD

**Issue by jimmyadaro** [PHPSocialNetwork/phpfastcache#493]
### Configuration:

PhpFastCache version: 6.0.2 _(Edited by @Geolim4)_
PHP version: 5.5.35
Operating system: Mac OS X

#### Issue description:

I'm trying to include `phpfastcache` without Composer, so I just copy the code from `docs/examples/withoutComposer.php`, but requiring `CacheManager.php` like so:

```
require(DOCUMENT_ROOT."/private/modules/phpFastCache/CacheManager.php");
use phpFastCache\CacheManager;

$InstanceCache = CacheManager::getInstance('memcache');

/**
 * Try to get $products from Caching First
 * product_page is "identity keyword";
 */
$key = "product_page";
$CachedString = $InstanceCache->getItem($key);

if (is_null($CachedString->get())) {
    //$CachedString = "APC Cache --> Cache Enabled --> Well done !";
    // Write products to Cache in 10 minutes with same keyword
    $CachedString->set("Memcache Cache --> Cache Enabled --> Well done !")->expiresAfter(5);
    $InstanceCache->save($CachedString);

    echo "FIRST LOAD // WROTE OBJECT TO CACHE // RELOAD THE PAGE AND SEE // ";
    echo $CachedString->get();

} else {
    echo "READ FROM CACHE // ";
    echo $CachedString->get();
}

echo '<br /><br /><a href="/">Back to index</a>&nbsp;--&nbsp;<a href="./' . basename(__FILE__) . '">Reload</a>';
```

FYI: `DOCUMENT_ROOT` is a global variable for `$_SERVER['DOCUMENT_ROOT']`.

The only thing printed in my page is:

`Fatal error: Class 'phpFastCache\Drivers\Memcache\Driver' not found in /Applications/XAMPP/xamppfiles/htdocs/cache_test/private/modules/phpFastCache/CacheManager.php on line 218`

Where may be the problem?
Thanks for your time.

**Comment by Geolim4** [comment]
Please provide me the PhpFastCache version, not the API version, thanks :)

**Comment by jimmyadaro** [comment]
@Geolim4 Sorry, I don't know where look for that. I'm using the current "final".

**Comment by Geolim4** [comment]
You got it from GIT ? If final then you are using v6.0.2 I guess.
But you are wrong, you are including cacheManager.php instead of autoload.php :)

**Comment by Geolim4** [comment]
Warning: The V6 is not intended to work with php 5.5, downgrade to phpFastCache v5 or upgrade your php to 5.6 at least for the v6 :)

**Comment by jimmyadaro** [comment]
@Geolim4 I got it downloading the ZIP from this repository. I tried before including the autoload file but still the same _fatal error_.

**Comment by jimmyadaro** [comment]
@Geolim4 Right, I will try upgrading PHP then! Thank you :)

**Comment by Geolim4** [comment]
There's no way to get this error by including the autoload.php provided by the lib. This error come from the fact hat you are hard-including the cacheManager.

**Comment by Geolim4** [comment]
I'm not taloking about the `vendor/autoload.php`, but the `src/autoload.php`

**Comment by Geolim4** [comment]
@jimmyadaro Is it working now ?

**Comment by jimmyadaro** [comment]
Geolim4 Sorry, I just left the office. I'll check tomorrow. Please don't close it!

**Comment by Geolim4** [comment]
@jimmyadaro bump :)

**Comment by Geolim4** [comment]
@jimmyadaro Hello Jimmy, some news ? :)

**Comment by jimmyadaro** [comment]
@Geolim4 Hi! Sorry, really busy days... Gonna try tomorrow, I didn't update PHP yet.

**Comment by Geolim4** [comment]
Okay, good luck :)

**Comment by Geolim4** [comment]
@jimmyadaro Any news , :)

**Comment by Geolim4** [comment]
I'm closing this one, feel free to re-open it if this issue is still relevant :)

Cheers,
Georges
