### ISSUE TITLE
Manual Install Documentation 

### ISSUE THREAD

**Issue by bluej130** [PHPSocialNetwork/phpfastcache#499]
On [http://www.phpfastcache.com/](http://www.phpfastcache.com/) under "Documentation" > "How to install it?" > "Manually" it reads "See the file examples/legacy.php for more information.". 

I could not find an "examples" directory or a "legacy.php" file in the git repository.

**Comment by Geolim4** [comment]
Hello,

The Website is not up to date, use the [Wiki](https://github.com/PHPSocialNetwork/phpfastcache/wiki) instead.

Cheers,
Georges
