### ISSUE TITLE
Geolocation Cache possibilities

### ISSUE THREAD

**Issue by delafred** [PHPSocialNetwork/phpfastcache#500]
### Configuration:

PhpFastCache version: ` ...replace me... `
PHP version: `7`
Operating system: `Debian`

#### Issue description:
Hello,

I use your awesome class since few weeks and thanks for it.

I have a project with geolocation and I actually can't use cache system on geolocate requests with your class.
Do you plan to add geolocation cache capacities like the geo API of Redis ?

Regards

Frédéric

... You can also read the [wiki](https://github.com/PHPSocialNetwork/phpfastcache/wiki) ...

**Comment by Geolim4** [comment]
Hello,

How do you use it ?
I don't get well your issue, show me your code please :)

Cheers,
Georges

**Comment by delafred** [comment]
Actually I have no code for this but I can explain the need :

I have a database of 100.000 campings
Users search camping by geolocation around them
example 1; A customer from Berlin search campings arround him
example 2: A customer from Lille search campings arround him
Using standard cache system I'll need to use a cache from each cities customer make search.

In 2015 Redis launch GeoAPI to store a cache and geohash for geolocation caching
http://cristian.regolo.cc/2015/07/07/introducing-the-geo-api-in-redis.html

With this I was thinking to have only one cache of my database with geohash.

I wanted to use this feature throught your class, and I wanted to know if you plan to implement it.

I'm not a Professionnal PHP developper and maybee the solution is to use redis directly in this case with no abstraction class.

Regards,

Frédéric

**Comment by Geolim4** [comment]
I cannot implement a geolocation system. 

It's up to you to resolve the user's location, then inject the latitude/longitude with the search term AS your cache key, ex:
```php

$item = $cacheInstance->getItem('lat|' . $latitude . '|lon|' . $longitude . '|term|' . $searchTerm);
```

You must resolve yourself the user location using libraries and/or server module (Apache GeoIP/Cloudflare, etc).

Cheers,
Georges

**Comment by delafred** [comment]
It's more to let the availabality use geo sorts from caching (redis and maybe others compatible ??) that a geolocation itself because it's already bulk in recent versions of redis.

But thanks for the answer.

Regards
Frédéric

**Comment by Geolim4** [comment]
Ok I got it, and I think that's you have a bit misunderstanding the caching concept:

The caching concept is to serve cached data without requiring database/API/etc call. It's main purpose is to serve cacheable content that comes from an API, a database, etc, for a limited duration time depending your needs.

In your case you need **dynamic** data depending your user's location. The cache is therefore not appropriated to your specific use.

Cheers,
Georges

**Comment by delafred** [comment]
You are right  if I have 100k campings and users launch a geolocate request from different cities.
Then I would need to put in cache for each cities and it will be useless.

That's exactly why Redis (and maybe others ?) added Geo API 
I can put 100k camping in cache with their own geo hash.
After depending the request I can make sort/filter on this cache with geo hash of campings to run faster and lighter than from my MySQL database.

I hope you get it, if not I can explain it in French also.

Regards,

Frédéric

**Comment by Geolim4** [comment]
Redis may added this option because it's main purpose is not to be used as a cache backend. It's a key-value memory server based. This is what i try to explain: We use it as a cache backend like we use Cassadra or Mongo as a cache backend, but they also offers Geo-spacial APIs for non-caching purposes.

Also, remember that PhpFastCache follows the psr6/psr16 specifications which does not implements such features, we have extended those specification but we can't permit ourselves to get too far from the specifications.

Cheers,
Georges

**Comment by Geolim4** [comment]
Why don't you use latitude/longitude as a cache key and short latitude/longitude as a cache ?

```php

$latitude = 1.026123245;
$longitude = 0.51922541;

$item = $cacheInstance
->getItem('lat|' . $latitude . '|lon|' . $longitude . '|term|' . $searchTerm)
->addTag('lat|' . round($latitude, 3))
->addTag('lon|' . round($latitude, 3));
```

This way you get approximate coordinate using tags :)

**Comment by Geolim4** [comment]
I'm closing this one, feel free to reopen it if needed :)

Cheers,
Georges
