### ISSUE TITLE
How can I set the Temp directory with Psr16Adapter ?

### ISSUE THREAD

**Issue by hriziya** [PHPSocialNetwork/phpfastcache#501]
### Configuration:

PhpFastCache version: `6.0.2`
PHP version: `7.0`
Operating system: `Ubuntu 16.04`

#### Question:
> How can I set the Temp directory using Psr16Adapter ? I see the Read Me file has the example available but it is using the CacheManager class.

I have tried using something like this.. but it did not worked. 
`$this->Psr16Adapter = new Psr16Adapter('Files', array("path" => '/var/www/html/site/tmp')); `

Can you tell me if this possible ?
The reason I need it is, I have multiple sites hosted on same server and at moment all sites are getting same data from cache. and so I want to make it different for each site. 

Thanks

**Comment by Geolim4** [comment]
Hello,

I check that as soon as I come home :)

Cheers,
Georges

Le 22 juil. 2017 3:06 PM, "Hitesh Riziya" <notifications@github.com> a
écrit :

**Comment by Geolim4** [comment]
Hello,

I tried your code but it's effectively working without problems, see:
![screenshot_2](https://user-images.githubusercontent.com/1332071/28499274-55f8a588-6fb2-11e7-93c6-0fa6a0c6eafd.png)

Does your directory is writable by the **webserver** ?

Cheers,
Georges

**Comment by hriziya** [comment]
Hi Georges, I just tried again the same code and it looks working to me too. 
Sorry for the question.  and Thanks for your efforts.

Hitesh
