### ISSUE TITLE
nonce system implementation...Am I doing something wrong?

### ISSUE THREAD

**Issue by prashant-saxena** [PHPSocialNetwork/phpfastcache#509]
### Configuration:

PhpFastCache version: `6.0.4 `
PHP version: `  5.6.31 `
Operating system: `Windows 7 `

#### Issue description:

```
use phpFastCache\Helper\Psr16Adapter;

function create_nonce($data, $time=300, $length=12)
{
    $nonce = base64_encode(randomToken($length));
    $psr16Adapter = new Psr16Adapter(PFC_DRIVER);
    $psr16Adapter->set($nonce, $data, $time);
    return $nonce;
}

function validate_nonce($nonce)
{
    $psr16Adapter = new Psr16Adapter(PFC_DRIVER);
    
    if(!$psr16Adapter->has($nonce))
        return false;
    else
        return $psr16Adapter->get($nonce);
}


function delete_nonce($nonce)
{
    $psr16Adapter = new Psr16Adapter(PFC_DRIVER);
    
    if($psr16Adapter->has($nonce)) {
        $psr16Adapter->delete($nonce);
        return true;
    } else {
        return false;
    }
}

function reset_nonce($nonce, $time=300)
{
    $psr16Adapter = new Psr16Adapter(PFC_DRIVER);
    $data = $psr16Adapter->get($nonce);
    $psr16Adapter->set($nonce, $data, $time);
    return true;
}
```

I'm trying to port and existing mysql based nonce system using PFC. Here is my initial approach but I think I'm doing something wrong here. These function area used heavily specially create and delete function. My tmp directory is filled with so many entries. I think $psr16Adapter->set is creating individual
file in case I'm using 'files' driver, where I was under the impression there would be only one file. In case I switch to 'apcu' driver I get an error:

> Calling many times CacheManager::getInstance() for already instanced drivers is a bad practice and have a significant impact on performances.

Please let me know how do I proceed. Last but not the least I'm definitely looking forward to use PFC. Right now various drivers are under testing and I'm getting my hands on slowly.

Cheers

Prashant

**Comment by Geolim4** [comment]
Hello,

Your approach is too procedural, let me explain:
Internally the psr16Adapter adapter store a CacheManager instance. By using the same psr16Adapter you will keep the same CacheManager instance.

But you are instantiating a new psr16Adapter each time you call one of your *_nonce() functions.
This is a bad practice for many reasons, by doing this:

- You will call the abstract method driver_connect() every time leading to a greedy resource time.
- This will increase the memory use, if you do not call not enough the GC, leading to some kind of memory leak.
- You will increase cpu cycles each time you re-instantiate the psr16Adapter object leading to a high cpu usage


If you can't doing your stuff object-style, at least try to store your psr16Adapter statically, like this:

```php
function getPsr16AdapterInstance($nonce, $time=300)
{
    static $psr16Adapter;

    if($psr16Adapter === null){
        $psr16Adapter = new Psr16Adapter(PFC_DRIVER);
    }

    return $psr16Adapter;
}
```
And call `getPsr16AdapterInstance()` in your *_nonce() functions.

> My tmp directory is filled with so many entries. 

This is how the Files drivers actually work: 1 cache item created = 1 serialized file written
You can use the $config variable `path` to set a different directory, see [Wiki](https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-The-driver-options#file-based-drivers-options-)

Cheers,
Georges

**Comment by Geolim4** [comment]
Hello @prashant-saxena,

I’m closing this issue _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the issue / add comment / clarify …).

Regards,
Georges.L
