### ISSUE TITLE
how to set array based variable and retrieve it later?

### ISSUE THREAD

**Issue by teddybugs** [PHPSocialNetwork/phpfastcache#514]
### Configuration:

PhpFastCache version: 6.0.5
PHP version: php 5.6
Operating system: centos 6

#### Issue description:
i have a project that using adodb which will select all the record into array like this:
```
$sql            = "SELECT * FROM video" .$sql_add. " LIMIT " .$limit;
$rs             = $conn->execute($sql);
$videos         = $rs->getrows();
```
later i will pass the $videos as smarty variable:
`$smarty->assign('videos', $videos);`
and i will use it on smarty template like:
```
{section name=i loop=$videos}
<a href="{$relative}/video/{$videos[i].VID}/{$videos[i].title|clean}">
 {/section}
```
**# Question is** : By using phpfastcache, how do it cache the $videos as array? because im doing something like this, it is not working:

```
$key = "videos_index";
$CachedString = $InstanceCache->getItem($key);
if (is_null($CachedString->get())) {

    $CachedString->set($videos)->expiresAfter(120);
    $InstanceCache->save($CachedString);
    echo "FIRST LOAD <br />";
    echo $CachedString->getItems(array $key);
} else {
    echo "READ FROM CACHE: <br />";
    echo $CachedString->getItems()."<br />";
	echo "\n EXPIRATION DATE: " . $CachedString->getExpirationDate()->format(DateTime::W3C);
}

```
because most of the example on your site/wiki are guiding you to set string like this:

`$CachedString->set("My beautifull Ios product");`

there is not much example by array.

any help would be great, phpfastcache are great invention :)

**Comment by Geolim4** [comment]
Hello,

What is that line ??

```php
    echo $CachedString->getItems()."<br />";
```

_ExtendedCacheItemInterface_ does not implements this method oO

You're maybe looking for that ?

```php
    echo $CachedString->get()."<br />";
```

Be caution that the **get()** method will return you an **array** (that you just put in the cache before).

Also please avoid to use;
```php
if (is_null($CachedString->get())) {
```
But instead:

```php
if (!$CachedString->isHit()) {
```
This will be cleaner and a bit faster.

Cheers,
Georges

**Comment by teddybugs** [comment]
thanks work like charms
