### ISSUE TITLE
Memcached seems get() not working

### ISSUE THREAD

**Issue by apapazisis** [PHPSocialNetwork/phpfastcache#518]
### Configuration:

PhpFastCache version: ` v6 `
PHP version: ` 7.1.8 `
Operating system: ` MAC Sierra 10.13 `

#### Issue description:

When i use the memcached the get() returns always NULL. 
The connection to 127.0.0.1, 11211 looks ok.

**Comment by Geolim4** [comment]
Hello,

Can you show me your code implementation please ?

Cheers,
Georges.L

**Comment by apapazisis** [comment]
`

    $instanceCache = CacheManager::getInstance('memcached');

    $key = 'test';
    $cachedString = $instanceCache->getItem($key);

    if (is_null($cachedString->get())) {
        ......
    }
`

In the driver of memcached exists configuration for the connection to 127.0.0.1 and port 11211. 

i have used $instanceCache->getStats function to check the connection and seems to be ok. 

i have seen also this issue https://github.com/PHPSocialNetwork/phpfastcache/issues/445 .

Thanks

**Comment by Geolim4** [comment]
Can you show me the part where you set and save the data ?
You can also send me sensitive code on my email: contact [a-t] geolim4.com

Thanks.

**Comment by apapazisis** [comment]
As an example is the following
    
    $instanceCache = CacheManager::getInstance('memcached');

    $key = 'test';
    $cachedString = $instanceCache->getItem($key);

    if (is_null($cachedString->get())) {
       $results = User::all();
            
       $cachedString->set($results)->expiresAfter(20);  
       $instanceCache->save($cachedString);
       app_log('CREATE FOR CACHE');
    } else {
       app_log('LOAD FROM CACHE');
    }
    
    $cachedResult = $cachedString->get();

**Comment by Geolim4** [comment]
Weird, this one driver was always working until today, I'm gonna make some test tonight.
I'll let you know once I made them.

Thanks you.

**Comment by Geolim4** [comment]
oO
I was able to reproduce the bug !!
I'm gonna inspect this quickly, thanks for the report !!

**Comment by Geolim4** [comment]
I may have identified a possible cause, I keep looking :)

**Comment by Geolim4** [comment]
I do have a question for you:
How big is: `$results = User::all();` ??

I'll enable binary mode it should be better.

**Comment by apapazisis** [comment]
Is not so big. SQLite and files drivers works well!!

**Comment by Geolim4** [comment]
I was able to reproduce it but only with a big array of data which has been truncated (and therefore corrupted) by memcached.

**Comment by apapazisis** [comment]
It may be this the problem... I have switched to SQLLite

**Comment by Geolim4** [comment]
Have a look at this:
https://stackoverflow.com/questions/4795536/increase-item-max-size-in-memcached

**Comment by Geolim4** [comment]
Also please make sure that the Memcached daemon is up and running. The php extension Memcached is not just enough.
