### ISSUE TITLE
Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]

### ISSUE THREAD

**Issue by marwan2** [PHPSocialNetwork/phpfastcache#52]
Dear Khoaofgod, suddenly in one of my projects, a fatal error displayed, and it cause some sections to be die.
This is the error message:

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 5 database is locked' in /home/estqlal/public_html/includes/phpfastcache/drivers/sqlite.php:272 Stack trace: #0 /home/estqlal/public_html/includes/phpfastcache/drivers/sqlite.php(272): PDOStatement->execute(Array) #1 /home/estqlal/public_html/includes/phpfastcache/drivers/sqlite.php(244): phpfastcache_sqlite->deleteRow(Array) #2 /home/estqlal/public_html/includes/phpfastcache/phpfastcache.php(98): phpfastcache_sqlite->driver_get('SidebarArticles', Array) #3 /home/estqlal/public_html/sidebar.php(20): phpFastCache->get('SidebarArticles') #4 /home/estqlal/public_html/index.php(161): require_once('/home/estqlal/p...') #5 {main} thrown in /home/estqlal/public_html/includes/phpfastcache/drivers/sqlite.php on line 272

**Comment by alexboss** [comment]
Dear phpFastCache team,

I also encountered the same problem but I'm not able to provide steps to reproduce as the problems happens randomly.

`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 5 database is locked' in /the/path/to/phpfastcache_2.1.0/drivers/sqlite.php on line 272`
`( ! ) PDOException: SQLSTATE[HY000]: General error: 5 database is locked in /the/path/to/phpfastcache_2.1.0/drivers/sqlite.php on line 272`
`Call Stack`
`#	Time	Memory	Function	Location`
`1	0.0001	266328	{main}( )	.../js.php:0`
`2	0.0067	901432	webtools\app\smartloader\execute_js( )	.../js.php:18`
`3	0.0077	1003256	phpFastCache->get( )	.../smartloader.php:263`
`4	0.0077	1003624	phpfastcache_sqlite->driver_get( )	.../phpfastcache.php:98`
`5	0.0084	1019192	phpfastcache_sqlite->deleteRow( )	.../sqlite.php:244`
`6	0.0086	1020480	execute ( )	.../sqlite.php:272`

I will try to upgrade the library to see if it fixes the situation.

Best regards,

Alexandre 8)
