### ISSUE TITLE
File cache become invalid (null) when cache folder moved

### ISSUE THREAD

**Issue by njentit** [PHPSocialNetwork/phpfastcache#520]
### Configuration:

PhpFastCache version: ` 6.0.5 `
PHP version: ` 7.0 `
Operating system: ` Centos 7 `

#### Issue description:

> I use File cache driver. When i moved my application into different folder all cache become invalid hence it regenerate new cache wich produce different value as part of my app cache is generated based on timestamp.

**Comment by Geolim4** [comment]
Hello,

This is not a bug, but an expected behavior. 
To avoid this, specify the `securityKey` in the configuration.
See [WIKI](https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-The-driver-options#file-based-drivers-options-) :)

Cheers,
Georges
