### ISSUE TITLE
Return value of phpFastCache\Drivers\Predis\Driver::driverWrite() must be of the type boolean, object returned

### ISSUE THREAD

**Issue by ftrudeau** [PHPSocialNetwork/phpfastcache#522]
### Configuration:

PhpFastCache version: v7.x-dev 120234d
PHP version: 7.1.8
Operating system: Windows 10
Redis client : predis/predis v1.1.1

Remote Redis server: v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42

#### Issue description:

When writing an item to cache with TTL, Predis driver returns an object, but phpFastCache is expecting a bool :

Type error: Return value of phpFastCache\Drivers\Predis\Driver::driverWrite() must be of the type boolean, object returned in Driver.php (line 116)

Here is a representation of the object returned :
Predis\Response\Status Object ( [payload:Predis\Response\Status:private] => OK )

Hope this helps.

**Comment by Geolim4** [comment]
Hello,

I'm gonna take a look, thanks !

**Comment by Geolim4** [comment]
Can you dump me this object please ?

**Comment by Geolim4** [comment]
Well.... The PhpDoc of Redis are completely wrong :(
https://github.com/nrk/predis/blob/111d100ee389d624036b46b35ed0c9ac59c71313/src/ClientInterface.php#L65

**Comment by ftrudeau** [comment]
object(Predis\Response\Status)#680 (1) { ["payload":"Predis\Response\Status":private]=> string(2) "OK" }

**Comment by Geolim4** [comment]
Magic fix incoming !

**Comment by Geolim4** [comment]
A test has been added to make sure that Predis will no longer returns unexpected type hint

**Comment by ftrudeau** [comment]
This is great, thanks, it's working :1st_place_medal:

**Comment by Geolim4** [comment]
Nahh, mah build is broken, dunno why...

**Comment by Geolim4** [comment]
Better now  :bowtie:
Thanks for the report.

Just be careful, the V7 is in development, not intended (yet) for production purposes.

Happy caching,
Cheers,
Georges.L
