### ISSUE TITLE
Memory leak ?

### ISSUE THREAD

**Issue by ftrudeau** [PHPSocialNetwork/phpfastcache#529]
### Configuration:

PhpFastCache version: 7.0.0-alpha
PHP version: 7.1.8
Operating system: Windows 10
Redis client : predis/predis v1.1.1

Remote Redis server: v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42

#### Issue description:

I've got this simple implementation, which is part of a PHP trait.

```
    /**
     * Return data from cache item
     *
     * @param $cache_key
     * @return mixed
     */
    public function cacheGet($cache_key)
    {

        $this->assetCacheAdapterExists();

        if ($item = $this->adapter->getItem($cache_key)) {

            if ($data = $item->get()) {

                Log::debug("MEMORY (cacheGet): " . (memory_get_peak_usage(true)/1024/1024));

                return $data;

            }

        }

        return false;

    }

    /**
     * Put stuff in cache
     *
     * @param $cache_key
     * @param $cache_data
     * @param $cache_tags
     * @param bool $cache_ttl
     * @return mixed
     */
    public function cachePut($cache_key, $cache_data, $cache_tags, $cache_ttl = false)
    {

        $this->assetCacheAdapterExists();

        if ($item = $this->adapter->getItem($cache_key)) {

            $expiresAfter = Carbon::now()->diffInSeconds($cache_ttl);

            $item->set($cache_data)->expiresAfter($expiresAfter);

            // Set cache tags
            foreach ($cache_tags as $tag) {

                $item->addTag($tag);

            }

            $this->adapter->save($item);

            Log::debug("MEMORY (cachePut): " . (memory_get_peak_usage(true)/1024/1024));
            
        }

    }

```

When memory usage appears in the logs, it keeps incrementing.

Not sure if my implementation is incorrect, or if there is a method I should call to reset some kind os state in the adapter

Any help would be greatly appreciated !

Thanks.

**Comment by Geolim4** [comment]
Internally, PhpFastCache store the tags as an array of tags but there's also a tag index that is stored in the cache. How many tags do you have ?

**Comment by Geolim4** [comment]
Also, all the cache items are stored in memory to provide a faster cache response.
Use $adapter->detachAllItems() or $adapter->detachItem($item) to unload them from memory.

This is an expected behavior ofc.

**Comment by ftrudeau** [comment]
I've got a lot of tags, and some may have thousands of items associated with them.
I'll try to use detachItem() or detachAllItems() where relevant, thanks !

Also, I noticed that a tag stays in the cache even if all associated items are deleted ( using the $adapter->deleteItemsByTag($tag) method ).

Is this expected behavior ?

**Comment by Geolim4** [comment]
Hulll I'm gonna check that, it should not, but maybe I miss something

**Comment by Geolim4** [comment]
I confirm that the tag stays in memory while it should not :/

**Comment by Geolim4** [comment]
Well this is a hell of a complex bug -_-
Gotta refactor a ton of code just for this...

**Comment by Geolim4** [comment]
Just realizing that this issue showed me a design issue too.
Thanks you, you made my day :D

**Comment by Geolim4** [comment]
A patch is coming and will be dispatched to v5, v6 (final) and and v7

**Comment by Geolim4** [comment]
Thanks for the report this ticket is now fixed, wait the next release or use dev-master.

Cheers,
Georges.L

**Comment by ftrudeau** [comment]
Merci Georges, feedback très réactif, c'est vraiment apprécié.

**Comment by Geolim4** [comment]
Mon plaisir ;)
