### ISSUE TITLE
Random "key does not exist on the server" messages

### ISSUE THREAD

**Issue by rdecourtney** [PHPSocialNetwork/phpfastcache#541]
### Configuration:

PhpFastCache version: 7.0.0-alpha
PHP version: 7.1.11
Operating system: Windows 2012 Datacentre

#### Issue description:

Using couchbase server as a memcached server, I'm getting rare, but random errors:

Error Message: Uncaught Couchbase\Exception: LCB_KEY_ENOENT: The key does not exist on the server in W:\web\assets\plugins\phpFastCache.v7\src\phpFastCache\Drivers\Couchbase\Driver.php:128
Stack trace:
#0 W:\web\assets\plugins\phpFastCache.v7\src\phpFastCache\Drivers\Couchbase\Driver.php(128): Couchbase\Bucket->remove('05f4b82707ebca6...')
#1 W:\web\assets\plugins\phpFastCache.v7\src\phpFastCache\Core\Pool\CacheItemPoolTrait.php(153): phpFastCache\Drivers\Couchbase\Driver->driverDelete(Object(phpFastCache\Drivers\Couchbase\Item))
#2 W:\web\includes\library\custom.functions.php(70): phpFastCache\Drivers\Couchbase\Driver->getItem('profile_timelin...')
#3 W:\web\platform\profile\pages\default.php(212): cache(Array)
#4 W:\web\platform\profile\index.php(116): require('W:\\web\\platform...')
#5 W:\web\platform\error\404.php(88): require('W:\\web\\platform...')
#6 {main}
 thrown
Error File: W:\web\assets\plugins\phpFastCache.v7\src\phpFastCache\Drivers\Couchbase\Driver.php
Error Line: 128

By default, keys are set to expire after 600 seconds, and I'm getting around 100,000 page views a day on the server with around 10 cached requests per page - I'm going to guess it's a resource / memory issue - but should driver.php gracefully handle the non-existent key or error out as above?

Thanks G!

**Comment by Geolim4** [comment]
Hello,

Do you reproduce this bug with the V6 (final) ?

Also I may need to access and/or collaborate with your project on this bug since it appears to be really specific if you don't mind.

Cheers,
Georges

**Comment by Geolim4** [comment]
I'm gonna push a fix for that, do you have any time to test it in real time with me ?

**Comment by rdecourtney** [comment]
Hi G.. yes of course :-) I'm devving all day today - it has only been a random issue though that I can't reproduce, but I can push an update and then monitor over the next few days if that helps?

**Comment by Geolim4** [comment]
Yes of course, I'll give you a patch in a moment

**Comment by Geolim4** [comment]
Try this:
https://gist.github.com/Geolim4/9ed87170ff6f6c2121e58697efd7e48b

**Comment by Geolim4** [comment]
@rdecourtney bump :D

**Comment by rdecourtney** [comment]
No errors so far! (I did comment on the update you pushed out, not here)..

**Comment by Geolim4** [comment]
Okay I'll push a fix tonight !
Thanks you !

**Comment by Geolim4** [comment]
Sorry my computer crashed 2 days ago, expect some days until I finished recovering my data.

My apologizes.

Cheers,
Georges

**Comment by rdecourtney** [comment]
Did you manage to fix your computer ok?

~ Rick


————————————————————————————————————————————————————
Check out our new project! https://competency.io <https://competency.io/>
COMPETENCY.IO is the online portfolio and competency assessment platform for users & enterprise

**Comment by Geolim4** [comment]
Not exactly, I did the commit from my work company ;)
I'll fix my computer tonight anyway, the hardest part was to retrieve my gpg signature to sign the commits above ;)

Cheers,
Georges
