### ISSUE TITLE
DeleteItems by providing pattern as key

### ISSUE THREAD

**Issue by ethereal-sandeep** [PHPSocialNetwork/phpfastcache#543]
### Configuration:

PhpFastCache version: ` 6.0.7 `
PHP version: ` 5.6. `
Operating system: `ubuntu `

#### Issue description: Function to delete all key-value for a particular key pattern.

> I was wondering if there is a possibility to provide a patter to remove keys. For example 
`key_pattern_alpha`
`key_pattern_beta`
and to remove these two value 
`delete("*_pattern_*);`

** Note: there is a way to separate by tags but i needed a more explicit way to remove keys.

ref: http://www.codedwell.com/post/60/redis-how-to-delete-keys-matching-a-pattern

**Comment by Geolim4** [comment]
Hello,

Like I already mentioned multiple times this wont be implemented for multiple reasons:

- We follow the psr6, that means that we respect the design behind this psr. Each string passed to *Item* methods must represents an existing item 
- Not all cache backend support the deletion by wildcard, and I do not want to implement a feature that will be supported only by few cache backend.
- This can be BC breaking

I'm pretty sure that you can work with tags if you take the time to think about a pertinent design ;)

Cheers,
Georges.L
