### ISSUE TITLE
How do I getInstance without: "use phpFastCache\CacheManager" ?

### ISSUE THREAD

**Issue by bongobongo** [PHPSocialNetwork/phpfastcache#544]
Testing PhpFastCache version: ` latest from yesterday `
PHP version: ` 7.0 `

Much to like and I get it working by starting with the syntax below:

include_once("../installdir/src/autoload.php");
use phpFastCache\CacheManager;
$cachePath = '/secret';
$cacheConfig = array(
	        "storage"   =>  "files", 
	        "path"      =>  "$cachePath" ,
	        "securityKey"   =>  "secret",
	        "fallback"  =>  "files",
	        "htaccess"  =>  true,
	        "server"        =>  array(),
	);
CacheManager::setDefaultConfig($cacheConfig);
$cache = CacheManager::getInstance('files');

How can I getInstance without using the line below?
use phpFastCache\CacheManager;

**Comment by Geolim4** [comment]
Hello,

Maybe I'm missing something but I don't really understand your issue ?
What's your issue precisely ?

Cheers,
Georges.L

**Comment by bongobongo** [comment]
Probably not an issue for many others I hope, but in my old PHP editor, the line below show up as an error. It is actually working when running on the server, but would be nice to get rid of the "error" inn the editor:
use phpFastCache\CacheManager;

So I was just wondering if it was possible instantiate the phpFastCache / CacheManager class without using that piece of code?

**Comment by Geolim4** [comment]
> Probably not an issue for many others I hope, but in my old PHP editor, the line below show up as an error

Is it working outside your IDE ? Aside of this what kind of IDE does not support namespace import even an old one ?

> use phpFastCache\CacheManager;

Try to put your 'use' statement before the include/require.

> It is actually working when running on the server, but would be nice to get rid of the "error" in the editor I'm using (Zend Studio 5.5.1) when I write PHP code:

I now understand, you have a **very old** version of Zend Studio oO. [The latest one](http://www.zend.com/fr/products/studio) is the version 13. I'm even suggesting you to use phpStorm which is the IDE I use to develop PhpfastCache. PhpStorm is free if you use the [EAP version](https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Early+Access+Program) or if you work on an OSS project.
I'm sorry to tell you that you MUST upgrade your IDE...

Cheers,
Georges

**Comment by bongobongo** [comment]
Okay, thank you very much for that information. 
I'll have a look at PhpStorm then.

**Comment by Geolim4** [comment]
Good decision my friend !!
Happy caching !!

Cheers,
Georges
