### ISSUE TITLE
Psr16Adapter get item even if it is expired

### ISSUE THREAD

**Issue by piernik** [PHPSocialNetwork/phpfastcache#545]
### Configuration:

PhpFastCache version: `6`
PHP version: ` 7.0`
Operating system: `widnows 10 `

#### Issue description:

As in topic. I think that adapter's `get` method  does not check expiration date. I think it should. I use `files` strategy

**Comment by Geolim4** [comment]
Hello,

What do you mean by:
> I think that adapter's get method does not check expiration date

The file is tested:
https://github.com/PHPSocialNetwork/phpfastcache/blob/final/tests/Psr16Adapter.test.php#L1

And the tests are passing ?
https://travis-ci.org/PHPSocialNetwork/phpfastcache/jobs/307150874#L771

Cheers,
georges

**Comment by piernik** [comment]
I set new item with time to be valid `set('key','value', 10);`.
After 15 seconds I fetch it with `get('key')`. I get `value` instead of null as it should be invalid.

**Comment by Geolim4** [comment]
After the 15 seconds are you still in the same process ?

**Comment by piernik** [comment]
Yes - for tests I give `sleep(15)`. But in `Psrl6Adapter` I see no `$item->isExpired()` call.
BTW: great class name ;)

**Comment by Geolim4** [comment]
You right, I'm storing the cache item in memory, this is maybe more a design issue more rather than a bug.
[The psr-16 documentation](http://www.php-fig.org/psr/psr-16/) is not really clear about it :/

> BTW: great class name ;)

[KISS principle](https://fr.wikipedia.org/wiki/Principe_KISS) :)

**Comment by Geolim4** [comment]
The next release is planned in a [couple of weeks](https://github.com/PHPSocialNetwork/phpfastcache/milestones), if you can't wait until then you can use dev-master.

Cheers,
Georges
