### ISSUE TITLE
Return value of phpFastCache\Drivers\Redis\Driver::driverDelete() must be of the type boolean, integer returned

### ISSUE THREAD

**Issue by ftrudeau** [PHPSocialNetwork/phpfastcache#548]
### Configuration:

PhpFastCache version: v7.x-dev 2c80fa5
PHP version: 7.1.8
Operating system: Windows 10
Redis client : PECL 3.1.4
Remote Redis server: v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42

#### Issue description:

Getting this error when deleteItemsByTag() is called.

Thanks.

**Comment by Geolim4** [comment]
Hello,

It's been fixed, thanks you for the report !
The fix is only available on **dev-master** for now until the next release of the v7.

Cheers,
Georges
