### ISSUE TITLE
Mongodb driver + itemDetailedDate option generates driverUnwrapCdate error

### ISSUE THREAD

**Issue by jcheron** [PHPSocialNetwork/phpfastcache#549]
### Configuration:

PhpFastCache version: ` 6.0.7 `
PHP version: `7.09 (x86) TS `
Operating system: `Windows 10`
mongoc version : `1.8.2`
ext-mongodb : `1.3.4`

#### Issue description:

Creating the CacheManager Instance : 
```php
$cacheInstance = CacheManager::getInstance('Mongodb',[
		'itemDetailedDate'=>true,
		'host' => '127.0.0.1',
  		'port' => '27017',
  		'username' => '',
 		 'password' => '',
 		 'timeout' => '1'
]);
```
Caching example : 
```php
		$item=$cacheInstance->getItem('key1');
		$item->set('data');
		$item->addTag('tag');
		$cacheInstance->save($item);
```
Fetches data stored for the given key : 
```php
		$value=$cacheInstance->getItem($key)->get();
```
Fetching works well, but 2 notices are generated by php : 

```
Notice: Undefined index: c in ...\src\phpFastCache\Core\Pool\DriverBaseTrait.php on line 201

Notice: Undefined index: m in ...\src\phpFastCache\Core\Pool\DriverBaseTrait.php on line 211
```

In one of the methods involved: **driverUnwrapCdate**
`var_dump` on $wrapper parameter displays:
```
array(3) {
  ["d"]=>  string(810) "data"
  ["g"]=>  array(1) {    [0]=>    string(6) "tag"  }
  ["e"]=>  object(DateTime)#33 (3) {    ["date"]=>    string(26) "2017-12-04 02:48:51.000000"
    ["timezone_type"]=>    int(3)    ["timezone"]=>    string(13) "Europe/Berlin"}
}
```
Indeed there is no key `c` or `m` in this associative array!

I activated the **itemDetailedDate** option because I just need the creationDate of each item  (I do not need to set the expirationDate)

did I make a mistake somewhere?

**Comment by Geolim4** [comment]
Hello,

> did I make a mistake somewhere?

Not exactly, you enabled this option after the item been created. Thus these indexes (m, c) does not exists.
Clear the cache and those notice will disappears.

I'm adding a note to myself to add a workaround for this design bug.

Cheers,
Georges

**Comment by jcheron** [comment]
Hello,
I checked, clearing the cache before:
```php
CacheManager::getInstance('Mongodb')->clear();
```
Items are created **after** the option **itemDetailedDate** is enabled,
and the 2 notices are still present.

**Comment by Geolim4** [comment]
I just tried like you did, no notice thrown. I get a notice only when I enable the option **after** filling the cache :/

**Comment by jcheron** [comment]
It's strange :
I checked that the cache had been cleared (with phpFastCache and directly in mongodb).

Items are created on a Cache instance initialized with the **itemDetailedDate** option. But the `$wrapper` parameter of the `driverUnwrapCdate` method never has a key `c` and `m`

And even if the cache was not empty, the new values should replace the old ones, since I use : 
```php
$cacheInstance->getItem($key)->set($content);
```
That's the result of `print_r($cacheInstance->getConfig())`,
just before the insertion of the items:

```php
Array
(
    [itemDetailedDate] => 1
    [autoTmpFallback] => 
    [secureFileManipulation] => 
    [ignoreSymfonyNotice] => 
    [defaultTtl] => 900
    [defaultKeyHashFunction] => 
    [securityKey] => Auto
    [htaccess] => 1
    [default_chmod] => 511
    [path] => 
    [fallback] => 
    [limited_memory_each_object] => 4096
    [compress_data] => 
    [preventCacheSlams] => 
    [cacheSlamsTimeout] => 15
    [cacheFileExtension] => txt
    [host] => 127.0.0.1
    [port] => 27017
    [username] => 
    [password] => 
    [timeout] => 1
)
```

**Comment by Geolim4** [comment]
Did you saved the item after setting up the value ?

**Comment by jcheron** [comment]
yes,
here is the complete code of the item creation: 
```php
protected function storeContent($key,$content,$tag) {
	$key=$this->getRealKey($key);
	$item=$this->cacheInstance->getItem($key);
	$item->set($content);
	$item->addTag($tag);
	$this->cacheInstance->save($item);
}
```

**Comment by Geolim4** [comment]
Ok, I'll take a look tomorrow night, I hope I will reproduce the bug.
Thanks you.

**Comment by Geolim4** [comment]
Ok got it, I may found out the origin of this bug :(
Gotta make a fix soon !

**Comment by Geolim4** [comment]
Apply this patch and tell me if it works:
https://gist.github.com/Geolim4/25f735b163fd9874d86bc9223dbd20a4

Thanks,
Georges

**Comment by jcheron** [comment]
Ok good !
Thank you Georges
The first tests are conclusive

**Comment by Geolim4** [comment]
Thanks you !

It's been fixed, wait the next release or use dev-master.

Cheers,
Georges.
