### ISSUE TITLE
How to set infinite ttl for keys in config

### ISSUE THREAD

**Issue by jcheron** [PHPSocialNetwork/phpfastcache#550]
### Configuration:

PhpFastCache version: ` 6.0.7 `
PHP version: `7.09 (x86) TS `
Operating system: `Windows 10`

#### Issue description:
I would like the keys to have infinite default ttl (permanent keys):

I assumed that by not specifying a ttl in the config:
```php
$cacheInstance = CacheManager::getInstance($driver,[ ]);
```
and using neither the methods `expireAfter`, `expireAt` and `setExpirationDate` on the creation of each item,
these items would be permanent.
But **phpFastCache** uses a default configuration that specifies a `defaultTtl` of 900

I tried to set the defaultTtl to 0, like to set an infinite ttl in memcached: 
```php
$cacheInstance = CacheManager::getInstance($driver,[ 'defaultTtl'=>0]);
```
But in this case, the items are immediately erased, which does not really make sense: 
The value `0` for the `defaultTtl` parameter should perhaps be for creating items that never expire.

**Comment by Geolim4** [comment]
Hello,

Put it a year, some backend does not support infinite ttl. I'm usually putting 365 days to make sure the cache is really "infinite" :)

Cheers,
Georges

**Comment by jcheron** [comment]
Hello Georges,
Thank you for responsiveness!
