### ISSUE TITLE
Distribute minimal composer version

### ISSUE THREAD

**Issue by Bob4ever** [PHPSocialNetwork/phpfastcache#551]
The problem:

I use PhpStorm as IDE and installed phpfastcache (v7.0.0-alpha2) per composer. Additionally I use the setting to synchronize the IDE Settings with the composer.json. With this setting PhpStorm will add every installed package to the autocomplete includePath (not the php includePath).
The real problem now is that e.g. \psr\simpleCache exist in two directories "/vendor/psr/simple-cache" and "vendor/phpfastcache/phpfastcache/bin/legacy/Psr/SimpleCache". And every usage of the interfaces of these packages will trigger a undefined class warning by default. 

I know it's also an problem of PhpStorm to just scan the complete package for any code but why is this even there in the composer release package?

Idea:

Could you please create a distribute version of phpFastCache for each (new) release without the ".github", "bin", "docs", "tests" directory and everything else which isn't really required.

**Comment by Geolim4** [comment]
> I know it's also an problem of PhpStorm to just scan the complete package for any code but why is this even there in the composer release package?

This code is here to guarantee that the library will still work without using composer by using our own [autoloader](https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/autoload.php). This ensure a maximum compatibility for non-composer users.

> Could you please create a distribute version of phpFastCache for each (new) release without the ".github", "bin", "docs", "tests" directory and everything else which isn't really required.

This is not how it work, even the biggest frameworks are not ignoring those files in theirs distributed releases:
![image](https://user-images.githubusercontent.com/1332071/33637295-6e794152-da20-11e7-978f-4cb7a81d8482.png)
Just ignore those directories with PhpStorm:
Right click on the directory, "Mark Directory As ..." select "Excluded".

Cheers,
Georges

**Comment by Bob4ever** [comment]
My main problem aren't the tests. Symfony and co doesn't something like you and store the composer dependencies additionally in the package and use an own autoloader. I fully understand why you are doing this but is there still any one out there who isn't using composer? Isn't version 7 a good moment to drop the non composer support? To use your comparison to the big frameworks, symfony, laravel and many others require composer and don't offer an package with an autoloader and the missing dependencies.

**Comment by Geolim4** [comment]
There's more users than you think that does not make use of composer. Especially "old-shool" companies. We have already pushed up the php version from 5.5, then 5.6 and finally 7. This already a huge step forward, but I do not want to force users to make use of composer since PFC must be autonomous enough to not depends only on a single dependency manager (even a big one).
