### ISSUE TITLE
Delete by tags concurrency issues

### ISSUE THREAD

**Issue by thomas-breese** [PHPSocialNetwork/phpfastcache#552]
### Configuration:

PhpFastCache version: ` 5.0.19 `
PHP version: ` 5.6.31 `
Operating system: ` Amazon Linux AMI release 2017.09 `

#### Issue description:

Hey there,

I'm running into a unique issue and it could technically be a redis thing and not anything on your end, but it's still a unique instance and I thought I'd mention it in case anyone else has experienced this. If this is not code related and you have a greater understanding of the expected behavior of this functionality and would care to enlighten me, that would be greatly appreciated.

Ultimately I'm running into an issue with tag concurrency when using deleteItemsByTag() or getItemsByTag(). What's happening is if I run deleteItemsByTag() I'm running into a race condition where if I insert anything new with this same tag before this operation completes, once the deleteItemByTag() operation completes, I can no longer run that exact same deleteItemsByTag() or getItemsByTag() method and ever match these newly inserted items. It's as if after the delete operation occurs, the tag is unlinked from the newly added items. I have verified that those items do still exist in redis, but they are no longer accessible by either of these methods. For all intents and purposes they are no longer associated with any tags. However, if I get one of these item and run getTags() on it, the tag is indeed present, I just can no longer use it to actually locate the item in redis.

Here's how I'm testing this.

I have a basic script to import a number of records:
```
<?php
/**
 * Sample script to interact with Redis via phpfastcache
 */
use phpFastCache\CacheManager;
use phpFastCache\Core\DriverAbstract;


$host = 'your-redis-host';
CacheManager::setDefaultConfig(array(
        "host" => $host,
        "port" => "6379"
        ));
$phpFastCache = CacheManager::getInstance('redis');


$tag = 'BANANAS';
$i = 0;
while ($i < 500) {
        if (!saveToCache($phpFastCache, $tag.'/'.uniqid().'.html', $tag)) {
                echo "Failed to write to cache.".PHP_EOL;
        }
        $i++;
}

// helper function to save an item in the cache
function saveToCache($phpFastCache, $filename, $tag) {
        $cachedItem = $phpFastCache->getItem($filename);
        $cachedItem->set('This is some garbage text');
        $cachedItem->expiresAfter(1200);
        $cachedItem->addTag($tag);
        return $phpFastCache->save($cachedItem);
}
```

Once they are all loaded I have another script to run to remove the items:
```
<?php
/**
 * Sample script to interact with Redis via phpfastcache
 */
use phpFastCache\CacheManager;
use phpFastCache\Core\DriverAbstract;


$host = 'your-redis-host';
CacheManager::setDefaultConfig(array(
        "host" => $host,
        "port" => "6379"
        ));
$phpFastCache = CacheManager::getInstance('redis');

$tag = 'BANANAS';
$deleted = $phpFastCache->deleteItemsByTag($tag);
```

So here's how I'm recreating this:
First run the import script.
Once that completes, kick off the delete script.
While that is still running, start the import script again.
When the delete script and import script ends, try and run the delete script again. It will never match any items.

You can also query redis directly to see that there are still indeed all the files by executing:
`redis-cli -h your-redis-host KEYS BANANAS*`

You can take one of the keys matched and run a GET on it and you'll see the tag is even present on the data. Here's a sample:
```
"a:3:{s:1:\"d\";s:25:\"This is some garbage text\";s:1:\"t\";O:8:\"DateTime\":3:{s:4:\"date\";s:26:\"2017-12-05 18:00:51.000000\";s:13:\"timezone_type\";i:3;s:8:\"timezone\";s:16:\"America/New_York\";}s:1:\"g\";a:1:{i:0;s:7:\"BANANAS\";}}"
```

So these items are now existing in the cache with the tag, but not accessible by the tag. Hopefully that explains things correctly, but please let me know if you need more info. Again, if this is outside of the scope of this library and there's a better way to do this in redis I'm all ears. The main purpose here is we have a very heavy cache and we're looking to delete by a specific tag. What's happening is that while the delete operation happens we're getting writes and then this disassociation is occurring in our cache, causing us to get a back up of old items that are not refreshing as intended, as we're always clearing by tag.

Thanks,
Tom

**Comment by Geolim4** [comment]
Hello @thomas-breese

This is a hell of a bug that you pointed out there !
Since the [v6 there's an option](https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-The-driver-options#global-options) called **preventCacheSlams** that was made to bypass this kind of bug for **item creation only**. I'm not sure however that it's working for deletion (your case).

You are facing to a rare use case that I'm completely unable to solve at this moment. In fact I have absolutely no idea on how to deal with those concurrency issues :/ 

I would like to reject the fault on your extreme use case, but I can't because this is a real headache :(

**Comment by Geolim4** [comment]
If you have any idea, do not hesitate to propose them !

**Comment by thomas-breese** [comment]
Thanks for your quick reply and sorry for causing such a headache! Honestly, I think my use case is a little extraordinary and I think I can find a way around it by reworking my implementation a little bit on the application code side of things. Unfortunately, I don't know enough about the code to propose any fixes, but based on how I started to track this down I ran into this issue, which you have since resolved: https://github.com/PHPSocialNetwork/phpfastcache/issues/529
This looks like you fixed an issue where deleteItemByTag() will now automatically remove the tag item once that operation completes and there are no longer any items associated with that tag. I am not familiar with the internals of the tagging mechanism you are using within redis (please feel free to point me in the right direction here and I'd be happy to take a look as well), but I would imagine this issue could be occurring in a similar area of the code. Perhaps there's a way to check if there are new items added with the same tag before deciding whether or not to remove that tag entirely when that delete operation completes? The strangest part to me is that those newly added items do have the same tag attached to the cached items themselves, so I'm not sure how that reference is established on those items and why you can no longer find those new items by the same tag. I would imaging removing the parent tag item breaks this association and therefore the tag is present, but not correctly correlated to the new parent tag item once it's created after the delete operation completes and removes it. That's what's stumping me a lot about this. Please let me know if I can be of assistance with this one or provide any more details. Thanks again for your reply!

**Comment by Geolim4** [comment]
I have an idea that could take potentially very long time to develop:
- Introducing operation locks in cache and if there's a concurrent write operation we trow an exception.

Let me explain it better:
- Client A request a deleteItemsByTag($tagName) using a lock before:
```php

$cacheInstance->lock($ttl = 10);
$cacheInstance->deleteItemsByTag($tagName);
// During this operation client B will receive an exception if he's trying to work on this cache item
$cacheInstance->release();
// Client B can now work on this cache item and will not get any exception
```
Using a $ttl to the lock will ensure you that the client B will not get blocked if the lock has not been released for some reason.
However my fear is that will degrade performances by using an additional check before getting an item :/

But there's maybe a solution:
Can you use multiple cache instances ? One by tag. Assuming that you do not have a tons of tags?

**Comment by Geolim4** [comment]
Hello @thomas-breese ,

I’m closing this issue _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the issue / add comment / clarify …).

Regards,
Georges.L
