### ISSUE TITLE
Too much cached files generated = saturated server (inodes)

### ISSUE THREAD

**Issue by kwizfreak** [PHPSocialNetwork/phpfastcache#558]
Hello, I have a niche site with 20 million id in database.
Every time a user or the google robot goes on one of my pages corresponding to an id, I cache with phpfastcache. But I realize that my server is saturated at the level of inodes, do you have solutions? I think of a cron job that would do a daily removal of all hidden files, but I do not know if it's the best solution

**Comment by Geolim4** [comment]
Hello,

Then in your case, files-disk based drivers are not appropriated, use
memory-based such as Redid, Ssdb or Couchbase, etc...

Cheers
Georges.L
