### ISSUE TITLE
How to disable the error message for Symfony?

### ISSUE THREAD

**Issue by alan-zhang-** [PHPSocialNetwork/phpfastcache#559]
### Configuration:

PhpFastCache version: ` v6 `
PHP version: ` PHP7.1`

#### Issue description:

>I use phpfastcache in a Symfony project. But I get notice message (A Symfony Bundle to make the PhpFastCache integration more easier is now available here...), how to disable it? I don't need a Symphony Bundle for my Symfony project. The original is fine.

**Comment by Geolim4** [comment]
Hello,

In a Symfony environment the PhpFastCache bundle must be used because it provides the phpfastcache service and the Yaml configuration.

It's not recommended at all to use the PhpFastCache without it's bundle in a Symfony project :)

Cheers,
Georges

**Comment by Geolim4** [comment]
And the installation is pretty standard and easy:
https://github.com/PHPSocialNetwork/phpfastcache-bundle/blob/master/README.md

It takes a couple of minutes to get it working.

Cheers,
Georges

**Comment by alan-zhang-** [comment]
Hi, Thanks.

I appreciate you offering Symfony version. But really, it should not be compulsory for Symfony project. Symfony project can also use common libs like any other projects. Actually, in my Smfony project, I made a lot a adjustment to make it just like common projects, using dot file(.env as the configuration files, totally ignore symfony configuration files).

As I dig into the source code, it works fine by removing CacheManager@lines212~215

Can these lines be removed from the source project?

**Comment by moazam1** [comment]
I am not using symfony framework only few components but getting this annoying warning. Can you please allow us to disable this warning?
