### ISSUE TITLE
Expiration date bug with sqlite driver

### ISSUE THREAD

**Issue by wloske** [PHPSocialNetwork/phpfastcache#560]
### Configuration:

PhpFastCache version: ` 6.0.8`
PHP version: ` 7.0.6`
Operating system: `win`

#### Issue description:

I think there's a severe error in expiration date handling somewhere. When I set my cacheTTL to `60 * 60 * 24 * 30` which is 30 days, everything works fine. However, when I ramp it up to 31 days, somehow the expiration date in the database is not correct anymore. 

I am using the sqlite driver. For 30 days I get `exp = 1518191956` but for 31 days I get `exp = 3033878630`.

When I dump the cacheItem object right after having set the TTL, it contains the right date. It also contains the right date, when having set the `defaultTtl` config value but still enters the wrong date into the database.

My code looks basically like this:

	$config = array('storage'            => 'sqlite',
		          'htaccess'           => false,
		          'cacheFileExtension' => 'db',
		          'defaultTtl'         => 60 * 60 * 24 * 30,
		          'path'               => $cachePath);

	CacheManager::setDefaultConfig($config);
	$cache = CacheManager::getInstance("sqlite");

	$cacheKey = 'TEST 1'; //increment here, we want only misses
	$cacheItem = $cache->getItem($cacheKey);

	var_dump($cacheItem);

	$cacheValue = "TEST";

	$cacheItem->set($cacheValue);
	//$cacheItem->expiresAfter(60 * 60 * 24 * 30);

	var_dump($cacheItem);

	$cache->save($cacheItem);

	$cacheContent = $cacheItem->get();
	return $cacheContent;

**Comment by wloske** [comment]
Test data created with the code above, first with 30 days, second with 31. The first one has both dates, in the object and exp columns right, but the second one not. Something goes wrong when writing to the db.

<table border="1" style="border-collapse:collapse">
<tr><th>id</th><th>keyword</th><th>object</th><th>exp</th></tr>
<tr><td>2</td><td>TEST 1</td><td>a:5:{s:1:&quot;d&quot;;s:4:&quot;TEST&quot;;s:1:&quot;g&quot;;a:0:{}s:1:&quot;e&quot;;O:8:&quot;DateTime&quot;:3:{s:4:&quot;date&quot;;s:26:&quot;2018-02-10 12:49:44.929876&quot;;s:13:&quot;timezone_type&quot;;i:3;s:8:&quot;timezone&quot;;s:13:&quot;Europe/Berlin&quot;;}s:1:&quot;m&quot;;N;s:1:&quot;c&quot;;N;}</td><td>1518263384</td></tr>
<tr><td>3</td><td>TEST 2</td><td>a:5:{s:1:&quot;d&quot;;s:4:&quot;TEST&quot;;s:1:&quot;g&quot;;a:0:{}s:1:&quot;e&quot;;O:8:&quot;DateTime&quot;:3:{s:4:&quot;date&quot;;s:26:&quot;2018-02-11 12:54:54.563876&quot;;s:13:&quot;timezone_type&quot;;i:3;s:8:&quot;timezone&quot;;s:13:&quot;Europe/Berlin&quot;;}s:1:&quot;m&quot;;N;s:1:&quot;c&quot;;N;}</td><td>3034021788</td></tr></table>

**Comment by wloske** [comment]
I think that function here this is the root cause of the problem. 

`vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/Item/ItemExtendedTrait.php:167` 

```
 public function getTtl()
    {
        $ttl = $this->expirationDate->getTimestamp() - time();
        if ($ttl > 2592000) {
            $ttl = time() + $ttl;
        }

        return $ttl;
    }
```

**Comment by Geolim4** [comment]
This function was made for some backed such as memcache that take dynamic
TTL.

I'll investigate.

Cheers,
Georges.L

**Comment by Geolim4** [comment]
You right,

It seem that we are dealing with dead code here.
I'm gonna check the old drivers too (memcache(d), xcache etc).

Thanks.

**Comment by Geolim4** [comment]
Okay I got it :)

Don't worry, this "expiration" column is no longer really used internally :)
We use the serialized object that contains the date as a DateTime object (the only one reliable format).

Currently the Sqlite *"is working well"* \*, but it's still storing wrong (but unused data).

For compatibility reason I'll keep this column in the V6 && V5, but it will deleted in the V7.

However...
\* You pointed out a very annoying bug that is related on the whole library for 31+days-based.
The code that you mentioned in `/src/phpFastCache/Core/Item/ItemExtendedTrait.php:167` is actually wrong.
In the first time I was wondering why no one complained about this bug before.
Then I realized that this kind of bug cannot be easily spotted due to the fact that you need a month of delay before discovering the fact that the item is not expired as expected.

Really thanks for this report @wloske :)

**Comment by Geolim4** [comment]
Thanks for the report.
The next releases (V5, V6, V7) will be dispatched shortly.

Cheers,
Georges

**Comment by Geolim4** [comment]
All the majors versions just got a new release:
[7.0.0-beta](https://github.com/PHPSocialNetwork/phpfastcache/releases/tag/7.0.0-beta), [6.1.0](https://github.com/PHPSocialNetwork/phpfastcache/releases/tag/6.1.0), [5.0.20](https://github.com/PHPSocialNetwork/phpfastcache/releases/tag/5.0.20)

Cheers,
Georges
