### ISSUE TITLE
Clearing the cache a second time on the files driver returns false

### ISSUE THREAD

**Issue by arcticlinux** [PHPSocialNetwork/phpfastcache#562]
### Configuration:

PhpFastCache version: `6.0.8`
PHP version: `7.1.10`
Operating system: `Windows 8`

#### Issue description:

After clearing the cache while using the files driver, a subsequent cache->clear() returns false
```
$driver = 'files';
$config = ['path' => __DIR__.'/../temp/fastcache/'];
$cache = new phpFastCache\Helper\Psr16Adapter($driver, $config);
print 'cache clear 1'.PHP_EOL;
var_dump($cache->clear());
print 'cache clear 2'.PHP_EOL;
var_dump($cache->clear());
```

Output:
```
$ php test/cache.php
cache clear 1
bool(true)
cache clear 2
bool(false)
```

**Comment by arcticlinux** [comment]
Tested on Linux.

### Configuration:

PhpFastCache version: `6.0.8`
PHP version: `7.1.13`
Operating system: `Ubuntu 16.04 LTS`

**Comment by Geolim4** [comment]
Hello,

This an expected behavior.
Once the cache is cleared and there's nothing left in the cache the second
cache clear has no reason to return true anymore.

Cheers,
Georges.L

**Comment by arcticlinux** [comment]
I see that it does the same thing with other adapters too.

It's not really well specified in PSR16, but other cache adapters will return true clearing empty caches.  I was not expecting it, since the memcached driver will return true in this case.

```
$driver = 'memcached';
$config = ['servers' => [
    [
        'host' => '127.0.0.1',
        'port' => 11211
    ]
]];
$cache = new phpFastCache\Helper\Psr16Adapter($driver, $config);
var_dump($cache->clear());
var_dump($cache->clear());

$driver = 'memcached';
$config = ['servers' => [
    [
        'host' => '127.0.0.1',
        'port' => 11211
    ]
]];
$cache = new phpFastCache\Helper\Psr16Adapter($driver, $config);
var_dump($cache->clear());
var_dump($cache->clear());

bool(true)
bool(true)
```
Some other examples:
https://github.com/symfony/cache/blob/f86432692b87c08c6ec2fab894ec1828375f692f/Adapter/NullAdapter.php#L70
https://github.com/symfony/cache/blob/746686ccf89fe28fb742736e8d8ca216c360b89a/Tests/Adapter/NullAdapterTest.php#L82

**Comment by arcticlinux** [comment]
The Devnull also returns true on clear.

```

$driver = 'Devnull';
$config = [];
$cache = new phpFastCache\Helper\Psr16Adapter($driver, $config);
var_dump($cache->clear());
var_dump($cache->clear());

bool(true)
bool(true)
```

**Comment by Geolim4** [comment]
In fact it returns the value that the backend itself return which is generally arbitrary.
FALSE is returned when there's no more data to clear in cache.

However you can try/catch the clear operation to expect a failure of the cache which generally throws an exception if something went wrong.

The Dev* driver are made for development purpose, the're like a blackhole driver.

**Comment by arcticlinux** [comment]
I had been writing tests around it for my own wrapper class and had noticed
the difference.    It's interesting that if you use the files driver
directly, it returns false both times.
