### ISSUE TITLE
how to use redis when my hosting provider use a sock for the connexion

### ISSUE THREAD

**Issue by pioc92** [PHPSocialNetwork/phpfastcache#563]
### Configuration:

PhpFastCache version: 6.0.8
PHP version: 7.1
Operating system: Apache ???

#### Issue description:

Hi, i know that my hosting provider tell us that for using redis, we have to connect with a socket like /var/run/redis/redis.sock
i tried to do that : $InstanceCache = CacheManager::getInstance('redis', [
  'host' => '/var/run/redis/redis.sock'
]); but i had a fatal error 
PHP message: PHP Warning:  Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/calendriergratuit.fr/www/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Redis/Driver.php on line 137

How to configure redis driver in my case?

**Comment by Geolim4** [comment]
Hello,

Funny, I never considered this possibility :)

I'll check it out this weekend.

Cheers,
Georges.L

**Comment by pioc92** [comment]
;-)
This is the link to the documentation https://documentation.online.net/en/web/web-hosting/cloud-management/memcached

redis is at the end of the page

Thanks

**Comment by Geolim4** [comment]
I'll take a look, but I'm not sure to target this for the v6, I have to check if it's BC breaking or not.

**Comment by Geolim4** [comment]
Ok, I see, the port should be optional.
I'm gonna fix this, but can you tell me if the Predis driver is working well or if it needs the same fix ?

**Comment by Geolim4** [comment]
Also, based on V6 try to apply this patch:
https://gist.github.com/Geolim4/fdcb754755e0c3d2b919adeb78f44e53

If it works I'll merge it asap for the V6.1

**Comment by pioc92** [comment]
Predis don't work too, it's the same problem.
I tested your patch this morning, you have just to remove { at line 40.
It's ok, i can connect to redis!!!!

**Comment by Geolim4** [comment]
Ok for Predis I'll make a fix too.
If I remove that bracket line 40, it throw a syntax error, are you sure ?

**Comment by Geolim4** [comment]
Did you applied the patch using git ?

**Comment by pioc92** [comment]
No i modify the file with sublime text. You could make thé same patch for memcached

**Comment by Geolim4** [comment]
Okay, it's better to apply a patch with Git. I checked for that bracked and it's fine.
I'll take a look for Memcache(d).

**Comment by Geolim4** [comment]
I updated the patch tell me if it's working.
Just provide the "path" option, I removed the "UnixSocket" option.
I the path is provided the code now considers it as an Unix Socket.

**Comment by Geolim4** [comment]
Also FYI, how to apply a patch file easily ;)
https://git-scm.com/docs/git-apply

**Comment by pioc92** [comment]
Same problem with memcached after applying your memcached TTL issue.

**Comment by Geolim4** [comment]
@pioc92 

I find out the issue, I should have noticed it before :(
You are passing "**host**" and "**path**" configuration directives straight into the $config array.

Memcache(d) have a quite different syntax but this is my fault because this is undocumented at all..
The right syntax for Memcache(d) is the following one:

For UNIX sockets:
```php
$InstanceCache = CacheManager::getInstance('memcached', ['servers' => [ 
	[   
	'path' => '/var/run/memcached/memcached.sock' 
	]
]]);
```

For standard TCP connections:
```php
$InstanceCache = CacheManager::getInstance('memcached', ['servers' => [ 
	[   
	'host' => 'hostname' ,
        'port' => $port
        // etc ...
	]
]]);
```

But I agree this can be quite disturbing, this is why I made a patch that will allow the following syntax as of the **V6.1** (which will be released by the end of January):

For UNIX sockets:
```php
$InstanceCache = CacheManager::getInstance('memcached', [
  'path' => '/var/run/memcached/memcached.sock' 
]);
```

For standard TCP connections:
```php
$InstanceCache = CacheManager::getInstance('memcached', [ 
   'host' => 'hostname' ,
    'port' => $port
    // etc ...
]);
```

In the meantime use the first syntax above using the "servers" configuration directive.

**Comment by pioc92** [comment]
Ok Geolim4, merci pour tout ;-)

**Comment by Geolim4** [comment]
I'm still running some tests to improve the Travis units tests and I'm gonna close this issue then.

Thanks you :)

**Comment by Geolim4** [comment]
The v7 (7.0.0-beta) has been released:
https://github.com/PHPSocialNetwork/phpfastcache/releases/tag/7.0.0-beta

The v6 (6.1.0) should follow in a moment.

**Comment by Geolim4** [comment]
The v7 (7.0.0-beta) has been released:
https://github.com/PHPSocialNetwork/phpfastcache/releases/tag/7.0.0-beta

The v6 (6.1.0) should follow in a moment.

**Comment by Geolim4** [comment]
The v6 (6.1.0) has been released:
https://github.com/PHPSocialNetwork/phpfastcache/releases/tag/6.1.0
