### ISSUE TITLE
Cloud Cache Files

### ISSUE THREAD

**Issue by rachmawatiafrida** [PHPSocialNetwork/phpfastcache#564]
### Configuration:

PhpFastCache version: ^6.0
PHP version: 7.1
Operating system: Apache ???

#### Issue description:

> Is it possible save cache files to Google Drive?

**Comment by Geolim4** [comment]
Hello,

Interesting idea for the V7.
I have to study the latency before doign anything :)

Cheers,
Georges

**Comment by Geolim4** [comment]
I tried many things using the [Google php's client](https://developers.google.com/drive/v3/web/quickstart/php) and many things came up:

- The latency is really unpredictable: From 50 ms to 800ms sometimes. This is too much.
- The Google php's client is very heavy: more than 7MB compressed !
- The Google php's client is very ugly: It's Using_Old_Namespacing_Style
- The Google REST Configuration is too much complex and requires a lot of configuration on the target account to get it working, thus making it almost unmaintainable :(

The Idea was however interesting, let's hope that some others cloud platforms provide a better SDK.

Cheers,
Georges.
