### ISSUE TITLE
clear() function

### ISSUE THREAD

**Issue by alan-zhang-** [PHPSocialNetwork/phpfastcache#565]
Hi

clear() // Allows you to completely empty the cache and restart from the beginning

I used predis driver. This clear function removed all redis data in /var/lib/redis. As we also use redis as a database, it seems we can't use clear function?

**Comment by Geolim4** [comment]
Hello,

This method by it's name effectively clear the whole cache as documented in the Redis doc.
Just use a different Redis server/database then.
See this line for more information:
https://github.com/PHPSocialNetwork/phpfastcache/blob/374999bdc0ab66517d1edef6f833b5995abe64e7/src/phpFastCache/Drivers/Redis/Driver.php#L140

Cheers,
Georges

**Comment by alan-zhang-** [comment]
Well, thanks. I used Memcached then.
