### ISSUE TITLE
Please update wiki

### ISSUE THREAD

**Issue by sajaddp** [PHPSocialNetwork/phpfastcache#569]
Hello,
Please update the explanations available on Wiki in section "As Fast To Implement As Opening a Beer"
https://github.com/PHPSocialNetwork/phpfastcache/wiki#as-fast-to-implement-as-opening-a-beer

**Comment by sajaddp** [comment]
it does not match with v6.
for the example method "setup" is deprecated.

**Comment by Geolim4** [comment]
Indeed, I'm gonna fix that. thanks you !

**Comment by Geolim4** [comment]
Fix merged, thanks you !
