### ISSUE TITLE
Litespeed Cache implementation

### ISSUE THREAD

**Issue by Vladdy88** [PHPSocialNetwork/phpfastcache#571]
### Configuration:

PhpFastCache version: ` 6.1 `
PHP version: ` 7.1 `
Operating system: ` CentOS 7 `

#### Issue description:
Do you plan someday to add Litespeed Cache driver too?
Thanks

**Comment by Geolim4** [comment]
@Vladdy88 UP :)

**Comment by Vladdy88** [comment]
Hello,

I don't have the documentation, I will search for it. I saw only that it is already implemented in different CMS' modules that`s why I asked.
I will get back after I study the implementation. 
Thanks

**Comment by khoaofgod** [comment]
If I remember it right, Lightspeed is caching on Server like Nginx Cache. It's has no GET/SET/DELETE/CLEAR
