### ISSUE TITLE
Cant start using cache

### ISSUE THREAD

**Issue by HubUzername** [PHPSocialNetwork/phpfastcache#572]
Hello!

1. composer require PHPSocialNetwork/phpfastcache
2. Require autoload.php
3. Add code

`
   use phpFastCache\CacheManager;
   CacheManager::setDefaultConfig([
         "path" => '/var/www/mysite/data/tmp',
         "itemDetailedDate" => false
   ]);
   $InstanceCache = CacheManager::getInstance();
   $data = $InstanceCache->getItem("key");
`

Error:

> Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'phpFastCache\Drivers\files' does not have a method 'setDefaultConfig' in /var/www/mysite/data/www/mysite.com/modules/classes/vendor/phpfastcache/phpfastcache/src/phpFastCache/CacheManager.php on line 130 Fatal error: Call to undefined method phpFastCache\Drivers\files::getItem() in /var/www/mysite/data/www/mysite.com/modules/init.php on line 19

Why?

**Comment by HubUzername** [comment]
Newest version, php 5.6.33, Linux

**Comment by Geolim4** [comment]
"Newest version" does not help, please specify.

**Comment by HubUzername** [comment]
Sorry, i can solve my problem.
Thank you very much for answer.
