### ISSUE TITLE
$expiration must be an object implementing the DateTimeInterface

### ISSUE THREAD

**Issue by dutom007** [PHPSocialNetwork/phpfastcache#575]
### Configuration:

PhpFastCache version: ` 6.1`
PHP version: `5.6`
Operating system: `FreeBSD 10.3`

#### Issue description:

I have an error :
`
Fatal error: Uncaught exception 'phpFastCache\Exceptions\phpFastCacheInvalidArgumentException' with message '$expiration must be an object implementing the DateTimeInterface got: NULL' in /MYPATH/phpfastcache-6.1/src/phpFastCache/Core/Item/ItemBaseTrait.php:159 Stack trace: #0 /MYPATH/phpfastcache-6.1/src/phpFastCache/Core/Pool/CacheItemPoolTrait.php(128): phpFastCache\Drivers\Redis\Item->expiresAt(NULL) #1 /MYSITEPATH/site/shipping.php(39): phpFastCache\Drivers\Redis\Driver->getItem('terms_PROD_ship...') #2 {main} thrown in /MYPATH/phpfastcache-6.1/src/phpFastCache/Core/Item/ItemBaseTrait.php on line 159
`

I init like that :
```
$config = array (
  'host' => 'EXTERNAL_IP',
  'port' => '6379',
  'password' => 'MY_PASS',
  'database' => 'MY_DATABASE',
);
	
use phpFastCache\CacheManager;
	
$InstanceCache = CacheManager::getInstance('redis',$config);

$terms_cached = $InstanceCache->getItem('terms_'.$cache_keyword);
```
Error is on the last line
Thanks

**Comment by Geolim4** [comment]
There's a missing line, where's the set() /save() calls ?

The getItem() method does not trigger this kind of error.

Cheers,
Georges.L

**Comment by dutom007** [comment]
Hi Geolim4,

I found the response on issue #456 !

I need to clear cache.

**Comment by Geolim4** [comment]
Yeah,

The Redis build is passing well:
https://travis-ci.org/PHPSocialNetwork/phpfastcache/jobs/345666767#L2092

Happy coding,
Georges.L
