### ISSUE TITLE
Files driver "securityKey" option configuration not working as documented

### ISSUE THREAD

**Issue by rahulthackkar** [PHPSocialNetwork/phpfastcache#581]
### Configuration:

PhpFastCache version: `6.1.1 `
PHP version: `7.0.22 `
Operating system: `Ubuntu`

#### Issue description:

> For Files driver configuration 'securityKey' => 'Auto' is not working, instead of creating folder by domain name it is creating folder named "Auto" which is being shared by all domains, so cached results are being overlapped, change it to 'securityKey' => 'auto' (lowecase of "Auto") or change your logic for creating cache directory that should work for word "auto" of any case.

**File : phpfastcache/src/phpFastCache/CacheManager.php**
Thank you for providing this Library, It is very useful for me

**Comment by Geolim4** [comment]
Hello,

I'll look into it, also please be aware that the securityKey is not available in CLI execution context.

Cheers.
Georges

**Comment by Geolim4** [comment]
I think I found out the bug. 
Just need some tests

Hang tight :P

**Comment by Geolim4** [comment]
The bug is now fixed, thanks for the report !

**Comment by rahulthackkar** [comment]
Thanks for support.,😊
