### ISSUE TITLE
Updated MVC Example? getInstance() called too often

### ISSUE THREAD

**Issue by revmitcz** [PHPSocialNetwork/phpfastcache#585]
### Configuration:

PhpFastCache version: `6.0.8`
PHP version: `7.1`
Operating system: `host_alias=x86_64-redhat-linux-gnu`

#### Issue description:

I received an error about calling getInstance() each time, leading me to this page :
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV5%5D-Why-calling-getInstance()-each-time-is-a-bad-practice-%3F

In another issue, you said that one can "find many examples" of using PFC with an MVC framework :
https://github.com/PHPSocialNetwork/phpfastcache/issues/372

But I can't seem to find a proper MVC example. Do you have an updated one somewhere?

I'm admittedly not a PHP expert, but I've tried multiple ways of instantiating this framework within my core Model (setting $cache as static, using a final class, using an abstract class with a static return, etc), and either I get a "call to member function getItem() on null" error, or the PFC warning about "Calling many times CacheManager::getInstance() for already instanced drivers is a bad practice".

Here is the basics of my core Model.php file :

```<?php

namespace Mini\Core;

use PDO;
// caching files
use phpFastCache\CacheManager;
use phpFastCache\Core\phpFastCache;

class Model
{
    /**
     * @var null Database Connection
     */
    public $db = null;
    public $cache = null;

    /**
     * Whenever model is created, open a database connection.
     */
    function __construct()
    {
        try {
            self::openDatabaseConnection();
            self::setupCaching();
        } catch (\PDOException $e) {
            exit('Database connection could not be established.');
        }
    }

    public function setupCaching()
    {
      // set cache instance
      $this->cache = CacheManager::getInstance('files');
    }
```

and here's an example of how I'm using it :

```
<?php

namespace Mini\Model;

use Mini\Core\Model;

class Gallery extends Model
{
  public function getGallery($gallery_id)
  {

    $key = "admin_gallery_".$gallery_id;
    $Cached = $this->cache->getItem($key);

    if (is_null($Cached->get())) {
      $sql = "SELECT * FROM galleries WHERE gallery_id = :gallery_id AND gallery_deleted = 0";
      $query = $this->db->prepare($sql);
      $params = array(':gallery_id' => $gallery_id);

      $query->execute($params);
      $result = $query->fetch();

      $Cached->set($result);
      $Cached->addTag('ind_gallery_'.$gallery_id);
      $this->cache->save($Cached);

    }

    return $Cached->get();
  }
```

What's a better way to instantiate this class in Model.php that would avoid that error and/or speed up my application? (It doesn't feel sluggish, but as the application grows, I have a feeling this may become an issue).

**Comment by Geolim4** [comment]
Hello,

In MVC frameworks like Symfony this can be defined as a Service. But this is already handled by the Phpfastaceche-bundle bundle in this case.

What you have to do is either a singleton class that will return you a unique pfc instance, either storing the instance in an application container or something like that.

It's up to you depending you needs & application architecture.
Just store the pfc instance somewhere and reuse it as much as you need to.

Cheers,
Georges

**Comment by revmitcz** [comment]
After much googling, I was able to find some good examples of PFC as a Singleton. Thanks for the help!

**Comment by premento** [comment]
@revmitcz Can you please share some of the examples as I am stuck with the same!!!

**Comment by revmitcz** [comment]
This is basically what I found after some googling, though I modified it for my purposes :

`// caching files
use phpFastCache\CacheManager;
use phpFastCache\Core\phpFastCache;
use phpFastCache\Proxy\phpFastCacheAbstractProxy;

abstract class Cache extends phpFastCacheAbstractProxy
{

  protected static $driver = 'files';
  protected static $objInstance;

  public function __construct()
  {
    $this->instance = parent::__construct('files', self::getOptions());
  }

  public static function getInstance()
  {
    if (static::$objInstance === null) {
      static::$objInstance = CacheManager::getInstance(static::$driver, self::getOptions());
    }
    return static::$objInstance;
  }
  public static function getOptions()
  {
    $arrOptions = array();
    if (ENVIRONMENT != 'development') {
      $arrOptions['path'] = '/var/www/vhosts/[...]/cache';
    }
    $arrOptions = array_merge(CacheManager::getDefaultConfig(), $arrOptions);
    return $arrOptions;
  }
}
`

Then, in my core Model.php file, I set it up in the construct : 

`    function __construct()
    {
        try {
            self::openDatabaseConnection();
            self::setupCaching();
        } catch (\PDOException $e) {
            exit('Database connection could not be established.');
        }
    }

    public function setupCaching()
    {
      // set cache instance
      $this->cache = \Mini\Core\Cache::getInstance();
    }
` 

and that's pretty much it. I can now use things like `$Cached = $this->cache->getItem($key)` in my models
