### ISSUE TITLE
Handle million key

### ISSUE THREAD

**Issue by rachmawatiafrida** [PHPSocialNetwork/phpfastcache#587]
Is it possible to handle big data (10 million key) in sqlite driver? Thanks,

**Comment by Geolim4** [comment]
Hello,

This could be theoretically possible but discouraged except if you have a monster SDD configuration.
For that such amount of key, I'm advising you to use memory-based drivers such as Redis, Ssdb, Cassadra etc. (Check out README to see the list of high-performances drivers).

Cheers,
Georges

**Comment by rachmawatiafrida** [comment]
How to delete cache by prefix? Can i use SQLite manager to run query? Do you have example query?

**Comment by Geolim4** [comment]
Don't access directly to the database that is handled by PFC, you would mess up the internal references created by PFC. 
Use tags instead. (See the README).

Again, if you really have million keys in your cache, I'm seriously suggesting you to choose a memory key-value driver.
SQLite is really not intended for massive storage use.
