### ISSUE TITLE
Custom driver

### ISSUE THREAD

**Issue by szepeviktor** [PHPSocialNetwork/phpfastcache#588]
Hello!

We'd like to add a modified Redis driver that implements deleting keys matching a wildcard pattern (by using a Lua script).

Is there a documentation or example on adding a custom driver while not modifying phpfastcache's files?

**Comment by Geolim4** [comment]
Hello,

What do you mean by "We'd like to add a modified Redis driver " ?
You want to submit a Pull Request, or just "extend" the Redis driver ?

Cheers,
Georges

**Comment by szepeviktor** [comment]
Just extend it in our code base.
Is it possible?

**Comment by Geolim4** [comment]
Check this out:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV5%CB%96%5D-Setup-your-own-namespace

In your own namespace, just extend the Redis driver by your own one.

**Comment by szepeviktor** [comment]
Thank you!
