### ISSUE TITLE
Clear section of cache

### ISSUE THREAD

**Issue by tylercollier** [PHPSocialNetwork/phpfastcache#59]
I'd like to clear a section of my cache. Say for example that I store data by prefixing it with a namespace. Perhaps I cache some twitter data, facebook data, etc. I might store them as `twitter.myvalue1`, `twitter.myvalue2`, and `facebook.myvalue1`, `facebook.myvalue2`. How could I delete the cache entries for twitter? And I don't know all the names of the values. It's not necessary myvalue1/2/3/etc, I just know it starts with `twitter`.

**Comment by rajneeshojha** [comment]
were you able to implement this group cache?

**Comment by tylercollier** [comment]
@rajneeshojha: yes. I did it just like spud suggested. It was very simple. It's in my own code, not part of the phpfastcache library, so I did not do a pull request or anything.

**Comment by rajneeshojha** [comment]
can you please share the code? Regards
Rajneesh Ojha 


     On Thursday, July 23, 2015 2:51 AM, Tyler Collier <notifications@github.com> wrote:
   

 @rajneeshojha: yes. I did it just like spud suggested. It was very simple. It's in my own code, not part of the phpfastcache library, so I did not do a pull request or anything.—

**Comment by tylercollier** [comment]
See code here: https://github.com/khoaofgod/phpfastcache/issues/59#issuecomment-58953860
