### ISSUE TITLE
Additional information in the value such as time 

### ISSUE THREAD

**Issue by WuJiY** [PHPSocialNetwork/phpfastcache#594]
### Configuration:

PhpFastCache version: ` 7` redis
PHP version: ` ...7...`
Operating system: ` ...... `

#### Issue description:

> ... What is the purpose of adding additional information such as time?...

**Comment by Geolim4** [comment]
Hello,

What are you talking about exactly ?

Cheers,
Georges

**Comment by WuJiY** [comment]
how can I configure to remove

**Comment by Geolim4** [comment]
You just can't since this is a part of the core.
It contains important item information such as expiration date, tags, etc.
They are internally stored and unserialized when the cache item is called.

**Comment by WuJiY** [comment]
Ok, I see. thank you for your reply. Have a nice day！

**Comment by WuJiY** [comment]
Ok, I see. thank you for your reply. Have a nice day！
