### ISSUE TITLE
How to increase limited memory each object using Memcached.

### ISSUE THREAD

**Issue by HardikElsner** [PHPSocialNetwork/phpfastcache#596]
### Configuration:

PhpFastCache version: `6.1.2 `
PHP version: ` 7.0.18 `
Operating system: ` Ubuntu 14.04 `

#### Issue description: I have use phpfastcache and i need to store around 128MB data using Memcached but as per your example it's not working. I have check CacheManager.php file there is one option like limited_memory_each_object i have increase that and as per variable comment it's working only Memcache(d) drivers only once i check in your site option you have mention limitedmemoryeach_object _| int (default: 4096)_ [>=V4.2] Maximum size (bytes) of object stored in memory. Currently only supported by Cookie driver.

Please let me know i need to store 128MB data using Memcached .

**Comment by Geolim4** [comment]
Hello,

Just setupyour Memcache backend:

https://serverfault.com/questions/202017/how-to-increase-the-amount-of-memory-memcache-uses

Cheers,
Georges.

**Comment by HardikElsner** [comment]
Hello Georges,

Thanks for your time.

I have already did this things but not stored more then 1MB. Any things else i need to do?

**Comment by Geolim4** [comment]
Nothing in the applicative level can be done for that. It's more likely a server-side configuration :/

**Comment by HardikElsner** [comment]
I have set 1024MB on server but one i store the data using phpfastcache memcache example its not stored.

**Comment by Geolim4** [comment]
Like I said, this not Phpfastcache-related, so I can't do anything for you with this issue.

**Comment by HardikElsner** [comment]
CacheManager.php have one variable **limited_memory_each_object** only supported by Cookie driver or Memcache ?

**Comment by Geolim4-dev** [comment]
Look the Wiki:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-The-driver-options-config

It's only valid for Cookie driver.

**Comment by Geolim4** [comment]
Look the Wiki:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-The-driver-options-config

It's only valid for Cookie driver.

**Comment by HardikElsner** [comment]
Can you please check **CacheManager.php** line no : 137
/**
* Maximum size (bytes) of object store in memory
* (Memcache(d) drivers only)
*/
'limited_memory_each_object' =>  4096,

https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/CacheManager.php

Here is the comment say it's working only Memcache.

Is there any another confrontation to store more then 1MB data in memcache ?

**Comment by Geolim4** [comment]
It's just a typo, it's reserved for the Cookie driver exclusively.
And again **no**, this is clearly a server configuration, php does not even offer an option to setup that since this is the kind of option that only a server administrator can manage.

**Comment by Geolim4** [comment]
I'm locking this issue now since this out of he phpfastcache's scope.
