### ISSUE TITLE
Dynamically loading cache data

### ISSUE THREAD

**Issue by pankajmalkani** [PHPSocialNetwork/phpfastcache#601]
### Configuration:

PhpFastCache version: ` 6.1.2 `
PHP version: ` 7.0 `
Operating system: `server 2012 r2 `

When it loads Redis data for the first time for an example fetching from database with same keyword and then save onto cache for 10 mins then it will automatically be fetched from cache while loading more than once but whenever i change the keyword within a minute but howerver it displays stale/old Redis data rather due to cache persistence. Please let me know how to kill the old Redis cache and reload the data with new keyword and then save onto cache dynamically.

thanks and regards,
Pankaj

**Comment by Geolim4** [comment]
Did you read the API section in readme ?
https://github.com/PHPSocialNetwork/phpfastcache#item-api

There's is everything here to manipulate the cache for every needs.

Cheers,
Georges

**Comment by pankajmalkani** [comment]
thanks for the link provided. But there are too many items in API. Can you guide me to the correct manipulation of cache item as per my logic above?

**Comment by Geolim4** [comment]
> clear() // Allows you to completely empty the cache and restart from the beginning

**Comment by pankajmalkani** [comment]
Thanks again. But how to identify new data which is different from previous data being loaded into cache.

**Comment by Geolim4** [comment]
Then don't use cache, I think you got a misconception of cache concept. A cache means that the data are temporary stored and frozen for a given time.
