### ISSUE TITLE
CacheManager::setDefaultConfig() must be an instance of

### ISSUE THREAD

**Issue by ghuisman19** [PHPSocialNetwork/phpfastcache#602]
### Configuration:

PhpFastCache version: 7.0.0.rc4
PHP version: 7.0.9
Operating system: Windows 10 / XAMPP

#### Issue description:
I get an error on this code:

use Phpfastcache\CacheManager;

CacheManager::setDefaultConfig(array(
         'path' => $framework->paths['tmp']
));

$InstanceCache = CacheManager::getInstance('files');
return $InstanceCache->getItem($key);

**Error:**
Fatal error: Uncaught TypeError: Argument 1 passed to Phpfastcache\CacheManager::setDefaultConfig() must be an instance of Phpfastcache\Config\ConfigurationOption, array given

maybe i do something wrong..

**Comment by Geolim4** [comment]
Hello @ghuisman19 

That's the new subtility of the V7 ^^
As of the V7, the configuration must be a valid `Phpfastcache\Config\ConfigurationOption` object :)

Here's a migration guide from the V6 to the V7:
https://github.com/PHPSocialNetwork/phpfastcache/blob/v7/docs/migration/MigratingFromV6ToV7.md

Cheers,
Georges
