### ISSUE TITLE
Keep file cache at maximum size

### ISSUE THREAD

**Issue by texelate** [PHPSocialNetwork/phpfastcache#611]
**Configuration (optional)**
V 6.0.

**My question**
I couldn't find anything relating to this but I am using file-based caching. I just wondered if there is an option to keep the file cache at a maximum size in MB? Let's say it's set to 100MB and a cache is added that makes the file cache exceed this the idea would be phpfastcache removes cache entries until the aggregate size is below 100MB, starting with the oldest.

As a second best, is there an option to _clear_ the cache after it reaches a certain size?

Does it do this? No worries if not, I'll just run a cron job daily and monitor it that way.

Great work, by the way, thanks!

**Comment by Geolim4** [comment]
Hello,

Since the configuration is the same for all drivers (abstraction) this is currently not possible.
And will probably not implemented in the future since this must be abstract-implemented and some drivers does not support that kind of operation.

Cheers,
Georges

**Comment by texelate** [comment]
I thought I'd ask anyway.

Thanks for the fast reply and all your work on this project!
