### ISSUE TITLE
Randomly getting the phpFastCacheIOException 

### ISSUE THREAD

**Issue by hriziya** [PHPSocialNetwork/phpfastcache#614]
**Configuration**
- **PhpFastCache version:** 6.0.2
- **PhpFastCache API version:** 1.2.5
- **PHP version:** PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )
- **Operating system:** Ubuntu 16.04

**I am using this since more than a year, and getting such permission exception once in a month or so. 
 It is completely random behavior and has no specific steps to duplicate it. Can anyone help with that?**

I have checked the CacheManager class and the default setting is 
`     'default_chmod' => 0777,`

here are my doubts
1) Should I use the `"autoTmpFallback" = true` in settings?
2) If this is write permission issue, then it should trigger exception on every try of writing content to directory. so can anyone help me find the exact issue?

here is the detailed log of the exception message. 

`Fatal error: Uncaught phpFastCache\Exceptions\phpFastCacheIOException: 
PLEASE CHMOD /tmp/beta/Auto/Files/73/74 - 511 OR ANY WRITABLE PERMISSION! in /var/www/html/beta/web_services/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/Pool/IO/IOHelperTrait.php:157` 

**Stack trace:** 
`#0 /var/www/html/beta/web_services/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Files/Driver.php(72): phpFastCache\Drivers\Files\Driver->getFilePath('all_types') `

`#1 var/www/html/beta/web_services/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/Pool/CacheItemPoolTrait.php(353): phpFastCache\Drivers\Files\Driver->driverWrite(Object(phpFastCache\Drivers\Files\Item)) `

`#2 /var/www/html/beta/web_services/vendor/phpfastcache/phpfastcache/src/phpFastCache/Helper/Psr16Adapter.php(84): phpFastCache\Drivers\Files\Driver->save(Object(phpFastCache\Drivers\Files\Item)) `

`#3 /var/www/html/beta/web_services/_HELPER.php(1257): phpFastCache\Helper\Psr16Adapter->set('all_types', Array, 1200) `

`#4 /var/www/html/beta/web_services/service.php(417): HELPER in /var/www/html/beta/web_services/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/Pool/IO/IOHelperTrait.php on line 157`

**Comment by Geolim4** [comment]
Hello,

I don't know what to say, tests are all green as you can see:
https://travis-ci.org/PHPSocialNetwork/phpfastcache

I may have a clue, but I need to see your cache code context :)
If it's sensitive, send me the sample at contact-at-geolim4.com

Thanks

**Comment by Geolim4** [comment]
As I have no possibility to create a test for that, I'm going to push a preventive fix that should logically fix your issue.

Here's my clue:
https://github.com/kalessil/phpinspectionsea/blob/master/docs/probable-bugs.md#mkdir-race-condition

**Comment by Geolim4** [comment]
Fix will be available in the next release (around next week).

**Comment by hriziya** [comment]
Thank you so much!

**Comment by Geolim4** [comment]
Since the v6 had no new release since march, I'm gonna release one immediately.
The v7 will wait a bit more thought.

**Comment by Geolim4** [comment]
Here you go:
https://github.com/PHPSocialNetwork/phpfastcache/releases/tag/6.1.3

**Comment by hriziya** [comment]
Hey @Geolim4 , I am using the Latest release 6.1.3..  
![image](https://user-images.githubusercontent.com/4135216/41341655-d48f9b08-6f17-11e8-89bb-50dab89a2b58.png)

I am still seeing the error
` Uncaught phpFastCache\Exceptions\phpFastCacheIOException: PLEASE CHMOD /tmp/beta/Auto/Files/5e/e0 - 511 OR ANY WRITABLE PERMISSION! in /var/www/html/beta/web_services/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/Pool/IO/IOHelperTrait.php:157`
**Stack trace:**
`#0 /var/www/html/beta/web_services/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Files/Driver.php(72): phpFastCache\Drivers\Files\Driver->getFilePath('all_modules')`

`#1 /var/www/html/beta/web_services/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/Pool/CacheItemPoolTrait.php(353): phpFastCache\Drivers\Files\Driver->driverWrite(Object(phpFastCache\Drivers\Files\Item))`

`#2 /var/www/html/beta/web_services/vendor/phpfastcache/phpfastcache/src/phpFastCache/Helper/Psr16Adapter.php(84): phpFastCache\Drivers\Files\Driver->save(Object(phpFastCache\Drivers\Files\Item))`

`#3 /var/www/html/beta/web_services/_HELPER.php(1257): phpFastCache\Helper\Psr16Adapter->set('all_modules', Array, 1200)`
`#4 /var/www/html/beta/web_services/service.php(274): HE`

here is the file created by phpfastcache 
![image](https://user-images.githubusercontent.com/4135216/41341721-08fa07e8-6f18-11e8-9b1d-3e82c58543b6.png)

however, I have given the full right 777 to the parent directories. 
![image](https://user-images.githubusercontent.com/4135216/41341840-5808f092-6f18-11e8-8310-fdf871813f40.png)

I have checked the CacheManager.php and it has `'default_chmod' => 0777,` so It should create file with 0777 I believe. 

Let me know if this can be fixed. 

Thank you

**Comment by Geolim4** [comment]
Are you sure that you updated the right composer ?

Because I see that error in your stack:
> Uncaught phpFastCache\Exceptions\phpFastCacheIOException: PLEASE CHMOD /tmp/beta/Auto/Files/5e/e0 - 511 OR ANY WRITABLE PERMISSION! in /var/www/html/beta/web_services/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/Pool/IO/IOHelperTrait.php:157

But it is not matching that line 157 updated in v6:
https://github.com/PHPSocialNetwork/phpfastcache/blob/v6/src/phpFastCache/Core/Pool/IO/IOHelperTrait.php#L157

But you have updated composer in 
/var/www/html/beta/web_panel/ while your error seems to be in `/var/www/html/beta/web_services/` ?

**Comment by hriziya** [comment]
Aaah, I see. Good catch buddy. Let me update it under /web_services and I will get back to you if needed. 

Thank you

**Comment by hriziya** [comment]
So, the issue with new files being created with wrong permission is fixed in 6.1.3?

**Comment by Geolim4** [comment]
It has to pe as per https://github.com/PHPSocialNetwork/phpfastcache/commit/ab15efd1dfe6b36e698d19a49df95dc210a59cde

**Comment by Geolim4** [comment]
@hriziya Is it working now ? :)

**Comment by hriziya** [comment]
I have manually set the full permission to existing directories..

I did not see the error again, so it seems working..

**Comment by hriziya** [comment]
I have faced this issue again on my another server where I have Ubuntu 18.04, PHP 7.4, nginx,  and `"phpfastcache/phpfastcache": "7.1.0"` and I am using CacheManager 

![image](https://user-images.githubusercontent.com/4135216/76846569-b7556000-6866-11ea-804d-6480890452ba.png)

Do you think this could have happen due to multiple process try to access the same file (I have no idea about it though).. 

I can easily overcome it by hiding the warning message, but as this is beta site, I used to keep it ON. 
I am copying my code here to make sure it is setup correctly.

![image](https://user-images.githubusercontent.com/4135216/76847048-7873da00-6867-11ea-8031-a511530c13eb.png)

Let me know if I need to set any special settings?

**Comment by Geolim4** [comment]
Nah it's your OS that clean up the temp directory, set a dedicated cache directory and the error will go away forever :)

/tmp should be for a temporary usage !

**Comment by hriziya** [comment]
That make sense. Thank you.

**Comment by Kokil** [comment]
I got the same issue in version 8.1.2
The directory /tmp/phpfastcache/cli/Files could not be created. {"exception":"[object] (Phpfastcache\\Exceptions\\PhpfastcacheIOException(code: 0):

**Comment by Geolim4** [comment]
> I got the same issue in version 8.1.2 The directory /tmp/phpfastcache/cli/Files could not be created. {"exception":"[object] (Phpfastcache\Exceptions\PhpfastcacheIOException(code: 0):

Check the ownership/chmod permission of you cache directory. The tests are passing without any issue recorded:
https://app.travis-ci.com/github/PHPSocialNetwork/phpfastcache/jobs/562163535#L3991

**Comment by jaideejung007** [comment]
> I got the same issue in version 8.1.2 The directory /tmp/phpfastcache/cli/Files could not be created. {"exception":"[object] (Phpfastcache\Exceptions\PhpfastcacheIOException(code: 0):

The same issue I encountered was resolved by specifying the proper host-allowed cache directory path. I specified the path as "/home/yourusername/domains/yourdomain.com/public_html/yourproject/data/cache" where I'm using DirectAdmin as the host for the control panel, and this problem is now fixed. ✅
