### ISSUE TITLE
cache folder empty

### ISSUE THREAD

**Issue by junxien** [PHPSocialNetwork/phpfastcache#618]
**Configuration (optional)**
- **PhpFastCache version:** 7.0
- **PHP version:** 7.0.30
- **Operating system:** Linux

**My question**
Hi i am using the latest version with a shared hosting and couldn't figure it out how it works, i am using code example providing from site here is the code :

=====================
```
require __DIR__ . '/vendor/autoload.php';
use Phpfastcache\CacheManager;
use Phpfastcache\Config\ConfigurationOption;

// Setup File Path on your config files
// Please note that as of the V6.1 the "path" config 
// can also be used for Unix sockets (Redis, Memcache, etc)
CacheManager::setDefaultConfig(new ConfigurationOption([
    'path' =>  __DIR__.'/tmp' // or in windows "C:/tmp/"
]));

// In your class, function, you can call the Cache
$InstanceCache = CacheManager::getInstance('files');

/**
 * Try to get $products from Caching First
 * product_page is "identity keyword";
 */
$key = "product_page";
$CachedString = $InstanceCache->getItem($key);

$your_product_data = [
    'First product',
    'Second product',
    'Third product'
     /* ... */
];

if ($CachedString->isHit()) {
    $CachedString->set($your_product_data)->expiresAfter(50);//in seconds, also accepts Datetime
	$InstanceCache->save($CachedString); // Save the cache item just like you do with doctrine and entities

    echo 'FIRST LOAD // WROTE OBJECT TO CACHE // RELOAD THE PAGE AND SEE // ';
    echo $CachedString->get();

} else {
    echo 'READ FROM CACHE // ';
    echo $CachedString->get()[0];// Will print 'First product'
}

/**
 * use your products here or return them;
 */
echo implode('<br />', $CachedString->get());// Will echo your product list

```
=============================================

and it's only return READ FROM CACHE //  without printing any product. And the tmp folder is empty. This is my phpinfo http://indo.a2hosted.com/ . Did i do anything wrong or it's just server side issues? I'm sorry i'm new to composer stuffs. Thank you for reading this.

**Comment by Geolim4** [comment]
Hello

Try to negate isHit() 😅
The exemple is buggy lol.

Cheers,
Georges

**Comment by junxien** [comment]
thanks George for the reply..... lol :smile:  I have changed it to is_null($CachedString->get()) and its working now... i can't believe i'm struggling for more than 12 hours for this :laughing:

**Comment by Geolim4** [comment]
Prefer using isHit() to test if it comes from cache. It's about a race
condition.
