### ISSUE TITLE
Method getOptionName() not implemented

### ISSUE THREAD

**Issue by mrcnpdlk** [PHPSocialNetwork/phpfastcache#619]
**Configuration**
- **PhpFastCache version:** 7.0.0
- **PhpFastCache API version:** 2.0.4
- **PHP version:** 7.2.5
- **Operating system:** Debian GNU/Linux 9 (stretch)

Method `getOptionName()` not implemented

I get in log:
```
Method "Phpfastcache\Config\ConfigurationOption::getOption" is deprecated, use "getOptionName()" instead, file: <mydir>/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Config/ConfigurationOption.php, line: 166
```

**To Reproduce**
1. Use e.g.: `$this->oCache->getConfig()->getOption('defaultTtl');`
Where Cache is `ExtendedCacheItemPoolInterface`
2. See error

**Expected behavior**
Implement method `getOptionName()`

**Comment by Geolim4** [comment]
Hello,

I think you misunderstood the `getOptionName()` context:
Try that instead:
`$this->oCache->getConfig()->getDefaultTtl();`

Cheers,
Georges

**Comment by mrcnpdlk** [comment]
Ok. Thanks.
But In version 6.x i used:
```$this->oCache->getConfigOption('defaultTtl');```
After Upgrade to 7 a I get:
``` Method "Phpfastcache\Core\Pool\DriverBaseTrait::getConfigOption" is deprecated, use "getConfig()->getOptionName()" instead```

**Comment by Geolim4** [comment]
Yeah this is a normal behavior, as stated in the migration guide, this change is deliberate to offer a stronger and better configuration system to developers :)

**Comment by mrcnpdlk** [comment]
Thanks a lot, I've fixed my repo.
