### ISSUE TITLE
Redis/Predis "prefix" option

### ISSUE THREAD

**Issue by frumbert** [PHPSocialNetwork/phpfastcache#627]
- **PhpFastCache version:** getPhpFastCacheVersion not found.
- **PhpFastCache API version:** 1.2.5
- **PHP version:** 7.0.30 
- **Operating system:** mscos 10.13.5 / debian 9

**My question**
> Can I set a prefix on the redis driver (Redis::OPT_PREFIX). Is this possible in V7 ? I

**Comment by Geolim4** [comment]
Yes and no...

This is natively not possible but as of the v7 you can provide your own Redis client:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-Configuration-Options#redispredis-specific-options

So in the meantime that I add the support for this option you can make use of your own Redis client.

Cheers,
Georges

**Comment by frumbert** [comment]
Ok, I'll have to look into the new version then. It's probably just as much work to refactor my apps to keep up to date than it is to hacky-workaround the prefix problem I'm having.

**Comment by Geolim4** [comment]
I'm re-opening this issue to work on this for the 7.0.2 ;)

**Comment by Geolim4** [comment]
The option "optPrefix" has been added and will be available as of the 7.0.2 comes out (in a couple of weeks or less).

Thanks @frumbert 
Cheers,
Georges.L
