### ISSUE TITLE
Psr\SimpleCache\CacheInterface dependecy in bin folder

### ISSUE THREAD

**Issue by dol** [PHPSocialNetwork/phpfastcache#628]
The current version contains a copy of Psr\SimpleCache\CacheInterface in the bin folder. https://github.com/PHPSocialNetwork/phpfastcache/blob/4aafbfea7cce1541ab4d7403fe60c9bfab7a75c8/bin/dependencies/Psr/SimpleCache/src/CacheInterface.php

My IDE complains about multiple instances of the class. Why are this dependencies shipped?

**Comment by Geolim4** [comment]
Hello,

Mine does too, the deps are shipped for those that are not making use of Composer benefits, using our [standalone auto-loader](https://github.com/PHPSocialNetwork/phpfastcache/blob/master/lib/Phpfastcache/Autoload/Autoload.php).

Just ignore them in your project, those deps are only loaded if Phpfastcache is not included in a project using composer.

Cheers,
Georges
