### ISSUE TITLE
Couchbase document query using N1QL

### ISSUE THREAD

**Issue by Yamakasi** [PHPSocialNetwork/phpfastcache#630]
Hi Guys,

This is a great library and also use a lot I see. I'm a huge fan of Couchbase and wondered if you thought about the fat that you can also query buckets their document using N1QL. I cannot see if it's in the library but would that be an idea to add ?

Thanks a lot for this great library!

Cheers,

Matt

**Comment by Geolim4** [comment]
Hello,

See by yourself:
https://github.com/PHPSocialNetwork/phpfastcache/blob/master/lib/Phpfastcache/Drivers/Couchbase/Driver.php

I'm using the CouchbaseClient class so I have no idea what's behind it.
I'm not very familiar with Couchbase and I worked only to test CRUD operations to work well.

If you fee like something could be improved feel free to submit a PR 😅 

Cheers,
Georges

**Comment by Yamakasi** [comment]
Hi,

Thanks for the quick response, indeed, default bucket set/get commands.

For this usable N1QL feature we need a (simple) querybuilder, examples for N1QL are:
[https://developer.couchbase.com/documentation/server/current/sdk/php/n1ql-queries-with-sdk.html](url)

I need to see if I can fiddle something in but if people have ideas about it and are familair with this lib in development I think it's even better :)

Cheers,

Matt

**Comment by Geolim4** [comment]
Do you really think that N1QL are "significantly faster" than traditional get/set commands ?
I means, if its improving slightly the performances I'd prefer not take the risk to update significantly something I don't control confidently.

However, if this is a significant improvement that effectively reduce the time-spend I'm really interested and ready to ship it for the next minor version (7.**1**.x). 

Cheers,
Georges

**Comment by Geolim4** [comment]
If you could provide me some Couchbase server to make the tests and dev, I'm completely open to it.
Actually I missing some free time to work on this kind of improvement despite the fact that I would terribly like to learn and discover new practices with these NoSQL backends.

By design and as Psr6 Phpfastcache would use upsert only because there's no need to check if it already exists or not.

> small question next to this: I'm installing phpfastcache/phpfastcache but I see it requires all cached drivers to be loaded in PHP, I think that is too much overhead or can I go around this ? 

Thanks to modern autoload systems provided by Php (spl_autoload) and composer, Php only load called classes on the fly. This means if you make use of Couchbase driver, only Couchbase file & Phpfastcache core will be loaded, nothing more.

**Comment by Yamakasi** [comment]
I'm not able to provide you a server currently, I run it on a local dev VM as well. Installation is easy these days, goes by itself.

I cannot agree with if you need to check if a document already exist or not. If it's cached and cache is already faster to access you need to know if it exists, there is cache for and you also fetch that document after it as well, or actually at the same time. It's just faster to access cache in any ways then you SQL backend in that case.

OK, that is indeed a nice feature of PHP, autoload, but why does someone need to install 25 extra extentions to install a composer package where he only uses 1 or a few, doesn't sound good to me so that might need some changement if you ask me.

For the rest this library is great I think 👍

**Comment by Geolim4** [comment]
When I talk about upsert it's only when using SET command only, not GET :)

When the user choose to persist an item there's no need to check it before
inserting at all :)

The library does not ask for many extensions, most of them are "suggested"
and each driver has its own requirements.

The only required extensions are mbstring and json which are part of the
core of phpfastcache.

Plus psr6 interface for being compliant.

Cheers,
Georges

**Comment by Yamakasi** [comment]
Sure Upserts are SET only! But for multiple upserts you could check if N1QL is faster compared to upsert. You could even UPSERT in SQL based on your SELECT. Sounds pretty flexible to me as extention to the cache.

About persistent, I don't know what you mean there but if you want to cache for an X period or based on some data in the document and don't want to expire but want to check for that data in the document cache is still faster, after it you can query SQL if needed and upsert/update again. It's not always needed but in some cases very handy.

It seems that composer is complaining about some Guzzle issue name naming it Problem 1 and then composer with the enable extentions... so I think that is fixed.

Got the idea ?

**Comment by Geolim4** [comment]
I'll check it out in the future when I'll reinstall my vagrant boxes since I formatted my computer recently.

Guzzle does not came from the phpfastcache's deps at all, the only one dep is the psr6 interface which has no other deps.

**Comment by Geolim4** [comment]
The support of many cache backend is the reason why phpfastcache became some kind of "popular".
Code once regardless the cache backend you choose, the abstraction allows you to not refactor your whole code and just update the configuration passed to the cache manager.

Why so many cache backends ? Different needs, different developments, different environment. So people just need filecache, some need memorycache.

**Comment by Yamakasi** [comment]
Sure the refactoring is good you don't have to do then. Querying Couchbase should maybe not lineup with the ideas behind the library indeed when others don't support it.

Does the library add some "latency" instead of writing a class for one caching backend for an example ? Is that tested maybe ?

**Comment by Geolim4** [comment]
If there's a latency, its extremely minor because phpfastcache has been optimized more and more over the major versions (v5, v6, v7) and became even more reliable since the v7 as it introduced strict types and type contracts. The idea of abstraction whatever the language/platform your choose is to have a very minor performance concession for a highly reliable and configurable application.

Also since php7 the performance difference is so insignificant that worrying about some nanosecond gained bypassing the abstraction is pointless.

Regarding the current Couchbase client I'm not even sure that there's a significant performance decrease especially if you're working with a set of redundant clusters.

**Comment by Geolim4** [comment]
Also remember that [Couchbase extension](https://github.com/couchbase/php-couchbase) (in contrary with  used by phpfastcache is written and compiled in C making the performance difference even more pointless ;)

**Comment by Yamakasi** [comment]
Ah good to hear, sure there had been optimized a lot over the versions, great to hear!

I don't worry about the couchbase SDK, it's extremely efficient and fast and that with an optimized abstraction layer I think it's a great solution, also with the options you build in!

Thanks for the clearifications !

**Comment by Geolim4** [comment]
You're welcome :)

**Comment by Yamakasi** [comment]
What I wanted to add, besides the query is nice and actually easy to add I see now, it's also an alternative for tagging because that is what you cannot do with Couchbase so far. 

Agree ?

**Comment by Geolim4** [comment]
Yeah tagging is natively supported whever the cache backend you choose.

**Comment by Yamakasi** [comment]
Yeah I wasn't sure about it, that is great. That is something the library provides in a fancy way ? I now store binary so I'm not able to see the data but it are extra keys for the document and not in the document it's data ?

**Comment by Geolim4** [comment]
There's a tag index for each tags that reference item were its tagged in.
This has been made in order to improve performances when looking for items by tags to avoid whole cache backend scanning to loop for item that possess tags.

**Comment by Yamakasi** [comment]
Ah OK, I saw that, so the second index for a document is actually the secondary indices ? That is why I also said earlier in one of my edits here that it might not be needed to N1QL at all, you just need to tag in a logical way.

Would it be possible to debug the cache in a readable format with a "debug" option ? It's now binary by default.

About the tags, I was wondering if you will get all documents when you search on a set of tags or only the matching one for the full array. <- can be solved with identical tags as well so just something I like to know.

Thanks again for the great work! It's pretty powerfull!
