### ISSUE TITLE
V6 redis driver - wrong key used in driverConnect

### ISSUE THREAD

**Issue by frumbert** [PHPSocialNetwork/phpfastcache#632]
PhpFastCache version: V6 branch
PhpFastCache API version: 1.2.5
PHP version: 7.0.30
Operating system: mscos 10.13.5

I realise that V6 is old (and am in process of moving to the v7 branch) but I found a problem in the Redis `driverConnect` method I found while debugging why changing database index wasn't working. The config object for host, port etc is being tested for values and falling back to a default, however the database settings are stored in a `redis` key inside the `config` object on `$this`, not as a key on the config itself, as implied by

            $host = isset($this->config[ 'host' ]) ? $this->config[ 'host' ] : '127.0.0.1';

This should be:

            $host = isset($this->config['redis'][ 'host' ]) ? $this->config['redis'][ 'host' ] : '127.0.0.1';

I just wanted to put this out there in case anyone else came across it who is still using the older branch.

**Comment by Geolim4** [comment]
Hello,

Thanks for the report, I'll take a look tomorrow.

Cheers,
Georged

**Comment by Geolim4** [comment]
Hello,

The V6 is not that old, it's even actively maintained, see the support timeline below:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-Global-support-timeline#v6-lts-june-2017

For your issue there's no such "redis" sub-object at all:
https://github.com/PHPSocialNetwork/phpfastcache/blob/v6/src/phpFastCache/Drivers/Redis/Driver.php#L136

I tested the v6 this morning and it's working very well 👍 
Can you show me your code implementation, you may missed something ?

Cheers,
Georges

**Comment by frumbert** [comment]
hmm, during my app instantiation I'm setting the default config

```php
$cacheConfig = array(
    "storage" => "redis",
    "redis" => array(
        "host" => Config::get('REDIS_HOST'),
        "port" => (int) Config::get('REDIS_PORT'),
        "password" => Config::get('REDIS_PASSWORD'),
        "database" => (int) Config::get('REDIS_DATABASE'),
        "timeout" => ""
    )
);
\phpFastCache\CacheManager::setDefaultConfig($cacheConfig);
```

I have a cache factory class to simplify connecting to it all the time

```php
class CacheFactory {
    private static $factory;
    private $cache;

    public static function getFactory() {
        if (!self::$factory) {
            self::$factory = new CacheFactory();
        }
        return self::$factory;
    }

    public function __destruct() {
        $this->cache = null;
        self::$factory = null;
    }

    public function getCache() {
        if (!$this->cache) {
            $this->cache = \phpFastCache\CacheManager::getInstance('redis');
        }
        return $this->cache;
    }
}
```

then when using the cache the gist of my process follows this pattern

```php
$cache = CacheFactory::getFactory()->getCache();
$cacheItem = $cache->getItem("some_model");
$model = $cacheItem->get();
if (is_null($model) {
    $model = some_expensive_operation();
    $cacheItem->set($model)->expiresAfter(3600)->addTags(["tag1","tag2"]);
    $cache->save($cacheItem);
}
do_thing_with_model($model); 
```
Then I have various separate instances of the same code with different configs pointing to different databases within the one redis db.

When I was down looking at `$this->config` at around https://github.com/PHPSocialNetwork/phpfastcache/blob/v6/src/phpFastCache/Drivers/Redis/Driver.php#L136 `$this->config['redis']` is set to the values put there by `setDefaultConfig`.

**Comment by Geolim4** [comment]
```php
$cacheConfig = array(
    "storage" => "redis",
    "redis" => array(
        "host" => Config::get('REDIS_HOST'),
        "port" => (int) Config::get('REDIS_PORT'),
        "password" => Config::get('REDIS_PASSWORD'),
        "database" => (int) Config::get('REDIS_DATABASE'),
        "timeout" => ""
    )
);
\phpFastCache\CacheManager::setDefaultConfig($cacheConfig);
```

This is so wrong:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-Configuration-Options
`storage` does not exists, and Redis subkey is just ignored because it's invalid:

Try this:

```php
$cacheConfig = [
        "host" => Config::get('REDIS_HOST'),
        "port" => (int) Config::get('REDIS_PORT'),
        "password" => Config::get('REDIS_PASSWORD'),
        "database" => (int) Config::get('REDIS_DATABASE'),
        "timeout" => "" // MUST BE A VALID NUMERIC NUMBER
];
\phpFastCache\CacheManager::setDefaultConfig($cacheConfig);

```

**Comment by frumbert** [comment]
wow. 😥
when I first set this up I remember following a tutorial (probably from sitepoint) and I never thought about the default config again. pays to re-read the documentation. 

sorry for the trouble

**Comment by Geolim4** [comment]
:)

The documentation you followed probably refer to a very old version (maybe v4) which is completely different from the v5 and even more, the v6.

Don't hesitate to check the Wiki and the migrations guides, they were made specifically to help people to migrate/integrate quietly.

Cheers,
Georges
