### ISSUE TITLE
Can't seem to get this work via php classes

### ISSUE THREAD

**Issue by rnicholls** [PHPSocialNetwork/phpfastcache#640]
**Configuration (optional)**
- **PhpFastCache version:** "...replace me (Can be retrieved using method `\Phpfastcache\Api::getPhpFastCacheVersion()`)..."
- **PhpFastCache API version:** "...replace me (Can be retrieved using method `\Phpfastcache\Api::GetVersion()`)..."
- **PHP version:** "...replace me (Can be retrieved using command line `php -v | sed -n 1p`)..."
- **Operating system:** " ...replace me (You REALLY should know it)... "

**My question**
> Your question goes here

I am trying to set up a global class that allows phpfastcache to be called dynamically in multiple places and I keep getting hit with Calling many times CacheManager::getInstance(). 

```php
use Phpfastcache\CacheManager;
use Phpfastcache\Drivers\Predis\Config;
  class fastcache {

    public $InstanceCache;

    public function __construct() {
      $this->connect();
    }

    private function connect(){

      $this->InstanceCache = CacheManager::getInstance('predis', new Config([ 'host' => getenv("DATA_REDIS_HOST"), 'port' => 6379 ]));

      return $this->InstanceCache;

    }

    public function isCached($key){

      $CachedString = $this->InstanceCache->getItem($key);

      return !is_null($CachedString->get()) ? true : false;

    }

    public function setCache($key, $data, $expire = 5){

      $CachedString = $this->InstanceCache->getItem($key);

      $CachedString->set($data)->expiresAfter($expire);

      $this->InstanceCache->save($CachedString);

    }

    public function get($key){

      $CachedString = $this->InstanceCache->getItem($key);

      $data = $CachedString->get();

      return $data;

    }
  }
```

This was the only way to get it working in the way i was thinking, but I can't figure out how to basically allow it to be set, and then use it in multiple places. I am trying to run the cache on multiple calls threw out the web app.

**Comment by Geolim4** [comment]
Hello,

Allow me to give you some feedback about your code:

```php
    public function isCached($key){

      $CachedString = $this->InstanceCache->getItem($key);

      return !is_null($CachedString->get()) ? true : false;

    }
```

```php
    public function get($key){

      $CachedString = $this->InstanceCache->getItem($key);

      $data = $CachedString->get();

      return $data;

    }
```
Here too, you can improve the performance by avoiding to use a temporary and redundant variable.
Just return straightly the cache data:

```php
    public function get($key){
      return $this->InstanceCache
                         ->getItem($key)
                         ->get();
    }
```

You should make use of `isHit()` here to improve the performance instead of testing `get()` against null.

Then, your code look like that you want a simpler way to get your cache implementation.
Why don't you take a look to the [Psr16 adapter](https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV6%CB%96%5D-Psr16-adapter) instead ? This one was made for this exact purpose and is [standardized by the FIG](https://www.php-fig.org/psr/psr-16/), enjoy it :)


Finally, I'm unable to find out your code mistake, you may have passed wrong argument to your class ?

**Comment by rnicholls** [comment]
Thank you for the feedback. Really appreciate it. I implemented the suggested changes. 

The only workaround i could really find was to make the "instance" global then pass that into my class.


`$GLOBALS["InstanceCache"] = CacheManager::getInstance('predis', new Config([ 'host' => getenv("DATA_REDIS_HOST"), 'port' => 6379 ]));` <--- this is set in my app where I have things like my constants set for the application 

`private function connect(){

    $this->InstanceCache = $GLOBALS["InstanceCache"];

    return $this->InstanceCache;

 }`

Not really sure how frowned upon that is lol. but it works for now.

**Comment by Geolim4** [comment]
You really should not make use of GLOBALS variable this is a very bad bad practice :/

I don't get where's your issue, why don't you create a singleton ?

**Comment by rnicholls** [comment]
Not gonna lie. Never used a singleton before. But, that did it. Thank you so much!

**Comment by Geolim4** [comment]
You're welcome :)
