### ISSUE TITLE
di you check out phpcache with xpm package manager (http://eirt.science/xpm/)? 

### ISSUE THREAD

**Issue by eirtscience** [PHPSocialNetwork/phpfastcache#641]
Did you check phpfastcache with xpm package manager(http://eirt.science/xpm/) ?

**Comment by Geolim4** [comment]
Hello,

At this moment the only package manager we support is packagist.
No additional package manager is planned at this time.

Being alone actually to maintain this library I won't add more third dependency to manage.

Cheers,
Georges.L
