### ISSUE TITLE
Accept Decimals and Floats as tags

### ISSUE THREAD

**Issue by Yamakasi** [PHPSocialNetwork/phpfastcache#642]
While working with the great tag feature I stumbled into the "issue" that you cannot use decimals/floats as tags, like latitude or longitude. 

I can remove the dot in my script but that is not ideal I think so I wonder, why is it not possible to use decimals or floats, would this be an issue as strings can contain dots as well.

**Comment by Geolim4** [comment]
Hi,

Can you please reformat the message using the predefined template please ?

Also please be more specific than "you cannot use decimals/floats as tags"

Thanks.

**Comment by Yamakasi** [comment]
Hi,

I have looked into the templates, I can make something out of it but it's not ideal if you ask me, questions cannot always fit in there I have seen.

So far I can give you this as what happens:

`Phpfastcache\Exceptions\PhpfastcacheInvalidArgumentException
File:
    /myprojects/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Core/Item/ItemExtendedTrait.php:328
Message:
    $tagName must be a string
Stack trace:
    #0 /myproject/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Core/Item/ItemExtendedTrait.php(338): Phpfastcache\Drivers\Couchbase\Item->addTag(50.9422858)`

**Comment by Yamakasi** [comment]
Sounds valid to me! Maybe this are simple and small notes we can add to the docs ?
