### ISSUE TITLE
Disable Cache folder by Hostname

### ISSUE THREAD

**Issue by rachmawatiafrida** [PHPSocialNetwork/phpfastcache#646]
- **PhpFastCache version:** "^7.0"
- **PHP version:** "7.0"

**My question**
I see my cache folder /cache/domain.com/Files/, how to disable grouping by hostname? I just want use /cache/Files/, thank you

**Comment by Geolim4** [comment]
Hello,

Setup `securityKey` configuration.

https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-Configuration-Options#file-based-drivers-options-

Cheers,
Georges
