### ISSUE TITLE
Why different hostname is using different cache?

### ISSUE THREAD

**Issue by hgneng** [PHPSocialNetwork/phpfastcache#652]
1. setup and read cache
```
phpFastCache::setup('apc');
$GLOBALS['phpfastcache'] = phpFastCache();
...
// set cache for the first time
$GLOBALS['phpfastcache']->set('max_count', 5);
...
$max_count = $GLOBALS['phpfastcache']->get('max_count');
```

2. update cache at host http://localhost
```
$GLOBALS['phpfastcache']->set('max_count', 1);
```

3. cache is remains the same at http://127.0.0.1
```
$max_count = $GLOBALS['phpfastcache']->get('max_count'); // 5, not 1
```

Is this behavior normal? This should bring trobles when website can be access different hostname (for example, with and without www.).

**Comment by Geolim4** [comment]
Hello,

Is this that hard to keep the issue template so I can see the library version, the phone version etc ?

Thanks.

**Comment by hgneng** [comment]
Sorry, I forgot I was using a very old version (3.0.0). But I am not planing to upgrade it. I will verify whether this issue exists in latest version in future. So we can ignore this issue now.
