### ISSUE TITLE
got error using mongodb

### ISSUE THREAD

**Issue by screamolic** [PHPSocialNetwork/phpfastcache#655]
**Configuration**
phpfastcache latest.
php 7.2
mongodb latest.

**my config

$InstanceCache = CacheManager::getInstance('mongodb', [
  'host' => $dbhost,
  'port' => $dbport,
  'username' => $dbuser,
  'password' => $dbpass,
  'timeout' => '1',
  // 'collectionName' => 'keywords',
  // 'databaseName' => $dbname
]);

**Describe the bug**

i got error like this using sample on the doc

"PHP Fatal error:  Uncaught Phpfastcache\Exceptions\PhpfastcacheInvalidConfigurationException: Invalid option(s) for the config Phpfastcache\Config\ConfigurationOption: host, port, username, password, timeout in /root/test/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Config/ConfigurationOption.php:115"

any suggestion ?

**Comment by Geolim4** [comment]
Hello,

Did you rood the migration guide ?
https://github.com/PHPSocialNetwork/phpfastcache/blob/master/docs/migration/MigratingFromV6ToV7.md#configuration-option-type


Mhhh 🤔 ....
Cheers,
Georges

**Comment by Geolim4** [comment]
Duplicate of #612

**Comment by screamolic** [comment]
i see. please update the DOCS example please  :) 👍
