### ISSUE TITLE
Does redis support hset hget?

### ISSUE THREAD

**Issue by WuJiY** [PHPSocialNetwork/phpfastcache#657]
**My question**
> Does redis support hset hget?

**Comment by Geolim4** [comment]
Hello, what usage for ? Is that some kind of "tagging" ?

**Comment by WuJiY** [comment]
I want to store the shopping cart data in redis

**Comment by Geolim4** [comment]
Store or cache it ? What do you expect with "hget" specifically ? Redis driver alredy support CRUD operations ?!

**Comment by WuJiY** [comment]
like https://redis.io/commands/hset

**Comment by WuJiY** [comment]
such as...?
append ,prepend?
Actually, I just want to store the shopping cart data in redis.

**Comment by Geolim4** [comment]
https://github.com/PHPSocialNetwork/phpfastcache#item-api-extendedcacheiteminterface

There's get/set/delete operations according the PSR6/16 specifications.

**Comment by Geolim4** [comment]
Hello @authorname,

I’m closing this issue _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the issue / add comment / clarify …).

Regards,
Georges.L
