### ISSUE TITLE
Loop over instance functions ?

### ISSUE THREAD

**Issue by Yamakasi** [PHPSocialNetwork/phpfastcache#660]
**Configuration (optional)**
All versions

**My question**
Is there a reason to loop over the $instance->get() in a while until it gives back a non empty response or doesn't it add any value at all ?

**Comment by Geolim4** [comment]
What ? I'm not sure what you're trying to do ??

**Comment by Yamakasi** [comment]
Make sure the get is done and doesn't get an empty array back as it didn't succeed. This if you talk to a couchbase cluster which could give back 3 servers, you talk to server 1 which between the getinstance() and ->get/set/etc dies and you need to try again.

**Comment by rnicholls** [comment]
Are you looping through an array of keys or are you just doing a while(true) loop. aka a infinite loop.

**Comment by Geolim4** [comment]
But what get() are you talking about ? Which interface ?

**Comment by Yamakasi** [comment]
> 
> 
> Are you looping through an array of keys or are you just doing a while(true) loop. aka a infinite loop.

Yes, a while(true) loop.

**Comment by Geolim4** [comment]
There's no loop on get as per psr6:
https://www.php-fig.org/psr/psr-6/

Please read the documentation and readme.

**Comment by Yamakasi** [comment]
> 
> 
> There's no loop on get as per psr6:
> https://www.php-fig.org/psr/psr-6/
> 
> Please read the documentation and readme.

Huh ? No I create one, that is what @rnicholls also ment. ->get() in your own while.

**Comment by rnicholls** [comment]
Could you post sample code of what you are trying to do?

**Comment by rnicholls** [comment]
Ok so, your goal seems to be keep looping until the key shows up, but shouldn't you be trying the key, if not get it from the database and cache the key?

**Comment by rnicholls** [comment]
Here is my code for example.

```
$fastcache = fastcache::getInstance();
$cacheConn = $fastcache->getConnection();

$rows = array();
$key = "query_newsArticles-$limit";

if ($fastcache->isCached($key)) { return $fastcache->get($key); }


/** Code to query DB **/

while($news = $results->fetch_object()){
 $rows[] = $news;
}

$fastcache->setCache($key, $rows);

return $rows;
```

**Comment by rnicholls** [comment]
My fastcache class

```
<?php

  use Phpfastcache\CacheManager;
  use Phpfastcache\Drivers\Predis\Config;

  class fastcache {

    private static $instance = null;
    private $conn;

    private function __construct(){
      $this->conn = CacheManager::getInstance('predis', new Config([ 'host' => getenv("DATA_REDIS_HOST"), 'port' => 6379 ]));
    }

    public static function getInstance(){
      if(!self::$instance){
        self::$instance = new fastcache();
      }
      return self::$instance;
    }

    public function getConnection(){
      return $this->conn;
    }

    public function isCached($key){
      $CachedString = $this->conn->getItem($key);
      return $CachedString->isHit();
    }

    public function setCache($key, $data, $expire = 5){
      $CachedString = $this->conn->getItem($key);
      $CachedString->set($data)->expiresAfter($expire);
      $this->conn->save($CachedString);
    }

    public function get($key){
      return $this->conn->getItem($key)->get();
    }

    public function increaseCount($key){
      $this->conn->getItem($key)->increment(1);
    }

  }

?>
```

**Comment by Yamakasi** [comment]
Yes sure, but I try because I think as explained a couchbase server could fail. This is just a function that I cal on getting an item, there is much more around it an in place. If this get returns empty I move to the Db and cache it.

**Comment by rnicholls** [comment]
So think the couchbase issue would not be on the fastcache side. 

My suggestion would be to check of the couchebase connection is active, if not loop until it is, and then use fastcache. 

If it is, go directly to using fastcache.

**Comment by Yamakasi** [comment]
@rnicholls Yes I agree there but as FastCache does initiate the instance it shoiuld be the way to check that.

 I have some sort of same class you have but every time, even when I initiate the class as Instance it complains about the driver loaded too often.

**Comment by Geolim4** [comment]
> I have some sort of same class you have but every time, even when I initiate the class as Instance it complains about the driver loaded too often.

You're just doing it wrong, **do not instantiate the same driver with the same config** multiple time in a script life. Store it statically, or assign an ID to this instance and delete it when needed.
Exemple here:
https://github.com/PHPSocialNetwork/phpfastcache/blob/master/tests/CacheInstanceId.test.php

**Comment by rnicholls** [comment]
@Yamakasi for the driver loaded too often, the way my class is done is actually specifically to fix that. try playing around with it.

**Comment by Yamakasi** [comment]
@Geolim4 yes, assign an id might work. I'm not doing it "wrong", it's the way to do in MVC's and is a little bit more complex because of being a MVC and also switching separate buckets. I have searched for a lot of ways, the Id might work but could be mentioned the docs or on the page!

@rnicholls yes I know about it and use it for other classes, it's just not possible for switching buckets, etc. As I said it's a little bit more complex in some environments.

I will report back if the Id works out, I think it will! Thanks!

**Comment by Yamakasi** [comment]
OK what the issue was is that my property was overwritten and there for it was initiating the driver over and over again. I don't know on what example I based it or if it happened during splitting up the connection class.

At least thanks for the updates, the Id way is very nice but not usable in a sane way when you need to go from top to bottom with quite some dependencies, etc.

What I dont have answered yet is would a while loop "work", I'm going to test with extra Couchbase servers to see what comes back in the instance.
