### ISSUE TITLE
Fetching raw cache value

### ISSUE THREAD

**Issue by kbhagchandani** [PHPSocialNetwork/phpfastcache#661]
**Configuration**
- **PhpFastCache version:** "7.0.3"
- **PhpFastCache API version:** "2.0.4"
- **PHP version:** "PHP 7.0.32 (cli) (built: Oct 16 2018 01:54:32) ( NTS )"
- **Operating system:** "Debian GNU/Linux 9 (stretch)"

**Is your feature request related to a problem? Please describe.**
I want to fetch raw cache value, which appears not possible in current state of the project. A simple string value set in the cache id considered as a miss because that is not serialised one. But there should be a way to get raw value. I tried to get using following workaround:
```php
$predis=$cacheManager->getConfig())->getPredisClient();
$rawValue=$predis->get('testKey');
```
Here in shared set of statements first statement crashes the system and making me clueless about it.

**Describe the solution you'd like**
provide another method **getRawItem()** or **getDriverInstance()**, to fit in the application specific usecase.

**Describe alternatives you've considered**
I have to create another instance of Predis to get the same thing done.

**Comment by Geolim4** [comment]
Hello,

Why would you do that ?

This is not how it's supposed to work:
- Build pool instance using CacheManager
- Get Cache item from pool using psr6 interfaces.

More informations here:
https://www.php-fig.org/psr/psr-6/

Cheers,
Georges

**Comment by Geolim4** [comment]
Hello @kbhagchandani,

I’m closing this issue _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the issue / add comment / clarify …).

Regards,
Georges.L
