### ISSUE TITLE
PHP7.1 with PhpFastCache 6.1.0

### ISSUE THREAD

**Issue by AlanOC91** [PHPSocialNetwork/phpfastcache#662]
**Configuration (optional)**
- **PhpFastCache version:** "6.1.0"
- **PHP version:** "5.6"

**My question**
Sorry if this is a silly question but I've searched for a bit and couldn't find an answer. Using PhpFastCache 6.1.0, am I safe to update my PHP version to 7.1?

I have plans for updating potentially this weekend but I want to make sure if it's safe beforehand.

While you don't have to answer this, you may know! Any idea if it's safe to quickly change PHP version on CloudLinux as a test? And if it doesn't work, swap back to 5.6 easily. It seems to just be a simple drop-down box selection.

**Comment by Geolim4** [comment]
Hello,

This should help you:
https://github.com/PHPSocialNetwork/phpfastcache/blob/master/docs/migration/MigratingFromV6ToV7.md

Regards,
Georges.
