### ISSUE TITLE
[Mongo DB] Missing `$driverOptions` argument when building the Mongo Client

### ISSUE THREAD

**Issue by vainj** [PHPSocialNetwork/phpfastcache#663]
**Configuration**
- **PhpFastCache version:** 4.2.0 (composer. json -> `"phpfastcache/phpfastcache" : "^7.0"`)
- **PhpFastCache API version:** 2.0.4
- **PHP version:** PHP 7.1.24-1+ubuntu18.04.1+deb.sury.org+1
- **Operating system:** " Linux Ubuntu 16.04

**Is your feature request related to a problem? Please describe.**
I would like to connect to a Mongo server using SSL certificates. 
It looks like when building the Mongo client (phpfastcache/lib/Phpfastcache/Drivers/Mongodb/Driver.php+189), the third parameter `$driverOptions` is not available (according to PHP Mongo DB library) : 
```php
$this->instance = $this->instance ?: new Client($this->buildConnectionURI($databaseName), ['connectTimeoutMS' => $timeout]);
``` 

So i cannot connect to the remote server because it requires SSL certificates to allow connection.

Did I miss something ?

**Describe the solution you'd like**
Add the third argument to the call of the Mongo DB client in order to accept the driver options.

Thanks in advance.

**Comment by Geolim4** [comment]
Hello,

Please replace:
```php
$this->instance = $this->instance ?: new Client($this->buildConnectionURI($databaseName), ['connectTimeoutMS' => $timeout]);
```

by
```php
$this->instance = $this->instance ?: new Client($this->buildConnectionURI($databaseName), ['connectTimeoutMS' => $timeout], $this->getConfig()->getOptions());
```

Then pass your Mongodb options to the "options" config name.
Tell me if it work.

Cheers,
Georges

**Comment by Geolim4** [comment]
Fixed thanks

**Comment by vainj** [comment]
Your welcome and thanks for your reactivity ;)

Last question :
Could you create a new tag in order to pull those modifications via Composer?

Thanks in advance.

**Comment by Geolim4** [comment]
Hello,

Not now (holidays etc), and I have a couple of thing to prepare in order to release a new version (changelog, tag, etc) that require a bunch of time that I don't have during Christmas holidays. I'll push a new release around first week of 2019, meanwhile please use "dev-master", thanks :)

**Comment by vainj** [comment]
Okay, thank you for your answer. I will use the "dev-master" version until then.
Have a good holiday:)
