### ISSUE TITLE
Redis Cache is the same instance

### ISSUE THREAD

**Issue by nikmauro** [PHPSocialNetwork/phpfastcache#672]
**My question**
I'm using phpfastcache with multiple projects on the same server.

I've noticed that Redis Cache is the same instance for all those projects , cache tags are getting overwritten.

Any ideas? (besides using separate servers)

**Comment by Geolim4** [comment]
Hello,

Use separate database index ?

Cheers,
George's

**Comment by nikmauro** [comment]
No i use the same database index. In the same server host Hundred of sites with redis.

**Comment by Geolim4** [comment]
Then use at least a different index for each sites.
It's not a bug since it's the "cache" behavior that works as is.

If you want to avoid overwrite side-effect, then use a distinct database index. 

Also using shared Redis instance for multiple sites is more dangerous than "practical".

**Comment by nikmauro** [comment]
Take a look in this post, it say about DB index and Prefix. The redis prefix it's drupal implementation?

If you use the Redis module for Drupal, you can set the database and prefix used by your sites. The default Redis database is 0 (so multiple sites use the same database) but the default prefix is the HTTP_HOST variable (so multiple sites use different prefix). You can however, set a shared prefix on both site in their settings.php:

$conf['cache_prefix']['default'] = 'mysite_';
You can also set prefix per cache bin, to only share a subset of the cache between them. See Redis module's README.txt for more details.

Of course, this should only be done if your are sure the cache can actually be shared. In your case, I guess the sites share the database and are used to balance the load.

**Comment by Geolim4** [comment]
The lib currently allows you to select a custom DB Index, why not making use of it.
I don't get where's issue since it's an implementation issue, not a bug ?
