### ISSUE TITLE
cant use option securitykey

### ISSUE THREAD

**Issue by screamolic** [PHPSocialNetwork/phpfastcache#674]
**Configuration**
- **PhpFastCache version:** "7.0.4"
- **PhpFastCache API version:** "DUNNO"
- **PHP version:** "7.2"
- **Operating system:** "ubuntu 18.04 "

**Describe the bug**

> ... A clear and concise description of what the bug is, goes here ... 
i cant use configuration option "securitykey"

**Additional context**
// my config //

use Phpfastcache\CacheManager;
use Phpfastcache\Config\ConfigurationOption;

$foldercache = __DIR__.'/cache';
if (!file_exists($foldercache)) {
    mkdir($foldercache);
}

CacheManager::setDefaultConfig(
    new ConfigurationOption([
        'path' => $foldercache, // or in windows "C:/tmp/"
        // 'securityKey' => "cache",
    ])
);
$InstanceCache = CacheManager::getInstance('files');

**Comment by Geolim4** [comment]
Hello,

The config "securityKey" does not belong to "Phpfastcache\Config\ConfigurationOption"....
https://github.com/PHPSocialNetwork/phpfastcache/blob/master/lib/Phpfastcache/Config/ConfigurationOption.php


Please read carefully the migration guide:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV6%CB%96%5D-Migrating-your-code-to-the-V7#configuration-option-type


Cheers,
Georges

**Comment by screamolic** [comment]
wheres belong to? sorry i dont understand. can you help me

**Comment by screamolic** [comment]
can you give me example?

**Comment by dezertdezine** [comment]
I'd like to see an example too.

**Comment by Geolim4** [comment]
Please read the WIKI, the APIs, the interfaces, etc.

I wrote a lot of documentation, please take a look at it.

**Comment by ilcham** [comment]
`<?php 
namespace Helpers;
use Phpfastcache\CacheManager;
use Phpfastcache\Helper\Psr16Adapter;
use Phpfastcache\Drivers\Files\Config;

CacheManager::setDefaultConfig(
    new Config([
        'path' => dirname(__DIR__, 3) . '/data/cache/agc',
        'securityKey' => extract_domain($_SERVER['HTTP_HOST']),
        'secureFileManipulation' => true,
        'cacheFileExtension' => 'cache'
    ])
);
  
class Cache {
    protected static $cacheDriver = 'Files';
    protected static $Psr16Adapter;

    public static function getAdapter(){
        if (static::$Psr16Adapter === null) {
            static::$Psr16Adapter = new Psr16Adapter(static::$cacheDriver);
        }
        
        return static::$Psr16Adapter;
    }
};`
