### ISSUE TITLE
Memcached ignores custom host/port configurations

### ISSUE THREAD

**Issue by zkwbbr** [PHPSocialNetwork/phpfastcache#675]
**Configuration**
- **PhpFastCache version:** "7.0.4"
- **PhpFastCache API version:** "2.0.4"
- **PHP version:** "7.3.2"
- **Operating system:** "Debian 9 (Docker image: php:7.3-apache-stretch)"

**My question**
How can I use memcached driver when connecting to a [Docker memcached container](https://hub.docker.com/_/memcached) ?

The following code below doesn't seem to work:

```php
<?php

use Phpfastcache\Helper\Psr16Adapter;
use Phpfastcache\CacheManager;
use Phpfastcache\Drivers;

$ip = '192.168.2.200';
$port = 11211;

$cfg = [
    'host' => $ip,
    'port' => $port
];

$driver = CacheManager::Memcached(new Drivers\Memcached\Config($cfg));
$cache = new Psr16Adapter($driver);
$cache->set('foo', 'bar');
echo $cache->get('foo');
```
The above code returns:

`Fatal error: Uncaught Phpfastcache\Exceptions\PhpfastcacheDriverConnectException: Memcached failed to connect with the following error message: "Memcached seems to not be connected" line 115 in /srv/app/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Drivers/Memcached/Driver.php`

---

However, when I test the same memcached connection using plain PHP, it works:
```php
$mc = new Memcached();
$mc->addServer($ip, $port);
$mc->set('foo', 'bar');
echo $mc->get('foo');
```

Any ideas why?

**Comment by Geolim4** [comment]
Hello, nope no idea.

It's up to you to find the host & port that allows memcached driver to connect to.

Cheers,
Georges

**Comment by zkwbbr** [comment]
@Geolim4 How does PHPFastCache use Memcached, does it use \[Memcached](http://php.net/manual/en/book.memcached.php)? If yes, then the code above should work as there's really no big difference.

**Comment by zkwbbr** [comment]
@Geolim4 I did some more tests and found that PHPFastCache appears to be not honoring the host and port details at all. I started a local memcached instance then it worked even after entering several fake host and port details. 

That said, this issue might not be related to Docker at all but simply due to PHPFastCache ignoring user supplied host and port details. Can you kindly confirm if this is indeed the case?

**Comment by Geolim4** [comment]
Phpfastcache does use Memcached:
https://github.com/PHPSocialNetwork/phpfastcache/blob/f50545ab2e2ffd6d1516738f2213fabe63ba6517/lib/Phpfastcache/Drivers/Memcached/Driver.php#L69

Memcacahed is also fully tested:
https://github.com/PHPSocialNetwork/phpfastcache/blob/master/tests/MemcachedAlternativeConfigurationSynax.test.php

So you've probably misconfigured the driver :/

**Comment by zkwbbr** [comment]
Not sure if it's related but I tried that [test ](https://github.com/PHPSocialNetwork/phpfastcache/blob/master/tests/MemcachedAlternativeConfigurationSynax.test.php) file and replaced line 29 and 30 with:
```php
'host' => '123',
'port' => 123,
```
which is an invalid host/port and it passed, is that expected?

**Comment by Geolim4** [comment]
The host and port are the default memcached ones, but if your memcached server does not listen on that host/port combination it's not the Pfc's fault then :)

**Comment by zkwbbr** [comment]
You mean to say it can only listen to localhost?

**Comment by zkwbbr** [comment]
Anyway, if what you're saying is true, what do you make of my first example where  PFC can't connect but using plain PHP's  `\Memcached();` can? They're both connecting on the same host/port.

**Comment by Geolim4** [comment]
What can I say ? The tests passes :/
Feel free to debug this method:
https://github.com/PHPSocialNetwork/phpfastcache/blob/f50545ab2e2ffd6d1516738f2213fabe63ba6517/lib/Phpfastcache/Drivers/Memcached/Driver.php#L69

Have a look at the config file too:
https://github.com/PHPSocialNetwork/phpfastcache/blob/master/lib/Phpfastcache/Drivers/Memcached/Config.php

And tells me if something can be improved, but actually the tests passes and my local vagrant box is connecting on a custom port too

**Comment by zkwbbr** [comment]
I'll see what I can find.

I think the custom port works fine but the issue is using a different host ip other than `127.0.01`.

Have you tried using a random fake host ip like `1.2.3.4`? If I do that it doesn't return an error and continues to work fine when it should at least return a connection error, right?

**Comment by Geolim4** [comment]
Can you try with `$mc->addServer($ip, $port);` instead of `setHost()` ?

**Comment by zkwbbr** [comment]
You mean in plain PHP memcached? Yes that's what I'm doing in my example, I don't think there's a `setHost()` method.

**Comment by Geolim4** [comment]
No I mean using phpfastcache config...

**Comment by zkwbbr** [comment]
How do I do that? This is what I'm using:
```php
$cfg = [
    'host' => $ip,
    'port' => $port
];

$driver = CacheManager::Memcached(new Drivers\Memcached\Config($cfg));
$cache = new Psr16Adapter($driver);
```

**Comment by Geolim4** [comment]
Are you using an IDE or a text-plain editor ?
If so I can understand why you haven't notice those method in `rivers\Memcached\Config()`

**Comment by zkwbbr** [comment]
IDE, I don't see `addServer()` method here https://github.com/PHPSocialNetwork/phpfastcache/blob/master/lib/Phpfastcache/Drivers/Memcached/Config.php

**Comment by Geolim4** [comment]
Sorry I mean `setServers()`

**Comment by zkwbbr** [comment]
Wait, can let me know how to properly use the PSR16 adapter with memcached? I feel like I'm missing something there. Here's what I'm currently doing:

```php
$servers = [[
    'host' => $ip,
    'port' => $port
    ]];

$conf = new Drivers\Memcached\Config;
$conf->setServers($servers);
$cache = new Psr16Adapter('memcached', $conf);
$cache->set('foo', 'bar');
echo $cache->get('foo');
```

This returns an error:

> Fatal error: Uncaught Phpfastcache\Exceptions\PhpfastcacheCoreException: The driverRead method returned an unexpected variable type: string in /srv/app/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Core/Pool/CacheItemPoolTrait.php:93

**Comment by Geolim4** [comment]
The memcached backend returned a string which is not expected at all :/

**Comment by Geolim4** [comment]
Phpfastcache stores values in a certain way and expected to retrieve them in the same way.

**Comment by zkwbbr** [comment]
The error happens just right after doing `$cache->set('foo', 'bar');`
What do you make of it?

**Comment by Geolim4** [comment]
Are you sure that you've not set data previously outside of phpfastcache api ?

**Comment by zkwbbr** [comment]
I did, I think that solves it.
Case closed I guess. Thank you!

**Comment by Geolim4** [comment]
It still bugs me why setHost() and setPort does not works on you

**Comment by Geolim4** [comment]
I have to dig it

**Comment by zkwbbr** [comment]
Yes, doing this doesn't work:

```
$conf = new Drivers\Memcached\Config;
$conf->setHost($ip);
$conf->setPort($port);
```

Also, my original first example post only works if localhost (127.0.0.1) memcached is active, it can't "see" a different IP.

**Comment by Geolim4** [comment]
I think I know why:

https://github.com/PHPSocialNetwork/phpfastcache/blob/f50545ab2e2ffd6d1516738f2213fabe63ba6517/lib/Phpfastcache/Drivers/Memcached/Driver.php#L75


I use `getHost()` and `getPort()` if `$servers` is empty.
This cannot work since it's already pre-filled here:
https://github.com/PHPSocialNetwork/phpfastcache/blob/f50545ab2e2ffd6d1516738f2213fabe63ba6517/lib/Phpfastcache/Drivers/Memcached/Config.php#L26

**Comment by Geolim4** [comment]
This can be confirmed by testing that:

Replace your old code:
```php
$conf = new Drivers\Memcached\Config;
$conf->setHost($ip);
$conf->setPort($port);
```

with that:
```php
$conf = new Drivers\Memcached\Config;
$conf->serServers([]);
$conf->setHost($ip);
$conf->setPort($port);
```
Tell me if it's working

**Comment by zkwbbr** [comment]
```php
$conf = new Drivers\Memcached\Config;
$conf->setServers([]);
$conf->setHost($ip);
$conf->setPort($port);
```
That works!

**Comment by Geolim4** [comment]
Mhhh okay, got it, I'll push a fix later, my tests are using `setServers()` so I was confused why it would not work for you. Sorry for being a little rude :)

**Comment by zkwbbr** [comment]
No worries, thank you.

**Comment by Geolim4** [comment]
I'm gonna push a new release by the end of week, thanks !

**Comment by Geolim4** [comment]
Have fun :)

https://github.com/PHPSocialNetwork/phpfastcache/releases/tag/7.0.5

**Comment by zkwbbr** [comment]
Sorry, I tried the new update, but I'm now facing a new issue.
When using `$conf->setServers($servers);` alone, it errors:

`Fatal error: Uncaught Phpfastcache\Exceptions\PhpfastcacheInvalidConfigurationException: Missing keys for memcached server: saslPassword in /srv/app/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Drivers/Memcached/Config.php:112`

It wasn't like this before the update, sorry about it :)

**Comment by Geolim4** [comment]
Yeah because these keys are still required, even if you set them to null ;)

**Comment by zkwbbr** [comment]
Sorry but I believe they're not required by memcached?

To clarify:

This works without setting `saslUser` and `saslPassword`:

```php
$conf->setHost($ip);
$conf->setPort($port);
```
This doesn't work (as of 7.0.5):

```php
$servers = [[
    'host' => $ip,
    'port' => $port,
    ]];
$conf->setServers($servers);
```

**Comment by Geolim4** [comment]
It's not about Memcached by itself, but about the config validation of PFC.
If you just use one server use `setHost()` and `setPort()` which does not require SASL specifications.
