### ISSUE TITLE
TLS connexion for (P)Redis

### ISSUE THREAD

**Issue by floSoX** [PHPSocialNetwork/phpfastcache#679]
**Configuration**
- **PhpFastCache version:** 7.0.5
- **PhpFastCache API version:** 2.0.4
- **PHP version:** `PHP 7.1.27-1+0~20190307202204.14+stretch~1.gbp7163d5 (cli) (built: Mar  7 2019 20:22:04) ( NTS )`
- **Operating system:** Debian Stretch

**Is your feature request related to a problem? Please describe.**
I would like to use phpfastcache with a Redis server configurated with a TLS connexion.

**Describe the solution you'd like**
Add a `scheme` optionnal option to Redis and Predis configurations.

**Describe alternatives you've considered**
Add a `tls` boolean option to Redis and Predis configurations to replace tcp scheme by tls.

**Additional context**
Part of Predis README for  Redis server connexion: https://github.com/nrk/predis/#connecting-to-redis

**Comment by floSoX** [comment]
As workaround, instead of:

```php
$cache = $this->phpfastcache->get('redis');
```
I use:
```php
$instanceName = 'predis';
if (array_key_exists($instanceName, $this->phpfastcache->getInstances())) {
	$cache = $this->phpfastcache->get($instanceName);
} else {
	$config = $this->phpfastcache->getConfig();

	$predisConfig = array_merge($config['drivers']['redis']['parameters'], ['scheme' => 'tls']);

	$predisClient = new \Predis\Client($predisConfig);

	$cache = CacheManager::getInstance('predis', new Config([
		'predisClient' => $predisClient
	]));

	$this->phpfastcache->createInstance($instanceName, $cache);
}
```

**Comment by Geolim4** [comment]
Hello,

I'll consider adding this to the 7.1.x eventually.
But you did the right thing by using an external predis instance with exotic configurations.

The 7.1 should be released around the first day of summer :)

Cheers,
Georges.
