### ISSUE TITLE
APC driverClear fails 

### ISSUE THREAD

**Issue by spud** [PHPSocialNetwork/phpfastcache#680]
**Configuration**
- **PhpFastCache version:** 7.0.2 (but the code appears the same in 7.0.5)
- **PhpFastCache API version:** 2.0.4
- **PHP version:** 7.2.14
- **Operating system:** (MAMP Pro 5.3 on MacOS 10.13)

The APC driver's "driverClear" method, which should clear the entire cache, has been failing me. I make changes, clear the cache, and earlier cached data persists. So I started digging for answers.

I found driverClear in /Drivers/APC/Driver.php, which executes:

` return @apc_clear_cache() && @apc_clear_cache('user');`

And should return "true." After a bunch of debugging statements and trials, I discovered that reducing the function to 

`apc_clear_cache('user')`

worked fine, and cleared my cache! It turns out that, **despite** [the official PHP documentation](https://www.php.net/manual/en/function.apc-clear-cache.php), apc_clear_cache() returns NULL. Consequently, the 'user' version never gets executed, and that's what actually clears the cache.

My current configuration is using the "APC" driver, though APCu appears to also be installed under MAMP (see attached screenshot). I'm not sure what effect that may have on this behavior, but as-is, there seems to be a bug in the APC-only version. I have had to hack the Driver.php file in order to allow my cache-clearing mechanism to work properly.

Strangely, apc_clear_cache('user') properly returns a boolean rather than NULL, so simply omitting the parameter-less version (or even inverting the order) would at least execute the clearing before choking on the NULL.

![Screen Shot 2019-03-25 at 5 16 51 PM](https://user-images.githubusercontent.com/526756/54954956-5bd9e600-4f22-11e9-8452-01d76aff83d7.png)

**Comment by Geolim4** [comment]
Hello,

You suggest that I would change the code for ` return @apc_clear_cache() || @apc_clear_cache('user');` ?

**Comment by spud** [comment]
I do not claim to have a full understanding of every permutation of use, but for my standard LAMP stack usage with APC(u), driverClear() always fails in its current form, so something has to change.

I believe

{
	@apc_clear_cache(); // returns null;
	return @apc_clear_cache(‘user’); // returns true;
}

would solve the problem, allowing both calls to execute, but returning only the “true” returned by apc_clear_cache(‘user’).

Cheers,
spud.

**Comment by Geolim4** [comment]
A commit has been added to address the issue. It should be available in the next release, in the meantime you can use dev-master :)

Thanks you.
