### ISSUE TITLE
PFC V7, mongodb does not work

### ISSUE THREAD

**Issue by harpreetsb** [PHPSocialNetwork/phpfastcache#681]
**Configuration (optional)**
- **PhpFastCache version:** 7.0.5
- **PhpFastCache API version:** 2.0.4
- **PHP version:** PHP 7.2.15-0ubuntu0.18.04.1 (cli) (built: Feb  8 2019 14:54:22) ( NTS )
- **Operating system:** Ubuntu 18.04

**My question**
> Trying to connect to the mongodb with below configuration:
`
$config["cacheInstance"] =  CacheManager::getInstance(
'Mongodb',
	new Config(
		array(
			"host" => "127.0.0.1",
			"port" => 27017,
			"username" => "$user",
			"password" => "$pwd",
			"collectionName" => "cache",
			"databaseName" => "MedCache",
			"timeout" => 1
		)
	)
);
`
this authentication work in `mongo` shell while running `mongod` with `--auth`
But I get the following error

> **An uncaught Exception was encountered
Type: Phpfastcache\Exceptions\PhpfastcacheDriverCheckException
Message: Mongodb is not installed or is misconfigured, cannot continue. Also, please verify the suggested dependencies in composer because as of the V6, 3rd party libraries are no longer required.
Filename: /var/www/html/medigence/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/CacheManager.php
Line Number: 174**

Any help is appreciated.

**Comment by harpreetsb** [comment]
**UPDATE:** php-mongodb is also installed

**Comment by harpreetsb** [comment]
**UPDATE**: using mongo without authentication gives same error

**Comment by Geolim4** [comment]
Hello,

Don't forget to install the 3rd party dependency (have a look at suggested packages):
https://github.com/PHPSocialNetwork/phpfastcache/blob/64638b27f473aa26603e84288d91a2b80a4aa388/composer.json#L42

Cheers,
Georges.

**Comment by harpreetsb** [comment]
@Geolim4 you solution worked will on my localhost
On there server I get same error.
Now the server is :
**OS: Ubuntu 16.04**
**PHP: PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )**

what is it that I am missing.

**Comment by harpreetsb** [comment]
Looks like an issue with plesk php installation.
