### ISSUE TITLE
help install with couchbase php

### ISSUE THREAD

**Issue by screamolic** [PHPSocialNetwork/phpfastcache#683]
**Configuration (optional)**
- **PhpFastCache version:** "7.0.5"
- **PhpFastCache API version:** "2.0.4"
- **PHP version:** "7.2.13"
- **Operating system:** "ubuntu 18.04 LTS "

**My question**
> anyone can help me setup using couchbase on php?

my config:
use Phpfastcache\CacheManager;
use Phpfastcache\Drivers\Couchbase\Config;

    $InstanceCache = CacheManager::getInstance('couchbase', new Config([
      'host' => 'localhost',
      'port' => 8091,
      'username' => 'scream',
      'password' => '^*1A^U8fac!t^',
      'bucketName' => 'default' // The bucket name, generally "default" by default
    ]));

i have install the SDK from this link: https://docs.couchbase.com/php-sdk/2.6/start-using-sdk.html
but i got error like this:

A driver could not be initialized due to missing requirement: Couchbase is not installed or is misconfigured, cannot continue. 
    Also, please verify the suggested dependencies in composer because as of the V6, 3rd party libraries are no longer required.

**Comment by Geolim4** [comment]
Hello,

Please check if the php extension is well installed:
https://github.com/PHPSocialNetwork/phpfastcache/blob/c35c02a2792763b4d9c2a74698648203c0fadd49/lib/Phpfastcache/Drivers/Couchbase/Driver.php#L57

You can check it using phpinfo() or "php -m" in command line.

Cheers,
Georges
