### ISSUE TITLE
Append function without reading the cache?

### ISSUE THREAD

**Issue by NicoxDJ** [PHPSocialNetwork/phpfastcache#684]
Hello! Is there anyway that i can append cached array every minute without loading it into variable or object? I just need to put a lot of data there, and i don't want to use a lot of ram every time to read the cache. I'm using PhpFsatCache in Laravel 5.7. I was trying to workaround but its unsuccessful :/

**Comment by Geolim4** [comment]
Hello,

You have to use the "appends" functions described here:
https://github.com/PHPSocialNetwork/phpfastcache/wiki#item-api-extendedcacheiteminterface

Of course you have to respect the PSR6 using "getItem()", "item->set()" and "saveItem()".

This is required as PSR6.

Cheers,
Georges.

**Comment by NicoxDJ** [comment]
Well.. i don't want to do getItem, because it will be big array.
And i have to do it 20 times on 10 minutes.
Anyway, Thank you for the replay. :)

**Comment by Geolim4** [comment]
Then it's more like a design issue, you better use tags in that case :)

Cheers,
Georges
