### ISSUE TITLE
(P)redis persistent / pooled connections

### ISSUE THREAD

**Issue by marcos-guerrero** [PHPSocialNetwork/phpfastcache#689]
Hello!

It would be great if phpfastcache allows us to use connection pooling feature available on (P)redis 

- In predis https://github.com/nrk/predis/wiki/Connection-Parameters :

persistent [boolean - default: false] :Specifies if the underlying connection resource should be left open when a script ends its lifecycle.

- In redis https://github.com/phpredis/phpredis#pconnect-popen

Description: Connects to a Redis instance or reuse a connection already established with pconnect/popen.

 Thank you for taking it into consideration
Kind regards

**Comment by Geolim4** [comment]
Hello,

I'll implement it in the 7.1 release (around end of summer), meanwhile you can pass a custom Predis/Redis instance to Phpfastcache as specified in the Wiki:

https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-Configuration-Options#redispredis-specific-options

Cheers,
Georges

**Comment by marcos-guerrero** [comment]
Ok, it's great to know it will be implemented!
I prefer to wait your release rather than switch to predis and use custom client:
We are using redis, and in this case phpfastcache has to call pconnect() or the redis client (no matter if is custom or internal) won't use persistent connections. Or am I missing something? 

Thanks for your help and quick response,
Marcos

**Comment by Geolim4** [comment]
Redis driver also support custom client ;)

**Comment by marcos-guerrero** [comment]
But redis client won't use persistent connection if phpfastcache doesn't call pconnect() instead the "normal" connect(), so that's why wait for your new release.

**Comment by Geolim4** [comment]
Not sure you got the principle of "custom client" 😅 
A custom client is an already-instantiated object that you provide to phpfastcache, so PFC does not need to call pconnect :)

**Comment by marcos-guerrero** [comment]
With predis client I understand that the custom client will work with persistent connections, as it's a matter of configuration, I'll create the custom client passing it the persistent parameter with 1 value and voila! the client will reuse / persist the connection. I've got it!
but... with the redis client it's not a matter of configuration, it a matter of calling pconnect() method instead connect() method... so, how is it possible to make PFC aware of it? PFC is going to call connect() ... or should I pass to PFC the custom client already "pconnected"? 
Thank you for help me to fully understand the custom client concept!

**Comment by Geolim4** [comment]
You pass the object fully instanciated + connected ofc ! Read the wiki
please :(

**Comment by marcos-guerrero** [comment]
Sorry! You're right, my fault for not re-read the manual. 
Thank you very much for your time and help!

**Comment by Geolim4** [comment]
Planned for 7.1.x
