### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by ARTPROITCo** [PHPSocialNetwork/phpfastcache#69]
Hello,
Introduction of tags will be?

**Comment by khoaofgod** [comment]
@ARTPROITCo 
What do you mean about "tags" ? Can you give me some details & examples. I will work on that right away.

**Comment by ARTPROITCo** [comment]
How it works can be found in [Zend](http://framework.zend.com/manual/current/en/modules/zend.cache.storage.adapter.html)

Example of logic:
```php
$user_id = 123;

// user page - transactions
$transactions_html = "....";
$cache->set(
    'pages-transactions-user_'.$user_id.'',
    $transactions_html,
    600,
    array( // array of tags
         'pages',
         'transactions',
         'user_'.$user_id,
    )
);

// user page - profile
$profile_html  = "....";
$cache->set(
    'pages-profiles-user_'.$user_id.'',
    $profile_html,
    600,
    array( // array of tags
         'pages',
         'profile',
         'user_'.$user_id,
    )
);

// deleting cache of transaction page for user
// where cache have tag1 && tag2 (or may tag2 || tag2 ...)
$cache->deleteByTags(array('pages', 'transactions', 'user-'.$user_id));

// deleting cache of all pages for user
$cache->deleteByTags(array('pages', 'user-'.$user_id));

// deleting cache of all transaction pages for all users
$cache->deleteByTags(array('pages', 'transactions'));

// deleting cache of all pages for all users
$cache->deleteByTags(array('pages'));
```

**Comment by khoaofgod** [comment]
oh. OK.
U meant tags / group / sets of "keywords" .. 
Got it, I will add it to next release 2.5 on March 02

**Comment by khoaofgod** [comment]
Working on this.

**Comment by khoaofgod** [comment]
This move to April 12 since I have an urgent project have to finish.

**Comment by maxicms** [comment]
This functionality will be added?

**Comment by pefstra** [comment]
Great work! Any news about tags?

**Comment by khoaofgod** [comment]
Next week, I'm working hard on this >_< a little bit busy with other projects. Will push this one next week.

**Comment by pefstra** [comment]
I know you're busy and sorry for my insistence. Are you gonna launch soon this new version with tags or it would be better to look for something else similar? I am in the middle of a project and I am waiting for this...

**Comment by maxicms** [comment]
Most likely this will not be functional

**Comment by khoaofgod** [comment]
I work on this one, we will have tags soon.

**Comment by nikmauro** [comment]
Any progress or any help about this?

**Comment by nikmauro** [comment]
here some libraries with tags implementations  [https://github.com/cpojer/php-cache] [http://www.gabrielemittica.com/cont/guide/brennocache-a-smart-cache-engine-for-your-php-applications/19/1.html]

**Comment by khoaofgod** [comment]
it will be add next week, on this version 4

**Comment by nikmauro** [comment]
@khoaofgod This is awesome news!

**Comment by khoaofgod** [comment]
@nikmauro Tags is added
https://github.com/PHPSocialNetwork/phpfastcache/releases/tag/4.1.0

Look at Examples/Tags.YourCaching.php

**Comment by maxicms** [comment]
stunned, it happened. Wow. You are best

**Comment by khoaofgod** [comment]
Example of tagging function here:
https://github.com/PHPSocialNetwork/phpfastcache/blob/final/examples/Tags.YourCaching.php
