### ISSUE TITLE
MongoDB driver DNS seedlist format

### ISSUE THREAD

**Issue by surekap** [PHPSocialNetwork/phpfastcache#692]
The mongodb driver has a hard-coded URL scheme in [Mongodb/Driver.php](https://github.com/PHPSocialNetwork/phpfastcache/blob/master/lib/Phpfastcache/Drivers/Mongodb/Driver.php#L245) on line 245: "mongodb://"

However, according [to: the MongoDB Docs](https://docs.mongodb.com/manual/reference/connection-string/) a new URL scheme "mongodb+srv" is usable with Atlas replica-sets

Can you allow this setting to be configurable. Also there are other recommended connection parameters which are unsupported
retryWrites=true&w=majority

**Comment by Geolim4** [comment]
Hello,

Thanks for the report, I'll add the support for the next minor release: 7.1.x which should be released by the end of summer.

Thanks you !

**Comment by Geolim4** [comment]
I'm currently implementing this !

> Also there are other recommended connection parameters which are unsupported
retryWrites=true&w=majority

Use the Mongodb config settings `setOptions()` & `getOptions()` which are already usable:
https://github.com/PHPSocialNetwork/phpfastcache/blob/2cb775c15ef10c7a821dbc00f0ec65559b75c8eb/lib/Phpfastcache/Drivers/Mongodb/Config.php#L220
