### ISSUE TITLE
Couchdb failed to connect with the following error message: "Warning: Invalid argument supplied for foreach()" line 82 in D:\XAMPP\htdocs\OctaPHP\application\library\vendor\phpfastcache\couchdb\lib\Doctrine\CouchDB\CouchDBClient.php'

### ISSUE THREAD

**Issue by synestergates788** [PHPSocialNetwork/phpfastcache#698]
**Configuration (optional)**
- **PhpFastCache version: 7.0.5**
- **PhpFastCache API version:**
- **PHP version:7.1.7**
- **Operating system: Windows 10

**My question**
> I got this error message when using couchdb
'Couchdb failed to connect with the following error message: "Warning: Invalid argument supplied for foreach()" line 82 in D:\XAMPP\htdocs\OctaPHP\application\library\vendor\phpfastcache\couchdb\lib\Doctrine\CouchDB\CouchDBClient.php'

use Phpfastcache\CacheManager;
use Phpfastcache\Drivers\Couchdb\Config as CouchdbConfig;

$InstanceCache = CacheManager::getInstance('couchdb', new CouchdbConfig([
            'host' => '127.0.0.1',
            'port' => 5984,
            'path' => ROOT.DS.'application'.DS.'library',
            'username' => 'root',
            'password' => 'root',
            'ssl' => true,
            'timeout' => 10,
        ]));

        $key = "product_page";
        $CachedString = $InstanceCache->getItem($key);
        if (is_null($CachedString->get())) {
            //$CachedString = "APC Cache --> Cache Enabled --> Well done !";
            // Write products to Cache in 10 minutes with same keyword
            $CachedString->set("Couchdb Cache --> Cache Enabled --> Well done !")->expiresAfter(5);
            $InstanceCache->save($CachedString);
            echo "FIRST LOAD // WROTE OBJECT TO CACHE // RELOAD THE PAGE AND SEE // ";
            echo $CachedString->get();
        } else {
            echo "READ FROM CACHE // ";
            echo $CachedString->get();
        }

**Comment by synestergates788** [comment]
i'm new to phpfastcache, can anyone help me with this error, is it something to do with 'new CouchdbConfig([some data config here])' config?

**Comment by Geolim4** [comment]
Host is misconfigured.
Try specifying a full http link instead.

Cheers,
Georges

**Comment by synestergates788** [comment]
http://127.0.0.1:5984/_utils/#database/baseball/_all_docs

'host' => 'http://127.0.0.1:5984/_utils/#database/baseball'

did you mean like that? sorry man i have no idea how to do this :(

**Comment by khoaofgod** [comment]
Just use FileDB

**Comment by synestergates788** [comment]
> FileDB

do you mean to use FileDB instead couchdb?
