### ISSUE TITLE
Psr16Adapter should convert Traversable into array in deleteMultiple

### ISSUE THREAD

**Issue by oskarakerlund** [PHPSocialNetwork/phpfastcache#700]
**Configuration**
- **PhpFastCache version:** 7.0.5
- **PHP version:** 7.1

**Describe the bug**

The PSR-6 `CacheItemPoolInterface` requires an array as input to `deleteItems` however PSR-16 accepts an array or a `Traversable` as input to `deleteMultiple`. But in `Psr16Adapter`, the input is passed from `deleteMultiple` directly to `deleteItems` without checking if it is an `array`. 

Using `Psr16Adapter` and calling `deleteMultiple` with the output from a generator function should work since it follows PSR-16. But currently it triggers an error:

```
Uncaught TypeError: Argument 1 passed to Phpfastcache\Drivers\Files\Driver::deleteItems() must be of the type array, object given, called in /var/www/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Helper/Psr16Adapter.php on line 178 and defined in /var/www/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Core/Pool/CacheItemPoolTrait.php:297
Stack trace:
#0 /var/www/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Helper/Psr16Adapter.php(178): Phpfastcache\Drivers\Files\Driver->deleteItems(Object(Generator))
#1 /var/www/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Collection/Cells.php(492): Phpfastcache\Helper\Psr16Adapter->deleteMultiple(Object(Generator))
```

**To Reproduce**
Use the `Psr16Adapter` and call `deleteMultiple` using a generator function. [PhpSpreadsheets does this](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/Collection/Cells.php#L492).

**Expected behavior**
`deleteMultiple` should convert any `Traversable` to an `array` before calling `deleteItems`.

**Comment by Geolim4** [comment]
Hello !

Thanks for that issue, I'll take a look this weekend.

Cheers,
Georges

**Comment by oskar-wikinggruppen** [comment]
@Geolim4 will you make sure this issue stays open?

**Comment by Geolim4** [comment]
Yeah, I'm a little sick these day, I will treat all the pending issues on a row :)
