### ISSUE TITLE
Uncaught Phpfastcache\Exceptions\PhpfastcacheDriverConnectException when failed to connect to Redis Server using Predis

### ISSUE THREAD

**Issue by juliardi** [PHPSocialNetwork/phpfastcache#701]
**Configuration**
- **PhpFastCache version:** "7.0.5"
- **PhpFastCache API version:** "2.0.4"
- **PHP version:** "7.2.12"
- **Operating system:** "Windows 10"

**Describe the bug**

> I am trying to use Predis driver with a fallback to Files driver. But, when Predis failed to connect to Redis server, it doesn't fallback to Files driver, and instead throws an uncaught `Phpfastcache\Exceptions\PhpfastcacheDriverConnectException` exception.

**To Reproduce**
1. Configure `CacheManager`
```php
$driver = \Phpfastcache\CacheManager::getInstance('predis', new \Phpfastcache\Drivers\Predis\Config([
            'host' => '127.0.0.1',
            'port' => 6379,
            // 'password' => '', //Default value
            // 'database' => '', //Default value
            'fallback' => 'Files',
            'fallbackConfig' => new Phpfastcache\Config\ConfigurationOption([
                'path' => dirname(__DIR__) . '/temp',
            ])
        ]));

        $instance = new \Phpfastcache\Helper\Psr16Adapter($driver);
```
2. Try to set something
```php
$instance->set('something', 'this is something');
```

**Expected behavior**
Phpfastcache should fallback to Files driver when Predis unable to connect to Redis server.

**Comment by Geolim4** [comment]
The fallback does not handle connexion issue, only driver requirement issues (missing vendor, php extension, etc)...

I have no plan for now to handle this behaviour since it's an "user-related" matter.

Cheers,
Georges
