### ISSUE TITLE
Please fix/add connection check to backend

### ISSUE THREAD

**Issue by Yamakasi** [PHPSocialNetwork/phpfastcache#705]
Referring to the earlier "issue" #666 I create this new ticket.

I strongly think this really needs a fix as you need to know where you connect to and cannot judge or rely on what happens on the backend if your app needs to know what is going on and expects an Exception.

There is nothing like, out of scope, "not going to fix others issues" as there aren't any. When you "talk" to someone/something proper you get a decent reply back, also with the connection unless you don't try to. (Couchbase for an example has a simple callback for it).

Now this library is, we know how to build an engine out of parts we order but don't know where to find a problem and report it when there is.

Let's hope Satan was not involved in #666 ;)

**Comment by Geolim4** [comment]
Hello,

Like I said, it's not the Job of the library to handle network/IO errors.
It has already a first "error handling" if the backend driver is broken (missing php extension, missing vendor) and I realize that I should've removed this fallback feature which is a total non-sense in the POV of a developer.

The library, should provide, as is, an abstract cache system, letting the developer handle the 3rd party errors by itself.

I'm sorry but I won't fix this behavior currently, I'm even tempted to remove the fallback feature in the future which make the library more difficult to maintain and out-of-scope of a library job.

Cheers,
Georges

**Comment by Yamakasi** [comment]
Hi George,

In my opinion, sorry to say, you are completely wrong.

PHP, Backend drivers, all give a solid response the library should handle and you are still thinking "something else" needs to do this which is wrong. If we need to check this ourselves in our code why would we use this library at all ? It's IN scope, not out of it, and because you are rapidly closing issues all the time no-one is able to respond in a decent way. 

Doesn't work, at all, sorry but it's the truth :(

Please reopen and let us discuss it widely.

Thanks and Cheers as well!
