### ISSUE TITLE
Cache Items not deleted in long running worker threads

### ISSUE THREAD

**Issue by jzaeske** [PHPSocialNetwork/phpfastcache#706]
**Configuration**
- **PhpFastCache version:** 7.0.5
- **PhpFastCache API version:** 7.0.5
- **PHP version:** 7.3.8
- **Operating system:** Linux Kernel with php running in docker-container

When using phpfastcache in a long running worker, it will not perform deleteItem Operations on the Cache Backend in some cases. Error happens for me when using memcached, but i guess it also affects all other shared cached backends

**To Reproduce**
To reproduce, you need two independend php scripts and a debugger to set a breakpoint to be set like described in code comments

Script A
```php
$driver = 'memcached';
$configArray = [ /* memcached config */ ];
$config = new \Phpfastcache\Drivers\Memcached\Config($configArray);
$cache = \Phpfastcache\CacheManager::getInstance($driver, $config);

// we have an item at first
$item = $this->cache->getItem('test');
$item->set("foo");
$this->cache->save($item);

// there is an item. We delete it.
 // result is true in this case, deletion was successful
$result = $this->cache->deleteItem('test');

// No change on cache here

// cache deletion results in false, because key did not exist
// REF (1)
$result = $this->cache->deleteItem('test');

// set a breakpoint on this line. while process is stopped, execute script B
$breakpoint = 1;

// result is false and the entry created by script B is still in cache
$result = $this->cache->deleteItem('test');
```

Script B:
```php
$driver = 'memcached';
 [ /* memcached config */ ];
$config = new \Phpfastcache\Drivers\Memcached\Config($configArray);
$cache = \Phpfastcache\CacheManager::getInstance($driver, $config);

$item = $cache->getItem('test');
$item->set("bar");
$cache->save($item);
```

**Expected behavior**
last line of script A results in true and cache item is deleted

**Additional context**
In our Application, script B represents a rest api, which reads and writes cache entries.
We also have an asynchronous worker, which is represented by script a. The worker listens to events, which invalidate the cache and then removes the cache entry. The described error occurs, when there are events to invalidate a cache entry, which does not exist in this moment.

The cause of the problem might be the following. In `lib/Phpfastcache/Core/Pool/CacheItemPoolTrait.php#261` `CacheItemPoolTrait::deleteItem($key)` performes `$this->getItem($key)` first. When the item does not exist in the cache, there is no hit and the if-statement in line 262 is skipped. But as a side-effect `$this->getItem()` stores the missed cache item in `$this->itemInstances`.
When the next delete is performed, `$this->getItem()` will return the cache miss stored in `$this->itemInstances` and not fetch the value from memcached, which was written by Script B. Since this is a cache miss `driverDelete` will not be executed and the item stays in the cache.

A possible solution may be to remove the item from  `$this->itemInstances` if there was a cache miss in for the item to be deleted. 
The workaround i use in my worker now is to call `$cache->detachItem($item)` before every delete Operation in the worker to force phpfastcache to fetch the current state

**Comment by Geolim4** [comment]
Hello

This is a concurrent job issue, more exactly a design-issue not specified by PSR6 specs.
I recommend you to use pool methods "detach*()" to force fetch from back-end.

Cheers,
Georges
