### ISSUE TITLE
Autodelete expired items

### ISSUE THREAD

**Issue by legale** [PHPSocialNetwork/phpfastcache#709]
It would be good to have an ability to autodelete expired items.

**Comment by Geolim4** [comment]
Hello,

You just can't... Since you don't know who's are the expired items except by grabing 'em all (which is unimaginable).
And some cache backend already does that (Redis, Mongo, Couch, Memcache etc)...

Cheers,
Georges

**Comment by Yamakasi** [comment]
You can simply auto delete expired items, your backend just needs to support it. @Geolim4 you build it in yourself, check the Couchbase plugin, that one supports it as Couchbase supports it.

**Comment by Geolim4** [comment]
No, it repeat: I won't implement a feature not supported by 100% of the supported backends....

**Comment by Yamakasi** [comment]
> No, it repeat: I won't implement a feature not supported by 100% of the supported backends....

Why is it already in then ?

**Comment by Geolim4** [comment]
It's not...
Re-read the docs, especially the API 😁

**Comment by Yamakasi** [comment]
> It's not... Re-read the docs, especially the API 😁
> […]

If you set expired with ->expiresAfter(INT) for an item the backend does the rest if it knows how to handle expired documents/items.

No re-read for the docs, just know how your backend works and implement the right one.

**Comment by Geolim4** [comment]
What don't you understand in "some blackend" does not implement "queryable
expired items".

If I decided not to implement it it's because that kind of feature is not
implementable in some backends (file, memcache, etc...)

So, end of discussion, this is not a receivable request at the moment since
not standardized.
