### ISSUE TITLE
Problem with ssdb to retrieve my key/value in cli or with phpssdbadmin

### ISSUE THREAD

**Issue by kwizfreak** [PHPSocialNetwork/phpfastcache#710]
**Configuration (optional)**
- **PhpFastCache version:** "7.1.0"
- **PhpFastCache API version:** "2.0.4"
- **PHP version:** PHP 7.3.9-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep  2 2019 12:54:04) ( NTS )
- **Operating system:** "ubuntu16.04.1"

**My question**
> Hello,
I set key / value in cache with phpfastcache and ssdb driver, with php i can see the key is been in cache i can get the value but when i search with phpssdbadmin or command line i can't find the key / value 
I don't understand why ?
Thanks

**Comment by Geolim4** [comment]
Hello,

It's because the key is hashed to avoid any possible injection or unsupported chars.

Cheers,
Georges
