### ISSUE TITLE
Verify which instanceId is already in object and reuse

### ISSUE THREAD

**Issue by di-rect** [PHPSocialNetwork/phpfastcache#711]
I would like to know if it is possible to verify if a instanceId already exists in the object.

`getInstanceId()` is usable for receiving the Id of an object but that doesn't work for if the instanceId is already in there. I am running into the `https://github.com/PHPSocialNetwork/phpfastcache/wiki/[V5]-Why-calling-getInstance%28%29-each-time-is-a-bad-practice-%3F` error which seem to occur even when I use different instanceIds but need to reuse an already existing one.

When I look at this part of the code: [https://github.com/PHPSocialNetwork/phpfastcache/blob/master/lib/Phpfastcache/CacheManager.php#L113-L149
](url)

I'm not 100% sure why the warning is there when there is actually nothing done because of the !isset() on line [https://github.com/PHPSocialNetwork/phpfastcache/blob/master/lib/Phpfastcache/CacheManager.php#L124
](url). 

I'm not able to find a way to check the object in front, not even with getInstanceId(). I assume you need to so you never need to call the CacheManager::getInstance() when it's already in.

I hope someone can point me to something workable.

**Comment by Geolim4** [comment]
Hello,

You need to store the object instance somewhere instead of calling `CacheManager::getInstance` multiple times.

So either you define an instanceId by yourself to this object (third arg):
https://github.com/PHPSocialNetwork/phpfastcache/blob/11c7b17a824925c2b99dce10df15ba67cbef132a/lib/Phpfastcache/CacheManager.php#L113

Either you get it automatically from the object instance itself.

Cheers,
Georges

**Comment by di-rect** [comment]
Hi,

That is what I understood from multiple issues here. What I do see is the object being extended in the CacheManager.php based on ID's but it's not returned in full when calling the getInstance() or I must be doing something wrong.

Can you share me an example about how you would store the object outside your library but with all instanceId's in it ? 

Then also, how to check of that instanceId is available in that object before you call the getInstance() again, as that is what I'm not seeing at all.

Thank you very much.

Regards,

Sam

**Comment by Geolim4** [comment]
> Can you share me an example about how you would store the object outside your library but with all instanceId's in it ?

It's written in WIKI:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV5%5D-Why-calling-getInstance()-each-time-is-a-bad-practice-%3F#white_check_mark-the-right-way
Store `$driverInstance` (or whatever name you want) somewhere and re-use it instead of call manager each time.

**Comment by di-rect** [comment]
Thanks for the wiki, I was aware of that, but how can I do so when I store multiple instances, or need to store multiple as I tried to explain ?

I don't know how to get the right instance from the object as it can store multiple in the object using the instanceId arg.

**Comment by Geolim4** [comment]
> Thanks for the wiki, I was aware of that, but how can I do so when I store multiple instances, or need to store multiple as I tried to explain ?

I don't understand where's the issue ??
You do store cache instance as you want !..

**Comment by di-rect** [comment]
I think there is a language barrier, we can work that out.

If I store many instances (which I do), how do I get one out so I don't need to re-create it again ?

**Comment by Geolim4** [comment]
I absolutely don't get what the issue ???
Why don't you store the object instance into a variable ?
Or to an array of instances ?

Example:
```php

$cacheInstances = [
   'redisCache' => CacheManager::getInstance('Redis'),
   'filesCache' => CacheManager::getInstance('Files'),
];
```

What's the matter ? YOU decide what you do with object instances provided by the cache manager ????
