### ISSUE TITLE
Show all itemId's with data from cache

### ISSUE THREAD

**Issue by di-rect** [PHPSocialNetwork/phpfastcache#712]
Is there a way to simply show all items with their stored data from cache ? This including the tag structure ?

Thanks!

**Comment by Geolim4** [comment]
Hello,

No, since not all backend drivers are supporting that kind of feature.
And this would be very dangerous also because this could potentially explode your php memory/CPU.

Cheers,
Georges

**Comment by di-rect** [comment]
Hi,

OK fair enough. Sometimes it's difficult to check what has been cached all. Most things are easy to debug but when you get tag related complexity it's almost not doable to compare items with what you though you were putting in.

Regards,
