### ISSUE TITLE
cache.storage different ip address and domains

### ISSUE THREAD

**Issue by abdullahtekin** [PHPSocialNetwork/phpfastcache#714]
**Configuration**
- **PhpFastCache version:** "6.1.1"
- **PhpFastCache API version:** "1.2.5"
- **PHP version:** "5.6.4"
- **Operating system:**"Centos 7"

**Screenshots**
https://i.ibb.co/wpdvtcs/Ekran-Resmi-2019-12-02-21-23-22.png

**Additional context**
Creating directory different url from my site into cache directory. What is the reason.

**Comment by Geolim4** [comment]
Hello,

Please reformat the message using default template that specify OS, Version, etc...
I'm not a soothsayer.

Cheers,
Georges

**Comment by abdullahtekin** [comment]
I sent informations

**Comment by Geolim4** [comment]
Hello,

You did not set the "securityKey" config.
Therefore the HTTP_HOST is used instead.

Cheers,
Georges.

**Comment by Geolim4** [comment]
The doc is here:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-Configuration-Options#file-based-drivers-options-

**Comment by abdullahtekin** [comment]
Thnx @Geolim4 
I will try this solution
