### ISSUE TITLE
xcache driver

### ISSUE THREAD

**Issue by reno1979** [PHPSocialNetwork/phpfastcache#72]
version 2.4.1  

Because the fastcache mechanism always selects sqlite (when available) I use the following: 
(even with version 2.4.1 sqlite sometimes complains about none existing tables) 

```
if(extension_loaded('xcache')){
    $_cache = phpFastCache("xcache");
} else {
    $_cache = phpFastCache("files"); 
}
```

If I run $_cache->systemInfo(); The result is: 

```
array (size=11)
  'path' => string '/tmp/cache.storage.inbouw/' (length=26)
  'htaccess' => boolean true
  'securityKey' => string 'cache.storage.inbouw' (length=20)
  'system' => 
    array (size=2)
      'driver' => string 'sqlite' (length=6)
      'drivers' => 
        array (size=10)
          'apc' => boolean false
          'cookie' => boolean true
          'example' => boolean false
          'files' => boolean true
          'memcache' => boolean false
          'memcached' => boolean true
          'redis' => boolean false
          'sqlite' => boolean true
          'wincache' => boolean false
          'xcache' => boolean true
  'storage' => string 'xcache' (length=6)
  'cachePath' => string '' (length=0)
  'fallback' => string 'files' (length=5)
  'memcache' => 
    array (size=1)
      0 => 
        array (size=3)
          0 => string '127.0.0.1' (length=9)
          1 => int 11211
          2 => int 1
  'redis' => 
    array (size=2)
      0 => string '127.0.0.1' (length=9)
      1 => int 6379
  'extensions' => 
    array (size=0)
      empty
  'skipError' => boolean true
```

So it looks like the xcache driver is used.

But then I would like to request the stats(), and the entire function hangs, though the driver file uses try catch.. 
Swicthing to memcached works fine. The stats 'data' key gets filled with the stats from memcache.

In php.ini I also tried to set : 

```
xcache.admin.enable_auth = Off
```

Still no luck.... please help

**Comment by khoaofgod** [comment]
Ok, I take a look tonight when I get home.

**Comment by khoaofgod** [comment]
I don't have enough documents on xcache_list so, I hang on this one, until someone fix it.

**Comment by reno1979** [comment]
Ok I understand, the xcache documents are very poor indeed.

Thank you anyway.

**Comment by khoaofgod** [comment]
I will open this issues again, for some one use xcache see this problem on issues again and if they can provide me some documents on xcache_list or get stats of xcache, then I will work on it.
