### ISSUE TITLE
Warning "Directory not empty" in Files driver

### ISSUE THREAD

**Issue by MaximilianKresse** [PHPSocialNetwork/phpfastcache#720]
**Configuration**
- **PhpFastCache version:** "7.1.0"
- **PhpFastCache API version:** "2.0.4"
- **PHP version:** "7.3.8"
- **Operating system:** "Gentoo"

**Describe the bug**

We found the following php warning in our error logs:
'rmdir(.../cache/_fastcache/Files/f1/92): Directory not empty' in: '.../vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Drivers/Files/Driver.php'(133) Code: 2

So the error occurs in the following line: https://github.com/PHPSocialNetwork/phpfastcache/blob/master/lib/Phpfastcache/Drivers/Files/Driver.php#L133

~~Is there any reason that you don't use "Util\Directory::rrmdir()" at this line?~~

**Comment by Geolim4** [comment]
Hello,

I don't reproduce this error, can you give me a reproducible script ?

Cheers,
Georges

**Comment by MaximilianKresse** [comment]
I'm sorry but i cannot even reproduce this error by myself. 
It seems to be a rare timing error.
```
if (!(new \FilesystemIterator($dir))->valid()) {
    \rmdir($dir);
}
```

So it looks like "(new \FilesystemIterator($dir))->valid()" isn't perfect to check whether a directory is empty. Alternativly you could just try to delete the directory with a silent operator "@" (and may drop the empty directory check). If it works everything is fine and if not we haven't lost anything :-)

**Comment by Geolim4** [comment]
The use of "@" operator have to be banned since it's relatively a "I don't care" operator so I decided not to use it as of the v6.
There's a test that simulate an intensive I/O activity with "Files" backend:
https://github.com/PHPSocialNetwork/phpfastcache/blob/master/tests/ReadWriteOperations.test.php

And the results here:
https://github.com/PHPSocialNetwork/phpfastcache/commit/f66d2d803141d0411aff5f7a63f8d40735a4d1c5/checks?check_suite_id=396555121#step:10:990

As you can see, there's absolutely no notices at all, so it looks like an issue on your OS or maybe a php core bug.

**Comment by MaximilianKresse** [comment]
I executed the TestCase on our server which logged the error but everythings works fine.
No warnings or anything. 
Additionally a small note: the project which logged the error doesn't use any dynamic cache key. 
Unfortunately i don't have a full error trace. We use the psr16 wrapper and never call delete manually for this key. So this have to be related to an internal call to the driverDelete()-method.

**Comment by MaximilianKresse** [comment]
I searched for usages of driverDelete() and found the following usage:
https://github.com/PHPSocialNetwork/phpfastcache/blob/master/lib/Phpfastcache/Core/Pool/CacheItemPoolTrait.php#L153

So it seems that you delete expired cache items.

The problem could also related to concurrency. Just think about it. There is a expired item. Two requests come at the exact same time. The first one gets delete the item while the other one already creates the new item. It is possible (but extremly rare) to get into the following if with a none empty directory:
```
if (!(new \FilesystemIterator($dir))->valid()) {
    \rmdir($dir);
}
```

I totally agree to you that the "@" operator shouldn't be used if possible but when operation on a filesystem there is often no another way around it (until we get exceptions instead of warnings).

**Comment by Geolim4** [comment]
I'm surprised this backend is the most used one, the lib has been downloaded almost over a million time and you're the first user to have this bug apparently.

Combined to the impossibility to reproduce the bug I'm highly sceptical about adding a dirty fix :/

**Comment by Geolim4** [comment]
Hello @MaximilianKresse,

I’m closing this issue _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the issue / add comment / clarify …).

Regards,
Georges.L
