### ISSUE TITLE
Couchbase 3.0.0 SDK support

### ISSUE THREAD

**Issue by di-rect** [PHPSocialNetwork/phpfastcache#721]
Hi,

When can Couchbase 3.0.0 SDK be supported in the current version or maybe V8 ?

Regards,

**Comment by Geolim4** [comment]
Hello,

I have no server with Couchbase on my hand atm.
If you could provide me a "test" server I would be able to implement the changes quickly !

Cheers,
Georges

**Comment by di-rect** [comment]
Hi,

Thanks for the quick update. I only have my local development VM and nothing public available, sorry.

Installation is pretty simple tho, never seen a better installer for backend stuff like this to be honest :)

Maybe someone else can provide something which would like to have this as well.

Regards,


> Hello,
> 
> I have no server with Couchbase on my hand atm.
> If you could provide me a "test" server I would be able to implement the changes quickly !
> 
> Cheers,
> Georges

**Comment by Geolim4** [comment]
Could you maybe try to go ahead and try to make me a PR ?
I'm not sure to be able to work on it in the enxt 2 month :/

**Comment by di-rect** [comment]
> Could you maybe try to go ahead and try to make me a PR ?
> I'm not sure to be able to work on it in the enxt 2 month :/

Sure, I didn't look into the underlying part yet but it's driver loader, I think I can manage it.

**Comment by Geolim4** [comment]
Thanks, if you do this, please do it on V8 and run the CRUD test, see an example here:
https://github.com/PHPSocialNetwork/phpfastcache/blob/92a104808907b71ae6c9a7f4013fc68ffd79252a/tests/Apcu.test.php#L27

Thanks you !

**Comment by di-rect** [comment]
> Thanks, if you do this, please do it on V8 and run the CRUD test, see an example here:
> https://github.com/PHPSocialNetwork/phpfastcache/blob/92a104808907b71ae6c9a7f4013fc68ffd79252a/tests/Apcu.test.php#L27
> 
> Thanks you !

OK, will, do, V8 is pretty "stable" ?

**Comment by Geolim4** [comment]
It should does, but I still have some tests and Docs to make to be sure of the stability.

**Comment by di-rect** [comment]
> It should does, but I still have some tests and Docs to make to be sure of the stability.

So let's see then :) I don't bite ;)

**Comment by di-rect** [comment]
Small update:

I need to dive into it fully, it seems they changed the whole connection object, see:

https://docs.couchbase.com/php-sdk/3.0/hello-world/start-using-sdk.html

**Comment by di-rect** [comment]
Hi,

Another small update: I need to see if I have time to check it fully out at the moment. I need to do a lot of code crawling on my side already so it will take some time and I'm not 100% familiar with your implementation. Basic changes didn't fix it yet.

To be continued, sorry.

Regards

**Comment by Geolim4** [comment]
The 3.0.0 SDk is in beta state ? If yes don't waste your time, I won't merge (yet) unstable third party code support, so take your time ;)

Thanks again !

**Comment by di-rect** [comment]
> The 3.0.0 SDk is in beta state ? If yes don't waste your time, I won't merge (yet) unstable third party code support, so take your time ;)
> 
> Thanks again !

It was stable at the moment I was writing this issue, some minutes later it went back beta again, nothing to find anymore on the website about stable.

The way of connecting won't change, I'm pretty sure but it could give you some bugs maybe you won't be able to debug.

Is V8 production stable enough ? I like to use the new removal way.

Cheers

**Comment by Geolim4** [comment]
> The way of connecting won't change, I'm pretty sure but it could give you some bugs maybe you won't be able to debug.

You're not wrong, please try the new SDK and keep me posted ;)

**Comment by di-rect** [comment]
> > The way of connecting won't change, I'm pretty sure but it could give you some bugs maybe you won't be able to debug.
> 
> You're not wrong, please try the new SDK and keep me posted ;)

I will do over time, I hope I can make it work based on your code.

**Comment by Geolim4** [comment]
*nostale*

**Comment by Geolim4** [comment]
Hello @di-rect, any news ? ;)

**Comment by Geolim4** [comment]
Hello @di-rect, again, any news ? ;)

**Comment by di-rect** [comment]
> Hello @di-rect, again, any news ? ;)

You know how it goes... schedules always change :(

**Comment by Geolim4** [comment]
Okay :)

**Comment by Geolim4** [comment]
I'm closing this one for now, poke me when you are ready to update this issue :)

**Comment by di-rect** [comment]
I'm running into this as it seems that installing, or compiling, release-2.6 is not working on Ubuntu 20.04 with PHP 7.4 

Can you confirm this ?

2.x is not supported anymore the Couchbase people say, but I'm not sure. Investigating.

**Comment by Geolim4** [comment]
Hello,

I'm gonna add support for Couchbase SDK 3.0 in next version, 8.0.8.
It will be available as "Couchbasev3" and will mostly extends the current Couchbase behavior.

Are you okay to make some tests with me before releasing 8.0.8 ?

Thanks :)

**Comment by Geolim4** [comment]
Please test this feature I will merge in few minutes.

Use `dev-master` on composer to test this, thanks.

If it's ok, I will make a new release in few days.

**Comment by Geolim4** [comment]
Hello,

The support for SDK 3 has been added, use `Couchbasev3` driver and optionally configure the scope and collection if needed.

A new version will be released soon.

Cheers,
Georges
