### ISSUE TITLE
Can we set root folder name instead of hostname?

### ISSUE THREAD

**Issue by msinghgithub** [PHPSocialNetwork/phpfastcache#722]
**Configuration (optional)**
- **PhpFastCache version:** "2.0.4"
- **PhpFastCache API version:** "7.1.0"
- **PHP version:** "7.3.9"
- **Operating system:** "Windows 8.1 "

**My question**
>I am using file based caching. Path to store cached files is  d;\datacache\ folder. Here phpFastcache creates a folder with hostname to store files. Can we use any fixed folder name instead of host name?

**Comment by Geolim4** [comment]
Hello,

Please read the Doc and look at "securityKey" feature.

Cheers,
Georges
