### ISSUE TITLE
PhpfastcacheInvalidConfigurationException

### ISSUE THREAD

**Issue by yoyon-sugiono** [PHPSocialNetwork/phpfastcache#723]
When I try to determine the value of the **$SecurityKey** an error appears, I finally try to move the **$securityKey** declaration from the **IOConfigurationOptionTrait.php** file into the **ConfigurationOption.php** file and it works fine.

**Comment by Geolim4** [comment]
Hi,

Please reformat the issue using the bug template and be more specific, I'm
not a magician.

Cheers,
Georges

**Comment by yoyon-sugiono** [comment]
Sorry,

I use phpFastCache with SQLite, when I want to specify a folder for the cache error appears:

> Fatal error: Uncaught Phpfastcache\Exceptions\PhpfastcacheInvalidConfigurationException: Invalid option(s) for the config Phpfastcache\Config\ConfigurationOption: securityKey in F:\www\_api-autoblog-pro\vendor\phpfastcache\phpfastcache\lib\Phpfastcache\Config\ConfigurationOption.php:118 Stack trace: #0 F:\www\_api-autoblog-pro\hotels\functions.php(9): Phpfastcache\Config\ConfigurationOption->__construct(Array) #1 F:\www\_api-autoblog-pro\hotels\hotels_by_country.php(9): include('F:\\www\\_api-aut...') #2 F:\www\_api-autoblog-pro\index.php(86): include('F:\\www\\_api-aut...') #3 [internal function]: hotels_by_country('192', '330') #4 F:\www\_api-autoblog-pro\vendor\steampixel\simple-php-router\src\Steampixel\Route.php(84): call_user_func_array('hotels_by_count...', Array) #5 F:\www\_api-autoblog-pro\index.php(105): Steampixel\Route::run('/') #6 {main} thrown in F:\www\_api-autoblog-pro\vendor\phpfastcache\phpfastcache\lib\Phpfastcache\Config\ConfigurationOption.php on line 118


I tried to move the declaration:

`protected $securityKey = '';`

from

**trait IOConfigurationOptionTrait** in _IOConfigurationOptionTrait.php_

to

**class ConfigurationOption extends ArrayObject implements ConfigurationOptionInterface** in _ConfigurationOption.php_

and work well.

**Comment by Geolim4** [comment]
The Sqlite driver is actually being tested many times (see /tests) and no errors appears, what version are you using ?

And please reformat your issue using github template.

**Comment by yoyon-sugiono** [comment]
Sorry, I am not familiar with github. 
Please see the video that I made about what I did: https://youtu.be/7GD0aLquSmg

**Comment by Geolim4** [comment]
Hello,

The securityKey is not part of default "ConfigurationOption" but "IOConfigurationOptionTrait".

Use "\Phpfastcache\Drivers\Sqlite\Config" instead.

And pass it to "CacheManager::getInstance()".


Cheers,
Georges

**Comment by yoyon-sugiono** [comment]
Thank you for the explanation.

So I should use this statement:

```
use Phpfastcache\Drivers\Sqlite\Config;

$cache = CacheManager::getInstance('sqlite',  new Config(['path' => $path, 'securityKey'=>$securityKey]));
```

**Comment by Geolim4** [comment]
Yes
