### ISSUE TITLE
Lots of duplicate key errors with MongoDB driver in error logs

### ISSUE THREAD

**Issue by marzsman** [PHPSocialNetwork/phpfastcache#724]
**Configuration (optional)**
- **PhpFastCache version:** 7.1.0
- **PhpFastCache API version:** 2.0.4
- **PHP version:** `PHP 7.2.12-1+0~20181112102304.11+stretch~1.gbp55f215 (cli) (built: Nov 12 2018 10:23:04) ( NTS )`
- **Operating system:** `Linux 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64 `

**My question**
At our website we switched from Files driver to MongoDB driver a couple of weeks ago. Everything seems to work ok but when I check the error logs I see lots of Fatal errors on our production server.

```
[Wed Mar 18 11:34:43.989237 2020] [proxy_fcgi:error] [pid 58727:tid 139777046218496] [client 54.236.1.18:24848] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught MongoDB\\Driver\\Exception\\BulkWriteException: E11000 duplicate key error collection: app.cache index: _id_ dup key: { : "18b07bc91aa1ef7be975a482317f3cb4" } in /home/apps/web/vendor/mongodb/mongodb/src/Operation/Update.php:225\nStack trace:\n#0 /home/apps/web/vendor/mongodb/mongodb/src/Operation/Update.php(225): MongoDB\\Driver\\Server->executeBulkWrite('app.cache', Object(MongoDB\\Driver\\BulkWrite), Array)\n#1 /home/apps/web/vendor/mongodb/mongodb/src/Operation/UpdateOne.php(117): MongoDB\\Operation\\Update->execute(Object(MongoDB\\Driver\\Server))\n#2 /home/apps/web/vendor/mongodb/mongodb/src/Collection.php(1075): MongoDB\\Operation\\UpdateOne->execute(Object(MongoDB\\Driver\\Server))\n#3 /home/apps/web/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Drivers/Mongodb/Driver.php(132): MongoDB\\Collection->updateOne(Array, Array, Array)\n#4 /home/apps/web/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Core/Pool/CacheI...\n'
```
I tried to debug the error but can't replicate it locally. And from the error I have no idea where it happens.

Anyone an idea how to avoid this error?

**Comment by Geolim4** [comment]
Hello
🤷‍♂ , is it working ? 

To be honest I haven't tested this back-end in a while.
If you could provide me a PR it would be great, thanks you :(

Georges

**Comment by Geolim4** [comment]
Hello @marzsman  any news ? :)

**Comment by marzsman** [comment]
No and I have no idea what's causing the errors. 
I hoped someone here could point me in a direction ;)

I'll have to do some more debugging

**Comment by Geolim4** [comment]
Okay thanks, keep me posted then !
