### ISSUE TITLE
Strange behaviour of APCu Cache.

### ISSUE THREAD

**Issue by andreapernici** [PHPSocialNetwork/phpfastcache#725]
Which is the best way to setup various driver + files fallback?

I tried the following, but even if I disable APCU it still uses APCU.

```
        $this->conn = CacheManager::getInstance('apcu', 
            new ConfigurationOption([
                "path" => "/home/www/html/application/cache/fastcache/",
                "fallback" => 'files' //dirname(__FILE__)."/".$this->CI->config->item('cache_path').'fastcache/'
            ])
        );
```

I also tried to remove APCU completely from the server and looks like it still uses APCU cache.

How is it possibile? I don't see any file saved on the folder, but the cache got HIT.

**Comment by Geolim4** [comment]
Hello,

I see that no one is understanding how fallback is working 🤦‍♂ 

The fallback is only triggered if the "driverCheck()" method returns false.
In your case it does that: 
https://github.com/PHPSocialNetwork/phpfastcache/blob/be966068db57bde2cf89cfe16eedb440a1246bbc/lib/Phpfastcache/Drivers/Apcu/Driver.php#L42

So even if the Apcu server is down the driver will keep "working".
However this feature is removed in V8 in favor of master/slave clusters.

Cheers,
Georges

**Comment by andreapernici** [comment]
From what I see the issue is in the fallback configuration path. Looks like it doesn't follow the Path I specified

Doing the following solve the problem of files not present in the specified folder, but I think there's a lack of documentation here. I tried to search before asking, but didn't found anything.

```
CacheManager::setDefaultConfig(new ConfigurationOption([
            "path" => "/home/www/html/application/cache/fastcache/",
            "fallback" => 'files' 
          ]));

        $this->conn = CacheManager::getInstance('apcu', 
            new ConfigurationOption([
                "path" => "/home/www/html/application/cache/fastcache/",
                "fallback" => 'files' 
            ])
        );
```

so looks like the second configuration in getInstance doesn't work.

**Comment by Geolim4** [comment]
> From what I see the issue is in the fallback configuration path. Looks like it doesn't follow the Path I specified

Looks like you did not read the doc well, I'm one the most documented library if you look at the readme, the Wiki, the samples :|

https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-Configuration-Options#global-options

In the second example, you are passing the "path" configuration straight to the APCU driver, not the "files" one.

If you took the time to checkout the wiki:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-Configuration-Options#global-options

You would see the "fallbackConfig" option out there...

Cheers,
Georges
