### ISSUE TITLE
Is there a way to obtain a sort of Stale Cache usage?

### ISSUE THREAD

**Issue by andreapernici** [PHPSocialNetwork/phpfastcache#726]
Is there a way to use an expired cache version and update the key in background for the next hit?

**Comment by Geolim4** [comment]
Hello,

Please reformat the issue using the template issue, I'm not a magician.

Thanks
Georges

**Comment by andreapernici** [comment]
Do you know what is a "Stale Cache"?

**Comment by Geolim4** [comment]
...
I'm not talking about that.
The issue template helps me to get some other crucial information.

**Comment by Geolim4** [comment]
And to answer your question, shortly: No.

> Is there a way to use an expired cache version and update the key in background for the next hit?

For many reasons:
1) Some cache backend delete the key permanently when its outdated
2) It's against PSR6/16 principle
3) It's against the cache concept itself: A cache is a... Cache. Not a k/v database.

**Comment by andreapernici** [comment]
Ok thanks for the reply. 

Regarding this I don't agree at all.

> It's against the cache concept itself: A cache is a... Cache. Not a k/v database.

Stale Cache is a powerfull feature in some use cases and it's not against any cache principle. It's caching as its best.

**Comment by Geolim4** [comment]
No, a cache is means to be temporary: hours, days, weeks, month at best. You should not be able to "persist" an outdated cache item. The cache is there to reduce the "source fetch" load, no to replace it !

Else just use a standalone couchdb/couchbase NoSQL database :))))
