### ISSUE TITLE
Adding tags with memcached driver takes a long time

### ISSUE THREAD

**Issue by jmossetc** [PHPSocialNetwork/phpfastcache#729]
**Configuration**
- **PhpFastCache version:** "7.1.0"
- **PhpFastCache API version:** "2.0.4"
- **PHP version:** "7.3.13"
- **Operating system:** " ubuntu 18.04.1 "

**Describe the bug**

>Using Memcached driver, when adding 20 tags on a cache items, my request takes approximatively 2.6s instead of 1.6s. I need to add all of those tags for invalidation. When using redis, I do not have this issue.

**To Reproduce**
1. Use Memcached
2. Cache something with 20 tags
3. Monitor time to cache
4. Remove the code that adds the tags
5. It shoud take much less time than with the tags

**Expected behavior**
Caching items with tags is fast when using Memcached. If not possible give a warning in the documentation.

**Comment by Geolim4** [comment]
Hello,

I'm guessing it's you there:
https://stackoverflow.com/questions/61010709/adding-tags-to-cache-entry-takes-a-long-time-using-phpfastcache-with-memcached-d

**Comment by jmossetc** [comment]
@Geolim4 Yes!

**Comment by Geolim4** [comment]
I'm closing this one as we continue on S/O :)
