### ISSUE TITLE
Stats are not returned in uniform format

### ISSUE THREAD

**Issue by reno1979** [PHPSocialNetwork/phpfastcache#73]
When requesting the stats (v2.4.1) the returned array looks like : 

'memcached' : 
```
array (size=3)
  'info' => string '' (length=0)
  'size' => string '' (length=0)
  'data' => array(  in here the memcached stats  )
```

or

'Files'
```
array (size=3)
  'info' => 
    array (size=3)
      'Total' => int 662348
      'Removed' => int 636158
      'Current' => int 26190
  'size' => int 26190
  'data' => string '' (length=0)
```

I would like to make a request for an uniform stats format, meaning that the drivers will always fill the info array with the basic details (Total, Removed and Current).

**Comment by khoaofgod** [comment]
I work on that on next monday release.

**Comment by khoaofgod** [comment]
It will be on March 02

**Comment by reno1979** [comment]
Thank you, can't wait.

**Comment by khoaofgod** [comment]
This may only work for memcache, redis, apc, sqlite, cookie and files. Because I have no documents on x-cache. So, I gave up xcache :D muaaaah
