### ISSUE TITLE
Class 'CouchbaseCluster' not found 

### ISSUE THREAD

**Issue by DaveInTO** [PHPSocialNetwork/phpfastcache#736]
**Configuration**
- **PhpFastCache version:** "8.0.1."
- **PhpFastCache API version:** "3.0.0"
- **PHP version:** "7.4.5"
- **Operating system:** "Ubuntu Bionic"

Using the example...
Works perfectly fine on a box using couchbase.so 2.6
Built a new box today using couchbase.so 3.0

[2020-04-27 11:42:46] EXCEPTION: (Error) Class 'CouchbaseCluster' not found at [/home/filemobile/sabretoothv5/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Drivers/Couchbase/Driver.php:100]
  #0 Phpfastcache\Drivers\Couchbase\Driver::driverConnect called at [/home/filemobile/sabretoothv5/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Core/Pool/DriverBaseTrait.php:80]
  #1 Phpfastcache\Drivers\Couchbase\Driver::__construct called at [/home/filemobile/sabretoothv5/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/CacheManager.php:188]
  #2 Phpfastcache\CacheManager::getInstance called at [/home/filemobile/sabretoothv5/cacheTest.php:6]

> ... A clear and concise description of what the bug is, goes here ... 
... You can also read the [wiki](https://github.com/PHPSocialNetwork/phpfastcache/wiki) ...

**To Reproduce**
Build PHP module
wget https://packages.couchbase.com/clients/php/couchbase-3.0.0.tgz
cd couchbase-3.0.0
phpize
 ./configure --with-couchbase
make
make install

USING w/modifications to Config representive my setup
<?php
/**
 *
 * This file is part of phpFastCache.
 *
 * @license MIT License (MIT)
 *
 * For full copyright and license information, please see the docs/CREDITS.txt file.
 *
 * @author Khoa Bui (khoaofgod)  <khoaofgod@gmail.com> https://www.phpfastcache.com
 * @author Georges.L (Geolim4)  <contact@geolim4.com>
 *
 */

use Phpfastcache\CacheManager;
use Phpfastcache\Drivers\Couchbase\Config;

// Include composer autoloader
require __DIR__ . '/../../vendor/autoload.php';

$InstanceCache = CacheManager::getInstance('couchbase', new Config([
  'host' => 'your-couchbase-host',
  'port' => '8091',
  'username' => 'your-couchbase-username',
  'password' => 'your-couchbase-password',
  'bucketName' => 'default' // The bucket name, generally "default" by default
]));

/**
 * Try to get $products from Caching First
 * product_page is "identity keyword";
 */
$key = "product_page";
$CachedString = $InstanceCache->getItem($key);

if (is_null($CachedString->get())) {
    //$CachedString = "APC Cache --> Cache Enabled --> Well done !";
    // Write products to Cache in 10 minutes with same keyword
    $CachedString->set("Couchbase Cache --> Cache Enabled --> Well done !")->expiresAfter(5);
    $InstanceCache->save($CachedString);

    echo "FIRST LOAD // WROTE OBJECT TO CACHE // RELOAD THE PAGE AND SEE // ";
    echo $CachedString->get();

} else {
    echo "READ FROM CACHE // ";
    echo $CachedString->get();
}

echo '<br /><br /><a href="/">Back to index</a>&nbsp;--&nbsp;<a href="./' . basename(__FILE__) . '">Reload</a>';

**Comment by Geolim4** [comment]
Hello,

Looks normal to me if they upgraded to 3.0.x, according to semver this is an API change, so our code is not longer compatible. So stay in couchbase 2.x until an update in the next major version since I can't support both versions with differents APIs in the same code.

Cheers,
Georges

**Comment by DaveInTO** [comment]
Yeah..that's what I did..
Spent some time changing the code to use 3.0, then changed my mind, and downgraded to 2.
Thanks
