### ISSUE TITLE
Files driver with external host

### ISSUE THREAD

**Issue by uriafranko** [PHPSocialNetwork/phpfastcache#737]
So I'm trying to use files driver with external hosting like s3 bucket
the docs says 
ConfigOptions has 'host' parameter 
**Host/Authenticating options ***
```
host | string (default: null) The hostname
path | string (default: null|string[temp. dir.])
```
but I can't manage to use it as there is no host variable in the ConfigOptions

#### anyone succeded making files cache works with other hosts?

**Comment by Geolim4** [comment]
Hello,

"Host" parameter is only for specific backends such as Redis, Memcache etc.
If you use an s3 bucket, I'm suggesting you either to create a virtual directory linked to your s3 bucked or using a Redis service which will be more efficient in your use case :)

Cheers,
Georges

**Comment by Geolim4** [comment]
Hello @uriafranko,

I’m closing this issue _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the issue / add comment / clarify …).

Regards,
Georges.L
