### ISSUE TITLE
Error `Calling many times CacheManager::getInstance()` when trying to get Laravel route:list

### ISSUE THREAD

**Issue by PhongNguyen512** [PHPSocialNetwork/phpfastcache#738]
**Configuration**
- **PhpFastCache version:** ^7.1
- **PHP version:** ^7.2
- **Operating system:** I'm running my project in Homestead (Laravel environment)

**Describe the bug**
I tried to list all route in my laravel project using `php artisan route:list`. I got error `[Files] Calling many times CacheManager::getInstance() for already instanced drivers is a bad practice and have a significant impact on performances.
           See https://github.com/PHPSocialNetwork/phpfastcache/wiki/[V5]-Why-calling-getInstance%28%29-each-time-is-a-bad-practice-%3F`.

I also follow a Good Practice of calling CacheManager:getInstance. I only call it in __contruct of my Controller. In the clearInstances() function of Phpfastcache, I saw `self::$instances = [];`. I have no issue during development time, but this is the first time I got this error when I try to get all route.

**Comment by Geolim4** [comment]
Hello,

This means your controller has been called twice at least, you probably have an issue in your implementation :)

Cheers,
Georges.

**Comment by PhongNguyen512** [comment]
Hi, Thanks for your reply.

I'm not sure about this issue. I got this issue when I was using the command in the console. I'm curious why I got no issue during the code run, but in the console.

**Comment by Geolim4** [comment]
Then start a backtrace, you've must called the manager multiples times for the same instance :/

**Comment by Geolim4** [comment]
Hello @PhongNguyen512,

I’m closing this issue _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the issue / add comment / clarify …).

Regards,
Georges.L
