### ISSUE TITLE
Is it possible to use one general and one unique key in same cache?

### ISSUE THREAD

**Issue by Skipytr** [PHPSocialNetwork/phpfastcache#739]
**Configuration**

**- PhpFastCache version:** ^8.0
**- PHP version:** ^7.4.5
**- Operating system:** Localhost for pure PHP project in centos 7

**Question**
I want to use 2 keys in one cache to store data.
For example, I have two data.
data1 and data2
I want to store data1 with keys like "posts", "post_data1" and I want to store data2 with "posts", "post_data2".
So if I clear "post_data1" only data1 will be cleared but if I clear "posts" both of them will be cleared.

Is there a way to do that?

**Comment by Geolim4** [comment]
Hello,

Please reformat your issue with the appropriate template please, thanks.

Cheers,
Georges

**Comment by Skipytr** [comment]
@Geolim4 Reformatted as requested.

**Comment by Geolim4** [comment]
Thanks,

Look at the Readme to see the list of "Tags APIs":
https://github.com/PHPSocialNetwork/phpfastcache#item-api-extendedcacheiteminterface


Cheers,
Georges.

**Comment by Skipytr** [comment]
So can I use something like this?

```
use Phpfastcache\Helper\Psr16Adapter;

$defaultDriver = 'Files';
$Psr16Adapter = new Psr16Adapter($defaultDriver);

if(!$Psr16Adapter->has('post_data1')){
    $Psr16Adapter->addTag("posts")->set('post_data1', 'data1', 300);
}else{
    $data = $Psr16Adapter->get('post_data1');
}
```

**Comment by Geolim4** [comment]
No,

Read the API correctly. The tags are not implemented on PSR16 adapters but on PSR6 ones.

**Comment by Skipytr** [comment]
Okay. I guess this one will do the trick.

```
use Phpfastcache\CacheManager;
$InstanceCache = CacheManager::getInstance('files');

$key = "post_data1";
$key2 = "post_data2";
$CachedData = $InstanceCache->getItem($key);
$CachedData2 = $InstanceCache->getItem($key2);
if (is_null($CachedData->get())) {
	$CachedString->set("Data1")->expiresAfter(300)->addTag('posts');
}
if (is_null($CachedData2->get())) {
	$CachedString->set("Data2")->expiresAfter(300)->addTag('posts');
}
```
I can use the `$InstanceCache->deleteItem("post_data1");` to clear just data1 and use `$InstanceCache->deleteItemsByTag('posts');` to delete both data1 and data2
