### ISSUE TITLE
can't connect couchdb on external server

### ISSUE THREAD

**Issue by sir-reynolds** [PHPSocialNetwork/phpfastcache#742]
**Configuration (optional)**
- **PhpFastCache version:** 7.1.1
- **PhpFastCache API version:** 2.0.4
- **PHP version:** 7.2
- **Operating system:** ubuntu 16.04

**My question**

```
require_once 'vendor/autoload.php';
use Phpfastcache\Drivers\Couchdb\Config;
use Phpfastcache\Helper\Psr16Adapter;

$_PhpFastCache = new Psr16Adapter(
									'couchdb', 
									new Config	(
													[
														'host' => '1.2.3.4', //couchdb ip address
														'port' => 9786,
														'path' => '/',
														'ssl' => false,
														'timeout' => 10,
													]
												)
								);
```

> PHP Fatal error:  Uncaught Phpfastcache\\Exceptions\\PhpfastcacheDriverCheckException: Couchdb is not installed or is misconfigured, cannot continue. \n    Also, please verify the suggested dependencies in composer because as of the V6, 3rd party libraries are no longer required. in /var/www/html/DMDMDMDMD/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Core/Pool/DriverBaseTrait.php:70\nStack trace:\n#0 /var/www/html/DMDMDMDMD/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/CacheManager.php(131): Phpfastcache\\Drivers\\Couchdb\\Driver->__construct(Object(Phpfastcache\\Drivers\\Couchdb\\Config), '856e5b5d013e0c5...')\n#1 /var/www/html/DMDMDMDMD/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Helper/Psr16Adapter.php(52): Phpfastcache\\CacheManager::getInstance('Couchdb', Object(Phpfastcache\\Drivers\\Couchdb\\Config))\n#2 /var/www/html/DMDMDMDMD/_vendor_config.php(37): Phpfastcache\\Helper\\Psr16Adapter->__construct('couchdb', Object(Phpfastcache\\Drivers\\Couchdb\\Config))\n#3 /var/www/html/DMDMDMDMD/index.php(10): require_once('/var/www/html/w...') in /var/www/html/DMDMDMDMD/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/CacheManager.php on line 174

**Comment by Geolim4** [comment]
Hello,

Did you installed the composer dependency ?
It is specified in "suggested" deps, not requirements :)

Cheers,
Georges

**Comment by sir-reynolds** [comment]
can you give me details info whats dependency i must installed?
 i try install https://github.com/doctrine/couchdb-client but failed, composer logs it's conflict with phpfastcache 7.1.1.



please give me info about dependency.

**Comment by Geolim4** [comment]
Please take a look at our composer.json:

https://github.com/PHPSocialNetwork/phpfastcache/blob/master/composer.json

**Comment by sir-reynolds** [comment]
thank you @Geolim4 

can i install it like this

composer require "PHPSocialNetwork/couchdb": "@dev"

**Comment by Geolim4** [comment]
Exactly.

**Comment by Geolim4** [comment]
Hello @sir-reynolds,

I’m closing this issue _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the issue / add comment / clarify …).

Regards,
Georges.L

**Comment by sir-reynolds** [comment]
sorry @Geolim4  i'm try `composer require "PHPSocialNetwork/couchdb": "@dev"` but this show error :

![image](https://user-images.githubusercontent.com/37714879/86908929-86fd3e80-c141-11ea-9739-b9650c1175f6.png)

**Comment by Geolim4** [comment]
Decrease your project stability or use dev-master

**Comment by sir-reynolds** [comment]
hi @Geolim4 i'm try again with more example but still failed

![image](https://user-images.githubusercontent.com/37714879/87052375-e6834900-c22a-11ea-9bf6-b2fd6ce82b0d.png)

i already decrease project stability but same still failed.

i try PHPSocialNetwork/couchdb and phpfastcache/couchdb but same Could not find package.

maybe i must use "doctrine/couchdb": "@dev" ?
