### ISSUE TITLE
Maybe support Memcached::OPT_PREFIX_KEY ?

### ISSUE THREAD

**Issue by juneszh** [PHPSocialNetwork/phpfastcache#744]
**Configuration (optional)**
- **PhpFastCache version:** "7.1.1"
- **PhpFastCache API version:** "2.0.4"
- **PHP version:** "7.2"
- **Operating system:** "Ubuntu 18.04"

**My question**
> There are some projects with same memcached in my server. I find the redis config has 'optPrefix' but memcached none.

**Comment by Geolim4** [comment]
Hello,

Indeed Redis supports natively this option as well as Memcached (but not Memcache).
I can consider adding the support of this option for sure !

Expect it to be released in the next minor version ;)

**Comment by Geolim4** [comment]
Hello,

A PR has been added, once its merged, this issue will be closed.

Expect the 8.0.2 to be out by the end of month.

Cheers,
Georges

**Comment by Geolim4** [comment]
Hello,

release 8.0.2 is out:
https://github.com/PHPSocialNetwork/phpfastcache/releases/tag/8.0.2

Cheers,
Georges
