### ISSUE TITLE
How to turn off phpfastcache?

### ISSUE THREAD

**Issue by rohitcoder** [PHPSocialNetwork/phpfastcache#745]
**Configuration (optional)**
- **PhpFastCache version:**  3.0.0
- **PhpFastCache API version:** 8.0.1
- **PHP version:** 7.1.9
- **Operating system:** Mac with MAMP / Also executed this same on Ubuntu

**My question**

Is there any option to turn off phpfastcache implementation without removing lib and codes? We want to test our system with different options like redis, file system, predis, cassandra and so on..

During performing test, we want to turn off phpfastcache and we want to use it without cache to see improvements and measure which option is best for us.

Our codebase is big enough, we want something simple enough to turn-off phpfastcache like it should bypass phpfastcache implementation, is it possible?

I checked your docs and i wasn't able to find something like this.

**Comment by Geolim4** [comment]
Use drivers Devnull :)

**Comment by Geolim4** [comment]
See WIKI:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV5%CB%96%5D-Disabling-PhpFastCache

**Comment by rohitcoder** [comment]
Working as expected! 

Thanks :)
