### ISSUE TITLE
phpfastcache v6 clear() is not clearing files and directories.

### ISSUE THREAD

**Issue by murali9lanka** [PHPSocialNetwork/phpfastcache#746]
**Configuration**
- **PhpFastCache version:** "6.1.4"
- **PhpFastCache API version:** "1.2.5"
- **PHP version:** "5.6.36"
- **Operating system:** "CentOS7"

**phpfastcache v6 clear() is not clearing files and directories.**

>
require_once  '/var/www/php/sys/libs/vendor/src/autoload.php';
use phpFastCache\CacheManager;
use Phpfastcache\Exceptions\PhpfastcacheDriverException;

CacheManager::setDefaultConfig(array('default_chmod' => 0777, 'path' => '/var/www/html/cacheTest'));
$c = CacheManager::getInstance('Files');
$it = $c->getItem('test');
$it->set('value');
$c->save($it);
$c->clear();

'/var/www/html/cacheTest' 'cacheTest' directory has 0777 permissions. 

After running the code snippet I see cacheTest directory and its sub-directoires.

**Expected behavior**
Expected clear content of cacheTest directory or remove cacheTest directory 

> Even after having 0777 permission on 'cacheTest' directory, above code is not clearing cacheTest directory. What could be the issue here. Installed phpfastcache v6 without composer, by unzip v6.zip.

**Comment by Geolim4** [comment]
Hello,

Can you reformat the issue according the bug template please ?

Thanks.

**Comment by murali9lanka** [comment]
Thank you for the quick response. Updated the issue according to the bug template.

**Comment by Geolim4** [comment]
Hello

Thanks you.
The clear() method does not necessarily remove the directory you specified, but the serialized file inside that directory.

Cheers,
Georges

**Comment by murali9lanka** [comment]
okay, could you help me with a method name which can remove directories as well. The requirement is to clenaup complete cache directory contents through a nightly job, so that we will not endup with disk outages.

Thank you,
Murali

**Comment by Geolim4** [comment]
The directories will be empty, Phpfastcache removes every serialized files when you call "clear" method.
So created directories won't lead to a disk outage at all if there's no files anymore.

You could try using an event method on "onclear' method by getting path from config, but that's a bit tricky.

Cheers,
Georges

**Comment by Geolim4** [comment]
Also I'm advising you to upgrade to V7 since the v6 is almost in EOL:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-Global-support-timeline#v6-lts-june-2017

**Comment by murali9lanka** [comment]
> The directories will be empty, Phpfastcache removes every serialized files when you call "clear" method.
> So created directories won't lead to a disk outage at all if there's no files anymore.
> 
> You could try using an event method on "onclear' method by getting path from config, but that's a bit tricky.
> 
> Cheers,
> Georges

Thank you. That makes sense.

**Comment by murali9lanka** [comment]
> Also I'm advising you to upgrade to V7 since the v6 is almost in EOL:
> https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-Global-support-timeline#v6-lts-june-2017

Yes, Sure. Currently we are using php V5.6.3, soon we will upgrade to php 7 then we will upgrade to phpfastcache V7.

Thanks,
Murali

**Comment by Geolim4** [comment]
Okay, I'm closing this issue then, happy caching ! :D
