### ISSUE TITLE
Running PHPFastCache as a proxy?

### ISSUE THREAD

**Issue by xwiz** [PHPSocialNetwork/phpfastcache#751]
My question/request might be a bit unusual.

We're currently facing a high traffic situation where opening and closing connections to Redis for every http request is costly for our setup. We're considering using Twemproxy but I went through the code of PHPFastCache and noticed it's capable of running as a proxy with some tweaking?

**Additional context**
This is just me thinking out loud whether there's a way PHPFastCache can be a single solution to using any cache driver for any traffic situation. So it's OK if this is not going to be worked on in the near foreseeable future.

**Comment by Geolim4** [comment]
Hello,

You can try to use your own Redis client instance by passing it through Config option:
https://github.com/PHPSocialNetwork/phpfastcache/blob/edb91d88b26723ac7317c01c5cfe3977582035ed/lib/Phpfastcache/Drivers/Redis/Config.php#L52

I have plan to add support of persistent connection to Redis through "pconnect()" in the 8.1 version, but it's a long term plan and you may be urged to use that before.

Else I have no other option for you atm than trying this,
Cheers,
Georges

**Comment by Geolim4** [comment]
Also please next time please use the default issue template or the issue will be immediately closed, thanks :)

**Comment by Geolim4** [comment]
Hello @xwiz,

I’m closing this issue _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the issue / add comment / clarify …).

Regards,
Georges.L
