### ISSUE TITLE
Is it possible to set TTL on tags lower that the default 900 seconds

### ISSUE THREAD

**Issue by mapcentia** [PHPSocialNetwork/phpfastcache#752]
When doing something like this:
`$CachedString->set($value)->addTags([$tag])->expiresAfter(100);`

The _TAG_ key in Redis will have a TTL of 900

Setting  expiresAfter to over 900 will result in a _TAG_ key with TTL of the same value.

So you can't set TTL on _TAG_ keys below 900 ?

**Comment by Geolim4** [comment]
Hello,

This a normal behavior, the Item tags (which are private internal items) relies on the longest TTL from those two values:
- *defaultTtl* value See Wiki: https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-Configuration-Options#global-options
- Or the parent item TTL value


If the parent TTL value is shortest than *defaultTtl* value then the *defaultTtl* value will be used instead.

Also please next time please use the default issue template or the issue will be immediately closed, thanks :)

Cheers,
Georges
