### ISSUE TITLE
Add the ability force driver read and skip $itemInstances

### ISSUE THREAD

**Issue by LowSociety** [PHPSocialNetwork/phpfastcache#754]
**Configuration**
- **PhpFastCache version:** "8.0.2"
- **PhpFastCache API version:** "3.0.0"
- **PHP version:** "7.4.8"
- **Operating system:** "macOS Catalina"

**Is your feature request related to a problem? Please describe.**
I am currently working on a queueing system which includes a daemon worker that pulls jobs off of a queue and fires them. As a way of restarting the daemon I was planning on using a cache item with a timestamp that lets the daemon know that it should restart. This proved to be harder than I though with the current version of PhpFastCache though, as the cache item is written by another process and the daemon process only reads the key from the driver once, and all subsequent reads result in the value from `$itemInstances`, which is only cleared if the same key is written to _in the same process_ or I call `detachAllItems()` on every cycle.

**Describe the solution you'd like**
Expose a way to read from the driver regardless of whether the item exists in `$itemInstances` or not.

**Describe alternatives you've considered**
Expose a was to force remove a key from `$itemInstances`.

**Comment by Geolim4** [comment]
Hello,

For now, you will need to keep calling "detachAllItems()" or "detachItem(CacheItemInterface $item);".

I will may add an option to disable "static caching"  in the 8.1x which is not planned before end of year.

Cheers,
Georges

**Comment by Geolim4** [comment]
I will finally release this feature for the 8.0.3 since it can be blocking for many people and the v8 is an LTS.

**Comment by Geolim4** [comment]
The config option "useStaticItemCaching" has been added (default true) to allow you to fetch straight from backend instead of looking on static cache first.
