### ISSUE TITLE
Storing image files

### ISSUE THREAD

**Issue by mertasan** [PHPSocialNetwork/phpfastcache#756]
**My question**

I use a package that allows the images on my website to be displayed dynamically in various sizes.

Can I store the thumbnail images created with this package in the Files driver? Is it suitable for image files? Is it possible for you to give a small code example?

If I do this, the website will not spend extra performance on creating thumbnails every time.

**Comment by Geolim4** [comment]
Hello,

Of course you can, by storing your image as a binary string:
You can store your image as a binary content or an hexadecimal content (using [bin2hex](https://www.php.net/manual/fr/function.bin2hex.php)).

The rest of the logic is up to you.

**Comment by Geolim4** [comment]
Hello @mertasan,

I’m closing this issue _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the issue / add comment / clarify …).

Regards,
Georges.L
