### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by prakashmuvi** [PHPSocialNetwork/phpfastcache#763]
**Configuration**
- **PhpFastCache version:** "7.1.0"
- **PhpFastCache API version:** "v7"
- **PHP version:** ".7.0.33."
- **Operating system:** "Linux"

**Getting PHP Fatal error**
PHP Fatal error: Class Phpfastcache\Drivers\Files\Item contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (JsonSerializable::/usr) in /var/www/html/newstudio/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Drivers/Files/Item.php on line 31, referer: https://youtube.com/mobile
PHP Fatal error: Class Phpfastcache\Drivers\Files\Item contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (JsonSerializable::/usr) in /var/www/html/newstudio/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Drivers/Files/Item.php on line 31, referer: https://www.xyz.com/sr?gclid=EAIaIQobChMI4L-ThJeM7AIV11DCCh1gNgL1EAEYASAAEgJ_B_D_BwE
PHP Fatal error: Class Phpfastcache\Drivers\Files\Item contains 1 abstract method and must therefore be declared abstract or implement the remaining
methods (JsonSerializable::/usr) in /var/www/html/newstudio/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Drivers/Files/Item.php on line 31
**To Reproduce**
This issue is randomly and getting where multiple concurrently requests are coming.
**Expected behavior**
Not getting any fatal error

**Screenshots**
Getting this Error from the server error log action

**Additional context**
Not always but randomly

**Comment by Geolim4** [comment]
Hello,

Please reformat your issue according default template.

Thanks you.
Georges.

**Comment by prakashmuvi** [comment]
HI,
Sorry, I am not getting your point **reformat your issue according default template**. Could you please help me to understand.

**Comment by Geolim4** [comment]
There was default data when your created your issue that I must know to help you with your issue:

https://github.com/PHPSocialNetwork/phpfastcache/issues/new?template=bug_report.md

**Comment by prakashmuvi** [comment]
**Configuration**
- **PhpFastCache version:** "7.1.0"
- **PhpFastCache API version:** "v7"
- **PHP version:** ".7.0.33."
- **Operating system:** "Linux"

**Getting PHP Fatal error**
PHP Fatal error: Class Phpfastcache\Drivers\Files\Item contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (JsonSerializable::/usr) in /var/www/html/newstudio/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Drivers/Files/Item.php on line 31, referer: https://youtube.com/mobile
PHP Fatal error: Class Phpfastcache\Drivers\Files\Item contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (JsonSerializable::/usr) in /var/www/html/newstudio/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Drivers/Files/Item.php on line 31, referer: https://www.xyz.com/sr?gclid=EAIaIQobChMI4L-ThJeM7AIV11DCCh1gNgL1EAEYASAAEgJ_B_D_BwE
PHP Fatal error: Class Phpfastcache\Drivers\Files\Item contains 1 abstract method and must therefore be declared abstract or implement the remaining
methods (JsonSerializable::/usr) in /var/www/html/newstudio/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Drivers/Files/Item.php on line 31
**To Reproduce**
Steps to reproduce the behavior:
This issue is randomly and getting where multiple concurrently requests are coming.
**Expected behavior**
Not getting any fatal error

**Screenshots**
Getting this Error from the server error log action

**Additional context**
Not always but randomly

**Comment by Geolim4** [comment]
Thanks,

I can confirm you that the issue is not Phpfastcache related since the tests passes and are calling "lib/Phpfastcache/Drivers/Files/Item.php" without throwing any error.

> 1 abstract method and must therefore be declared abstract or implement the remaining methods (JsonSerializable::/usr)

This error is very strange, in my opinion you have an issue with your php installation/configuration (Apc/Opcache issue?) 

As you can see in official php doc:
https://www.php.net/manual/fr/class.jsonserializable.php

The method "usr" in class "JsonSerializable" does not exists at all.

Cheers,
Georges

**Comment by prakashmuvi** [comment]
Hi Geolim4,
Thank you for your reply. I will check internally and get back to you.

**Comment by Geolim4** [comment]
#
Hello @prakashmuvi,

I’m closing this issue _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the issue / add comment / clarify …).

Regards,
Georges.L
