### ISSUE TITLE
Getting Exception in phpFastCache

### ISSUE THREAD

**Issue by prakashmuvi** [PHPSocialNetwork/phpfastcache#764]
**Configuration**
- **PhpFastCache version:** "7.1.0"
- **PhpFastCache API version:** "V7"
- **PHP version:** "7.0.33"
- **Operating system:** " Linux "

**Describe the bug**

> ... Getting Exception ... 

We are getting this Exception randomly not always. We are suspecting the permission related issue but not find the same type of issue.

Path "/var/www/html/test/cache/8482/language/xyz.com/Files/b3/19" is not writable, please set a chmod 0777 or any writable permission and make sure to make use of an absolute path ! Additional information provided by error_get_last(): mkdir(): File exists in /var/www/html/test/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Core/Pool/IO/IOHelperTrait.php line 165

**Comment by Geolim4** [comment]
Hello,

You may face chown issue here.
If the chmod can't get applied this means that you have a proprietary issue on your file system.

I have already seen this kind of bug.
Just make sure that your web-server group (usually www-data) is the owner of your app project.
If you use CLI command from another user, make sure he's on the www-data group too.

Cheers,
Georges
