### ISSUE TITLE
The migration link is dead (404) on the documentation page

### ISSUE THREAD

**Issue by jmossetc** [PHPSocialNetwork/phpfastcache#765]
To reproduce: 

- Go here : https://www.phpfastcache.com#warningpleasenotethatthev8isanimportantwithsmallbcbreakingupdateofphpfastcache
- Click on migration guide link
- The page linked is a 404

**Comment by Geolim4** [comment]
Hello,

I confirm the issue, but the Readme is a mirror version of the on of the repository (which is working):
https://github.com/PHPSocialNetwork/phpfastcache

So I can't fix it to be working in both side :(

Thanks again Jérémie !
