### ISSUE TITLE
Site-only issue

### ISSUE THREAD

**Issue by spud** [PHPSocialNetwork/phpfastcache#780]
The first "migration guide" link on https://www.phpfastcache.com/ is a 404, since it appears you moved all the docs to GitHub. Also, near the very end of the home page, "For curious developers, there is a lot of other examples available here." the "here" is also a 404. Just FYI, I did end up finding everything I needed!

**Comment by Geolim4** [comment]
Hello,


Thanks for the issue which is caused by the website's Readme being a mirror of the repository's readme.
I'll update the relative link to an absolute link by the end of week.

Cheers,
Georges
