### ISSUE TITLE
Expected parameter of type 'int', 'false' provided

### ISSUE THREAD

**Issue by applibs** [PHPSocialNetwork/phpfastcache#781]
In this code:
return (new DriverStatistic())
            ->setData(implode(', ', array_keys($this->itemInstances)))
            ->setRawData($info)
            ->setSize(false)
            ->setInfo('Riak does not provide size/date information att all :(');

I see that setSize has int type. Its impossible send boolean.

**Comment by Geolim4** [comment]
Hello,

It's not fixed, thanks you.
