### ISSUE TITLE
Getting Exception 

### ISSUE THREAD

**Issue by prakashmuvi** [PHPSocialNetwork/phpfastcache#783]
**Configuration**
- **PhpFastCache version:** "7.1.0"
- **PhpFastCache API version:** "v7"
- **PHP version:**".7.0.33."
- **Operating system:**"Linux"
**Describe the bug**

> ... Path "/var/www/vhosts/muvi-usa/cache/48397/language/api.muvi.com/Files/46/d6" is not writable, please set a chmod 0777 or any writable permission and make sure to make use of an absolute path ! Additional information provided by error_get_last(): mkdir(): File exists in /var/www/vhosts/muvi-usa/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Core/Pool/IO/IOHelperTrait.php line 165 ...

**To Reproduce**
We are getting this type of exception randomly for multi lingual website. We have set the file and folder permission 0777

**Expected behavior**
It should not raise the above type of exception.

**Comment by Geolim4** [comment]
Hello,

The tests passes on the v7 with strong tests on this driver:
https://travis-ci.org/github/PHPSocialNetwork/phpfastcache/builds/744509436

Are you sure that you don't have a chown issue instead ?
(CLI script ran in same directory than Web scripts)

This is a common issue that can be only fixed by adding your CLI cron user to the same group as Web script user (usally www-data).

Cheers,
Georges

**Comment by prakashmuvi** [comment]
Hi,
Yes, i am sure. All folders and files have Apache owner.

**Comment by Geolim4** [comment]
Then I don't know what's wrong.
The tests pass without any errors with strong tests of "Files" driver, to be honest without more investigation on your side I can't do anything else :/

**Comment by Geolim4** [comment]
```php
        if (!$skip && !\is_dir($path) && @!\mkdir($path, $this->getDefaultChmod(), true) && !\is_dir($path)) {
            throw new PhpfastcacheIOException('Path "' . $path . '" is not writable, please set a chmod 0777 or any writable permission and make sure to make use of an absolute path !');
        }
```


See ? I can't change that, this is an issue with your filesystem, not Phpfastcache.
The above code does the following things:

- Checking if $skip isn't true
- Checking if directory exists
- Attempting to create it, recursively if needed
- Check if the directory created effectively exists

If everything above return false it means that the directory does not exists and have not created leading to an exception.

**Comment by prakashmuvi** [comment]
Hi,
Thanks for your reply. 
For you information ,We are not getting constantly this type of exception.
We are getting this type of exception near about 20% case where Multilanguage available.

**Comment by Geolim4** [comment]
This is so strange as you can see in [this build](https://github.com/PHPSocialNetwork/phpfastcache/pull/784/checks?check_run_id=1791597686), the tests "ReadWriteOperations.test.php" does a LOT of read/write operation with "Files" driver and I don't encounter this issue ?

Can you please show me the configuration passed to the cache manager ?

**Comment by prakashmuvi** [comment]
Hi,
Please find my function to set and get.
public function getPageCache($studioId = false, $cacheKey = false) {
		if (!empty($studioId) && !empty($cacheKey)) {
                   CacheManager::setDefaultConfig(new ConfigurationOption(['path' =>self::cacheLanguagePath($studioId)]));
			$InstanceCache = CacheManager::getInstance('files');
			$cachedString = $InstanceCache->getItem($cacheKey);
			$getPageCache = $cachedString->get();
			return $getPageCache;
		} else {
			return false;
		}
	}

	public function setPageCache($studioId = false, $cacheKey = false, $data = false, $duration = 600) {
		if (!empty($studioId) && !empty($cacheKey) && !empty($data)) {                                          
                CacheManager::setDefaultConfig(new ConfigurationOption(['path' =>self::cacheLanguagePath($studioId)])); 
			$InstanceCache = CacheManager::getInstance('files');
			$cachedString = $InstanceCache->getItem($cacheKey);
			$cachedString->set($data)->expiresAfter($duration);
			$InstanceCache->save($cachedString);
			return true;
		} else {
			return false;
		}
	}
public function cacheLanguagePath($studioId) {
		$dirpath = $_SERVER["DOCUMENT_ROOT"] . '/cache/' . $studioId . '/language/';
		$mode = FILE_PERMISSION;
		if (is_dir($dirpath) || mkdir($dirpath, $mode, true)) {
			return $dirpath;
		} else {
			return false;
		}
	}
I hope the above function will help to identify the root cause of this issue.

**Comment by Geolim4** [comment]
For sure, the root path is not on Phpfastcache's side. There's a lot of tests on this drivers and I did not noticed this error yet :/

**Comment by prakashmuvi** [comment]
Hi
Thanks for your cooperation. We are not getting this exception in last 3 dayas after increasing the cache folder space.

**Comment by Geolim4** [comment]
Great news, thanks for the feedback !

Happy caching !
