### ISSUE TITLE
Howto autoload phpfastcache with composer.json (psr-4)

### ISSUE THREAD

**Issue by moorl** [PHPSocialNetwork/phpfastcache#787]
Hi, I can't autoload this module via composer.json. Is it even possible here?

```
{
    "autoload": {
        "psr-4": {
            "Psr\\Http\\Message\\": "vendor/psr/http-message/src/",
            "Psr\\Http\\Client\\": "vendor/psr/http-client/src/",
            "Psr\\SimpleCache\\": "vendor/psr/simple-cache/src/",
            "Phpfastcache\\": "vendor/phpfastcache/phpfastcache/lib/Phpfastcache",
            "InstagramScraper\\": "vendor/raiym/instagram-php-scraper/src/InstagramScraper"
        }
    }
}
```

I can get all of the Classes and Namespaces from the other modules but not from Phpfastcache. Is there any alernative autoload method?

Here is my Error Message
``Attempted to load class "Psr16Adapter" from namespace "Phpfastcache\Helper".
Did you forget a "use" statement for "Symfony\Component\Cache\Adapter\Psr16Adapter"?
``

**Comment by Geolim4** [comment]
You don't need to make the autoloader by yourself  ??

Just require "phpfastcache/phpfastcache" with composer and it's done !

Cheers,
Georges
