### ISSUE TITLE
SQLite has duplicate folder in path

### ISSUE THREAD

**Issue by neico** [PHPSocialNetwork/phpfastcache#788]
**Configuration**
- **PhpFastCache version:** 8.0.4
- **PhpFastCache API version:** 3.0.0
- **PHP version:** >= 7.4
- **Operating system:** windows / linux

**Describe the bug**
Apparently sqlite has been using a path akin to `<config "path">/<config "securityKey">/<driver name, aka "Sqlite">/sqlite/<file name, ex. db1/indexing>` since v5 (according to git history) where `getPath()` gained the driver folder segment, but the sqlite driver still appending another "sqlite" to it

As the files driver seemed to have a similar history (it's `FILE_DIR` seemed to have been unused since v5 and finally removed with v8) I'd assume it's just an oversight from then...

**Expected behavior**
the path being `<config "path">/<config "securityKey">/<driver name, aka "Sqlite">/<file name, ex. db1/indexing>`
maybe with the driver name lowercased, but eh, details

While not strictly part of the behavior mentioned, I noticed that `securityKey` doesn't seem to be "nullable" (aka, setting it to an empty string), to avoid an additional folder from being created. (making the conditional check in `getPath()` almost, if never hit: `if ($securityKey !== '') $securityKey .= '/';`)
This seems to be caused by the `!$securityKey` check which not only considers unset or `null` variables as false, but also string "" and "0" (I actually had to look this up too because it's non-common behavior, coming from other languages)

I'm just not a fan of having multiple layers of almost empty folders, of which I know won't get any more content.

**Comment by Geolim4** [comment]
Hello,

You right this is totally redundant, I just fixed it.

Expect the next release to be out by mid, maybe end of March.

Meantime use "dev-master" if this is blocking for you.

Cheers,
Georges
