### ISSUE TITLE
Mongodb failed to connect

### ISSUE THREAD

**Issue by alfirus** [PHPSocialNetwork/phpfastcache#795]
I try to use https://github.com/PHPSocialNetwork/phpfastcache/blob/master/docs/examples/mongodb.php

Then i edit the 'host', 'port', 'port','username' and 'password'.

Once i run in web browser, it shows error below

Fatal error: Uncaught Phpfastcache\Exceptions\PhpfastcacheDriverConnectException: Mongodb failed to connect with the following error message: "Authentication failed." line 114 in /vendor/mongodb/mongodb/src/Command/ListCollections.php in /vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Core/Pool/DriverBaseTrait.php:82 Stack trace: #0 /vendor/phpfastcache/phpfastcache/lib/Phpfastcache/CacheManager.php(190): Phpfastcache\Drivers\Mongodb\Driver->__construct() #1 test.php(25): Phpfastcache\CacheManager::getInstance() #2 {main} thrown in /vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Core/Pool/DriverBaseTrait.php on line 82

**Comment by Geolim4** [comment]
Hello,

The issue template is here for a good reason.

Resubmit your issue with template filled.

Thanks.
