### ISSUE TITLE
What should be configuration, can't find any manual?

### ISSUE THREAD

**Issue by erimeilis** [PHPSocialNetwork/phpfastcache#799]
**Configuration (optional)**
- **PhpFastCache version:** "latest"
- **PhpFastCache API version:** "latest"
- **PHP version:** "7.4"
- **Operating system:** "Ubuntu LTS 20.04"

**My question**
> Well, i see in manuals: CacheManager::setDefaultConfig(new ConfigurationOption([
    'path' => '/var/www/phpfastcache.com/dev/tmp', // or in windows "C:/tmp/"
]));

K, so i have to put there the path to file, where my config file lays, it's clear. But what should be that file? For example, i want to use MariaDB as cache, - what shall i put in this config file?

**Comment by erimeilis** [comment]
I've found this 
OR $InstanceCache = CacheManager::getInstance() <-- open examples/global.setup.php to see more
but there's no such file "examples/global.setup.php"

**Comment by Geolim4** [comment]
Hello,

I think you misunderstood the usage of this configuration entry.
`path` is the directory where Phpfastcache will write its cache files, not the path where its looking for a configuration file.

https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-Configuration-Options

Cheeers,
Georges

**Comment by erimeilis** [comment]
So if i want to use mysql as the place for cache, how shall i configure it?
Is there an example?

**Comment by erimeilis** [comment]
> Hello,
> 
> I think you misunderstood the usage of this configuration entry.
> `path` is the directory where Phpfastcache will write its cache files, not the path where its looking for a configuration file.
> 
> https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-Configuration-Options
> 
> Cheeers,
> Georges

How shall i configure database credentials? Is there any example?

I'd like to cache to db by one script and to read info from it by another one.

**Comment by Geolim4** [comment]
> 
> 
> So if i want to use mysql as the place for cache, how shall i configure it?
> Is there an example?

Mysql is not meant to be a cache backend, i think you don't understand the caching principle.


> 
> 
> > Hello,
> > I think you misunderstood the usage of this configuration entry.
> > `path` is the directory where Phpfastcache will write its cache files, not the path where its looking for a configuration file.
> > https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-Configuration-Options
> > Cheeers,
> > Georges
> 
> How shall i configure database credentials? Is there any example?
> 
> I'd like to cache to db by one script and to read info from it by another one.

Every backend support by MySQL is available in README.md.
Each of support backends have a Config object available in its directory, have a look here:
https://github.com/PHPSocialNetwork/phpfastcache/tree/master/lib/Phpfastcache/Drivers

You can use Redis or Memcache or Files backend etc. Depends your needs.
