### ISSUE TITLE
phpfastcache/couchdb should be in require-dev 

### ISSUE THREAD

**Issue by netsnatch** [PHPSocialNetwork/phpfastcache#822]
composer.json

**Comment by netsnatch** [comment]
version 8.0.7

**Comment by Geolim4** [comment]
No, it does not, it's already in suggest section.

**Comment by netsnatch** [comment]
Thanks for the quick reply.
I mean move from require. It shouldn't be there.

```
    "require": {
        "php": ">=7.3",
        "psr/cache": "~1.0.0",
        "psr/simple-cache": "~1.0.0",
        "ext-mbstring": "*",
        "ext-json": "*",
        "phpfastcache/couchdb": "^1.0"
    },
```

**Comment by Geolim4** [comment]
Ohhh right sorry, it should not be there indeed, I will patch this asap in next release along with Couchbase changes.
