### ISSUE TITLE
Override set method for all drivers 

### ISSUE THREAD

**Issue by Awilum** [PHPSocialNetwork/phpfastcache#828]
Hello!

I want to use such approach with *time delta* for all cache set execution in my project

```php
// 1 Day 
$cacheTime = 24 * 60 * 60; 

// Time delta for cache regeneration
$delta = 60; 

cache()->set('blog', $blogCollection, ($cacheTime + rand(0, $delta)));
cache()->set('catalog', $catalogCollection, ($cacheTime + rand(0, $delta)));
cache()->set('testimonials', $testimonialsCollection, ($cacheTime + rand(0, $delta)));
```
I want to avoid cache invalidation at once with help of *time delta*.

Is it possible somehow to override the `set` method for all cache drivers to add this optional feature right in the `set` method?

Or it's only one way, to create my class, that will add this custom logic for default `set` method?

**Comment by Geolim4** [comment]
Hello,

I don't understand what you're trying to do ?
Are you working with the PSR6 interface or the PSR16 one ?

Anyway you can set the cache expiration of your cache item by setting it using `expireAt(\Datetime)` or  `expireAfter(\DateInterval|int) or `

**Comment by Awilum** [comment]
I don't want to write this every time (when I am using  Psr16 adapter)

```php
->set('blog', $blogCollection, ($cacheTime + rand(0, $delta)));
->set('catalog', $catalogCollection, ($cacheTime + rand(0, $delta)));
->set('testimonials', $testimonialsCollection, ($cacheTime + rand(0, $delta)));
```

I want to write this 

```php
->set('blog', $blogCollection, $cacheTime);
->set('catalog', $catalogCollection, $cacheTime);
->set('testimonials', $testimonialsCollection, $cacheTime);
```

but delta time should be optional and comes underthehood of `set` method like this

```php
function set($key, $data, $time)
{
  ...->set($key, $data, ($cacheTime + rand(0, $delta))); 
}
```

**Comment by Geolim4** [comment]
Oh I understand, in that case it's up to your own implementation.

Or you can try to alter the date with [an event](https://github.com/PHPSocialNetwork/phpfastcache/blob/master/docs/EVENTS.md).

Using the `onCacheSaveItem` event would allow you to add your "delta".

**Comment by Awilum** [comment]
Thanks for your answer
