### ISSUE TITLE
Bug in the getMultiple method

### ISSUE THREAD

**Issue by Awilum** [PHPSocialNetwork/phpfastcache#831]
**Configuration**

PhpFastCache version: 8.0.8
PhpFastCache API version: 3.0.0
PHP version: 7.4.2
Operating system: macOS (but it is affect any)

I can't get default value from `getMultiple` method by using `Psr16Adapter`.

Example:

```php
$values = ['foo' => 'Foo', 'bar' => 'Bar'];
$ttl = 300;
$cache->setMultiple($values, $ttl);

var_dump($cache->getMultiple(['zed', 'ted'], 'Default'));
```

Actual result:
```
array(2) {
  ["zed"]=>
  NULL
  ["ted"]=>
  NULL
}
```

Excepted result:
```
array(2) {
  ["zed"]=>
  string(7) 'Default'
  ["ted"]=>
 string(7) 'Default'
}
```

or Excepted result if `var_dump($cache->getMultiple(['zed', 'ted'], ['Default1', 'Default2']));`

```
array(2) {
  ["zed"]=>
  string(8) 'Default1'
  ["ted"]=>
 string(8) 'Default2'
}
```

**Comment by Geolim4** [comment]
hello,

Please reformat the issue using the template issue.

Thanks.

**Comment by Awilum** [comment]
@Geolim4 updated
