### ISSUE TITLE
Psr16Adapter not compatible with psr/simple-cache 3.0.0?

### ISSUE THREAD

**Issue by therealsamsquanch** [PHPSocialNetwork/phpfastcache#847]
- **PhpFastCache version:** 9.0.1
- **PHP version:** 8.0.14
- **Operating system:** Ubuntu 20.04
- 
After updating to 9.0.1 I'm getting this error:
`Fatal error: Declaration of Phpfastcache\Helper\Psr16Adapter::get(string $key, mixed $default = null): mixed must be compatible with Psr\SimpleCache\CacheInterface::get($key, $default = ) in /path/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Helper/Psr16Adapter.php on line 69`

I have psr/simple-cache 3.0.0 installed.

I'm using mimmi20/BrowserDetector, it requires a PSR-16 compatible cache, so I'm passing phpfastcache's PSR-16 adapter. It used to work fine with phpfastcache 8.x and psr/simple-cache 1.0.0

**Comment by Geolim4** [comment]
Hello,

By looking the expected signature: `Psr\SimpleCache\CacheInterface::get($key, $default = )` you're not using `3.0.0` but `2.0.0`.

**Comment by therealsamsquanch** [comment]
It's weird, because I confirmed that `3.0.0` was installed by using `composer show`. 
I went back to phpfastcache 8.1.0 and psr/simple-cache automatically reverted to 1.0.1. Everything is working again.

**Comment by Geolim4** [comment]
Always clear the composer cache before using `composer show` :)
