### ISSUE TITLE
How do I delete a specific item?

### ISSUE THREAD

**Issue by MathiasReker** [PHPSocialNetwork/phpfastcache#851]
**Configuration (optional)**
- **PhpFastCache version:** "7.1.2"
- **PhpFastCache API version:** "...replace me (Can be retrieved using method `\Phpfastcache\Api::GetVersion()`)..."
- **PHP version:** "7.1"
- **Operating system:** "Windows 10"

**My question**
> I have used this great library for a while, thanks!

I have one issue: I cannot delete a specific cache item. Can you help me understand what I am doing wrong?

I have something like this for saving the item - this is working great, and I can receive the cache. Also, I can clear all caches.
```
    public function save(string $html): void
    {
        try {
            $key = $this->getKey(); // for the specific case, $key this is: **01765bbaf27f4d1467cb0878208f6ccbc9463770**
            $item = $this->cache->getItem($key);

            if (!$item->isHit()) {
                $item->set($html)->expiresAfter(self::TTL);
                $this->cache->save($item);
            }
        } catch (PhpfastcacheInvalidArgumentException $e) {
            LogService::error($e->getMessage(), $e->getTrace());
        }
    }
```

However, I can't figure out how to delete a specific item.
I tried something like this:

```
    public function deleteItem($key) // $key = **01765bbaf27f4d1467cb0878208f6ccbc9463770**
    {
        $this->cache->deleteItem($key);
    }
```
Doing this will clear the whole cache.

What am I missing? 🤔

**Comment by Geolim4** [comment]
Hello,

Please read the [PSR-6 documentation](https://www.php-fig.org/psr/psr-6/). 🤷🏻 

Thanks.

**Comment by Geolim4** [comment]
Also if you want a simplified way to deal with cache you can use our [PSR-16 adapter ](https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV6%CB%96%5D-Psr16-adapter).

**Comment by MathiasReker** [comment]
This should do it, but it deletes every item in the cache: `$this->cache->deleteItem($key);` 🤔

**Comment by Geolim4** [comment]
I don't know what to say, maybe a wrong implementation from your project...
Phpfastcache is heavily tested and such a big bug would immediately thrown the CI down :/

**Comment by MathiasReker** [comment]
You are right, something is wrong with my implementation. I just can't figure out what is wrong. I will do some more research. Thanks,
