### ISSUE TITLE
Tags are deleted automatically

### ISSUE THREAD

**Issue by adis0308** [PHPSocialNetwork/phpfastcache#859]
**Configuration**
- **PhpFastCache version:** "8.0.8"
- **PhpFastCache API version:** "3.0.0"
- **PHP version:** "PHP 7.3.25 (cli) (built: Nov 24 2020 13:41:31) ( NTS MSVC15 (Visual C++ 2017) x64 )"
- **Operating system:** "Windows 10"

**Describe the bug**
Tags that have an expiration date are always deleted even though one of the items still exists.

**Expected behavior**
I want the Tag to not be deleted if the Item in the tag still exists.

**Code Example**
$cache = $InstanceCache->getItem('item');
$cache->set('cache data here')->expiresAfter(60);
$cache->addTags(['global', 'tag1']);

$cache = $InstanceCache->getItem('another item');
$cache->set('another cache data here')->expiresAfter(1314000);
$cache->addTags(['global', 'tag 2']);

**In the example code above it produces**
If the "item" cache expires then the "global" and "tag 1" tags will be deleted. The "global" tag should not be deleted because it still has cache "another item" with tag "tag 2"

**Comment by Geolim4** [comment]
Hello,

Hmm weird, I will made some tests tonight, I'm surprised this case is not covered by tests.

Cheers,
Georges

**Comment by Geolim4** [comment]
Hello,

I made some tests (on Files driver) and I'm unable to reproduce the bug:
![image](https://user-images.githubusercontent.com/1332071/161597940-a6cdc774-f015-4f7c-b5d9-3d90fe26205a.png)

**Comment by Geolim4** [comment]
Also I'm able to recover the second cache item by its tag after the first one being deleted:
![image](https://user-images.githubusercontent.com/1332071/161598634-5bff8d01-edc0-4585-8a3d-06fc88ef37f0.png)

**Comment by adis0308** [comment]
Please reopen this issue. I have tried version 8.1.2 and it doesn't solve the problem. I am using Redis cache and the problem is not solved. If I add more alternative tags then the 'global' tag like in the example will be deleted automatically again.

**Comment by Geolim4** [comment]
I can't reproduce it, I made deep tests, the CI passe too with multiple tags tests, I can't reproduce it 🤷🏻‍♂️

**Comment by Geolim4** [comment]
Redis tests with tags on v8 3 days ago:
https://app.travis-ci.com/github/PHPSocialNetwork/phpfastcache/jobs/565989218#L5485

**Comment by Geolim4** [comment]
Due to the fact that I'm unable to reproduce this bug, confirmed by deep tests, I'm reclosing it again, until you provide me a strong proof with code and screenshoot/video if needed.

Thanks.
