### ISSUE TITLE
Front page need re-examine

### ISSUE THREAD

**Issue by Triloworld** [PHPSocialNetwork/phpfastcache#861]
Some feature can be added and some fix can be implement.
List what we found:
- Linking to tab need code examine. No hashes to tab shown in browser that can help to navigate into tab. Manually added don't change after clicking on other tab.
- Sections don't have any headers with ID (another time #v8-api needed)
- 404 in tab https://www.phpfastcache.com/#changelog link to https://www.phpfastcache.com/CHANGELOG_API.md
- 404 in main page https://www.phpfastcache.com/ to https://www.phpfastcache.com/docs/examples 
- 404 on https://www.phpfastcache.com/#options in link https://www.phpfastcache.com/lib/Phpfastcache/Drivers
- github action to build front page for this page

Some fixes can be apply:
[phpfastcache.com.pdf](https://github.com/PHPSocialNetwork/phpfastcache/files/8427245/phpfastcache.com.pdf)

Even PWA can be added. Header cache only by this method: https://stackoverflow.com/a/31771772

This in code is bad, need to be checked and fix before I can contribute or anybody:

**Comment by Geolim4** [comment]
Hello,

I have not planned to rework on the Github page for now, due to lack of personal time, the code is not perfect but it does the job.

I'll eventually fix the 404 but no more for now.

Thank for your feedback,
Georges

**Comment by Triloworld** [comment]
Add pleas # only on tabs. Help a lot. Thx for 404 issue.
