### ISSUE TITLE
Website broken - Unable to browse any documentation page

### ISSUE THREAD

**Issue by hriziya** [PHPSocialNetwork/phpfastcache#886]
### What type of issue is this?

Incorrect/unexpected/unexplainable behavior

### Operating system + version

Windows 10

### PHP version

8

### Phpfastcache version

9.1.2 ✅

### Describe the issue you're facing

Website is not loading any content inside the Tabs. Attached screenshot.

### Do you have anything more you want to share? (optional)

![image](https://user-images.githubusercontent.com/4135216/208864844-49e524d0-9e30-439d-8d64-cb120ad60755.png)

### Have you searched in our Wiki before posting ?

- [X] I have searched over the Wiki

**Comment by Geolim4** [comment]
Hello,

Works fine on my side, do you have any console errors to show me ?

![Capture d’écran de 2022-12-21 11-30-35](https://user-images.githubusercontent.com/1332071/208884014-46dd0d9c-6ab6-4284-bbda-976fb1017a20.png)

**Comment by hriziya** [comment]
Strange! I just see it now.. 
![image](https://user-images.githubusercontent.com/4135216/208885258-2d5ffac9-e20f-4f57-8b6c-bbdd9ea26e29.png)

when I try to open the URL in separate tab, it still timed out. 
![image](https://user-images.githubusercontent.com/4135216/208885400-8c50fe50-f884-4531-a3f4-b7e59a6c0bd3.png)

I have tried browsing it from mobile to confirm its not my ISP issue.. still same. 
do you want me to follow any steps? open to help.

**Comment by Geolim4** [comment]
Then it is completely related to your ISP, I can't help you more ATM :/

Maybe some governmental censorship or whatsoever...

**Comment by hriziya** [comment]
No problem. Thanks for the guidance.

**Comment by Geolim4** [comment]
You're welcome, good luck !
