### ISSUE TITLE
PDO Cache is case insensitive?

### ISSUE THREAD

**Issue by dbwodlf3** [PHPSocialNetwork/phpfastcache#887]
### What's your question ?

many cases database like mysql varchar is case insensitive. sqlite3 is also case insensitive.
PHPFastCache are also case insensitive?

**Comment by Geolim4** [comment]
Hello, "case insensitive" about what exactly ?

If you're talking about cache keys, no it's not case insensitive as per PSR-6 compliance.

**Comment by dbwodlf3** [comment]
yes. about cache key. thanks answer.

**Comment by Geolim4** [comment]
> yes. about cache key. thanks answer. you means, "KEYA" and "KEYa" is different?

Exactly, they will mostly return you different cache item, if it does not then it's bug I should work on.

**Comment by Geolim4** [comment]
Hello @dbwodlf3,

I’m closing this issue _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the issue / add comment / clarify …).

Regards,
Georges.L
