### ISSUE TITLE
Memcached driver compress_data cache miss

### ISSUE THREAD

**Issue by iftaras** [PHPSocialNetwork/phpfastcache#889]
### What type of issue is this?

Incorrect/unexpected/unexplainable behavior

### Operating system + version

Ubuntu 20.04 5.10.16.3-microsoft-standard-WSL2

### PHP version

8.1.12

### Connector/Database version (if applicable)

Memcached 1.6.18 + PECL Extension 3.2.0

### Phpfastcache version

9.1.2 ✅

### Describe the issue you're facing

During configuration of the Memcached instance if we specify the `compress_data` option either be true or false we always hit a cache miss even though the data exists.

### Expected behavior

Since the data exists on the Memcached server we should get true when querying `isHit()`.

### Code sample (optional)

Instance configuration:
```
$memcached = CacheManager::getInstance('Memcached', new MemcachedConfig([
        'host' => $_ENV['ME_HOST'],
        'port' => intval($_ENV['MEM_PORT']),
        'saslUser' => $_ENV['MEM_USER'] ?? '',
        'saslPassword' => $_ENV['MEM_PASS'] ?? '',
        'optPrefix' => 'testing_',
        'defaultTtl' => 90,
        'compress_data' => true,
        'preventCacheSlams' => true,
        'cacheSlamsTimeout' => 3
]));
```

Example:
```
$cacheItem = $memcached->getItem('get_exampleData');

if (!$cacheItem->isHit()) {
    echo 'CACHE MISS';
    $data = 'get_the_data_from_the_db';
    $cacheItem->set($data);
    $cacheItem->setTags(['data', 'homepage', 'summary']);
    $memcached->save($cacheItem);
} else {
    echo 'CACHE HIT!!!!';
    $data = $cacheItem->get();
}
```

In the example above no matter how many passes we do, we will always get **CACHE MISS**. If we remove the `compress_data` option from the configuration everything returns to normal.

### Have you searched in our Wiki before posting ?

- [X] I have searched over the Wiki

**Comment by Geolim4** [comment]
Hello,

I'm not sure if you have a try/catch somewhere in your code, but this code is definitely triggering me an error:

![image](https://user-images.githubusercontent.com/1332071/212897855-5c5b18db-567c-4acf-80c9-8fd50e3de64e.png)


```
[Begin Test: Memcached]
[PHPFASTCACHE: CORE v9.1.2#c2dfc471 | API v4.2.0]
[PHP v8.0.27 with: bcmath, calendar, Core, ctype, curl, date, dom, fileinfo, filter, gettext, grpc, hash, iconv, json, libxml, mbstring, memcached, mongodb, mysqlnd, openssl, pcre, PDO, pdo_sqlite, Phar, readline, Reflection, session, SimpleXML, SPL, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib]
---
[FAIL] Uncaught exception "Phpfastcache\Exceptions\PhpfastcacheInvalidConfigurationException" in "~/lib/Phpfastcache/Config/ConfigurationOption.php" line 64 with message: "Unknown configuration option name "compress_data" for the config class "Phpfastcache\Drivers\Memcached\Config". Allowed configurations options are "servers", "host", "port", "saslUser", "saslPassword", "optPrefix", "itemDetailedDate", "autoTmpFallback", "defaultTtl", "defaultKeyHashFunction", "defaultFileNameHashFunction", "path", "preventCacheSlams", "cacheSlamsTimeout", "useStaticItemCaching", "superGlobalAccessor""
Test results:  1 assertion failed, 0 assertions skipped and 0 assertions passed out of a total of 1 assertion.
Test duration: 0.072s
```

Also make sure you phpfastcache version is up to date, since the option `compress_data` has been removed a long time ago.

**Comment by iftaras** [comment]
My apologies, you are correct. I had a fallback instance which resulted in a cache miss.
The `compress_data` option though is still referenced for Memcache(d) in the [Global configuration options wiki page](https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-Configuration-Options).

**Comment by Geolim4** [comment]
Ohh right, I fixed the Wiki, thanks !
