### ISSUE TITLE
Config('path') - Can't declare path from the parent directory of index file directory.

### ISSUE THREAD

**Issue by Irakli-GZ** [PHPSocialNetwork/phpfastcache#890]
### What type of issue is this?

Incorrect/unexpected/unexplainable behavior

### Operating system + version

Windows 10

### PHP version

8.1.12

### Phpfastcache version

9.1.2 ✅

### Describe the issue you're facing

So... I'm using .htaccess configs to access the root directories.
I have a specific folder "Index" for index.php, from where the execution starts, and I have a "Storage" dir next to the "Index" dir to store data files... and I want to land caching in "Storage" dir ... so I've tried pretty much everything, including checking my .htaccess configs, which didn't seem to affect anything at all, and I think it somehow can't be done to detect the '../' and escape from the index dir . ...

Thanks.

### Have you searched in our Wiki before posting ?

- [X] I have searched over the Wiki

**Comment by Geolim4** [comment]
Hello,

How did you setup the config of Phpfastcache exactly ?

You can customize the cache path as you want, just read the Wiki.

**Comment by Irakli-GZ** [comment]
$config = new Phpfastcache\Config\ConfigurationOption([
                'path' => '../Storage/Cache',
                'preventCacheSlams' => true,
                'cacheSlamsTimeout' => 20
            ]);

            \Phpfastcache\CacheManager::setDefaultConfig($config);

**Comment by Geolim4** [comment]
Don't use a relative path, use an absolute path.

**Comment by Irakli-GZ** [comment]
Yes, I tried, it worked.
But did not work in this system.
The problem was that my .htaccess config was preventing unwanted access from outside of the system in to the target dir with absolute url path.. so... I inserted DOCUMENT_ROOT path and it's fine.

Thanks.

**Comment by Geolim4** [comment]
Ok, have a nice day :)
