### ISSUE TITLE
Installation fails: 'Fatal error: Uncaught Error: Class "CacheManager" not found ...'

### ISSUE THREAD

**Issue by andreaspacher** [PHPSocialNetwork/phpfastcache#892]
### What type of issue is this?

Incorrect/unexpected/unexplainable behavior

### Operating system + version

Windows 10

### PHP version

8.0.3

### Phpfastcache version

9.1.2 ✅

### Describe the issue you're facing

I am trying to get Phpfastcache running.

I did both a manual download and used composer.

However, I get an error message: `Fatal error: Uncaught Error: Class "CacheManager" not found ...`

### Code sample (optional)

An example code I used is:

```
# I checked, the path is correct!
require_once './vendor/autoload.php';

CacheManager::setDefaultConfig(new ConfigurationOption([
    'path' => '/cache', 
]));
$cache = \Phpfastcache\CacheManager::getInstance('Files');
```

Or I also tried:

```
use Phpfastcache\CacheManager;
use Phpfastcache\Config\ConfigurationOption;

CacheManager::setDefaultConfig(new ConfigurationOption([
    'path' => '/cache', 
]));
$cache = \Phpfastcache\CacheManager::getInstance('Files');
```

### Have you searched in our Wiki before posting ?

- [X] I have searched over the Wiki

**Comment by Geolim4** [comment]
Hello,

Just check your composer installation, something is not right, it look like an autoload issue to me.

Look README:
https://github.com/PHPSocialNetwork/phpfastcache/blob/master/README.md#construction-step-2-setup-your-website-code-to-implement-the-phpfastcache-calls-with-composer

**Comment by Geolim4** [comment]
Hello @andreaspacher ,

I’m closing this issue _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the issue / add comment / clarify …).

Regards,
Georges.L
