### ISSUE TITLE
getItemsByTag() - empty after one item has expired

### ISSUE THREAD

**Issue by MaxChri** [PHPSocialNetwork/phpfastcache#893]
### What type of issue is this?

Incorrect/unexpected/unexplainable behavior

### Operating system + version

Debian 11

### PHP version

8.1

### Connector/Database version (if applicable)

Memcached, Files

### Phpfastcache version

9.1.2 ✅

### Describe the issue you're facing

I create multiple keys with different expiration values using expiresAfter(). I'm using the addTags() function to search for the keys if necessary (e.g to manage them in a CMS). When a first item key expires, all other keys with the same tag name are immediately gone and are not callable anymore with getItemsByTag().

So basically if you have a 5 seconds key and another 10 seconds key (both initialized at the same time) with the same tag name, both items will be returned by getItemsByTag(). But if the 5 seconds key has expired, the 10 seconds key is also gone when calling getItemsByTag(). The 10 seconds key is still physically there but cannot be found by the previously declared tag anymore. So a 10 seconds timer would be gone within 5 seconds in this scenario. If the 5 seconds timer would not exist, the 10 seconds timer would of course counting down until 0.

### Expected behavior

All keys with the same tag name should be still callable, even if previous keys with the same tag has been expired.

### Do you have anything more you want to share? (optional)

In the video you can see, that when the statistics key expires, the player object key is also gone while it should have 5 seconds left. At the same time, a new statistics key will be created (which is not important).
https://i.gyazo.com/ad584c00607032c41a83db2378ff51d8.mp4

### Have you searched in our Wiki before posting ?

- [X] I have searched over the Wiki

**Comment by Geolim4** [comment]
Hello,

I'm not sure how you get this behavior since the cache already benefits from the cache item with the longest date:
https://github.com/PHPSocialNetwork/phpfastcache/blob/master/lib/Phpfastcache/Core/Pool/TaggableCacheItemPoolTrait.php#L430

Also the tags are tested against this behavior too:
https://github.com/PHPSocialNetwork/phpfastcache/blob/master/tests/ItemTags.test.php

**Comment by Geolim4** [comment]
Interesting, if you set the 5 sec key first then the 10 sec, the result are valid.
By your example, you does the opposite and there's, indeed an issue.

**Comment by Geolim4** [comment]
That's why I doubted it first, because my tests are doing the first use case, not yours. I'm investigating.

**Comment by MaxChri** [comment]
I have replaced the code and it works perfectly now. Thank you very much for your quick help, I really appreciate it! :)

**Comment by Geolim4** [comment]
I will make an anti-regression test as well, since this behavior was difficult to catch without your specific case.

**Comment by Geolim4** [comment]
Versions [9.1.3](https://github.com/PHPSocialNetwork/phpfastcache/releases/tag/9.1.3) and [8.1.4](https://github.com/PHPSocialNetwork/phpfastcache/releases/tag/8.1.4) have been released.

Happy caching !
