### ISSUE TITLE
2 million data cache?

### ISSUE THREAD

**Issue by eskoctr** [PHPSocialNetwork/phpfastcache#898]
### What's your question ?

How can I cache a mysql table with 2 million rows?

**Comment by Geolim4** [comment]
> How can I cache a mysql table with 2 million rows?

Short answer: Don't.

Long answer: If caching 2 millions rows is the solution to some overload/timeout issue then you probably asking yourself the wrong question.

**Comment by eskoctr** [comment]
Thanks. So, is partitioned storage possible? I'm trying to do something special. For example, there is a 200mb document, but I want to separate it into 3mb documents and combine them in the query. Is it possible?

**Comment by Geolim4** [comment]
You don't need a cache, you either need a CDN or a document storage (Solr, AWS, or NoDB storage).

**Comment by Geolim4** [comment]
Hello @eskoctr ,

I’m closing this issue _for now_ because of (inactivity / outdated code / …).

You can always reopen it though! :) 
Please (update the issue / add comment / clarify …).

Regards,
Georges.L
