### ISSUE TITLE
cache not clearing manually in html

### ISSUE THREAD

**Issue by parvinders347** [PHPSocialNetwork/phpfastcache#901]
### What's your question ?

I want to clear my cache manually in HTML
I have added this
`<button type="submit" name="submit" class="btn btn-lg btn-block btn-primary mt-4"><?= l('admin_settings.cache.clear') ?></button>`

### Do you have anything more you want to share? (optional)

my phpfastcache folder:
[https://file.io/GOnPeGwDAbtf](url)

**Comment by Geolim4** [comment]
Hello,

Sorry I can't help you with the implementation itself of Phpfastcache.

Follow the README instructions and check out the Wiki.

Cheers,
Georges
